# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: historical_battles/scripts/common/historical_battles_common/hb_constants_extension.py
import constants
from constants_utils import ConstInjector
from BattleFeedbackCommon import BATTLE_EVENT_TYPE as ORIG_BATTLE_EVENT_TYPE
from UnitBase import UNIT_MGR_FLAGS as ORIG_UNIT_MGR_FLAGS, ROSTER_TYPE as ORIG_ROSTER_TYPE, CLIENT_UNIT_CMD as ORIG_CLIENT_UNIT_CMD, UNIT_NOTIFY_CMD as ORIG_UNIT_NOTIFY_CMD

class ARENA_GUI_TYPE(constants.ARENA_GUI_TYPE, ConstInjector):
    HISTORICAL_BATTLES = 101
    HB_RANGE = (HISTORICAL_BATTLES,)


class ARENA_BONUS_TYPE(constants.ARENA_BONUS_TYPE, ConstInjector):
    HISTORICAL_BATTLES = 101
    HB_RANGE = (HISTORICAL_BATTLES,)


class QUEUE_TYPE(constants.QUEUE_TYPE, ConstInjector):
    HISTORICAL_BATTLES = 101
    HB_RANGE = (HISTORICAL_BATTLES,)


class PREBATTLE_TYPE(constants.PREBATTLE_TYPE, ConstInjector):
    HISTORICAL_BATTLES = 101


class UNIT_MGR_FLAGS(ORIG_UNIT_MGR_FLAGS, ConstInjector):
    HISTORICAL_BATTLES = 2097152


HB_UNIT_MGR_FLAGS_GENERAL_MASK = UNIT_MGR_FLAGS.HISTORICAL_BATTLES

class ROSTER_TYPE(ORIG_ROSTER_TYPE, ConstInjector):
    HISTORICAL_BATTLES = UNIT_MGR_FLAGS.SQUAD | UNIT_MGR_FLAGS.HISTORICAL_BATTLES


HB_ROSTER_TYPE_GENERAL_MASK = UNIT_MGR_FLAGS.SQUAD | HB_UNIT_MGR_FLAGS_GENERAL_MASK
QUEUE_TYPE_TO_UNIT_DATA = {QUEUE_TYPE.HISTORICAL_BATTLES: (UNIT_MGR_FLAGS.HISTORICAL_BATTLES, ROSTER_TYPE.HISTORICAL_BATTLES)}

class INVITATION_TYPE(constants.INVITATION_TYPE, ConstInjector):
    HISTORICAL_BATTLES = PREBATTLE_TYPE.HISTORICAL_BATTLES


class CLIENT_UNIT_CMD(ORIG_CLIENT_UNIT_CMD, ConstInjector):
    SET_UNIT_FRONTMAN = 1001
    SET_UNIT_FRONT = 1002
    START_UNIT_HISTORICAL_BATTLES = 1003


class UNIT_NOTIFY_CMD(ORIG_UNIT_NOTIFY_CMD, ConstInjector):
    SET_NOTIFY_FRONTMAN_READY = 101
    SET_NOTIFY_FRONTMAN = 102
    SET_NOTIFY_FRONT = 103


class BATTLE_EVENT_TYPE(ORIG_BATTLE_EVENT_TYPE, ConstInjector):
    HB_ACTION_APPLIED = 101
    HEAL_VEHICLE_APPLIED_ACTION = 102
    TOTAL_VEHICLES_HEAL_APPLIED_ACTION = 103
    HEAL_SELF_VEHICLE_APPLIED_ACTION = 104


INVALID_FRONT_ID = -1
INVALID_FRONTMAN_ID = 0
INVALID_FRONTMAN_ROLE_ID = -1
HB_SYS_MESSAGE_TYPES = ['hbShopBundlePurchased',
 'hbCouponsBundlePurchased',
 'hbTankModuleBundlePurchased',
 'hbMainPrizeVehiclePurchased',
 'HBProgressionNotification']
FRONT_QUEUE_TYPES = {'offence': QUEUE_TYPE.HISTORICAL_BATTLES}
QUEUE_TYPE_TO_BATTLE_MGR = {QUEUE_TYPE.HISTORICAL_BATTLES: 'HBBattleMgr'}
