# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/client/gui/event_boards/event_board_mock_data.py
from collections import defaultdict
from random import randint, uniform
rewardGroups = [{'start_position': 1,
  'end_position': 5,
  'group_type': 1,
  'rewards_by_position': {1: [{'item_icon': '../maps/icons/quests/bonuses/small/additionalBriefing.png',
                               'item_count': 3}, {'item_icon': '../maps/icons/quests/bonuses/small/aimingStabilizer.png',
                               'item_count': 2}, {'item_icon': '../maps/icons/quests/bonuses/small/antifragmentationLining.png',
                               'item_count': 1}],
                          2: [{'item_icon': '../maps/icons/quests/bonuses/small/autoExtinguishers.png',
                               'item_count': 4}, {'item_icon': '../maps/icons/quests/bonuses/small/berths.png',
                               'item_count': 5}, {'item_icon': '../maps/icons/quests/bonuses/small/booster_credits.png',
                               'item_count': 6}],
                          3: [{'item_icon': '../maps/icons/quests/bonuses/small/booster_crew_xp.png',
                               'item_count': 7}, {'item_icon': '../maps/icons/quests/bonuses/small/booster_free_xp.png',
                               'item_count': 8}, {'item_icon': '../maps/icons/quests/bonuses/small/booster_xp.png',
                               'item_count': 9}],
                          4: [{'item_icon': '../maps/icons/quests/bonuses/small/booster_crew_xp.png',
                               'item_count': 4}, {'item_icon': '../maps/icons/quests/bonuses/small/booster_free_xp.png',
                               'item_count': 5}, {'item_icon': '../maps/icons/quests/bonuses/small/booster_xp.png',
                               'item_count': 6}],
                          5: [{'item_icon': '../maps/icons/quests/bonuses/small/booster_crew_xp.png',
                               'item_count': 1}, {'item_icon': '../maps/icons/quests/bonuses/small/booster_free_xp.png',
                               'item_count': 2}, {'item_icon': '../maps/icons/quests/bonuses/small/booster_xp.png',
                               'item_count': 3}]}},
 {'start_position': 6,
  'end_position': 20,
  'group_type': 2,
  'rewards_by_group': [{'item_icon': '../maps/icons/quests/bonuses/small/camouflageNet.png',
                        'item_count': 1}, {'item_icon': '../maps/icons/quests/bonuses/small/camouflages.png',
                        'item_count': 2}]},
 {'start_position': 21,
  'end_position': 30,
  'group_type': 3,
  'rewards_by_group': [{'item_icon': '../maps/icons/quests/bonuses/small/chocolate.png',
                        'item_count': 1}, {'item_icon': '../maps/icons/quests/bonuses/small/coatedOptics.png',
                        'item_count': 2}, {'item_icon': '../maps/icons/quests/bonuses/small/cocacola.png',
                        'item_count': 3}]},
 {'start_position': 31,
  'end_position': 1000,
  'group_type': 5}]
myLeaderboardInfo = {0: {'rank': 1,
     'p1': 99999,
     'p2': randint(100, 9999),
     'p3': randint(100, 9999),
     'page_number': 1,
     'is_inside_viewsize': True,
     'last_in_leaderboard_value': 1024,
     'battles_count': 1024},
 1: {'rank': 3,
     'p1': 99001,
     'p2': randint(100, 9999),
     'p3': randint(100, 9999),
     'page_number': 1,
     'is_inside_viewsize': True,
     'last_in_leaderboard_value': 1024,
     'battles_count': 998},
 2: {'rank': 12,
     'p1': 5555,
     'p2': randint(100, 9999),
     'p3': randint(100, 9999),
     'page_number': 1,
     'is_inside_viewsize': True,
     'last_in_leaderboard_value': 1024,
     'battles_count': 440},
 3: {'rank': 55,
     'p1': 3421,
     'p2': randint(100, 9999),
     'p3': randint(100, 9999),
     'page_number': 2,
     'is_inside_viewsize': True,
     'last_in_leaderboard_value': 1024,
     'battles_count': 100},
 4: {'rank': 666,
     'p1': 1300,
     'p2': randint(100, 9999),
     'p3': randint(100, 9999),
     'page_number': 14,
     'is_inside_viewsize': True,
     'last_in_leaderboard_value': 1024,
     'battles_count': 10},
 5: {'rank': None,
     'p1': 100,
     'p2': randint(100, 9999),
     'p3': randint(100, 9999),
     'page_number': None,
     'is_inside_viewsize': False,
     'last_in_leaderboard_value': 1024,
     'battles_count': 5}}
userNamesForLB = ['TankMan',
 'Vasia',
 'Vasia1234567890Vasia',
 'Nagibator2017',
 'WGELENTANKMASTERSUPER2017',
 'VeryLongNameForPlayerAndWithClantTagOloloIetoNeVseVotSeichasVse',
 'ToxaMolodec',
 'TotalAnigilator',
 'Traktorist',
 'Shkololo',
 'SuperTankoYpravlatel',
 'WoTGM',
 'VotTytIyYzheNeZnalKakNazivat',
 'wtf',
 'NyzhnoBolsheZolota',
 'ChuckNorris',
 'Marinka',
 'SeregaPozakryvalyP',
 'Nikolaich']
userClanTagForLB = ['OLOLO',
 'TM_1',
 'O_O',
 'WOTGM',
 'CGK',
 'DNO',
 'XXX',
 'ZZZ',
 'SALO',
 'PIVO',
 'UA',
 'BY',
 'RU',
 'XZ',
 'XYZ',
 'OMG',
 'AFK',
 'GG',
 'HF',
 '']
cdUSA = [14881,
 56865,
 19489,
 8481,
 10785,
 13089,
 14113,
 40737,
 13857,
 15905,
 55841]
cdUSSR = [3329,
 7169,
 58369,
 61185,
 61697,
 50689,
 50433,
 19201,
 40705,
 64257,
 8705,
 13825,
 63745,
 13569,
 6145,
 14337,
 15617,
 60673,
 17153,
 16897]
cdGER = [1,
 19217,
 19985,
 19473,
 6929,
 40721,
 9489,
 9233]
cdFRA = [6209,
 64833,
 3649,
 40257,
 13889,
 17729,
 15425,
 17217]
cdCH = [4145,
 39217,
 5425,
 62769,
 63537,
 5937,
 8497,
 6193,
 2417]
cdJP = [3681, 39265, 3937]
cdLongNameTank = [2353,
 38705,
 40257,
 52481,
 40449]
userClanTagColorForLB = [16399286,
 11189247,
 1135991,
 4527653,
 16764125,
 11141341,
 5592405,
 7829367,
 3355443,
 1118481,
 16595622]
availableNationVeh = [cdUSA,
 cdUSSR,
 cdGER,
 cdFRA,
 cdCH,
 cdJP]
leaderboardMockRequest = {'value': None}

def makeLeaderboard(vNation):
    playersData = []
    playersDataSumAll = []
    leaderboardData = []
    leaderboardDataSumAll = []
    for i in range(1000):
        playersData.append({'rank': i + 1,
         'spa_id': i,
         'name': getRandomValue(userNamesForLB) + str(i),
         'clan_tag': getRandomValue(userClanTagForLB),
         'clan_color': str(getRandomValue(userClanTagColorForLB)),
         'p1': randint(100, 99999),
         'p2': randint(100, 99999),
         'p3': randint(100, 99999),
         'info': [{'battle_ts': 1503363600,
                   'vehicle_cd': getRandomValue(vNation),
                   'battle_result': 'win',
                   'is_in_squad': True,
                   'exp': randint(1000, 99999),
                   'damage': randint(100, 99999),
                   'assisted_damage': randint(100, 99999),
                   'frags': randint(0, 15),
                   'blocked_damage': randint(100, 99999)},
                  {'battle_ts': 1503363600,
                   'vehicle_cd': getRandomValue(vNation),
                   'battle_result': 'loss',
                   'is_in_squad': False,
                   'exp': randint(1000, 99999),
                   'damage': randint(100, 99999),
                   'assisted_damage': randint(100, 99999),
                   'frags': randint(0, 15),
                   'blocked_damage': randint(100, 99999)},
                  {'battle_ts': 1503363600,
                   'vehicle_cd': getRandomValue(vNation),
                   'battle_result': 'win',
                   'is_in_squad': True,
                   'exp': randint(1000, 99999),
                   'damage': randint(100, 99999),
                   'assisted_damage': randint(100, 99999),
                   'frags': randint(0, 15),
                   'blocked_damage': randint(100, 99999)},
                  {'battle_ts': 1500634215,
                   'vehicle_cd': getRandomValue(vNation),
                   'battle_result': 'loss',
                   'is_in_squad': False,
                   'exp': randint(1000, 99999),
                   'damage': randint(100, 99999),
                   'assisted_damage': randint(100, 99999),
                   'frags': randint(0, 15),
                   'blocked_damage': randint(100, 99999)},
                  {'battle_ts': 1500634215,
                   'vehicle_cd': getRandomValue(vNation),
                   'battle_result': 'loss',
                   'is_in_squad': False,
                   'exp': randint(1000, 99999),
                   'damage': randint(100, 99999),
                   'assisted_damage': randint(100, 99999),
                   'frags': randint(0, 15),
                   'blocked_damage': randint(100, 99999)}]})
        playersDataSumAll.append({'rank': i + 1,
         'spa_id': i,
         'name': getRandomValue(userNamesForLB) + str(i),
         'clan_tag': getRandomValue(userClanTagForLB),
         'clan_color': str(getRandomValue(userClanTagColorForLB)),
         'p1': randint(100, 9999),
         'p2': randint(100, 9999),
         'p3': randint(100, 9999),
         'info': [{'avg_exp': randint(100, 99999),
                   'avg_damage_dealt': randint(100, 99999),
                   'avg_damage_assisted': randint(100, 99999),
                   'win_rate': uniform(30, 70)},
                  {'avg_exp': randint(100, 99999),
                   'avg_damage_dealt': randint(100, 99999),
                   'avg_damage_assisted': randint(100, 99999),
                   'win_rate': uniform(30, 70)},
                  {'avg_exp': randint(100, 99999),
                   'avg_damage_dealt': randint(100, 99999),
                   'avg_damage_assisted': randint(100, 99999),
                   'win_rate': uniform(30, 70)},
                  {'avg_exp': randint(100, 99999),
                   'avg_damage_dealt': randint(100, 99999),
                   'avg_damage_assisted': randint(100, 99999),
                   'win_rate': uniform(30, 70)},
                  {'avg_exp': randint(100, 99999),
                   'avg_damage_dealt': randint(100, 99999),
                   'avg_damage_assisted': randint(100, 99999),
                   'win_rate': uniform(30, 70)}]})

    for page in range(50):
        leaderboardData.append({'meta': {'page_number': page + 1,
                  'pages_amount': 20,
                  'rewards': [{'reward_category_number': 1,
                               'page_number': 1},
                              {'reward_category_number': 2,
                               'page_number': 1},
                              {'reward_category_number': 3,
                               'page_number': 2},
                              {'reward_category_number': 4,
                               'page_number': 3}],
                  'recalculation_interval': 3600,
                  'last_leaderboard_recalculation_ts': 1501156127,
                  'next_leaderboard_recalculation_ts': 1501242527},
         'data': []})
        leaderboardDataSumAll.append({'meta': {'page_number': page + 1,
                  'pages_amount': 20,
                  'rewards': [{'reward_category_number': 1,
                               'page_number': 1},
                              {'reward_category_number': 2,
                               'page_number': 1},
                              {'reward_category_number': 3,
                               'page_number': 2},
                              {'reward_category_number': 4,
                               'page_number': 3}],
                  'recalculation_interval': 3600,
                  'last_leaderboard_recalculation_ts': 1501156127,
                  'next_leaderboard_recalculation_ts': 1501242527},
         'data': []})

    for idx, player in enumerate(playersData):
        leaderboardData[idx / 50]['data'].append(player)

    for idx, player in enumerate(playersDataSumAll):
        leaderboardDataSumAll[idx / 50]['data'].append(player)
        return (leaderboardData, leaderboardDataSumAll)


def getRandomValue(source):
    return source[randint(0, len(source) - 1)]


LeaderboardsData = defaultdict(dict)
indx = 0
for nation in availableNationVeh:
    lbd, lbdsa = makeLeaderboard(nation)
    LeaderboardsData[indx]['leaderboardData'] = lbd
    LeaderboardsData[indx]['leaderboardDataSumAll'] = lbdsa
    indx += 1

eventPlayerData = {'all_battles_count': 12345,
 'win_rate': 46.4,
 'events_list': [{'event_id': '1',
                  'player_state': 1,
                  'player_state_reasons': [],
                  'players_in_event': 1000,
                  'can_join': False}]}
hangarFlagData = [{'event_id': '1',
  'is_registered': True}]
eventMyTop = {'meta': {'recalculation_interval': 3600,
          'last_leaderboard_recalculation_ts': 1502360027,
          'next_leaderboard_recalculation_ts': 1502370027},
 'data': [{'leaderboard_id': 0,
           'my_position': 1,
           'battles_count': 1024,
           'my_value': 99999,
           'last_in_leaderboard_value': 1024},
          {'leaderboard_id': 1,
           'my_position': 3,
           'battles_count': 998,
           'my_value': 99001,
           'last_in_leaderboard_value': 1024},
          {'leaderboard_id': 2,
           'my_position': 12,
           'battles_count': 440,
           'my_value': 5555,
           'last_in_leaderboard_value': 1024},
          {'leaderboard_id': 3,
           'my_position': 55,
           'battles_count': 100,
           'my_value': 3421,
           'last_in_leaderboard_value': 1024},
          {'leaderboard_id': 4,
           'my_position': 666,
           'battles_count': 10,
           'my_value': 1300,
           'last_in_leaderboard_value': 1024},
          {'leaderboard_id': 5,
           'my_position': None,
           'battles_count': 5,
           'my_value': 100,
           'last_in_leaderboard_value': 1024}]}
eventEventsData = [{'event_id': '1',
  'name': '\xd0\x9c\xd0\xb0\xd1\x80\xd1\x88 \xd0\xbd\xd0\xb0\xd1\x86\xd0\xb8\xd0\xb9',
  'type': 'nation',
  'leaderboard_view_size': 1000,
  'publish_date': '',
  'start_date': '2017-07-10T10:15:00',
  'participants_freeze_deadline': '2017-09-29T10:15:00',
  'end_date': '2017-09-30T10:15:00',
  'rewarding_date': '2017-12-30T10:15:00',
  'manual': '',
  'is_squad_allowed': False,
  'battle_type': 1,
  'prime_times': [{'server': '0',
                   'start_time': '01:00:00',
                   'end_time': '23:00:00'},
                  {'server': '201',
                   'start_time': '01:00:00',
                   'end_time': '23:00:00'},
                  {'server': '202',
                   'start_time': '01:00:00',
                   'end_time': '23:00:00'},
                  {'server': '101',
                   'start_time': '01:00:00',
                   'end_time': '02:00:00'},
                  {'server': '102',
                   'start_time': '01:00:00',
                   'end_time': '02:00:00'}],
  'objective_parameter': 'damageDealt',
  'additional_sorting_parameter': '',
  'informational_parameter': '',
  'method': 'max',
  'cardinality': 5,
  'limits': {'win_rate_min': 26.4,
             'win_rate_max': 66.4,
             'registration_date_max': '2017-07-10T10:21:00',
             'is_registration_needed': True,
             'battles_count_min': 1,
             'vehicles': [{'leaderboard_id': 0,
                           'vehicles': cdUSA},
                          {'leaderboard_id': 1,
                           'vehicles': cdUSSR},
                          {'leaderboard_id': 2,
                           'vehicles': cdGER},
                          {'leaderboard_id': 3,
                           'vehicles': cdFRA},
                          {'leaderboard_id': 4,
                           'vehicles': cdCH},
                          {'leaderboard_id': 5,
                           'vehicles': cdJP}],
             'nations': [{'leaderboard_id': 0,
                          'nation': 'usa'},
                         {'leaderboard_id': 1,
                          'nation': 'ussr'},
                         {'leaderboard_id': 2,
                          'nation': 'germany'},
                         {'leaderboard_id': 3,
                          'nation': 'france'},
                         {'leaderboard_id': 4,
                          'nation': 'china'},
                         {'leaderboard_id': 5,
                          'nation': 'japan'},
                         {'leaderboard_id': 6,
                          'nation': 'czech'},
                         {'leaderboard_id': 7,
                          'nation': 'uk'},
                         {'leaderboard_id': 8,
                          'nation': 'poland'},
                         {'leaderboard_id': 9,
                          'nation': 'sweden'}],
             'vehicles_levels': [{'leaderboard_id': 0,
                                  'level': 5},
                                 {'leaderboard_id': 1,
                                  'level': 6},
                                 {'leaderboard_id': 2,
                                  'level': 7},
                                 {'leaderboard_id': 3,
                                  'level': 8},
                                 {'leaderboard_id': 4,
                                  'level': 9},
                                 {'leaderboard_id': 5,
                                  'level': 10}],
             'vehicles_classes': [{'leaderboard_id': 0,
                                   'class': 'heavyTank'},
                                  {'leaderboard_id': 1,
                                   'class': 'mediumTank'},
                                  {'leaderboard_id': 2,
                                   'class': 'lightTank'},
                                  {'leaderboard_id': 3,
                                   'class': 'AT-SPG'},
                                  {'leaderboard_id': 4,
                                   'class': 'SPG'}]},
  'rewards_by_rank': [{'leaderboard_id': 0,
                       'reward_groups': [{'reward_category_number': 1,
                                          'rank_min': 1,
                                          'rank_max': 1,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/additionalBriefing.png',
                                                       'rewards_amount': 3}, {'reward_type': '../maps/icons/quests/bonuses/small/aimingStabilizer.png',
                                                       'rewards_amount': 2}, {'reward_type': '../maps/icons/quests/bonuses/small/antifragmentationLining.png',
                                                       'rewards_amount': 1}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 2,
                                          'rank_max': 2,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/autoExtinguishers.png',
                                                       'rewards_amount': 4}, {'reward_type': '../maps/icons/quests/bonuses/small/berths.png',
                                                       'rewards_amount': 5}, {'reward_type': '../maps/icons/quests/bonuses/small/booster_credits.png',
                                                       'rewards_amount': 6}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 3,
                                          'rank_max': 3,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/booster_crew_xp.png',
                                                       'rewards_amount': 7}, {'reward_type': '../maps/icons/quests/bonuses/small/booster_free_xp.png',
                                                       'rewards_amount': 8}, {'reward_type': '../maps/icons/quests/bonuses/small/booster_xp.png',
                                                       'rewards_amount': 9}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 4,
                                          'rank_max': 4,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/booster_crew_xp.png',
                                                       'rewards_amount': 4}, {'reward_type': '../maps/icons/quests/bonuses/small/booster_free_xp.png',
                                                       'rewards_amount': 5}, {'reward_type': '../maps/icons/quests/bonuses/small/booster_xp.png',
                                                       'rewards_amount': 6}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 5,
                                          'rank_max': 5,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/booster_crew_xp.png',
                                                       'rewards_amount': 1}, {'reward_type': '../maps/icons/quests/bonuses/small/booster_free_xp.png',
                                                       'rewards_amount': 2}, {'reward_type': '../maps/icons/quests/bonuses/small/booster_xp.png',
                                                       'rewards_amount': 3}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 6,
                                          'rank_max': 6,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/camouflageNet.png',
                                                       'rewards_amount': 1}, {'reward_type': '../maps/icons/quests/bonuses/small/camouflages.png',
                                                       'rewards_amount': 2}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 7,
                                          'rank_max': 7,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/chocolate.png',
                                                       'rewards_amount': 1}, {'reward_type': '../maps/icons/quests/bonuses/small/coatedOptics.png',
                                                       'rewards_amount': 2}, {'reward_type': '../maps/icons/quests/bonuses/small/cocacola.png',
                                                       'rewards_amount': 3}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 8,
                                          'rank_max': 8,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/combatPayments.png',
                                                       'rewards_amount': 1}, {'reward_type': '../maps/icons/quests/bonuses/small/credits.png',
                                                       'rewards_amount': 2}, {'reward_type': '../maps/icons/quests/bonuses/small/crew.png',
                                                       'rewards_amount': 3}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 9,
                                          'rank_max': 9,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/crystal.png',
                                                       'rewards_amount': 1}, {'reward_type': '../maps/icons/quests/bonuses/small/default.png',
                                                       'rewards_amount': 2}, {'reward_type': '../maps/icons/quests/bonuses/small/emblems.png',
                                                       'rewards_amount': 3}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 10,
                                          'rank_max': 10,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/enhancedAimDrives.png',
                                                       'rewards_amount': 1}, {'reward_type': '../maps/icons/quests/bonuses/small/exp.png',
                                                       'rewards_amount': 2}]},
                                         {'reward_category_number': 2,
                                          'rank_min': 11,
                                          'rank_max': 50,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/antifragmentationLining.png',
                                                       'rewards_amount': 2}]},
                                         {'reward_category_number': 3,
                                          'rank_min': 51,
                                          'rank_max': 100,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/antifragmentationLining.png',
                                                       'rewards_amount': 2}]},
                                         {'reward_category_number': 4,
                                          'rank_min': 101,
                                          'rank_max': 1000,
                                          'rewards': []}]},
                      {'leaderboard_id': 1,
                       'reward_groups': [{'reward_category_number': 1,
                                          'rank_min': 1,
                                          'rank_max': 1,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/additionalBriefing.png',
                                                       'rewards_amount': 3}, {'reward_type': '../maps/icons/quests/bonuses/small/aimingStabilizer.png',
                                                       'rewards_amount': 2}, {'reward_type': '../maps/icons/quests/bonuses/small/antifragmentationLining.png',
                                                       'rewards_amount': 1}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 2,
                                          'rank_max': 2,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/autoExtinguishers.png',
                                                       'rewards_amount': 4}, {'reward_type': '../maps/icons/quests/bonuses/small/berths.png',
                                                       'rewards_amount': 5}, {'reward_type': '../maps/icons/quests/bonuses/small/booster_credits.png',
                                                       'rewards_amount': 6}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 3,
                                          'rank_max': 3,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/booster_crew_xp.png',
                                                       'rewards_amount': 7}, {'reward_type': '../maps/icons/quests/bonuses/small/booster_free_xp.png',
                                                       'rewards_amount': 8}, {'reward_type': '../maps/icons/quests/bonuses/small/booster_xp.png',
                                                       'rewards_amount': 9}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 4,
                                          'rank_max': 4,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/booster_crew_xp.png',
                                                       'rewards_amount': 4}, {'reward_type': '../maps/icons/quests/bonuses/small/booster_free_xp.png',
                                                       'rewards_amount': 5}, {'reward_type': '../maps/icons/quests/bonuses/small/booster_xp.png',
                                                       'rewards_amount': 6}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 5,
                                          'rank_max': 5,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/booster_crew_xp.png',
                                                       'rewards_amount': 1}, {'reward_type': '../maps/icons/quests/bonuses/small/booster_free_xp.png',
                                                       'rewards_amount': 2}, {'reward_type': '../maps/icons/quests/bonuses/small/booster_xp.png',
                                                       'rewards_amount': 3}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 6,
                                          'rank_max': 6,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/camouflageNet.png',
                                                       'rewards_amount': 1}, {'reward_type': '../maps/icons/quests/bonuses/small/camouflages.png',
                                                       'rewards_amount': 2}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 7,
                                          'rank_max': 7,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/chocolate.png',
                                                       'rewards_amount': 1}, {'reward_type': '../maps/icons/quests/bonuses/small/coatedOptics.png',
                                                       'rewards_amount': 2}, {'reward_type': '../maps/icons/quests/bonuses/small/cocacola.png',
                                                       'rewards_amount': 3}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 8,
                                          'rank_max': 8,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/combatPayments.png',
                                                       'rewards_amount': 1}, {'reward_type': '../maps/icons/quests/bonuses/small/credits.png',
                                                       'rewards_amount': 2}, {'reward_type': '../maps/icons/quests/bonuses/small/crew.png',
                                                       'rewards_amount': 3}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 9,
                                          'rank_max': 9,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/crystal.png',
                                                       'rewards_amount': 1}, {'reward_type': '../maps/icons/quests/bonuses/small/default.png',
                                                       'rewards_amount': 2}, {'reward_type': '../maps/icons/quests/bonuses/small/emblems.png',
                                                       'rewards_amount': 3}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 10,
                                          'rank_max': 10,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/enhancedAimDrives.png',
                                                       'rewards_amount': 1}, {'reward_type': '../maps/icons/quests/bonuses/small/exp.png',
                                                       'rewards_amount': 2}]},
                                         {'reward_category_number': 2,
                                          'rank_min': 11,
                                          'rank_max': 50,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/antifragmentationLining.png',
                                                       'rewards_amount': 2}]},
                                         {'reward_category_number': 3,
                                          'rank_min': 51,
                                          'rank_max': 100,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/antifragmentationLining.png',
                                                       'rewards_amount': 2}]},
                                         {'reward_category_number': 4,
                                          'rank_min': 101,
                                          'rank_max': 1000,
                                          'rewards': []}]},
                      {'leaderboard_id': 2,
                       'reward_groups': [{'reward_category_number': 1,
                                          'rank_min': 1,
                                          'rank_max': 1,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/additionalBriefing.png',
                                                       'rewards_amount': 3}, {'reward_type': '../maps/icons/quests/bonuses/small/aimingStabilizer.png',
                                                       'rewards_amount': 2}, {'reward_type': '../maps/icons/quests/bonuses/small/antifragmentationLining.png',
                                                       'rewards_amount': 1}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 2,
                                          'rank_max': 2,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/autoExtinguishers.png',
                                                       'rewards_amount': 4}, {'reward_type': '../maps/icons/quests/bonuses/small/berths.png',
                                                       'rewards_amount': 5}, {'reward_type': '../maps/icons/quests/bonuses/small/booster_credits.png',
                                                       'rewards_amount': 6}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 3,
                                          'rank_max': 3,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/booster_crew_xp.png',
                                                       'rewards_amount': 7}, {'reward_type': '../maps/icons/quests/bonuses/small/booster_free_xp.png',
                                                       'rewards_amount': 8}, {'reward_type': '../maps/icons/quests/bonuses/small/booster_xp.png',
                                                       'rewards_amount': 9}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 4,
                                          'rank_max': 4,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/booster_crew_xp.png',
                                                       'rewards_amount': 4}, {'reward_type': '../maps/icons/quests/bonuses/small/booster_free_xp.png',
                                                       'rewards_amount': 5}, {'reward_type': '../maps/icons/quests/bonuses/small/booster_xp.png',
                                                       'rewards_amount': 6}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 5,
                                          'rank_max': 5,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/booster_crew_xp.png',
                                                       'rewards_amount': 1}, {'reward_type': '../maps/icons/quests/bonuses/small/booster_free_xp.png',
                                                       'rewards_amount': 2}, {'reward_type': '../maps/icons/quests/bonuses/small/booster_xp.png',
                                                       'rewards_amount': 3}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 6,
                                          'rank_max': 6,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/camouflageNet.png',
                                                       'rewards_amount': 1}, {'reward_type': '../maps/icons/quests/bonuses/small/camouflages.png',
                                                       'rewards_amount': 2}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 7,
                                          'rank_max': 7,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/chocolate.png',
                                                       'rewards_amount': 1}, {'reward_type': '../maps/icons/quests/bonuses/small/coatedOptics.png',
                                                       'rewards_amount': 2}, {'reward_type': '../maps/icons/quests/bonuses/small/cocacola.png',
                                                       'rewards_amount': 3}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 8,
                                          'rank_max': 8,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/combatPayments.png',
                                                       'rewards_amount': 1}, {'reward_type': '../maps/icons/quests/bonuses/small/credits.png',
                                                       'rewards_amount': 2}, {'reward_type': '../maps/icons/quests/bonuses/small/crew.png',
                                                       'rewards_amount': 3}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 9,
                                          'rank_max': 9,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/crystal.png',
                                                       'rewards_amount': 1}, {'reward_type': '../maps/icons/quests/bonuses/small/default.png',
                                                       'rewards_amount': 2}, {'reward_type': '../maps/icons/quests/bonuses/small/emblems.png',
                                                       'rewards_amount': 3}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 10,
                                          'rank_max': 10,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/enhancedAimDrives.png',
                                                       'rewards_amount': 1}, {'reward_type': '../maps/icons/quests/bonuses/small/exp.png',
                                                       'rewards_amount': 2}]},
                                         {'reward_category_number': 2,
                                          'rank_min': 11,
                                          'rank_max': 50,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/antifragmentationLining.png',
                                                       'rewards_amount': 2}]},
                                         {'reward_category_number': 3,
                                          'rank_min': 51,
                                          'rank_max': 100,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/antifragmentationLining.png',
                                                       'rewards_amount': 2}]},
                                         {'reward_category_number': 4,
                                          'rank_min': 101,
                                          'rank_max': 1000,
                                          'rewards': []}]},
                      {'leaderboard_id': 3,
                       'reward_groups': [{'reward_category_number': 1,
                                          'rank_min': 1,
                                          'rank_max': 1,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/additionalBriefing.png',
                                                       'rewards_amount': 3}, {'reward_type': '../maps/icons/quests/bonuses/small/aimingStabilizer.png',
                                                       'rewards_amount': 2}, {'reward_type': '../maps/icons/quests/bonuses/small/antifragmentationLining.png',
                                                       'rewards_amount': 1}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 2,
                                          'rank_max': 2,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/autoExtinguishers.png',
                                                       'rewards_amount': 4}, {'reward_type': '../maps/icons/quests/bonuses/small/berths.png',
                                                       'rewards_amount': 5}, {'reward_type': '../maps/icons/quests/bonuses/small/booster_credits.png',
                                                       'rewards_amount': 6}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 3,
                                          'rank_max': 3,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/booster_crew_xp.png',
                                                       'rewards_amount': 7}, {'reward_type': '../maps/icons/quests/bonuses/small/booster_free_xp.png',
                                                       'rewards_amount': 8}, {'reward_type': '../maps/icons/quests/bonuses/small/booster_xp.png',
                                                       'rewards_amount': 9}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 4,
                                          'rank_max': 4,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/booster_crew_xp.png',
                                                       'rewards_amount': 4}, {'reward_type': '../maps/icons/quests/bonuses/small/booster_free_xp.png',
                                                       'rewards_amount': 5}, {'reward_type': '../maps/icons/quests/bonuses/small/booster_xp.png',
                                                       'rewards_amount': 6}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 5,
                                          'rank_max': 5,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/booster_crew_xp.png',
                                                       'rewards_amount': 1}, {'reward_type': '../maps/icons/quests/bonuses/small/booster_free_xp.png',
                                                       'rewards_amount': 2}, {'reward_type': '../maps/icons/quests/bonuses/small/booster_xp.png',
                                                       'rewards_amount': 3}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 6,
                                          'rank_max': 6,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/camouflageNet.png',
                                                       'rewards_amount': 1}, {'reward_type': '../maps/icons/quests/bonuses/small/camouflages.png',
                                                       'rewards_amount': 2}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 7,
                                          'rank_max': 7,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/chocolate.png',
                                                       'rewards_amount': 1}, {'reward_type': '../maps/icons/quests/bonuses/small/coatedOptics.png',
                                                       'rewards_amount': 2}, {'reward_type': '../maps/icons/quests/bonuses/small/cocacola.png',
                                                       'rewards_amount': 3}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 8,
                                          'rank_max': 8,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/combatPayments.png',
                                                       'rewards_amount': 1}, {'reward_type': '../maps/icons/quests/bonuses/small/credits.png',
                                                       'rewards_amount': 2}, {'reward_type': '../maps/icons/quests/bonuses/small/crew.png',
                                                       'rewards_amount': 3}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 9,
                                          'rank_max': 9,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/crystal.png',
                                                       'rewards_amount': 1}, {'reward_type': '../maps/icons/quests/bonuses/small/default.png',
                                                       'rewards_amount': 2}, {'reward_type': '../maps/icons/quests/bonuses/small/emblems.png',
                                                       'rewards_amount': 3}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 10,
                                          'rank_max': 10,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/enhancedAimDrives.png',
                                                       'rewards_amount': 1}, {'reward_type': '../maps/icons/quests/bonuses/small/exp.png',
                                                       'rewards_amount': 2}]},
                                         {'reward_category_number': 2,
                                          'rank_min': 11,
                                          'rank_max': 50,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/antifragmentationLining.png',
                                                       'rewards_amount': 2}]},
                                         {'reward_category_number': 3,
                                          'rank_min': 51,
                                          'rank_max': 100,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/antifragmentationLining.png',
                                                       'rewards_amount': 2}]},
                                         {'reward_category_number': 4,
                                          'rank_min': 101,
                                          'rank_max': 1000,
                                          'rewards': []}]},
                      {'leaderboard_id': 4,
                       'reward_groups': [{'reward_category_number': 1,
                                          'rank_min': 1,
                                          'rank_max': 1,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/additionalBriefing.png',
                                                       'rewards_amount': 3}, {'reward_type': '../maps/icons/quests/bonuses/small/aimingStabilizer.png',
                                                       'rewards_amount': 2}, {'reward_type': '../maps/icons/quests/bonuses/small/antifragmentationLining.png',
                                                       'rewards_amount': 1}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 2,
                                          'rank_max': 2,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/autoExtinguishers.png',
                                                       'rewards_amount': 4}, {'reward_type': '../maps/icons/quests/bonuses/small/berths.png',
                                                       'rewards_amount': 5}, {'reward_type': '../maps/icons/quests/bonuses/small/booster_credits.png',
                                                       'rewards_amount': 6}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 3,
                                          'rank_max': 3,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/booster_crew_xp.png',
                                                       'rewards_amount': 7}, {'reward_type': '../maps/icons/quests/bonuses/small/booster_free_xp.png',
                                                       'rewards_amount': 8}, {'reward_type': '../maps/icons/quests/bonuses/small/booster_xp.png',
                                                       'rewards_amount': 9}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 4,
                                          'rank_max': 4,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/booster_crew_xp.png',
                                                       'rewards_amount': 4}, {'reward_type': '../maps/icons/quests/bonuses/small/booster_free_xp.png',
                                                       'rewards_amount': 5}, {'reward_type': '../maps/icons/quests/bonuses/small/booster_xp.png',
                                                       'rewards_amount': 6}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 5,
                                          'rank_max': 5,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/booster_crew_xp.png',
                                                       'rewards_amount': 1}, {'reward_type': '../maps/icons/quests/bonuses/small/booster_free_xp.png',
                                                       'rewards_amount': 2}, {'reward_type': '../maps/icons/quests/bonuses/small/booster_xp.png',
                                                       'rewards_amount': 3}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 6,
                                          'rank_max': 6,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/camouflageNet.png',
                                                       'rewards_amount': 1}, {'reward_type': '../maps/icons/quests/bonuses/small/camouflages.png',
                                                       'rewards_amount': 2}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 7,
                                          'rank_max': 7,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/chocolate.png',
                                                       'rewards_amount': 1}, {'reward_type': '../maps/icons/quests/bonuses/small/coatedOptics.png',
                                                       'rewards_amount': 2}, {'reward_type': '../maps/icons/quests/bonuses/small/cocacola.png',
                                                       'rewards_amount': 3}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 8,
                                          'rank_max': 8,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/combatPayments.png',
                                                       'rewards_amount': 1}, {'reward_type': '../maps/icons/quests/bonuses/small/credits.png',
                                                       'rewards_amount': 2}, {'reward_type': '../maps/icons/quests/bonuses/small/crew.png',
                                                       'rewards_amount': 3}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 9,
                                          'rank_max': 9,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/crystal.png',
                                                       'rewards_amount': 1}, {'reward_type': '../maps/icons/quests/bonuses/small/default.png',
                                                       'rewards_amount': 2}, {'reward_type': '../maps/icons/quests/bonuses/small/emblems.png',
                                                       'rewards_amount': 3}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 10,
                                          'rank_max': 10,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/enhancedAimDrives.png',
                                                       'rewards_amount': 1}, {'reward_type': '../maps/icons/quests/bonuses/small/exp.png',
                                                       'rewards_amount': 2}]},
                                         {'reward_category_number': 2,
                                          'rank_min': 11,
                                          'rank_max': 50,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/antifragmentationLining.png',
                                                       'rewards_amount': 2}]},
                                         {'reward_category_number': 3,
                                          'rank_min': 51,
                                          'rank_max': 100,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/antifragmentationLining.png',
                                                       'rewards_amount': 2}]},
                                         {'reward_category_number': 4,
                                          'rank_min': 101,
                                          'rank_max': 1000,
                                          'rewards': []}]},
                      {'leaderboard_id': 5,
                       'reward_groups': [{'reward_category_number': 1,
                                          'rank_min': 1,
                                          'rank_max': 1,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/additionalBriefing.png',
                                                       'rewards_amount': 3}, {'reward_type': '../maps/icons/quests/bonuses/small/aimingStabilizer.png',
                                                       'rewards_amount': 2}, {'reward_type': '../maps/icons/quests/bonuses/small/antifragmentationLining.png',
                                                       'rewards_amount': 1}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 2,
                                          'rank_max': 2,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/autoExtinguishers.png',
                                                       'rewards_amount': 4}, {'reward_type': '../maps/icons/quests/bonuses/small/berths.png',
                                                       'rewards_amount': 5}, {'reward_type': '../maps/icons/quests/bonuses/small/booster_credits.png',
                                                       'rewards_amount': 6}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 3,
                                          'rank_max': 3,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/booster_crew_xp.png',
                                                       'rewards_amount': 7}, {'reward_type': '../maps/icons/quests/bonuses/small/booster_free_xp.png',
                                                       'rewards_amount': 8}, {'reward_type': '../maps/icons/quests/bonuses/small/booster_xp.png',
                                                       'rewards_amount': 9}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 4,
                                          'rank_max': 4,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/booster_crew_xp.png',
                                                       'rewards_amount': 4}, {'reward_type': '../maps/icons/quests/bonuses/small/booster_free_xp.png',
                                                       'rewards_amount': 5}, {'reward_type': '../maps/icons/quests/bonuses/small/booster_xp.png',
                                                       'rewards_amount': 6}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 5,
                                          'rank_max': 5,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/booster_crew_xp.png',
                                                       'rewards_amount': 1}, {'reward_type': '../maps/icons/quests/bonuses/small/booster_free_xp.png',
                                                       'rewards_amount': 2}, {'reward_type': '../maps/icons/quests/bonuses/small/booster_xp.png',
                                                       'rewards_amount': 3}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 6,
                                          'rank_max': 6,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/camouflageNet.png',
                                                       'rewards_amount': 1}, {'reward_type': '../maps/icons/quests/bonuses/small/camouflages.png',
                                                       'rewards_amount': 2}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 7,
                                          'rank_max': 7,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/chocolate.png',
                                                       'rewards_amount': 1}, {'reward_type': '../maps/icons/quests/bonuses/small/coatedOptics.png',
                                                       'rewards_amount': 2}, {'reward_type': '../maps/icons/quests/bonuses/small/cocacola.png',
                                                       'rewards_amount': 3}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 8,
                                          'rank_max': 8,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/combatPayments.png',
                                                       'rewards_amount': 1}, {'reward_type': '../maps/icons/quests/bonuses/small/credits.png',
                                                       'rewards_amount': 2}, {'reward_type': '../maps/icons/quests/bonuses/small/crew.png',
                                                       'rewards_amount': 3}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 9,
                                          'rank_max': 9,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/crystal.png',
                                                       'rewards_amount': 1}, {'reward_type': '../maps/icons/quests/bonuses/small/default.png',
                                                       'rewards_amount': 2}, {'reward_type': '../maps/icons/quests/bonuses/small/emblems.png',
                                                       'rewards_amount': 3}]},
                                         {'reward_category_number': 1,
                                          'rank_min': 10,
                                          'rank_max': 10,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/enhancedAimDrives.png',
                                                       'rewards_amount': 1}, {'reward_type': '../maps/icons/quests/bonuses/small/exp.png',
                                                       'rewards_amount': 2}]},
                                         {'reward_category_number': 2,
                                          'rank_min': 11,
                                          'rank_max': 50,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/antifragmentationLining.png',
                                                       'rewards_amount': 2}]},
                                         {'reward_category_number': 3,
                                          'rank_min': 51,
                                          'rank_max': 100,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/antifragmentationLining.png',
                                                       'rewards_amount': 2}]},
                                         {'reward_category_number': 4,
                                          'rank_min': 101,
                                          'rank_max': 1000,
                                          'rewards': []}]},
                      {'leaderboard_id': 6,
                       'reward_groups': [{'reward_category_number': 1,
                                          'rank_min': 1,
                                          'rank_max': 1,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/additionalBriefing.png',
                                                       'rewards_amount': 3}]},
                                         {'reward_category_number': 2,
                                          'rank_min': 11,
                                          'rank_max': 50,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/antifragmentationLining.png',
                                                       'rewards_amount': 2}]},
                                         {'reward_category_number': 3,
                                          'rank_min': 51,
                                          'rank_max': 100,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/antifragmentationLining.png',
                                                       'rewards_amount': 2}]},
                                         {'reward_category_number': 4,
                                          'rank_min': 101,
                                          'rank_max': 1000,
                                          'rewards': []}]},
                      {'leaderboard_id': 7,
                       'reward_groups': [{'reward_category_number': 1,
                                          'rank_min': 1,
                                          'rank_max': 1,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/additionalBriefing.png',
                                                       'rewards_amount': 3}]},
                                         {'reward_category_number': 2,
                                          'rank_min': 11,
                                          'rank_max': 50,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/antifragmentationLining.png',
                                                       'rewards_amount': 2}]},
                                         {'reward_category_number': 3,
                                          'rank_min': 51,
                                          'rank_max': 100,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/antifragmentationLining.png',
                                                       'rewards_amount': 2}]},
                                         {'reward_category_number': 4,
                                          'rank_min': 101,
                                          'rank_max': 1000,
                                          'rewards': []}]},
                      {'leaderboard_id': 8,
                       'reward_groups': [{'reward_category_number': 1,
                                          'rank_min': 1,
                                          'rank_max': 1,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/additionalBriefing.png',
                                                       'rewards_amount': 3}]},
                                         {'reward_category_number': 2,
                                          'rank_min': 11,
                                          'rank_max': 50,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/antifragmentationLining.png',
                                                       'rewards_amount': 2}]},
                                         {'reward_category_number': 3,
                                          'rank_min': 51,
                                          'rank_max': 100,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/antifragmentationLining.png',
                                                       'rewards_amount': 2}]},
                                         {'reward_category_number': 4,
                                          'rank_min': 101,
                                          'rank_max': 1000,
                                          'rewards': []}]},
                      {'leaderboard_id': 9,
                       'reward_groups': [{'reward_category_number': 1,
                                          'rank_min': 1,
                                          'rank_max': 1,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/additionalBriefing.png',
                                                       'rewards_amount': 3}]},
                                         {'reward_category_number': 2,
                                          'rank_min': 11,
                                          'rank_max': 50,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/antifragmentationLining.png',
                                                       'rewards_amount': 2}]},
                                         {'reward_category_number': 3,
                                          'rank_min': 51,
                                          'rank_max': 100,
                                          'rewards': [{'reward_type': '../maps/icons/quests/bonuses/small/antifragmentationLining.png',
                                                       'rewards_amount': 2}]},
                                         {'reward_category_number': 4,
                                          'rank_min': 101,
                                          'rank_max': 1000,
                                          'rewards': []}]}]}]
