# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/common/items/attributes_static.py
from items.attributes_helpers import CommonFactorsHelper, MODIFIER_TYPE
ALLOWED_STATIC_ATTRS = ['additiveShotDispersionFactor',
 'ammoBayHealthFactor',
 'ammoBayReduceFineFactor',
 'antifragmentationLiningFactor',
 'armorSpallsDamageDevicesFactor',
 'backwardMaxSpeedKMHTerm',
 'centerRotationFwdSpeedFactor',
 'chassis/shotDispersionFactors/movement',
 'chassis/shotDispersionFactors/rotation',
 'chassisHealthAfterHysteresisFactor',
 'chassisHealthFactor',
 'chassisRepairSpeedFactor',
 'circularVisionRadiusFactor',
 'circularVisionRadiusBaseFactor',
 'crewChanceToHitFactor',
 'crewLevelIncrease',
 ('damageFactor', MODIFIER_TYPE.MUL),
 'deathZones/sensitivityFactor',
 'decreaseOwnSpottingTime',
 'demaskFoliageFactor',
 'demaskMovingFactor',
 'engineHealthFactor',
 'enginePowerFactor',
 'engineReduceFineFactor',
 'fireStartingChanceFactor',
 'forwardMaxSpeedKMHTerm',
 'fuelTankHealthFactor',
 'gun/shotDispersionFactors/afterShot',
 'gun/shotDispersionFactors/turretRotation',
 'gun/shotDispersionFactors/whileGunDamaged',
 'gunAimingTimeFactor',
 'gunHealthFactor',
 'gunReloadTimeFactor',
 'healthFactor',
 'increaseEnemySpottingTime',
 'invisibilityBaseAdditive',
 'invisibilityAdditiveTerm',
 'invisibilityMultFactor',
 'invisibilityFactorAtShot',
 'multShotDispersionFactor',
 'onMoveRotationSpeedFactor',
 'onStillRotationSpeedFactor',
 'radioHealthFactor',
 'rammingFactor',
 'repairSpeedFactor',
 'repeatedStunDurationFactor',
 'rollingFrictionFactor',
 'stunResistanceDuration',
 'stunResistanceEffect',
 'surveyingDeviceHealthFactor',
 'turretRotationSpeed',
 'turretRotatorHealthFactor',
 'vehicleByChassisDamageFactor',
 'moduleDamageFactor',
 'engineAndFuelTanksDamageFactor']

class StaticFactorsHelper(CommonFactorsHelper):
    ALLOWED_ATTRS = ALLOWED_STATIC_ATTRS
    PREFIX = 'miscAttrs/'


attributes_static_factory = StaticFactorsHelper()
