# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/common/items/descr_modify_attrs_allowed.py
IS_NUMBER = False
IS_ARRAY = True
DESCR_MODIFY_ATTRS_ALLOWED = {'hull/maxHealth',
 'hullAimingParamsPitch/wheelsCorrectionSpeed',
 'chassis/rotationSpeedDegrees',
 'chassis/shotDispersionFactors',
 'engine/fireStartingChance',
 'engine/power',
 'engine/maxSpeedForward',
 'engine/maxSpeedBack',
 'shot0/piercingPower',
 'shot0/speed',
 'shell0/armorDamage',
 'shell0/deviceDamage',
 'shot1/piercingPower',
 'shot1/speed',
 'shell1/armorDamage',
 'shell1/deviceDamage',
 'shot2/piercingPower',
 'shot2/speed',
 'shell2/armorDamage',
 'shell2/deviceDamage',
 'turret/rotationSpeedDegrees',
 'turret/circularVisionRadius',
 'gun/reloadTime',
 'gun/maxAmmo',
 'gun/clip',
 'gun/burst',
 'gun/shotDispersionRadius',
 'gun/aimingTime',
 'gun/rotationSpeed',
 'gun/turretYawLimitsDegrees',
 'gun/invisibilityFactorAtShot',
 'gunPitchLimits/minPitchDegrees',
 'gunPitchLimits/maxPitchDegrees',
 'gunShotDispersionFactors/afterShot',
 'gunShotDispersionFactors/whileGunDamaged',
 'gunShotDispersionFactors/turretRotation',
 'twinGun/twinGunReloadTime'}
DESCR_MODIFY_ATTRS_TYPE = {'autoShoot/maxShotDispersion': IS_NUMBER,
 'autoShoot/shotDispersionPerSec': IS_NUMBER,
 'chassis/armorHomogenization': IS_NUMBER,
 'chassis/brakeForce': IS_NUMBER,
 'chassis/bulkHealthFactor': IS_NUMBER,
 'chassis/drivingWheelsSizes': IS_ARRAY,
 'chassis/minPlaneNormalY': IS_NUMBER,
 'chassis/rotationSpeed': IS_NUMBER,
 'chassis/rotationSpeedDegrees': IS_NUMBER,
 'chassis/shotDispersionFactors': IS_ARRAY,
 'chassis/specificFriction': IS_NUMBER,
 'chassis/terrainResistance': IS_ARRAY,
 'chassis/topRightCarryingPoint': IS_ARRAY,
 'dualAccuracy/afterShotDispersionAngle': IS_NUMBER,
 'dualAccuracy/coolingDelay': IS_NUMBER,
 'dualGun/afterShotDelay': IS_NUMBER,
 'dualGun/chargeCancelTime': IS_NUMBER,
 'dualGun/chargeThreshold': IS_NUMBER,
 'dualGun/chargeTime': IS_NUMBER,
 'dualGun/preChargeIndication': IS_NUMBER,
 'dualGun/rateTime': IS_NUMBER,
 'dualGun/reloadLockTime': IS_NUMBER,
 'dualGun/reloadTimes': IS_ARRAY,
 'dualGun/shootImpulse': IS_NUMBER,
 'engine/armorHomogenization': IS_NUMBER,
 'engine/fireStartingChance': IS_NUMBER,
 'engine/minFireStartingDamage': IS_NUMBER,
 'engine/power': IS_NUMBER,
 'engine/rpm_max': IS_NUMBER,
 'engine/rpm_min': IS_NUMBER,
 'engine/maxSpeedForward': IS_NUMBER,
 'engine/maxSpeedBack': IS_NUMBER,
 'fuelTank/armorHomogenization': IS_NUMBER,
 'gun/shotDispersionRadius': IS_NUMBER,
 'gun/aimingTime': IS_NUMBER,
 'gun/armorHomogenization': IS_NUMBER,
 'gun/burst': IS_ARRAY,
 'gun/clip': IS_ARRAY,
 'gun/forcedReloadTime': IS_NUMBER,
 'gun/impulse': IS_NUMBER,
 'gun/invisibilityFactorAtShot': IS_NUMBER,
 'gun/maxAmmo': IS_NUMBER,
 'gun/reloadTime': IS_NUMBER,
 'gun/rotationSpeed': IS_NUMBER,
 'gun/shootImpulses': IS_ARRAY,
 'gun/shotDispersionAngle': IS_NUMBER,
 'gun/shotOffset': IS_ARRAY,
 'gun/turretYawLimits': IS_ARRAY,
 'gun/turretYawLimitsDegrees': IS_ARRAY,
 'gunPitchLimits/absolute': IS_ARRAY,
 'gunPitchLimits/minPitchDegrees': IS_ARRAY,
 'gunPitchLimits/maxPitchDegrees': IS_ARRAY,
 'gunShotDispersionFactors/afterShot': IS_NUMBER,
 'gunShotDispersionFactors/afterShotInBurst': IS_NUMBER,
 'gunShotDispersionFactors/turretRotation': IS_NUMBER,
 'gunShotDispersionFactors/whileGunDamaged': IS_NUMBER,
 'hull/armorHomogenization': IS_NUMBER,
 'hull/maxHealth': IS_NUMBER,
 'hull/primaryArmor': IS_ARRAY,
 'hull/turretHardPoints': IS_ARRAY,
 'hull/turretPitches': IS_ARRAY,
 'hullAimingParamsPitch/wheelCorrectionCenterZ': IS_NUMBER,
 'hullAimingParamsPitch/wheelsCorrectionSpeed': IS_NUMBER,
 'radio/armorHomogenization': IS_NUMBER,
 'radio/distance': IS_NUMBER,
 'radio/radarCooldown': IS_NUMBER,
 'radio/radarRadius': IS_NUMBER,
 'shell0/armorDamage': IS_ARRAY,
 'shell0/caliber': IS_NUMBER,
 'shell0/damageRandomization': IS_NUMBER,
 'shell0/deviceDamage': IS_ARRAY,
 'shell0/maxDistance': IS_NUMBER,
 'shell0/piercingPowerRandomization': IS_NUMBER,
 'shell1/armorDamage': IS_ARRAY,
 'shell1/caliber': IS_NUMBER,
 'shell1/damageRandomization': IS_NUMBER,
 'shell1/deviceDamage': IS_ARRAY,
 'shell1/maxDistance': IS_NUMBER,
 'shell1/piercingPowerRandomization': IS_NUMBER,
 'shell2/armorDamage': IS_ARRAY,
 'shell2/caliber': IS_NUMBER,
 'shell2/damageRandomization': IS_NUMBER,
 'shell2/deviceDamage': IS_ARRAY,
 'shell2/maxDistance': IS_NUMBER,
 'shell2/piercingPowerRandomization': IS_NUMBER,
 'shellType0/nonPiercingArmorDamage': IS_NUMBER,
 'shellType0/normalizationAngle': IS_NUMBER,
 'shellType0/ricochetAngleCos': IS_NUMBER,
 'shellTypeArmorSpalls0/armorDamage': IS_ARRAY,
 'shellTypeArmorSpalls0/coneAngleCos': IS_NUMBER,
 'shellTypeArmorSpalls0/deviceDamage': IS_ARRAY,
 'shellTypeArmorSpalls0/radius': IS_NUMBER,
 'shellType1/nonPiercingArmorDamage': IS_NUMBER,
 'shellType1/piercingPowerLossFactorByDistance': IS_NUMBER,
 'shellType1/ricochetAngleCos': IS_NUMBER,
 'shellTypeArmorSpalls1/armorDamage': IS_ARRAY,
 'shellTypeArmorSpalls1/coneAngleCos': IS_NUMBER,
 'shellTypeArmorSpalls1/deviceDamage': IS_ARRAY,
 'shellTypeArmorSpalls1/radius': IS_NUMBER,
 'shellType2/explosionDamageAbsorptionFactor': IS_NUMBER,
 'shellType2/explosionDamageFactor': IS_NUMBER,
 'shellType2/explosionEdgeDamageFactor': IS_NUMBER,
 'shellType2/explosionRadius': IS_NUMBER,
 'shellType2/maxDamage': IS_NUMBER,
 'shellType2/shellFragmentsDamageAbsorptionFactor': IS_NUMBER,
 'shellTypeArmorSpalls2/armorDamage': IS_ARRAY,
 'shellTypeArmorSpalls2/coneAngleCos': IS_NUMBER,
 'shellTypeArmorSpalls2/deviceDamage': IS_ARRAY,
 'shellTypeArmorSpalls2/radius': IS_NUMBER,
 'shot0/defaultPortion': IS_NUMBER,
 'shot0/gravity': IS_NUMBER,
 'shot0/maxDistance': IS_NUMBER,
 'shot0/maxHeight': IS_NUMBER,
 'shot0/nominalMaxDistance': IS_NUMBER,
 'shot0/piercingPower': IS_ARRAY,
 'shot0/speed': IS_NUMBER,
 'shot1/defaultPortion': IS_NUMBER,
 'shot1/gravity': IS_NUMBER,
 'shot1/maxDistance': IS_NUMBER,
 'shot1/maxHeight': IS_NUMBER,
 'shot1/nominalMaxDistance': IS_NUMBER,
 'shot1/piercingPower': IS_ARRAY,
 'shot1/speed': IS_NUMBER,
 'shot2/defaultPortion': IS_NUMBER,
 'shot2/gravity': IS_NUMBER,
 'shot2/maxDistance': IS_NUMBER,
 'shot2/maxHeight': IS_NUMBER,
 'shot2/nominalMaxDistance': IS_NUMBER,
 'shot2/piercingPower': IS_ARRAY,
 'shot2/speed': IS_NUMBER,
 'siegeModeParams/engineDamageCoeff': IS_NUMBER,
 'siegeModeParams/switchOffTime': IS_NUMBER,
 'siegeModeParams/switchOnTime': IS_NUMBER,
 'turret/armorHomogenization': IS_NUMBER,
 'turret/circularVisionRadius': IS_NUMBER,
 'turret/gunJointPitch': IS_NUMBER,
 'turret/invisibilityFactor': IS_NUMBER,
 'turret/primaryArmor': IS_ARRAY,
 'turret/rotationSpeedDegrees': IS_NUMBER,
 'twinGun/afterShotDelay': IS_NUMBER,
 'twinGun/gunMarkerOffset': IS_NUMBER,
 'twinGun/shootImpulse': IS_NUMBER,
 'twinGun/twinGunReloadTime': IS_NUMBER,
 'type/healthBurnPerSec': IS_NUMBER,
 'type/healthBurnPerSecLossFraction': IS_NUMBER,
 'type/invisibility': IS_ARRAY,
 'type/speedLimits': IS_ARRAY,
 'typeDamageByStaticsChances/module': IS_NUMBER,
 'typeDamageByStaticsChances/tankman': IS_NUMBER,
 'typeInvisibilityDeltas/camouflageBonus': IS_NUMBER,
 'typeInvisibilityDeltas/firePenalty': IS_NUMBER,
 'xphysicsChassis/angVelocityFactor': IS_NUMBER,
 'xphysicsChassis/angVelocityFactor0': IS_NUMBER,
 'xphysicsChassis/axleCount': IS_NUMBER,
 'xphysicsChassis/bkLagRatio': IS_NUMBER,
 'xphysicsChassis/bodyHeight': IS_NUMBER,
 'xphysicsChassis/brake': IS_NUMBER,
 'xphysicsChassis/centerRotationFwdSpeed': IS_NUMBER,
 'xphysicsChassis/chassisMassFraction': IS_NUMBER,
 'xphysicsChassis/chsDmgMultiplier': IS_NUMBER,
 'xphysicsChassis/clearance': IS_NUMBER,
 'xphysicsChassis/comFrictionYOffs': IS_NUMBER,
 'xphysicsChassis/comSideFriction': IS_NUMBER,
 'xphysicsChassis/damping': IS_NUMBER,
 'xphysicsChassis/fwLagRatio': IS_NUMBER,
 'xphysicsChassis/gimletGoalWOnMove': IS_NUMBER,
 'xphysicsChassis/gimletGoalWOnSpot': IS_NUMBER,
 'xphysicsChassis/gimletPushOnMoveFinal': IS_NUMBER,
 'xphysicsChassis/gimletPushOnMoveInit': IS_NUMBER,
 'xphysicsChassis/gimletPushOnSpotFinal': IS_NUMBER,
 'xphysicsChassis/gimletPushOnSpotInit': IS_NUMBER,
 'xphysicsChassis/gimletVelScaleMax': IS_NUMBER,
 'xphysicsChassis/gimletVelScaleMin': IS_NUMBER,
 'xphysicsChassis/hullCOM': IS_ARRAY,
 'xphysicsChassis/hullCOMShiftY': IS_NUMBER,
 'xphysicsChassis/hullInertiaFactors': IS_ARRAY,
 'xphysicsChassis/movementRevertSpeed': IS_NUMBER,
 'xphysicsChassis/pushRotOnMoveFixedPeriod': IS_NUMBER,
 'xphysicsChassis/pushRotOnMoveGrowPeriod': IS_NUMBER,
 'xphysicsChassis/pushRotOnSpotFixedPeriod': IS_NUMBER,
 'xphysicsChassis/pushRotOnSpotGrowPeriod': IS_NUMBER,
 'xphysicsChassis/pushStop': IS_NUMBER,
 'xphysicsChassis/roadWheelPositions': IS_ARRAY,
 'xphysicsChassis/rotFritionFactor': IS_NUMBER,
 'xphysicsChassis/rotationBrake': IS_NUMBER,
 'xphysicsChassis/rotationByLockChoker': IS_NUMBER,
 'xphysicsChassis/sideFrictionConstantRatio': IS_NUMBER,
 'xphysicsChassis/stiffness0': IS_NUMBER,
 'xphysicsChassis/stiffness1': IS_NUMBER,
 'xphysicsChassis/stiffnessFactors': IS_ARRAY,
 'xphysicsChassis/wPushedDiag': IS_NUMBER,
 'xphysicsChassis/wPushedMediumFactor': IS_NUMBER,
 'xphysicsChassis/wPushedRot': IS_NUMBER,
 'xphysicsChassis/wPushedSoftFactor': IS_NUMBER,
 'xphysicsChassis/wheelInertiaFactor': IS_NUMBER,
 'xphysicsChassis/wheelRadius': IS_NUMBER,
 'xphysicsChassis/wheelSinkageResistFactor': IS_NUMBER,
 'xphysicsChassis/wheelStroke': IS_NUMBER,
 'xphysicsEngine/engineInertia': IS_NUMBER,
 'xphysicsEngine/engineLoses': IS_ARRAY,
 'xphysicsEngine/idleChoker': IS_NUMBER,
 'xphysicsEngine/idleRPM': IS_NUMBER,
 'xphysicsEngine/powerFactor': IS_NUMBER,
 'xphysicsEngine/rotationFactor': IS_NUMBER,
 'xphysicsEngine/smplBkMaxSpeed': IS_NUMBER,
 'xphysicsEngine/smplEnginePower': IS_NUMBER,
 'xphysicsEngine/smplFwMaxSpeed': IS_NUMBER,
 'xphysicsEngine/startRPM': IS_NUMBER}
