# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/common/epic_missions_config.py
from personal_missions_constants import PROGRESS_TEMPLATE, CONDITION_ICON, VISIBLE_SCOPE, CRIT_TYPES
_config = {'lightTank_shots_easy': {'hits': {'type': PROGRESS_TEMPLATE.VALUE,
                                   'config': {'goal': 2,
                                              'isMain': True,
                                              'isAward': True,
                                              'isCumulative': True,
                                              'visibleScope': [VISIBLE_SCOPE.BATTLE],
                                              'params': {'attackReasons': ['shot']}},
                                   'description': 'lightTank_shots_plural',
                                   'icon': CONDITION_ICON.HIT}},
 'lightTank_shots_medium': {'hits': {'type': PROGRESS_TEMPLATE.VALUE,
                                     'config': {'goal': 4,
                                                'isMain': True,
                                                'isAward': True,
                                                'isCumulative': True,
                                                'visibleScope': [VISIBLE_SCOPE.BATTLE],
                                                'params': {'attackReasons': ['shot']}},
                                     'description': 'lightTank_shots_plural',
                                     'icon': CONDITION_ICON.HIT}},
 'lightTank_shots_hard': {'hits': {'type': PROGRESS_TEMPLATE.VALUE,
                                   'config': {'goal': 7,
                                              'isMain': True,
                                              'isAward': True,
                                              'isCumulative': True,
                                              'visibleScope': [VISIBLE_SCOPE.BATTLE],
                                              'params': {'attackReasons': ['shot']}},
                                   'description': 'lightTank_shots_plural',
                                   'icon': CONDITION_ICON.HIT}},
 'lightTank_damage_easy': {'damage': {'type': PROGRESS_TEMPLATE.VALUE,
                                      'config': {'goal': 400,
                                                 'isMain': True,
                                                 'isAward': True,
                                                 'isCumulative': True,
                                                 'visibleScope': [VISIBLE_SCOPE.BATTLE]},
                                      'description': 'lightTank_damage',
                                      'icon': CONDITION_ICON.DAMAGE}},
 'lightTank_damage_medium': {'damage': {'type': PROGRESS_TEMPLATE.VALUE,
                                        'config': {'goal': 700,
                                                   'isMain': True,
                                                   'isAward': True,
                                                   'isCumulative': True,
                                                   'visibleScope': [VISIBLE_SCOPE.BATTLE]},
                                        'description': 'lightTank_damage',
                                        'icon': CONDITION_ICON.DAMAGE}},
 'lightTank_damage_hard': {'damage': {'type': PROGRESS_TEMPLATE.VALUE,
                                      'config': {'goal': 1100,
                                                 'isMain': True,
                                                 'isAward': True,
                                                 'isCumulative': True,
                                                 'visibleScope': [VISIBLE_SCOPE.BATTLE]},
                                      'description': 'lightTank_damage',
                                      'icon': CONDITION_ICON.DAMAGE}},
 'lightTank_kills_easy': {'kills': {'type': PROGRESS_TEMPLATE.VALUE,
                                    'config': {'goal': 1,
                                               'isMain': True,
                                               'isAward': True,
                                               'isCumulative': True,
                                               'visibleScope': [VISIBLE_SCOPE.BATTLE]},
                                    'description': 'lightTank_kills',
                                    'icon': CONDITION_ICON.KILL_VEHICLES}},
 'lightTank_kills_medium': {'kills': {'type': PROGRESS_TEMPLATE.VALUE,
                                      'config': {'goal': 2,
                                                 'isMain': True,
                                                 'isAward': True,
                                                 'isCumulative': True,
                                                 'visibleScope': [VISIBLE_SCOPE.BATTLE]},
                                      'description': 'lightTank_kills',
                                      'icon': CONDITION_ICON.KILL_VEHICLES}},
 'lightTank_kills_hard': {'kills': {'type': PROGRESS_TEMPLATE.VALUE,
                                    'config': {'goal': 3,
                                               'isMain': True,
                                               'isAward': True,
                                               'isCumulative': True,
                                               'visibleScope': [VISIBLE_SCOPE.BATTLE]},
                                    'description': 'lightTank_kills',
                                    'icon': CONDITION_ICON.KILL_VEHICLES}},
 'lightTank_critsTracks_easy': {'crits': {'type': PROGRESS_TEMPLATE.VALUE,
                                          'config': {'goal': 1,
                                                     'isMain': True,
                                                     'isAward': True,
                                                     'isCumulative': True,
                                                     'visibleScope': [VISIBLE_SCOPE.BATTLE],
                                                     'params': {'critTypes': CRIT_TYPES.DESTROYED_TRACKS}},
                                          'description': 'lightTank_critsTracks',
                                          'icon': CONDITION_ICON.MODULE_CRIT}},
 'lightTank_critsTracks_medium': {'crits': {'type': PROGRESS_TEMPLATE.VALUE,
                                            'config': {'goal': 2,
                                                       'isMain': True,
                                                       'isAward': True,
                                                       'isCumulative': True,
                                                       'visibleScope': [VISIBLE_SCOPE.BATTLE],
                                                       'params': {'critTypes': CRIT_TYPES.DESTROYED_TRACKS}},
                                            'description': 'lightTank_critsTracks',
                                            'icon': CONDITION_ICON.MODULE_CRIT}},
 'lightTank_critsTracks_hard': {'crits': {'type': PROGRESS_TEMPLATE.VALUE,
                                          'config': {'goal': 3,
                                                     'isMain': True,
                                                     'isAward': True,
                                                     'isCumulative': True,
                                                     'visibleScope': [VISIBLE_SCOPE.BATTLE],
                                                     'params': {'critTypes': CRIT_TYPES.DESTROYED_TRACKS}},
                                          'description': 'lightTank_critsTracks',
                                          'icon': CONDITION_ICON.MODULE_CRIT}},
 'mediumTank_shots_easy': {'hits': {'type': PROGRESS_TEMPLATE.VALUE,
                                    'config': {'goal': 3,
                                               'isMain': True,
                                               'isAward': True,
                                               'isCumulative': True,
                                               'visibleScope': [VISIBLE_SCOPE.BATTLE],
                                               'params': {'attackReasons': ['shot']}},
                                    'description': 'mediumTank_shots_plural',
                                    'icon': CONDITION_ICON.HIT}},
 'mediumTank_shots_medium': {'hits': {'type': PROGRESS_TEMPLATE.VALUE,
                                      'config': {'goal': 6,
                                                 'isMain': True,
                                                 'isAward': True,
                                                 'isCumulative': True,
                                                 'visibleScope': [VISIBLE_SCOPE.BATTLE],
                                                 'params': {'attackReasons': ['shot']}},
                                      'description': 'mediumTank_shots_plural',
                                      'icon': CONDITION_ICON.HIT}},
 'mediumTank_shots_hard': {'hits': {'type': PROGRESS_TEMPLATE.VALUE,
                                    'config': {'goal': 9,
                                               'isMain': True,
                                               'isAward': True,
                                               'isCumulative': True,
                                               'visibleScope': [VISIBLE_SCOPE.BATTLE],
                                               'params': {'attackReasons': ['shot']}},
                                    'description': 'mediumTank_shots_plural',
                                    'icon': CONDITION_ICON.HIT}},
 'mediumTank_damage_easy': {'damage': {'type': PROGRESS_TEMPLATE.VALUE,
                                       'config': {'goal': 800,
                                                  'isMain': True,
                                                  'isAward': True,
                                                  'isCumulative': True,
                                                  'visibleScope': [VISIBLE_SCOPE.BATTLE]},
                                       'description': 'mediumTank_damage',
                                       'icon': CONDITION_ICON.DAMAGE}},
 'mediumTank_damage_medium': {'damage': {'type': PROGRESS_TEMPLATE.VALUE,
                                         'config': {'goal': 1300,
                                                    'isMain': True,
                                                    'isAward': True,
                                                    'isCumulative': True,
                                                    'visibleScope': [VISIBLE_SCOPE.BATTLE]},
                                         'description': 'mediumTank_damage',
                                         'icon': CONDITION_ICON.DAMAGE}},
 'mediumTank_damage_hard': {'damage': {'type': PROGRESS_TEMPLATE.VALUE,
                                       'config': {'goal': 2100,
                                                  'isMain': True,
                                                  'isAward': True,
                                                  'isCumulative': True,
                                                  'visibleScope': [VISIBLE_SCOPE.BATTLE]},
                                       'description': 'mediumTank_damage',
                                       'icon': CONDITION_ICON.DAMAGE}},
 'mediumTank_hits_easy': {'hits': {'type': PROGRESS_TEMPLATE.VALUE,
                                   'config': {'goal': 2,
                                              'isMain': True,
                                              'isAward': True,
                                              'isCumulative': True,
                                              'visibleScope': [VISIBLE_SCOPE.BATTLE],
                                              'params': {'uniqueTargetAndType': True}},
                                   'description': 'mediumTank_hits',
                                   'icon': CONDITION_ICON.HIT}},
 'mediumTank_hits_medium': {'hits': {'type': PROGRESS_TEMPLATE.VALUE,
                                     'config': {'goal': 4,
                                                'isMain': True,
                                                'isAward': True,
                                                'isCumulative': True,
                                                'visibleScope': [VISIBLE_SCOPE.BATTLE],
                                                'params': {'uniqueTargetAndType': True}},
                                     'description': 'mediumTank_hits',
                                     'icon': CONDITION_ICON.HIT}},
 'mediumTank_hits_hard': {'hits': {'type': PROGRESS_TEMPLATE.VALUE,
                                   'config': {'goal': 6,
                                              'isMain': True,
                                              'isAward': True,
                                              'isCumulative': True,
                                              'visibleScope': [VISIBLE_SCOPE.BATTLE],
                                              'params': {'uniqueTargetAndType': True}},
                                   'description': 'mediumTank_hits',
                                   'icon': CONDITION_ICON.HIT}},
 'mediumTank_hitsDiversity_easy': {'hitsDiversity': {'type': PROGRESS_TEMPLATE.COUNTER,
                                                     'config': {'uniqueGoal': 2,
                                                                'totalGoal': 2,
                                                                'isMain': True,
                                                                'isAward': True,
                                                                'isCumulative': True,
                                                                'visibleScope': [VISIBLE_SCOPE.BATTLE]},
                                                     'description': 'mediumTank_hitsDiversity',
                                                     'icon': CONDITION_ICON.HURT_VEHICLES}},
 'mediumTank_hitsDiversity_medium': {'hitsDiversity': {'type': PROGRESS_TEMPLATE.COUNTER,
                                                       'config': {'uniqueGoal': 3,
                                                                  'totalGoal': 3,
                                                                  'isMain': True,
                                                                  'isAward': True,
                                                                  'isCumulative': True,
                                                                  'visibleScope': [VISIBLE_SCOPE.BATTLE]},
                                                       'description': 'mediumTank_hitsDiversity',
                                                       'icon': CONDITION_ICON.HURT_VEHICLES}},
 'mediumTank_kills_easy': {'kills': {'type': PROGRESS_TEMPLATE.VALUE,
                                     'config': {'goal': 1,
                                                'isMain': True,
                                                'isAward': True,
                                                'isCumulative': True,
                                                'visibleScope': [VISIBLE_SCOPE.BATTLE]},
                                     'description': 'mediumTank_kills',
                                     'icon': CONDITION_ICON.KILL_VEHICLES}},
 'mediumTank_kills_medium': {'kills': {'type': PROGRESS_TEMPLATE.VALUE,
                                       'config': {'goal': 2,
                                                  'isMain': True,
                                                  'isAward': True,
                                                  'isCumulative': True,
                                                  'visibleScope': [VISIBLE_SCOPE.BATTLE]},
                                       'description': 'mediumTank_kills',
                                       'icon': CONDITION_ICON.KILL_VEHICLES}},
 'mediumTank_kills_hard': {'kills': {'type': PROGRESS_TEMPLATE.VALUE,
                                     'config': {'goal': 3,
                                                'isMain': True,
                                                'isAward': True,
                                                'isCumulative': True,
                                                'visibleScope': [VISIBLE_SCOPE.BATTLE]},
                                     'description': 'mediumTank_kills',
                                     'icon': CONDITION_ICON.KILL_VEHICLES}},
 'mediumTank_killsDiversity_medium': {'killsDiversity': {'type': PROGRESS_TEMPLATE.COUNTER,
                                                         'config': {'uniqueGoal': 2,
                                                                    'totalGoal': 2,
                                                                    'isMain': True,
                                                                    'isAward': True,
                                                                    'isCumulative': True,
                                                                    'visibleScope': [VISIBLE_SCOPE.BATTLE]},
                                                         'description': 'mediumTank_killsDiversity',
                                                         'icon': CONDITION_ICON.KILL_VEHICLES}},
 'mediumTank_critsTracks_easy': {'crits': {'type': PROGRESS_TEMPLATE.VALUE,
                                           'config': {'goal': 1,
                                                      'isMain': True,
                                                      'isAward': True,
                                                      'isCumulative': True,
                                                      'visibleScope': [VISIBLE_SCOPE.BATTLE],
                                                      'params': {'critTypes': CRIT_TYPES.DESTROYED_TRACKS}},
                                           'description': 'mediumTank_critsTracks',
                                           'icon': CONDITION_ICON.MODULE_CRIT}},
 'mediumTank_critsTracks_medium': {'crits': {'type': PROGRESS_TEMPLATE.VALUE,
                                             'config': {'goal': 2,
                                                        'isMain': True,
                                                        'isAward': True,
                                                        'isCumulative': True,
                                                        'visibleScope': [VISIBLE_SCOPE.BATTLE],
                                                        'params': {'critTypes': CRIT_TYPES.DESTROYED_TRACKS}},
                                             'description': 'mediumTank_critsTracks',
                                             'icon': CONDITION_ICON.MODULE_CRIT}},
 'mediumTank_critsTracks_hard': {'crits': {'type': PROGRESS_TEMPLATE.VALUE,
                                           'config': {'goal': 3,
                                                      'isMain': True,
                                                      'isAward': True,
                                                      'isCumulative': True,
                                                      'visibleScope': [VISIBLE_SCOPE.BATTLE],
                                                      'params': {'critTypes': CRIT_TYPES.DESTROYED_TRACKS}},
                                           'description': 'mediumTank_critsTracks',
                                           'icon': CONDITION_ICON.MODULE_CRIT}},
 'heavyTank_kills_easy': {'kills': {'type': PROGRESS_TEMPLATE.VALUE,
                                    'config': {'goal': 1,
                                               'isMain': True,
                                               'isAward': True,
                                               'isCumulative': True,
                                               'visibleScope': [VISIBLE_SCOPE.BATTLE]},
                                    'description': 'heavyTank_kills',
                                    'icon': CONDITION_ICON.KILL_VEHICLES}},
 'heavyTank_kills_medium': {'kills': {'type': PROGRESS_TEMPLATE.VALUE,
                                      'config': {'goal': 2,
                                                 'isMain': True,
                                                 'isAward': True,
                                                 'isCumulative': True,
                                                 'visibleScope': [VISIBLE_SCOPE.BATTLE]},
                                      'description': 'heavyTank_kills',
                                      'icon': CONDITION_ICON.KILL_VEHICLES}},
 'heavyTank_kills_hard': {'kills': {'type': PROGRESS_TEMPLATE.VALUE,
                                    'config': {'goal': 3,
                                               'isMain': True,
                                               'isAward': True,
                                               'isCumulative': True,
                                               'visibleScope': [VISIBLE_SCOPE.BATTLE]},
                                    'description': 'heavyTank_kills',
                                    'icon': CONDITION_ICON.KILL_VEHICLES}},
 'heavyTank_killsDiversity_medium': {'killsDiversity': {'type': PROGRESS_TEMPLATE.COUNTER,
                                                        'config': {'uniqueGoal': 2,
                                                                   'totalGoal': 2,
                                                                   'isMain': True,
                                                                   'isAward': True,
                                                                   'isCumulative': True,
                                                                   'visibleScope': [VISIBLE_SCOPE.BATTLE]},
                                                        'description': 'heavyTank_killsDiversity',
                                                        'icon': CONDITION_ICON.KILL_VEHICLES}},
 'heavyTank_damage_easy': {'damage': {'type': PROGRESS_TEMPLATE.VALUE,
                                      'config': {'goal': 800,
                                                 'isMain': True,
                                                 'isAward': True,
                                                 'isCumulative': True,
                                                 'visibleScope': [VISIBLE_SCOPE.BATTLE]},
                                      'description': 'heavyTank_damage',
                                      'icon': CONDITION_ICON.DAMAGE}},
 'heavyTank_damage_medium': {'damage': {'type': PROGRESS_TEMPLATE.VALUE,
                                        'config': {'goal': 1400,
                                                   'isMain': True,
                                                   'isAward': True,
                                                   'isCumulative': True,
                                                   'visibleScope': [VISIBLE_SCOPE.BATTLE]},
                                        'description': 'heavyTank_damage',
                                        'icon': CONDITION_ICON.DAMAGE}},
 'heavyTank_damage_hard': {'damage': {'type': PROGRESS_TEMPLATE.VALUE,
                                      'config': {'goal': 2300,
                                                 'isMain': True,
                                                 'isAward': True,
                                                 'isCumulative': True,
                                                 'visibleScope': [VISIBLE_SCOPE.BATTLE]},
                                      'description': 'heavyTank_damage',
                                      'icon': CONDITION_ICON.DAMAGE}},
 'heavyTank_damageDealtReceivedAndBlocked_easy': {'damageDealtReceivedAndBlocked': {'type': PROGRESS_TEMPLATE.VALUE,
                                                                                    'config': {'goal': 2000,
                                                                                               'isMain': True,
                                                                                               'isAward': True,
                                                                                               'isCumulative': True,
                                                                                               'visibleScope': [VISIBLE_SCOPE.BATTLE]},
                                                                                    'description': 'heavyTank_damageDealtReceivedAndBlocked',
                                                                                    'icon': CONDITION_ICON.FOLDER}},
 'heavyTank_damageDealtReceivedAndBlocked_medium': {'damageDealtReceivedAndBlocked': {'type': PROGRESS_TEMPLATE.VALUE,
                                                                                      'config': {'goal': 3500,
                                                                                                 'isMain': True,
                                                                                                 'isAward': True,
                                                                                                 'isCumulative': True,
                                                                                                 'visibleScope': [VISIBLE_SCOPE.BATTLE]},
                                                                                      'description': 'heavyTank_damageDealtReceivedAndBlocked',
                                                                                      'icon': CONDITION_ICON.FOLDER}},
 'heavyTank_damageDealtReceivedAndBlocked_hard': {'damageDealtReceivedAndBlocked': {'type': PROGRESS_TEMPLATE.VALUE,
                                                                                    'config': {'goal': 5750,
                                                                                               'isMain': True,
                                                                                               'isAward': True,
                                                                                               'isCumulative': True,
                                                                                               'visibleScope': [VISIBLE_SCOPE.BATTLE]},
                                                                                    'description': 'heavyTank_damageDealtReceivedAndBlocked',
                                                                                    'icon': CONDITION_ICON.FOLDER}},
 'ATSPG_damage_easy': {'damage': {'type': PROGRESS_TEMPLATE.VALUE,
                                  'config': {'goal': 900,
                                             'isMain': True,
                                             'isAward': True,
                                             'isCumulative': True,
                                             'visibleScope': [VISIBLE_SCOPE.BATTLE]},
                                  'description': 'AT_SPG_damage',
                                  'icon': CONDITION_ICON.DAMAGE}},
 'ATSPG_damage_medium': {'damage': {'type': PROGRESS_TEMPLATE.VALUE,
                                    'config': {'goal': 1500,
                                               'isMain': True,
                                               'isAward': True,
                                               'isCumulative': True,
                                               'visibleScope': [VISIBLE_SCOPE.BATTLE]},
                                    'description': 'AT_SPG_damage',
                                    'icon': CONDITION_ICON.DAMAGE}},
 'ATSPG_damage_hard': {'damage': {'type': PROGRESS_TEMPLATE.VALUE,
                                  'config': {'goal': 2400,
                                             'isMain': True,
                                             'isAward': True,
                                             'isCumulative': True,
                                             'visibleScope': [VISIBLE_SCOPE.BATTLE]},
                                  'description': 'AT_SPG_damage',
                                  'icon': CONDITION_ICON.DAMAGE}},
 'ATSPG_hits_easy': {'hits': {'type': PROGRESS_TEMPLATE.VALUE,
                              'config': {'goal': 2,
                                         'isMain': True,
                                         'isAward': True,
                                         'isCumulative': True,
                                         'visibleScope': [VISIBLE_SCOPE.BATTLE],
                                         'params': {'uniqueTargetAndType': True}},
                              'description': 'AT_SPG_hits',
                              'icon': CONDITION_ICON.HIT}},
 'ATSPG_hits_medium': {'hits': {'type': PROGRESS_TEMPLATE.VALUE,
                                'config': {'goal': 4,
                                           'isMain': True,
                                           'isAward': True,
                                           'isCumulative': True,
                                           'visibleScope': [VISIBLE_SCOPE.BATTLE],
                                           'params': {'uniqueTargetAndType': True}},
                                'description': 'AT_SPG_hits',
                                'icon': CONDITION_ICON.HIT}},
 'ATSPG_hits_hard': {'hits': {'type': PROGRESS_TEMPLATE.VALUE,
                              'config': {'goal': 6,
                                         'isMain': True,
                                         'isAward': True,
                                         'isCumulative': True,
                                         'visibleScope': [VISIBLE_SCOPE.BATTLE],
                                         'params': {'uniqueTargetAndType': True}},
                              'description': 'AT_SPG_hits',
                              'icon': CONDITION_ICON.HIT}},
 'ATSPG_kills_easy': {'kills': {'type': PROGRESS_TEMPLATE.VALUE,
                                'config': {'goal': 1,
                                           'isMain': True,
                                           'isAward': True,
                                           'isCumulative': True,
                                           'visibleScope': [VISIBLE_SCOPE.BATTLE]},
                                'description': 'AT_SPG_kills',
                                'icon': CONDITION_ICON.KILL_VEHICLES}},
 'ATSPG_kills_medium': {'kills': {'type': PROGRESS_TEMPLATE.VALUE,
                                  'config': {'goal': 2,
                                             'isMain': True,
                                             'isAward': True,
                                             'isCumulative': True,
                                             'visibleScope': [VISIBLE_SCOPE.BATTLE]},
                                  'description': 'AT_SPG_kills',
                                  'icon': CONDITION_ICON.KILL_VEHICLES}},
 'ATSPG_kills_hard': {'kills': {'type': PROGRESS_TEMPLATE.VALUE,
                                'config': {'goal': 3,
                                           'isMain': True,
                                           'isAward': True,
                                           'isCumulative': True,
                                           'visibleScope': [VISIBLE_SCOPE.BATTLE]},
                                'description': 'AT_SPG_kills',
                                'icon': CONDITION_ICON.KILL_VEHICLES}},
 'ATSPG_piercingSeries_easy': {'piercingSeries': {'type': PROGRESS_TEMPLATE.VALUE,
                                                  'config': {'goal': 2,
                                                             'isMain': True,
                                                             'isAward': True,
                                                             'isCumulative': True,
                                                             'visibleScope': [VISIBLE_SCOPE.BATTLE]},
                                                  'description': 'AT_SPG_piercingSeries_plural',
                                                  'icon': CONDITION_ICON.HIT}},
 'ATSPG_piercingSeries_medium': {'piercingSeries': {'type': PROGRESS_TEMPLATE.VALUE,
                                                    'config': {'goal': 4,
                                                               'isMain': True,
                                                               'isAward': True,
                                                               'isCumulative': True,
                                                               'visibleScope': [VISIBLE_SCOPE.BATTLE]},
                                                    'description': 'AT_SPG_piercingSeries_plural',
                                                    'icon': CONDITION_ICON.HIT}},
 'ATSPG_piercingSeries_hard': {'piercingSeries': {'type': PROGRESS_TEMPLATE.VALUE,
                                                  'config': {'goal': 6,
                                                             'isMain': True,
                                                             'isAward': True,
                                                             'isCumulative': True,
                                                             'visibleScope': [VISIBLE_SCOPE.BATTLE]},
                                                  'description': 'AT_SPG_piercingSeries_plural',
                                                  'icon': CONDITION_ICON.HIT}},
 'SPG_hits_easy': {'hits': {'type': PROGRESS_TEMPLATE.VALUE,
                            'config': {'goal': 4,
                                       'isMain': True,
                                       'isAward': True,
                                       'isCumulative': True,
                                       'visibleScope': [VISIBLE_SCOPE.BATTLE]},
                            'description': 'SPG_hits_plural',
                            'icon': CONDITION_ICON.HIT}},
 'SPG_hits_medium': {'hits': {'type': PROGRESS_TEMPLATE.VALUE,
                              'config': {'goal': 7,
                                         'isMain': True,
                                         'isAward': True,
                                         'isCumulative': True,
                                         'visibleScope': [VISIBLE_SCOPE.BATTLE]},
                              'description': 'SPG_hits_plural',
                              'icon': CONDITION_ICON.HIT}},
 'SPG_hits_hard': {'hits': {'type': PROGRESS_TEMPLATE.VALUE,
                            'config': {'goal': 11,
                                       'isMain': True,
                                       'isAward': True,
                                       'isCumulative': True,
                                       'visibleScope': [VISIBLE_SCOPE.BATTLE]},
                            'description': 'SPG_hits_plural',
                            'icon': CONDITION_ICON.HIT}},
 'SPG_damage_easy': {'damage': {'type': PROGRESS_TEMPLATE.VALUE,
                                'config': {'goal': 600,
                                           'isMain': True,
                                           'isAward': True,
                                           'isCumulative': True,
                                           'visibleScope': [VISIBLE_SCOPE.BATTLE]},
                                'description': 'SPG_damage',
                                'icon': CONDITION_ICON.DAMAGE}},
 'SPG_damage_medium': {'damage': {'type': PROGRESS_TEMPLATE.VALUE,
                                  'config': {'goal': 1100,
                                             'isMain': True,
                                             'isAward': True,
                                             'isCumulative': True,
                                             'visibleScope': [VISIBLE_SCOPE.BATTLE]},
                                  'description': 'SPG_damage',
                                  'icon': CONDITION_ICON.DAMAGE}},
 'SPG_damage_hard': {'damage': {'type': PROGRESS_TEMPLATE.VALUE,
                                'config': {'goal': 1800,
                                           'isMain': True,
                                           'isAward': True,
                                           'isCumulative': True,
                                           'visibleScope': [VISIBLE_SCOPE.BATTLE]},
                                'description': 'SPG_damage',
                                'icon': CONDITION_ICON.DAMAGE}},
 'SPG_kills_easy': {'kills': {'type': PROGRESS_TEMPLATE.VALUE,
                              'config': {'goal': 1,
                                         'isMain': True,
                                         'isAward': True,
                                         'isCumulative': True,
                                         'visibleScope': [VISIBLE_SCOPE.BATTLE]},
                              'description': 'SPG_kills',
                              'icon': CONDITION_ICON.KILL_VEHICLES}},
 'SPG_kills_medium': {'kills': {'type': PROGRESS_TEMPLATE.VALUE,
                                'config': {'goal': 2,
                                           'isMain': True,
                                           'isAward': True,
                                           'isCumulative': True,
                                           'visibleScope': [VISIBLE_SCOPE.BATTLE]},
                                'description': 'SPG_kills',
                                'icon': CONDITION_ICON.KILL_VEHICLES}},
 'SPG_kills_hard': {'kills': {'type': PROGRESS_TEMPLATE.VALUE,
                              'config': {'goal': 3,
                                         'isMain': True,
                                         'isAward': True,
                                         'isCumulative': True,
                                         'visibleScope': [VISIBLE_SCOPE.BATTLE]},
                              'description': 'SPG_kills',
                              'icon': CONDITION_ICON.KILL_VEHICLES}}}

def getQuestConfig(questID):
    return _config.get(questID, {})


def getQuestInfo(questName):
    return questName.split('_')


def getQuestType(questName):
    return getQuestInfo(questName)[1]
