# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/common/event_common.py
from constants import OFFER_TOKEN_PREFIX
WT_PROGRESSION_TOKEN_LIFETIME = 4320
WT_PROGRESSION_PREFIX = 'wt_progression:'
WT_PROGRESSION_TOKEN_PREFIX = OFFER_TOKEN_PREFIX + WT_PROGRESSION_PREFIX
WT_PROGRESSION_TOKEN_CREW_OFFER = WT_PROGRESSION_TOKEN_PREFIX + 'tankmen:'
WT_PROGRESSION_TOKEN_CREW_GIFT_OFFER = WT_PROGRESSION_TOKEN_PREFIX + 'tankmen_gift:'
BP_TANKMEN_ENTITLEMENT_TAG_PREFIX = 'tankmen_bp'
WT_PROGRESSION_CHOICE_REWARD_OFFER_TOKENS = (WT_PROGRESSION_TOKEN_CREW_OFFER,)
WT_PROGRESSION_CHOICE_REWARD_OFFER_GIFT_TOKENS = (WT_PROGRESSION_TOKEN_CREW_GIFT_OFFER,)
