# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: server_side_replay/scripts/client/server_side_replay/gui/wgcg/providers/example_responses/server_replays.py
from server_side_replay.gui.wgcg.data_wrappers.server_replays import DataNames
EXAMPLE_DATA = {DataNames.TOP_REPLAYS: {'kills_made': [{'rank': 1,
                                         'top_stat_param': 'kills_made',
                                         'replay_id': 12345,
                                         'arena_id': 3110150727074121L,
                                         'vehicle_entity_id': 0,
                                         'map': '01_karelia',
                                         'battle_type': 1,
                                         'battle_start': 12345678,
                                         'vehicle_cd': 32769,
                                         'spa_id': 1001,
                                         'nickname': 'Player1',
                                         'clan_tag': 'CLN1',
                                         'exp': 1000,
                                         'damage_dealt': 50,
                                         'damage_assisted': 150,
                                         'damage_blocked': 0,
                                         'kills_made': 1,
                                         'mastery_mark': 2,
                                         'achievements_received': 5,
                                         'achievements': ['achievement-1',
                                                          'achievement-2',
                                                          'achievement-8',
                                                          'achievement-3',
                                                          'achievement-4']}, {'rank': 2,
                                         'top_stat_param': 'damage_assisted',
                                         'replay_id': 12345,
                                         'arena_id': 3110150727074122L,
                                         'vehicle_entity_id': 0,
                                         'map': '34_redshire',
                                         'battle_type': 1,
                                         'battle_start': 12345678,
                                         'vehicle_cd': 46849,
                                         'spa_id': 1002,
                                         'nickname': 'Player2',
                                         'clan_tag': 'CLN2',
                                         'exp': 1020,
                                         'damage_dealt': 600,
                                         'damage_assisted': 250,
                                         'damage_blocked': 460,
                                         'kills_made': 6,
                                         'mastery_mark': 4,
                                         'achievements_received': 2,
                                         'achievements': ['achievement-1', 'achievement-2']}, {'rank': 3,
                                         'top_stat_param': 'damage_blocked',
                                         'replay_id': 12345,
                                         'arena_id': 3110150727074122L,
                                         'vehicle_entity_id': 0,
                                         'map': '34_redshire',
                                         'battle_type': 1,
                                         'battle_start': 12345678,
                                         'vehicle_cd': 50849,
                                         'spa_id': 1002,
                                         'nickname': 'Player3',
                                         'clan_tag': '',
                                         'exp': 1020,
                                         'damage_dealt': 600,
                                         'damage_assisted': 250,
                                         'damage_blocked': 460,
                                         'kills_made': 6,
                                         'mastery_mark': 4,
                                         'achievements_received': 2,
                                         'achievements': ['achievement-1', 'achievement-2']}],
                         'total_entries': 1000,
                         'limit': 20,
                         'offset': 0},
 DataNames.BEST_REPLAYS: {'rankings': [{'rank': 1,
                                        'replay_id': 12345,
                                        'arena_id': 3110150727074121L,
                                        'vehicle_entity_id': 0,
                                        'map': '01_karelia',
                                        'battle_type': 1,
                                        'battle_start': 12345678,
                                        'vehicle_cd': 32769,
                                        'spa_id': 1001,
                                        'nickname': 'Player1',
                                        'clan_tag': 'CLN1',
                                        'exp': 1000,
                                        'damage_dealt': 50,
                                        'damage_assisted': 150,
                                        'damage_blocked': 0,
                                        'kills_made': 1,
                                        'mastery_mark': 2,
                                        'achievements_received': 5,
                                        'achievements': ['achievement-1',
                                                         'achievement-2',
                                                         'achievement-8',
                                                         'achievement-3',
                                                         'achievement-4']}, {'rank': 2,
                                        'replay_id': 12345,
                                        'arena_id': 3110150727074122L,
                                        'vehicle_entity_id': 0,
                                        'map': '34_redshire',
                                        'battle_type': 1,
                                        'battle_start': 12345678,
                                        'vehicle_cd': 46849,
                                        'spa_id': 1002,
                                        'nickname': 'Player2',
                                        'clan_tag': 'CLN2',
                                        'exp': 1020,
                                        'damage_dealt': 600,
                                        'damage_assisted': 250,
                                        'damage_blocked': 460,
                                        'kills_made': 6,
                                        'mastery_mark': 4,
                                        'achievements_received': 2,
                                        'achievements': ['achievement-1', 'achievement-2']}],
                          'total_entries': 1000,
                          'limit': 20,
                          'offset': 0},
 DataNames.MY_REPLAYS: {'rankings': [{'rank': 1,
                                      'replay_id': 12345,
                                      'arena_id': 3110150727074121L,
                                      'vehicle_entity_id': 0,
                                      'map': '01_karelia',
                                      'battle_type': 1,
                                      'battle_start': 12345678,
                                      'vehicle_cd': 32769,
                                      'spa_id': 1001,
                                      'nickname': 'Player1',
                                      'clan_tag': 'CLN1',
                                      'exp': 1000,
                                      'damage_dealt': 50,
                                      'damage_assisted': 150,
                                      'damage_blocked': 0,
                                      'kills_made': 1,
                                      'mastery_mark': 2,
                                      'achievements_received': 5,
                                      'achievements': ['achievement-1',
                                                       'achievement-2',
                                                       'achievement-8',
                                                       'achievement-3',
                                                       'achievement-4']}, {'rank': 2,
                                      'replay_id': 12345,
                                      'arena_id': 3110150727074122L,
                                      'vehicle_entity_id': 0,
                                      'map': '34_redshire',
                                      'battle_type': 1,
                                      'battle_start': 12345678,
                                      'vehicle_cd': 46849,
                                      'spa_id': 1002,
                                      'nickname': 'Player2',
                                      'clan_tag': 'CLN2',
                                      'exp': 1020,
                                      'damage_dealt': 600,
                                      'damage_assisted': 250,
                                      'damage_blocked': 460,
                                      'kills_made': 6,
                                      'mastery_mark': 4,
                                      'achievements_received': 2,
                                      'achievements': ['achievement-1', 'achievement-2']}],
                        'total_entries': 1000,
                        'limit': 20,
                        'offset': 0},
 DataNames.REPLAY_LINK: {'replay_id': '12',
                         'replay_link': 'fake_link',
                         'expire_time': 1720819384}}
