# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/client/gui/clans/cache_providers/example_responses/clan_supply.py
from gui.clans.data_wrapper.clan_supply import DataNames
from helpers import time_utils
EXAMPLE_DATA = {DataNames.QUESTS_INFO: {'enabled': True,
                         'cycle_end': time_utils.getServerUTCTime() + time_utils.ONE_DAY,
                         'cycle_duration': 24,
                         'previous_rewards': {'industrial_resource': 100,
                                              'tourcoin': 200},
                         'quest_info': [{'name': 'QUEST_1',
                                         'level': 1,
                                         'current_progress': 1,
                                         'required_progress': 3,
                                         'status': 'INCOMPLETE',
                                         'conditions': {'main': {'rule': {'type': 'FRAGS',
                                                                          'frags_count': 123},
                                                                 'squad_states': ['solo', 'platoon']},
                                                        'alternative': {'rule': {'type': 'WIN'},
                                                                        'squad_states': ['detachment']},
                                                        'common': {'level_from': 6,
                                                                   'level_to': 10}},
                                         'rewards': {'industrial_resource': 60,
                                                     'tourcoin': 50}}, {'name': 'QUEST_2',
                                         'level': 2,
                                         'current_progress': 0,
                                         'required_progress': 3,
                                         'status': 'INCOMPLETE',
                                         'conditions': {'main': {'rule': {'type': 'EXP',
                                                                          'exp_earned': 404},
                                                                 'squad_states': ['platoon']},
                                                        'alternative': {'rule': {'type': 'WIN'},
                                                                        'squad_states': ['detachment']},
                                                        'common': {'level_from': 6,
                                                                   'level_to': 10}},
                                         'rewards': {'industrial_resource': 999,
                                                     'tourcoin': 666}}, {'name': 'QUEST_3',
                                         'level': 3,
                                         'current_progress': 0,
                                         'required_progress': 5,
                                         'status': 'INCOMPLETE',
                                         'conditions': {'main': {'rule': {'type': 'FULL_DAMAGE',
                                                                          'full_damage': 69},
                                                                 'squad_states': ['platoon']},
                                                        'alternative': {'rule': {'type': 'WIN'},
                                                                        'squad_states': ['detachment']},
                                                        'common': {'level_from': 6,
                                                                   'level_to': 10}},
                                         'rewards': {'industrial_resource': 300,
                                                     'tourcoin': 400}}]},
 DataNames.PROGRESSION_SETTINGS: {'enabled': True,
                                  'points': {'1': {'is_elite': False,
                                                   'price': 35000,
                                                   'rewards': {'premium_plus': 7,
                                                               'customizations': [{'custType': 'decal',
                                                                                   'id': 14856,
                                                                                   'value': 1}],
                                                               'credits': 100,
                                                               'items': {'2334': 3,
                                                                         '2846': 1,
                                                                         '2078': 1}}},
                                             '2': {'is_elite': False,
                                                   'price': 35900,
                                                   'rewards': {'premium_plus': 7,
                                                               'equipCoin': 10000}},
                                             '3': {'is_elite': False,
                                                   'price': 35900,
                                                   'rewards': {'gold': 700,
                                                               'credits': 20000}},
                                             '4': {'is_elite': True,
                                                   'price': 35900,
                                                   'rewards': {'premium_plus': 7,
                                                               'gold': 10000,
                                                               'customizations': [{'custType': 'style',
                                                                                   'id': 98,
                                                                                   'value': 1}]}},
                                             '5': {'is_elite': True,
                                                   'price': 35900,
                                                   'rewards': {'premium_plus': 7,
                                                               'gold': 10000}},
                                             '6': {'is_elite': False,
                                                   'price': 35900,
                                                   'rewards': {'premium_plus': 7,
                                                               'credits': 10000}},
                                             '7': {'is_elite': False,
                                                   'price': 35900,
                                                   'rewards': {'gold': 9999,
                                                               'credits': 50000}},
                                             '8': {'is_elite': False,
                                                   'price': 35900,
                                                   'rewards': {'premium_plus': 7,
                                                               'credits': 10000,
                                                               'customizations': [{'custType': 'style',
                                                                                   'id': 98,
                                                                                   'value': 1}]}},
                                             '9': {'is_elite': True,
                                                   'price': 35900,
                                                   'rewards': {'premium_plus': 7,
                                                               'credits': 10000}},
                                             '10': {'is_elite': True,
                                                    'price': 35900,
                                                    'rewards': {'premium_plus': 7,
                                                                'credits': 10000,
                                                                'items': {'286': 3,
                                                                          '13561': 1}}},
                                             '11': {'is_elite': False,
                                                    'price': 35000,
                                                    'rewards': {'premium_plus': 7,
                                                                'customizations': [{'custType': 'style',
                                                                                    'id': 112,
                                                                                    'value': 1}]}},
                                             '12': {'is_elite': False,
                                                    'price': 35900,
                                                    'rewards': {'premium_plus': 7,
                                                                'credits': 10000}},
                                             '13': {'is_elite': False,
                                                    'price': 35900,
                                                    'rewards': {'premium_plus': 7,
                                                                'credits': 10000}},
                                             '14': {'is_elite': True,
                                                    'price': 35900,
                                                    'rewards': {'premium_plus': 7,
                                                                'credits': 10000,
                                                                'customizations': [{'custType': 'style',
                                                                                    'id': 112,
                                                                                    'value': 1}]}},
                                             '15': {'is_elite': True,
                                                    'price': 35900,
                                                    'rewards': {'premium_plus': 7,
                                                                'credits': 10000}},
                                             '16': {'is_elite': False,
                                                    'price': 35900,
                                                    'rewards': {'premium_plus': 7,
                                                                'credits': 10000}},
                                             '17': {'is_elite': False,
                                                    'price': 35900,
                                                    'rewards': {'premium_plus': 7,
                                                                'credits': 10000}},
                                             '18': {'is_elite': False,
                                                    'price': 35900,
                                                    'rewards': {'premium_plus': 7,
                                                                'gold': 10000,
                                                                'items': {'2846': 1,
                                                                          '2078': 1}}},
                                             '19': {'is_elite': True,
                                                    'price': 35900,
                                                    'rewards': {'premium_plus': 7,
                                                                'credits': 10000}},
                                             '20': {'is_elite': True,
                                                    'price': 35900,
                                                    'rewards': {'premium_plus': 7,
                                                                'credits': 10000}},
                                             '21': {'is_elite': True,
                                                    'price': 95900,
                                                    'rewards': {'premium_plus': 7,
                                                                'credits': 10000,
                                                                'slots': 1,
                                                                'customizations': [{'custType': 'style',
                                                                                    'id': 506,
                                                                                    'value': 1}],
                                                                'vehicles': {'50849': {'crewLvl': 75,
                                                                                       'crewFreeXP': 45000,
                                                                                       'customCompensation': (0, 5550, 0)}}}}}},
 DataNames.PROGRESSION_PROGRESS: {'last_purchased': '4',
                                  'points': {'1': {'status': 'PURCHASED'},
                                             '2': {'status': 'PURCHASED'},
                                             '3': {'status': 'PURCHASED'},
                                             '4': {'status': 'PURCHASED'},
                                             '5': {'status': 'AVAILABLE'},
                                             '6': {'status': 'AVAILABLE'}}}}
