# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/client/gui/wot_anniversary/wot_anniversary_constants.py
from shared_utils import CONST_CONTAINER
WOT_ANNIVERSARY_PREFIX = 'anniversary:'
WOT_ANNIVERSARY_LOGIN_QUESTS_PREFIX = WOT_ANNIVERSARY_PREFIX + 'quests:login:day:'
WOT_ANNIVERSARY_LOGIN_UNLOCK_TOKEN = WOT_ANNIVERSARY_PREFIX + 'login:unlock'
WOT_ANNIVERSARY_LOGIN_CLAIM_REWARD_TOKEN = WOT_ANNIVERSARY_PREFIX + 'login:claim_reward'
WOT_ANNIVERSARY_ALL_MASCOT_QUESTS_PREFIX = WOT_ANNIVERSARY_PREFIX + 'quests:mascot:'
WOT_ANNIVERSARY_ALL_MASCOT_BATTLE_QUESTS_PREFIX = WOT_ANNIVERSARY_ALL_MASCOT_QUESTS_PREFIX + 'repeat:'
WOT_ANNIVERSARY_MASCOT_BATTLE_QUESTS_PREFIX = WOT_ANNIVERSARY_ALL_MASCOT_QUESTS_PREFIX + 'repeat:{0}'
WOT_ANNIVERSARY_ALL_MASCOT_REWARD_QUEST = WOT_ANNIVERSARY_ALL_MASCOT_QUESTS_PREFIX + 'reward:'
WOT_ANNIVERSARY_MASCOT_REWARD_QUEST = WOT_ANNIVERSARY_ALL_MASCOT_QUESTS_PREFIX + 'reward:{0}'
WOT_ANNIVERSARY_MASCOT_TOKEN = WOT_ANNIVERSARY_PREFIX + 'mascot:{0}'
WOT_ANNIVERSARY_MASCOT_BLOCK_TOKEN = WOT_ANNIVERSARY_PREFIX + 'mascot:block_completion'
WOT_ANNIVERSARY_MASCOT_CLAIM_REWARD_TOKEN = WOT_ANNIVERSARY_PREFIX + 'mascot:claim_reward'
WOT_ANNIVERSARY_DAILY_QUEST_PREFIX = WOT_ANNIVERSARY_PREFIX + 'quests:daily:'

class Phase(CONST_CONTAINER):
    CAT = 'cat'
    MOUSE = 'mouse'
    DEER = 'deer'
