# Python 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/client/PostProcessing/D3DEnums.py
BW_BLEND_ZERO = 1
BW_BLEND_ONE = 2
BW_BLEND_SRCCOLOR = 3
BW_BLEND_INVSRCCOLOR = 4
BW_BLEND_SRCALPHA = 5
BW_BLEND_INVSRCALPHA = 6
BW_BLEND_DESTALPHA = 7
BW_BLEND_INVDESTALPHA = 8
BW_BLEND_DESTCOLOR = 9
BW_BLEND_INVDESTCOLOR = 10
BW_BLEND_SRCALPHASAT = 11
BW_BLEND_BOTHSRCALPHA = 12
BW_BLEND_BOTHINVSRCALPHA = 13
BW_BLEND_BLENDFACTOR = 14
BW_BLEND_INVBLENDFACTOR = 15
