# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/client/gui/Scaleform/daapi/view/lobby/vehicle_preview/vehicle_preview_constants.py
from gui.Scaleform.daapi.settings.views import VIEW_ALIAS
VEHICLE_PREVIEW_ALIASES = [VIEW_ALIAS.VEHICLE_PREVIEW,
 VIEW_ALIAS.HERO_VEHICLE_PREVIEW,
 VIEW_ALIAS.OFFER_GIFT_VEHICLE_PREVIEW,
 VIEW_ALIAS.TRADE_IN_VEHICLE_PREVIEW,
 VIEW_ALIAS.MARATHON_VEHICLE_PREVIEW,
 VIEW_ALIAS.CONFIGURABLE_VEHICLE_PREVIEW,
 VIEW_ALIAS.RENTAL_VEHICLE_PREVIEW,
 VIEW_ALIAS.RESOURCE_WELL_VEHICLE_PREVIEW,
 VIEW_ALIAS.RESOURCE_WELL_HERO_VEHICLE_PREVIEW,
 VIEW_ALIAS.EARLY_ACCESS_VEHICLE_PREVIEW]
