# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: frontline/scripts/common/frontline_common/frontline_account_commands.py
CMD_ENQUEUE_EPIC = 900
CMD_DEQUEUE_EPIC = 901
CMD_CREATE_PREBATTLE_EPIC_TRAINING = 902
CMD_FORCE_EPIC_DEV_START = 903
CMD_CREATE_PREBATTLE_EPIC = 904
CMD_UPDATE_SELECTED_EPIC_META_ABILITY = 905
CMD_INCREASE_EPIC_META_ABILITY = 906
CMD_RESET_EPIC_META_GAME = 907
CMD_UPDATE_SELECTED_EPIC_META_ABILITY_VEHICLES = 908
CMD_SHOW_FRONTLINE_SYS_MSG = 909
CMD_GET_FREE_EPIC_DISCOUNT = 910
CMD_FL_GAME_MODE_SETUP = 911
CMD_FRONTLINE_UNLOCK_RESERVES = 912
