# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/common/goodies/goodie_constants.py
from enum import Enum, IntEnum, unique
MAX_ACTIVE_PERSONAL_BOOSTERS = 3
MAX_ACTIVE_EVENT_BOOSTERS = 1
MAX_ACTIVE_BOOSTERS = MAX_ACTIVE_PERSONAL_BOOSTERS + MAX_ACTIVE_EVENT_BOOSTERS

class GOODIE_STATE:
    INACTIVE = 0
    ACTIVE = 1
    USED = 2


class GOODIE_VARIETY:
    DISCOUNT = 0
    BOOSTER = 1
    DEMOUNT_KIT = 2
    RECERTIFICATION_FORM = 3
    DISCOUNT_NAME = 'discount'
    BOOSTER_NAME = 'booster'
    DEMOUNT_KIT_NAME = 'demountKit'
    RECERTIFICATION_FORM_NAME = 'recertificationForm'
    NAME_TO_ID = {DISCOUNT_NAME: DISCOUNT,
     BOOSTER_NAME: BOOSTER,
     DEMOUNT_KIT_NAME: DEMOUNT_KIT,
     RECERTIFICATION_FORM_NAME: RECERTIFICATION_FORM}
    DISCOUNT_LIKE = (DISCOUNT, DEMOUNT_KIT, RECERTIFICATION_FORM)


class GOODIE_TARGET_TYPE:
    ON_BUY_PREMIUM = 1
    ON_BUY_SLOT = 2
    ON_POST_BATTLE = 3
    ON_BUY_GOLD_TANKMEN = 4
    ON_FREE_XP_CONVERSION = 5
    ON_BUY_VEHICLE = 6
    ON_EPIC_META = 7
    ON_DEMOUNT_OPTIONAL_DEVICE = 8
    EPIC_POST_BATTLE = 9
    ON_DROP_SKILL = 10


class GOODIE_CONDITION_TYPE:
    MAX_VEHICLE_LEVEL = 1


class GOODIE_RESOURCE_TYPE:
    GOLD = 10
    CREDITS = 20
    XP = 30
    CREW_XP = 40
    FREE_XP = 50
    FL_XP = 60
    FREE_XP_CREW_XP = 70
    FREE_XP_MAIN_XP = 80


@unique
class ACTION_REASON_ID(IntEnum):
    UNKNOWN = 0
    GOODIE_ENABLED = 1
    GOODIE_DISABLED = 2
    END_OF_EFFECT = 3
    EXPIRATION_HAS_PASSED = 4
    USE_BY_HAS_PASSED = 5
    ACTIVATION = 6
    DEACTIVATION = 7
    APPLYING = 8
    EXTERNAL = 9


class PR2BoosterIDs(object):
    XP = 121001
    CRED = 121003
    XP_CREW_FREE = 121005
    XP_DEF = 121000
    CRED_DEF = 121002
    XP_CREW_FREE_DEF = 121004
    EXPR_XP_7D = 122310
    EXPR_XP_14D = 122311
    EXPR_XP_28D = 122312
    EXPR_XP_CREW_FREE_7D = 122610
    EXPR_XP_CREW_FREE_14D = 122611
    EXPR_XP_CREW_FREE_28D = 122612
    EXPR_XP_DEF_7D = 122210
    EXPR_XP_DEF_14D = 122211
    EXPR_XP_DEF_28D = 122212
    EXPR_CRED_DEF_7D = 122410
    EXPR_CRED_DEF_14D = 122411
    EXPR_CRED_DEF_28D = 122412
    EXPR_XP_CREW_FREE_DEF_7D = 122510
    EXPR_XP_CREW_FREE_DEF_14D = 122511
    EXPR_XP_CREW_FREE_DEF_28D = 122512
    STANDARD_ITEMS = (XP_DEF, CRED_DEF, XP_CREW_FREE_DEF)
    ADVANCED_ITEMS = (XP, CRED, XP_CREW_FREE)
    EXPIRABLE_STANDARD_ITEMS = (EXPR_XP_DEF_7D,
     EXPR_XP_DEF_14D,
     EXPR_XP_DEF_28D,
     EXPR_CRED_DEF_7D,
     EXPR_CRED_DEF_14D,
     EXPR_CRED_DEF_28D,
     EXPR_XP_CREW_FREE_DEF_7D,
     EXPR_XP_CREW_FREE_DEF_14D,
     EXPR_XP_CREW_FREE_DEF_28D)
    EXPIRABLE_ADVANCED_ITEMS = (EXPR_XP_7D,
     EXPR_XP_14D,
     EXPR_XP_28D,
     EXPR_XP_CREW_FREE_7D,
     EXPR_XP_CREW_FREE_14D,
     EXPR_XP_CREW_FREE_28D)
    ALL_EXPIRABLE_ITEMS = EXPIRABLE_STANDARD_ITEMS + EXPIRABLE_ADVANCED_ITEMS
    ALL_NON_EXPIRABLE_ITEMS = STANDARD_ITEMS + ADVANCED_ITEMS
    ALL_ITEMS = ALL_NON_EXPIRABLE_ITEMS + ALL_EXPIRABLE_ITEMS


class BoosterCategory(Enum):
    PERSONAL = 'personal'
    CLAN = 'clan'
    EVENT = 'event'
