# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/client/uilogging/ny/constants.py


class NY_LOG_KEYS(object):
    NY_LOBBY_MENU = 'ny_lobby_menu'
    NY_GLADE_MENU = 'ny_glade_menu'
    NY_ALBUM_MENU = 'ny_album_menu'
    NY_REWARDS_MENU = 'ny_rewards_menu'
    NY_LOOT_BOX_MENU = 'ny_loot_box_menu'
    NY_INFO_VIEW = 'ny_info_view'
    NY_MAIN_WIDGET = 'ny_main_widget'
    NY_WIDGET_TOOLTIP = 'ny_widget_tooltip'
    NY_DECOR_POPOVER = 'ny_decorations_popover'
    NY_CELEBRITY_CHALLENGE = 'ny_celebrity_challenge'
    NY_TALISMANS = 'ny_talismans'
    NY_LOOT_BOX_WIDGET = 'ny_loot_box_widget'
    NY_LOOT_BOX_VIEW = 'ny_loot_box_view'
    NY_LOOT_BOX_OPEN_VIEW = 'ny_loot_box_open_view'
    NY_LOOT_BOX_PREMIUM_OPEN_VIEW = 'ny_loot_box_premium_open_view'
    NY_LOOT_BOX_SPECIAL_REWARD_VIEW = 'ny_loot_box_special_reward_view'
    NY_MISSIONS_VIEW = 'ny_missions_view'
    NY_CRAFT_VIEW = 'ny_craft_view'
    NY_BREAK_FILTER_POPOVER = 'ny_break_filter_popover'
    NY_VEHICLE_WINDOW = 'ny_vehicle_window'
    NY_AMMUNITION_PANEL = 'ny_ammunition_panel'
    NY_COLLECTION_REWARDS_VIEW = 'ny_collection_rewards_view'


class NY_LOG_ACTIONS(object):
    NY_TABS_ENTERING = 'ny_entering_{}'
    NY_TABS_EXIT = 'ny_closing_{}'
    NY_BREAK_POPOVER_OPEN = 'ny_break_popover_open'
    NY_BREAK_POPOVER_LEVELS_CHANGED = 'ny_break_popover_levels_filter_changed'
    NY_BREAK_POPOVER_TYPES_CHANGED = 'ny_break_popover_types_filter_changed'
    NY_BREAK_POPOVER_MEGA_CHANGED = 'ny_break_popover_mega_filter_changed'
    NY_CELEBRITY_ENTRY_FROM_HANGAR = 'ny_celebrity_entry_from_hangar'
    NY_CELEBRITY_INFO_SCREEN_OPEN = 'ny_celebrity_info_screen_open'
    NY_CELEBRITY_INFO_SCREEN_AUTO_OPEN = 'ny_celebrity_info_screen_auto_open'
    NY_CELEBRITY_INFO_SCREEN_CLOSE = 'ny_celebrity_info_screen_close'
    NY_CHALLENGE_QUESTS_SHOW = 'ny_challenge_screen_all_quests_show'
    NY_CHALLENGE_QUESTS_HIDE = 'ny_challenge_screen_all_quests_hide'
    NY_CRAFT_VIEW_CRAFT_CLICK = 'ny_craft_view_craft_click'
    NY_DECOR_POPOVER_SELECT_FOR_BREAK = 'ny_decorations_popover_toy_selected_for_break'
    NY_DISCOUNT_FROM_REWARD_VIEW = 'ny_discount_from_reward_view'
    NY_DISCOUNT_FROM_SCREEN = 'ny_discount_from_challenge_screen'
    NY_INTRO_VIEW_OPEN = 'ny_intro_view_open'
    NY_GET_COLLECTION_BUTTON_CLICK = 'ny_get_collection_button_click'
    NY_GO_TO_COLLECTION_BUTTON_CLICK = 'ny_go_to_collection_button_click'
    NY_LOBBY_CLOSE = 'ny_lobby_close'
    NY_LOOT_BOX_POPOVER_FROM_TALISMAN = 'ny_loot_box_popover_opened_from_talisman_view'
    NY_LOOT_BOX_BUY_CLICK = 'ny_loot_box_buy_click'
    NY_LOOT_BOX_VIEW_BUY_CLICK = 'ny_loot_box_buy_click_from_open_screen'
    NY_LOOT_BOX_CLICK_OPEN = 'ny_loot_box_click_open_single'
    NY_LOOT_BOX_HIT_OPEN = 'ny_loot_box_click_open_single_from_hit_area'
    NY_LOOT_BOX_CLICK_MULTI_OPEN = 'ny_loot_box_click_open_multiple'
    NY_LOOT_BOX_ANIM_ON = 'ny_loot_box_animation_turn_on'
    NY_LOOT_BOX_ANIM_OFF = 'ny_loot_box_animation_turn_off'
    NY_LOOT_BOX_SWITCH_FROM = 'ny_loot_box_switch_from_{}'
    NY_LOOT_BOX_OPEN_COUNT_CHANGED = 'ny_loot_box_open_count_changed_to_{}'
    NY_LOOT_BOX_COUNT = 'ny_loot_box_count_{}'
    NY_LOOT_BOX_OPEN_NEXT_BOXES = 'ny_loot_box_open_next_boxes'
    NY_LOOT_BOX_DRAG_N_DROP = 'ny_loot_box_drag_n_drop'
    NY_LOOT_BOX_DELIVERY_INTERRUPTED = 'ny_loot_box_delivery_video_interrupted'
    NY_LOOT_BOX_REWARD_INTERRUPTED = 'ny_loot_box_reward_video_interrupted'
    NY_MISSIONS_BANNER_GOTO_DAILY = 'ny_missions_banner_go_to_daily_quests'
    NY_MISSIONS_BANNER_GOTO_CELEBRITY = 'ny_missions_banner_go_to_celebrity_challenge'
    NY_MISSIONS_OPEN_VIEW = 'ny_mission_open_view'
    NY_MISSIONS_POPULATE_VIEW = 'ny_missions_populate_view'
    NY_PREVIEW_STYLE_BUTTON_CLICK = 'ny_preview_style_button_click'
    NY_TALISMAN_CLICK_AVAILABLE = 'ny_talisman_click_gift_available'
    NY_TALISMAN_CLICK_RECEIVED = 'ny_talisman_click_gift_received'
    NY_TALISMAN_ENTRY_FROM_HANGAR = 'ny_talisman_from_hangar'
    NY_TALISMAN_SELECT_FROM_REWARDS = 'ny_talisman_select_from_rewards'
    NY_TALISMAN_SELECT_FROM_SCREEN = 'ny_talisman_select_from_screen'
    NY_TALISMAN_PROGRESS_CLICK = 'ny_talisman_progress_click'
    NY_TALISMAN_PROGRESS_HOVER = 'ny_talisman_progress_hover'
    NY_TANKSLOTS_FROM_AMMUNITION_PANEL_CLICK = 'ny_tankslots_from_ammunition_panel_click'
    NY_TANKSLOTS_FROM_REWARDS_CLICK = 'ny_tankslots_from_rewards_click'
    NY_VEHICLE_WINDOW_CLOSED = 'ny_vehicle_window_closed'
    NY_VEHICLE_WINDOW_DROP_VEHICLE = 'ny_vehicle_window_drop_vehicle'
    NY_WIDGET_CLICK = 'ny_widget_click'
    NY_WIDGET_TOOLTIP = 'ny_widget_tooltip'
