# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/client/uilogging/ny/constants.py
from enum import Enum
FEATURE = 'ny2023_event'
TIME_LIMIT = 2.0

class LogItems(Enum):
    CELEBRITY_BUTTON = 'celebrity_button'
    DOG_BUTTON = 'dog_button'
    INFO_VIDEO = 'info_video'
    NY_INFO_PAGE = 'ny_info_page'
    NY_INFO_PAGE_SLIDE = 'ny_info_page_slide'
    NY_MAIN_WIDGET = 'ny_main_widget'
    NY_SELECTABLE_OBJECT = 'ny_selectable_object'
    STATISTICS_BUTTON = 'statistics_button'
    WIDGET_TOP_MENU_TAB = 'widget_top_menu_tab'


class LogElements(Enum):
    NY23_UILOG_WIDG = 'NY23_UILOG_WIDG'
    NY23_UILOG_MENU = 'NY23_UILOG_MENU'
    NY23_UILOG_LOGO = 'NY23_UILOG_LOGO'
    NY23_UILOG_LOGO_INF = 'NY23_UILOG_LOGO_INF'
    NY23_UILOG_BACK = 'NY23_UILOG_BACK'
    NY23_UILOG_NAME = 'NY23_UILOG_NAME'
    NY23_UILOG_INPUT = 'NY23_UILOG_INPUT'
    NY23_UILOG_OK_MENU = 'NY23_UILOG_OK_MENU'
    NY23_UILOG_OK_SCR = 'NY23_UILOG_OK_SCR'
    NY23_UILOG_OK_MARK = 'NY23_UILOG_OK_MARK'
    NY23_UILOG_OK_TUT = 'NY23_UILOG_OK_TUT'
    NY23_UILOG_OK_SLOT = 'NY23_UILOG_OK_SLOT'
    NY23_UILOG_RES_ICON = 'NY23_UILOG_RES_ICON'
    NY23_UILOG_RES_MARKER = 'NY23_UILOG_RES_MARKER'
    NY23_UILOG_RES_CONF_1 = 'NY23_UILOG_RES_CONF_1'
    NY23_UILOG_RES_CONF_2 = 'NY23_UILOG_RES_CONF_2'
    NY23_UILOG_RES_DEACTIV_BTN = 'NY23_UILOG_RES_DEACTIV_BTN'
    NY23_UILOG_CONV = 'NY23_UILOG_CONV'
    NY23_UILOG_CONV_BTN = 'NY23_UILOG_CONV_BTN'
    NY23_UILOG_CONV_EMPTY = 'NY23_UILOG_CONV_EMPTY'
    NY23_UILOG_FRIEND_CARD = 'NY23_UILOG_FRIEND_CARD'
    NY23_UILOG_FRIEND_STAR = 'NY23_UILOG_FRIEND_STAR'
    NY23_UILOG_FRIEND_MENU = 'NY23_UILOG_FRIEND_MENU'
    NY23_UILOG_FRIEND_RES_BTN = 'NY23_UILOG_FRIEND_RES_BTN'
    NY23_UILOG_FRIEND_TOY = 'NY23_UILOG_FRIEND_TOY'
    NY23_UILOG_FRIEND_SEARCH = 'NY23_UILOG_FRIEND_SEARCH'
    NY23_UILOG_FRIEND_BOX = 'NY23_UILOG_FRIEND_BOX'
    NY23_UILOG_FRIEND_ADD_BTN = 'NY23_UILOG_FRIEND_ADD_BTN'
    NY23_UILOG_TASK = 'NY23_UILOG_TASK'
    NY23_UILOG_TASK_DISC = 'NY23_UILOG_TASK_DISC'
    NY23_UILOG_TASK_ALL = 'NY23_UILOG_TASK_ALL'
    NY23_UILOG_TASK_ITEM = 'NY23_UILOG_TASK_ITEM'
    NY23_UILOG_TASK_STORY = 'NY23_UILOG_TASK_STORY'
    NY23_UILOG_TASK_ACTION = 'NY23_UILOG_TASK_ACTION'
    NY23_UILOG_TASK_BONUS = 'NY23_UILOG_TASK_BONUS'
    NY23_UILOG_AUTOM_PLAY = 'NY23_UILOG_AUTOM_PLAY'
    NY23_UILOG_AUTOM_NAV = 'NY23_UILOG_AUTOM_NAV'
    NY23_UILOG_AUTOM_QUIT = 'NY23_UILOG_AUTOM_QUIT'
    NY23_UILOG_AUTOM_BUY = 'NY23_UILOG_AUTOM_BUY'
    NY23_UILOG_BB_QUIT = 'NY23_UILOG_BB_QUIT'
    NY23_UILOG_BB_BUY = 'NY23_UILOG_BB_BUY'
    NY23_UILOG_BB_STAT = 'NY23_UILOG_BB_STAT'
    NY23_UILOG_BB_CAT = 'NY23_UILOG_BB_CAT'
    NY23_UILOG_BB_MSQ = 'NY23_UILOG_BB_MSQ'
    NY23_UILOG_BB_GIFT = 'NY23_UILOG_BB_GIFT'
    NY23_UILOG_BB_STAT_REF = 'NY23_UILOG_BB_STAT_REF'
    NY23_UILOG_BB_SET = 'NY23_UILOG_BB_SET'
    NY23_UILOG_BB_QTY = 'NY23_UILOG_BB_QTY'
    NY23_UILOG_ABOUT_VID = 'NY23_UILOG_ABOUT_VID'
    NY23_UILOG_ABOUT_WEB = 'NY23_UILOG_ABOUT_WEB'
    NY23_UILOG_ABOUT_BB = 'NY23_UILOG_ABOUT_BB'
    NY23_UILOG_MARKET_DIS = 'NY23_UILOG_MARKET_DIS'
    NY23_UILOG_MARKET_TANK = 'NY23_UILOG_MARKET_TANK'
    NY23_UILOG_REW_1 = 'NY23_UILOG_REW_1'
    NY23_UILOG_REW_AUTO = 'NY23_UILOG_REW_AUTO'
    NY23_UILOG_REW_MARKET = 'NY23_UILOG_REW_MARKET'
    NY23_UILOG_REW_STYLE = 'NY23_UILOG_REW_STYLE'
    NY23_UILOG_BONUS = 'NY23_UILOG_BONUS'
    NY23_UILOG_BONUS_DROP = 'NY23_UILOG_BONUS_DROP'
    NY23_UILOG_ALERT = 'NY23_UILOG_ALERT'
    NY23_UILOG_MSQ_AUTO = 'NY23_UILOG_MSQ_AUTO'
    NY23_UILOG_DOG_CLICK = 'NY23_UILOG_DOG_CLICK'
    NY23_UILOG_DOG_CASTOM_BTN = 'NY23_UILOG_DOG_CASTOM_BTN'
    NY23_UILOG_DOG_CASTOM_ITEMS = 'NY23_UILOG_DOG_CASTOM_ITEMS'
    NY23_UILOG_DOG_CASTOM_CONFIRM = 'NY23_UILOG_DOG_CASTOM_CONFIRM'


class LogActions(Enum):
    CLICK = 'click'
    CLOSE = 'close'
    MOVE = 'move'
    CONTEXT_MENU = 'context_menu'
    TOOLTIP_WATCHED = 'tooltip_watched'
    MAIN_VIEW_WATCHED = 'main_view_watched'
    NAME_VIEW_WATCHED = 'name_view_watched'


class AdditionalInfo(Enum):
    ENTRY_POINTS_AND_NAVIGATION = 'entry_point_and_navigation'
    PLAYER_HANGAR_AND_FIRST_ENTRY = 'player_hangar_and_first_entry'
    CUSTOMIZATION_OBJECTS = 'customization_objects'
    RESOURCES = 'resources'
    DOG_AND_CUSTOMIZATION = 'dog_and_customization'
    NOTIFICATIONS = 'notifications'
    CELEBRITY = 'celebrity'
    INFO_ENTRY_POINT = 'info_entry_point'
    MULTI_OPEN = 'multiple_open'
    TREE = 'tree'
    SINGLE_OPEN = 'single_open'
    VEHICLES = 'vehicles'


class ParentScreens(Enum):
    BATTLE_QUESTS_PAGE = 'battle_quests_page'
    HANGAR = 'hangar'
    NY_BOXES_PAGE = 'ny_boxes_page'
    NY_LOBBY = 'ny_lobby'
    NY_INFO_PAGE = 'ny_info_page'
    REWARDS_PAGE = 'rewards_page'


class Views(Enum):
    BIG_DECORATIONS = 'big_decorations'
    FRIENDS = 'friends'
    CELEBRITY = 'celebrity'
    MARKETPLACE = 'marketplace'
    HANGAR = 'hangar'
    INFO = 'info_page'
    RESOURCES = 'resources'
    INSTALLATION = 'installation'
    KITCHEN = 'kitchen'
    LOOTBOXES = 'lootboxes'
    LOOTBOX_STYLE_PREVIEW = 'lootbox_style_preview'
    REWARDS_FOR_LEVELS = 'rewards_for_levels'
    REWARDS = 'rewards_'
    SHARDS = 'shards'
    TREE = 'tree'


class TransitionMethods(Enum):
    BIG_DECORATIONS_SLOT_POPOVER = 'big_decorations_slot_popover'
    CLOSE_BUTTON = 'close_button'
    ESC_BUTTON = 'esc_button'
    FIGHT_BUTTON = 'fight_button'
    INFO_BACK_BUTTON = 'info_back_button'
    INFO_PAGE_BUTTON = 'info_page_buttons'
    LOBBY_HEADER = 'lobby_header'
    LOOTBOXES_CELEBRITY_BUTTON = 'lootboxes_celebrity_button'
    LOOTBOXES_CLOSE_BUTTON = 'lootboxes_close_button'
    LOOTBOXES_PAGE_BUTTONS = 'lootboxes_page_buttons'
    LOOTBOXES_POPOVER_OPEN = 'lootboxes_popover_open'
    LOOTBOXES_POPOVER_BUY = 'lootboxes_popover_buy'
    NY_MAIN_WIDGET = 'ny_main_widget'
    PREVIEW_BACK_BUTTON = 'preview_back_button'
    SELECTABLE_OBJECT = '3d_selectable_object'
    SHOW_LOOTBOX_VEHICLE = 'show_lootbox_vehicle'
    SHOW_LOOTBOX_STYLE_PREVIEW = 'show_lootbox_style_preview'
    SIDE_BAR_TAB = 'side_bar_tab'
    SMALL_DECORATIONS_SLOT_POPOVER = 'small_decorations_slot_popover'
    VEHICLES_INFO_BUTTON = 'vehicles_info_button'
    WIDGET_TOP_MENU_TAB = 'widget_top_menu_tab'
