# Python bytecode 2.6 (decompiled from Python 2.7)
# Embedded file name: scripts/common/dossiers/achievements.py
# Compiled at: 2011-08-23 16:44:54
ACHIEVEMENTS = {'warrior': {'type': 'repeatable',
             'section': 'battle'},
 'invader': {'type': 'repeatable',
             'section': 'battle'},
 'sniper': {'type': 'repeatable',
            'section': 'battle'},
 'defender': {'type': 'repeatable',
              'section': 'battle'},
 'steelwall': {'type': 'repeatable',
               'section': 'battle'},
 'supporter': {'type': 'repeatable',
               'section': 'battle'},
 'scout': {'type': 'repeatable',
           'section': 'battle'},
 'evileye': {'type': 'repeatable',
             'section': 'battle'},
 'medalKay': {'type': 'class',
              'section': 'class'},
 'medalCarius': {'type': 'class',
                 'section': 'class'},
 'medalKnispel': {'type': 'class',
                  'section': 'class'},
 'medalPoppel': {'type': 'class',
                 'section': 'class'},
 'medalAbrams': {'type': 'class',
                 'section': 'class'},
 'medalLeClerc': {'type': 'class',
                  'section': 'class'},
 'medalLavrinenko': {'type': 'class',
                     'section': 'class'},
 'medalEkins': {'type': 'class',
                'section': 'class'},
 'medalWittmann': {'type': 'repeatable',
                   'section': 'epic'},
 'medalOrlik': {'type': 'repeatable',
                'section': 'epic'},
 'medalOskin': {'type': 'repeatable',
                'section': 'epic'},
 'medalHalonen': {'type': 'repeatable',
                  'section': 'epic'},
 'medalBurda': {'type': 'repeatable',
                'section': 'epic'},
 'medalBillotte': {'type': 'repeatable',
                   'section': 'epic'},
 'medalKolobanov': {'type': 'repeatable',
                    'section': 'epic'},
 'medalFadin': {'type': 'repeatable',
                'section': 'epic'},
 'medalHeroesOfRassenai': {'type': 'repeatable',
                           'section': 'epic'},
 'medalDeLaglanda': {'type': 'repeatable',
                     'section': 'epic'},
 'medalTamadaYoshio': {'type': 'repeatable',
                       'section': 'epic'},
 'medalErohin': {'type': 'repeatable',
                 'section': 'epic'},
 'medalHoroshilov': {'type': 'repeatable',
                     'section': 'epic'},
 'medalLister': {'type': 'repeatable',
                 'section': 'epic'},
 'kamikaze': {'type': 'repeatable',
              'section': 'special'},
 'raider': {'type': 'repeatable',
            'section': 'special'},
 'mousebane': {'type': 'repeatable',
               'section': 'special'},
 'beasthunter': {'type': 'repeatable',
                 'section': 'special'},
 'tankExpert': {'type': 'custom',
                'section': 'special'},
 'titleSniper': {'type': 'series',
                 'section': 'special',
                 'record': 'maxSniperSeries'},
 'invincible': {'type': 'series',
                'section': 'special',
                'record': 'maxInvincibleSeries'},
 'diehard': {'type': 'series',
             'section': 'special',
             'record': 'maxDiehardSeries'},
 'handOfDeath': {'type': 'series',
                 'section': 'special',
                 'record': 'maxKillingSeries'},
 'armorPiercer': {'type': 'series',
                  'section': 'special',
                  'record': 'maxPiercingSeries'}}
