# Python bytecode 2.6 (decompiled from Python 2.7)
# Embedded file name: scripts/common/dossiers/fmt_storage.py
# Compiled at: 2011-11-02 13:49:22
from utils import getVehTypeFragsFmtValues, unpackVehTypeFrags, getVehDossiersCutFmtValues, unpackVehDossiersCut, extendRecordPacking
__RECORD_PACKING_1 = {'_version': ('p', 'H', 2, 32767),
 'warrior': ('p', 'H', 2, 60001),
 'invader': ('p', 'H', 2, 60001),
 'sniper': ('p', 'H', 2, 60001),
 'defender': ('p', 'H', 2, 60001),
 'steelwall': ('p', 'H', 2, 60001),
 'supporter': ('p', 'H', 2, 60001),
 'scout': ('p', 'H', 2, 60001),
 'battleHeroes': ('p', 'H', 2, 60001),
 'treesCut': ('p', 'H', 2, 60001),
 'maxXP': ('p', 'H', 2, 60001),
 'sniperSeries': ('p', 'H', 2, 60001),
 'maxSniperSeries': ('p', 'H', 2, 60001),
 'invincibleSeries': ('p', 'B', 1, 201),
 'maxInvincibleSeries': ('p', 'B', 1, 201),
 'diehardSeries': ('p', 'B', 1, 201),
 'maxDiehardSeries': ('p', 'B', 1, 201),
 'killingSeries': ('p', 'B', 1, 201),
 'maxKillingSeries': ('p', 'B', 1, 201),
 'piercingSeries': ('p', 'B', 1, 201),
 'maxPiercingSeries': ('p', 'B', 1, 201),
 'maxFrags': ('p', 'B', 1, 201),
 'xp': ('p', 'I', 4, 4000000001L),
 'battlesCount': ('p', 'I', 4, 4000000001L),
 'wins': ('p', 'I', 4, 4000000001L),
 'losses': ('p', 'I', 4, 4000000001L),
 'survivedBattles': ('p', 'I', 4, 4000000001L),
 'winAndSurvived': ('p', 'I', 4, 4000000001L),
 'lastBattleTime': ('p', 'I', 4, 4000000001L),
 'frags': ('p', 'I', 4, 4000000001L),
 'frags8p': ('p', 'I', 4, 4000000001L),
 'fragsBeast': ('p', 'I', 4, 4000000001L),
 'shots': ('p', 'I', 4, 4000000001L),
 'hits': ('p', 'I', 4, 4000000001L),
 'spotted': ('p', 'I', 4, 4000000001L),
 'damageDealt': ('p', 'I', 4, 4000000001L),
 'damageReceived': ('p', 'I', 4, 4000000001L),
 'capturePoints': ('p', 'I', 4, 4000000001L),
 'droppedCapturePoints': ('p', 'I', 4, 4000000001L),
 'battleLifeTime': ('p', 'I', 4, 4000000001L),
 'creationTime': ('p', 'I', 4, 4000000001L),
 'maxXPVehicle': ('p', 'I', 4, 4294967295L),
 'maxFragsVehicle': ('p', 'I', 4, 4294967295L),
 'medalKay': ('p', 'B', 1, 4),
 'medalCarius': ('p', 'B', 1, 4),
 'medalKnispel': ('p', 'B', 1, 4),
 'medalPoppel': ('p', 'B', 1, 4),
 'medalAbrams': ('p', 'B', 1, 4),
 'medalLeClerc': ('p', 'B', 1, 4),
 'medalLavrinenko': ('p', 'B', 1, 4),
 'medalEkins': ('p', 'B', 1, 4),
 'medalWittmann': ('p', 'B', 1, 201),
 'medalOrlik': ('p', 'B', 1, 201),
 'medalOskin': ('p', 'B', 1, 201),
 'medalHalonen': ('p', 'B', 1, 201),
 'medalBurda': ('p', 'B', 1, 201),
 'medalBillotte': ('p', 'B', 1, 201),
 'medalKolobanov': ('p', 'B', 1, 201),
 'medalFadin': ('p', 'B', 1, 201),
 'beasthunter': ('p', 'B', 1, 1),
 'mousebane': ('p', 'B', 1, 201),
 'tankExpert': ('p', 'B', 1, 1),
 'titleSniper': ('p', 'B', 1, 1),
 'invincible': ('p', 'B', 1, 1),
 'diehard': ('p', 'B', 1, 1),
 'raider': ('p', 'B', 1, 201),
 'handOfDeath': ('p', 'B', 1, 1),
 'armorPiercer': ('p', 'B', 1, 1),
 'kamikaze': ('p', 'B', 1, 201),
 'lumberjack': ('p', 'B', 1, 1),
 'vehTypeFrags': ('d', getVehTypeFragsFmtValues, unpackVehTypeFrags),
 'vehDossiersCut': ('d', getVehDossiersCutFmtValues, unpackVehDossiersCut)}
__TANKMAN_LAYOUT_10 = (['_version',
  'lastBattleTime',
  'battleLifeTime',
  'maxFrags',
  'xp',
  'maxXP',
  'battlesCount',
  'wins',
  'losses',
  'survivedBattles',
  'winAndSurvived',
  'frags',
  'frags8p',
  'fragsBeast',
  'shots',
  'hits',
  'spotted',
  'damageDealt',
  'damageReceived',
  'treesCut',
  'capturePoints',
  'droppedCapturePoints',
  'sniperSeries',
  'maxSniperSeries',
  'invincibleSeries',
  'maxInvincibleSeries',
  'diehardSeries',
  'maxDiehardSeries',
  'killingSeries',
  'maxKillingSeries',
  'piercingSeries',
  'maxPiercingSeries',
  'battleHeroes',
  'warrior',
  'invader',
  'sniper',
  'defender',
  'steelwall',
  'supporter',
  'scout',
  'medalKay',
  'medalCarius',
  'medalKnispel',
  'medalPoppel',
  'medalAbrams',
  'medalLeClerc',
  'medalLavrinenko',
  'medalEkins',
  'medalWittmann',
  'medalOrlik',
  'medalOskin',
  'medalHalonen',
  'medalBurda',
  'medalBillotte',
  'medalKolobanov',
  'medalFadin',
  'beasthunter',
  'titleSniper',
  'invincible',
  'diehard',
  'raider',
  'handOfDeath',
  'armorPiercer',
  'kamikaze',
  'lumberjack',
  '_dynRecPos_tankman'], [])
extendRecordPacking(__TANKMAN_LAYOUT_10, '_dynRecPos_tankman', __RECORD_PACKING_1)
__ACCOUNT_LAYOUT_19 = (['_version',
  'creationTime',
  'maxXPVehicle',
  'maxFragsVehicle',
  'lastBattleTime',
  'battleLifeTime',
  'maxFrags',
  'xp',
  'maxXP',
  'battlesCount',
  'wins',
  'losses',
  'survivedBattles',
  'winAndSurvived',
  'frags',
  'frags8p',
  'fragsBeast',
  'shots',
  'hits',
  'spotted',
  'damageDealt',
  'damageReceived',
  'treesCut',
  'capturePoints',
  'droppedCapturePoints',
  'sniperSeries',
  'maxSniperSeries',
  'invincibleSeries',
  'maxInvincibleSeries',
  'diehardSeries',
  'maxDiehardSeries',
  'killingSeries',
  'maxKillingSeries',
  'piercingSeries',
  'maxPiercingSeries',
  'battleHeroes',
  'warrior',
  'invader',
  'sniper',
  'defender',
  'steelwall',
  'supporter',
  'scout',
  'medalKay',
  'medalCarius',
  'medalKnispel',
  'medalPoppel',
  'medalAbrams',
  'medalLeClerc',
  'medalLavrinenko',
  'medalEkins',
  'medalWittmann',
  'medalOrlik',
  'medalOskin',
  'medalHalonen',
  'medalBurda',
  'medalBillotte',
  'medalKolobanov',
  'medalFadin',
  'beasthunter',
  'mousebane',
  'tankExpert',
  'titleSniper',
  'invincible',
  'diehard',
  'raider',
  'handOfDeath',
  'armorPiercer',
  'kamikaze',
  'lumberjack',
  '_dynRecPos_account'], ['vehTypeFrags', 'vehDossiersCut'])
extendRecordPacking(__ACCOUNT_LAYOUT_19, '_dynRecPos_account', __RECORD_PACKING_1)
__VEHICLE_LAYOUT_17 = (['_version',
  'lastBattleTime',
  'battleLifeTime',
  'maxFrags',
  'xp',
  'maxXP',
  'battlesCount',
  'wins',
  'losses',
  'survivedBattles',
  'winAndSurvived',
  'frags',
  'frags8p',
  'fragsBeast',
  'shots',
  'hits',
  'spotted',
  'damageDealt',
  'damageReceived',
  'treesCut',
  'capturePoints',
  'droppedCapturePoints',
  'sniperSeries',
  'maxSniperSeries',
  'invincibleSeries',
  'maxInvincibleSeries',
  'diehardSeries',
  'maxDiehardSeries',
  'killingSeries',
  'maxKillingSeries',
  'piercingSeries',
  'maxPiercingSeries',
  'battleHeroes',
  'warrior',
  'invader',
  'sniper',
  'defender',
  'steelwall',
  'supporter',
  'scout',
  'medalKay',
  'medalCarius',
  'medalKnispel',
  'medalPoppel',
  'medalAbrams',
  'medalLeClerc',
  'medalLavrinenko',
  'medalEkins',
  'medalWittmann',
  'medalOrlik',
  'medalOskin',
  'medalHalonen',
  'medalBurda',
  'medalBillotte',
  'medalKolobanov',
  'medalFadin',
  'beasthunter',
  'mousebane',
  'tankExpert',
  'titleSniper',
  'invincible',
  'diehard',
  'raider',
  'handOfDeath',
  'armorPiercer',
  'kamikaze',
  'lumberjack',
  '_dynRecPos_vehicle'], ['vehTypeFrags'])
extendRecordPacking(__VEHICLE_LAYOUT_17, '_dynRecPos_vehicle', __RECORD_PACKING_1)
__RECORD_PACKING_2 = {'_version': ('p', 'H', 2, 32767),
 'warrior': ('p', 'H', 2, 60001),
 'invader': ('p', 'H', 2, 60001),
 'sniper': ('p', 'H', 2, 60001),
 'defender': ('p', 'H', 2, 60001),
 'steelwall': ('p', 'H', 2, 60001),
 'supporter': ('p', 'H', 2, 60001),
 'scout': ('p', 'H', 2, 60001),
 'evileye': ('p', 'H', 2, 60001),
 'battleHeroes': ('p', 'H', 2, 60001),
 'treesCut': ('p', 'H', 2, 60001),
 'maxXP': ('p', 'H', 2, 60001),
 'sniperSeries': ('p', 'H', 2, 60001),
 'maxSniperSeries': ('p', 'H', 2, 60001),
 'invincibleSeries': ('p', 'B', 1, 201),
 'maxInvincibleSeries': ('p', 'B', 1, 201),
 'diehardSeries': ('p', 'B', 1, 201),
 'maxDiehardSeries': ('p', 'B', 1, 201),
 'killingSeries': ('p', 'B', 1, 201),
 'maxKillingSeries': ('p', 'B', 1, 201),
 'piercingSeries': ('p', 'B', 1, 201),
 'maxPiercingSeries': ('p', 'B', 1, 201),
 'maxFrags': ('p', 'B', 1, 201),
 'xp': ('p', 'I', 4, 4000000001L),
 'battlesCount': ('p', 'I', 4, 4000000001L),
 'wins': ('p', 'I', 4, 4000000001L),
 'losses': ('p', 'I', 4, 4000000001L),
 'survivedBattles': ('p', 'I', 4, 4000000001L),
 'winAndSurvived': ('p', 'I', 4, 4000000001L),
 'lastBattleTime': ('p', 'I', 4, 4000000001L),
 'frags': ('p', 'I', 4, 4000000001L),
 'frags8p': ('p', 'I', 4, 4000000001L),
 'fragsBeast': ('p', 'I', 4, 4000000001L),
 'shots': ('p', 'I', 4, 4000000001L),
 'hits': ('p', 'I', 4, 4000000001L),
 'spotted': ('p', 'I', 4, 4000000001L),
 'damageDealt': ('p', 'I', 4, 4000000001L),
 'damageReceived': ('p', 'I', 4, 4000000001L),
 'capturePoints': ('p', 'I', 4, 4000000001L),
 'droppedCapturePoints': ('p', 'I', 4, 4000000001L),
 'battleLifeTime': ('p', 'I', 4, 4000000001L),
 'creationTime': ('p', 'I', 4, 4000000001L),
 'maxXPVehicle': ('p', 'I', 4, 4294967295L),
 'maxFragsVehicle': ('p', 'I', 4, 4294967295L),
 'medalKay': ('p', 'B', 1, 4),
 'medalCarius': ('p', 'B', 1, 4),
 'medalKnispel': ('p', 'B', 1, 4),
 'medalPoppel': ('p', 'B', 1, 4),
 'medalAbrams': ('p', 'B', 1, 4),
 'medalLeClerc': ('p', 'B', 1, 4),
 'medalLavrinenko': ('p', 'B', 1, 4),
 'medalEkins': ('p', 'B', 1, 4),
 'medalWittmann': ('p', 'H', 2, 60001),
 'medalOrlik': ('p', 'H', 2, 60001),
 'medalOskin': ('p', 'H', 2, 60001),
 'medalHalonen': ('p', 'H', 2, 60001),
 'medalBurda': ('p', 'H', 2, 60001),
 'medalBillotte': ('p', 'H', 2, 60001),
 'medalKolobanov': ('p', 'H', 2, 60001),
 'medalFadin': ('p', 'H', 2, 60001),
 'medalHeroesOfRassenai': ('p', 'H', 2, 60001),
 'medalDeLaglanda': ('p', 'H', 2, 60001),
 'medalTamadaYoshio': ('p', 'H', 2, 60001),
 'medalErohin': ('p', 'H', 2, 60001),
 'medalHoroshilov': ('p', 'H', 2, 60001),
 'medalLister': ('p', 'H', 2, 60001),
 'beasthunter': ('p', 'H', 2, 60001),
 'mousebane': ('p', 'H', 2, 60001),
 'tankExpert': ('p', 'B', 1, 1),
 'titleSniper': ('p', 'B', 1, 1),
 'invincible': ('p', 'B', 1, 1),
 'diehard': ('p', 'B', 1, 1),
 'raider': ('p', 'H', 2, 60001),
 'handOfDeath': ('p', 'B', 1, 1),
 'armorPiercer': ('p', 'B', 1, 1),
 'kamikaze': ('p', 'H', 2, 60001),
 'lumberjack': ('p', 'B', 1, 1),
 'vehTypeFrags': ('d', getVehTypeFragsFmtValues, unpackVehTypeFrags),
 'vehDossiersCut': ('d', getVehDossiersCutFmtValues, unpackVehDossiersCut)}
__VEHICLE_LAYOUT_18 = (['_version',
  'lastBattleTime',
  'battleLifeTime',
  'maxFrags',
  'xp',
  'maxXP',
  'battlesCount',
  'wins',
  'losses',
  'survivedBattles',
  'winAndSurvived',
  'frags',
  'frags8p',
  'fragsBeast',
  'shots',
  'hits',
  'spotted',
  'damageDealt',
  'damageReceived',
  'treesCut',
  'capturePoints',
  'droppedCapturePoints',
  'sniperSeries',
  'maxSniperSeries',
  'invincibleSeries',
  'maxInvincibleSeries',
  'diehardSeries',
  'maxDiehardSeries',
  'killingSeries',
  'maxKillingSeries',
  'piercingSeries',
  'maxPiercingSeries',
  'battleHeroes',
  'warrior',
  'invader',
  'sniper',
  'defender',
  'steelwall',
  'supporter',
  'scout',
  'evileye',
  'medalKay',
  'medalCarius',
  'medalKnispel',
  'medalPoppel',
  'medalAbrams',
  'medalLeClerc',
  'medalLavrinenko',
  'medalEkins',
  'medalWittmann',
  'medalOrlik',
  'medalOskin',
  'medalHalonen',
  'medalBurda',
  'medalBillotte',
  'medalKolobanov',
  'medalFadin',
  'medalHeroesOfRassenai',
  'medalDeLaglanda',
  'medalTamadaYoshio',
  'medalErohin',
  'medalHoroshilov',
  'medalLister',
  'beasthunter',
  'mousebane',
  'tankExpert',
  'titleSniper',
  'invincible',
  'diehard',
  'raider',
  'handOfDeath',
  'armorPiercer',
  'kamikaze',
  'lumberjack',
  '_dynRecPos_vehicle'], ['vehTypeFrags'])
extendRecordPacking(__VEHICLE_LAYOUT_18, '_dynRecPos_vehicle', __RECORD_PACKING_2)
__RECORD_PACKING_3 = {'_version': ('p', 'H', 2, 32767),
 'warrior': ('p', 'H', 2, 60001),
 'invader': ('p', 'H', 2, 60001),
 'sniper': ('p', 'H', 2, 60001),
 'defender': ('p', 'H', 2, 60001),
 'steelwall': ('p', 'H', 2, 60001),
 'supporter': ('p', 'H', 2, 60001),
 'scout': ('p', 'H', 2, 60001),
 'evileye': ('p', 'H', 2, 60001),
 'battleHeroes': ('p', 'H', 2, 60001),
 'treesCut': ('p', 'H', 2, 60001),
 'maxXP': ('p', 'H', 2, 60001),
 'sniperSeries': ('p', 'H', 2, 60001),
 'maxSniperSeries': ('p', 'H', 2, 60001),
 'invincibleSeries': ('p', 'B', 1, 201),
 'maxInvincibleSeries': ('p', 'B', 1, 201),
 'diehardSeries': ('p', 'B', 1, 201),
 'maxDiehardSeries': ('p', 'B', 1, 201),
 'killingSeries': ('p', 'B', 1, 201),
 'maxKillingSeries': ('p', 'B', 1, 201),
 'piercingSeries': ('p', 'B', 1, 201),
 'maxPiercingSeries': ('p', 'B', 1, 201),
 'maxFrags': ('p', 'B', 1, 201),
 'xp': ('p', 'I', 4, 4000000001L),
 'battlesCount': ('p', 'I', 4, 4000000001L),
 'wins': ('p', 'I', 4, 4000000001L),
 'losses': ('p', 'I', 4, 4000000001L),
 'survivedBattles': ('p', 'I', 4, 4000000001L),
 'winAndSurvived': ('p', 'I', 4, 4000000001L),
 'lastBattleTime': ('p', 'I', 4, 4000000001L),
 'frags': ('p', 'I', 4, 4000000001L),
 'frags8p': ('p', 'I', 4, 4000000001L),
 'fragsBeast': ('p', 'I', 4, 4000000001L),
 'shots': ('p', 'I', 4, 4000000001L),
 'hits': ('p', 'I', 4, 4000000001L),
 'spotted': ('p', 'I', 4, 4000000001L),
 'damageDealt': ('p', 'I', 4, 4000000001L),
 'damageReceived': ('p', 'I', 4, 4000000001L),
 'capturePoints': ('p', 'I', 4, 4000000001L),
 'droppedCapturePoints': ('p', 'I', 4, 4000000001L),
 'battleLifeTime': ('p', 'I', 4, 4000000001L),
 'creationTime': ('p', 'I', 4, 4000000001L),
 'maxXPVehicle': ('p', 'I', 4, 4294967295L),
 'maxFragsVehicle': ('p', 'I', 4, 4294967295L),
 'medalKay': ('p', 'B', 1, 4),
 'medalCarius': ('p', 'B', 1, 4),
 'medalKnispel': ('p', 'B', 1, 4),
 'medalPoppel': ('p', 'B', 1, 4),
 'medalAbrams': ('p', 'B', 1, 4),
 'medalLeClerc': ('p', 'B', 1, 4),
 'medalLavrinenko': ('p', 'B', 1, 4),
 'medalEkins': ('p', 'B', 1, 4),
 'medalWittmann': ('p', 'H', 2, 60001),
 'medalOrlik': ('p', 'H', 2, 60001),
 'medalOskin': ('p', 'H', 2, 60001),
 'medalHalonen': ('p', 'H', 2, 60001),
 'medalBurda': ('p', 'H', 2, 60001),
 'medalBillotte': ('p', 'H', 2, 60001),
 'medalKolobanov': ('p', 'H', 2, 60001),
 'medalFadin': ('p', 'H', 2, 60001),
 'medalHeroesOfRassenai': ('p', 'H', 2, 60001),
 'medalDeLaglanda': ('p', 'H', 2, 60001),
 'medalTamadaYoshio': ('p', 'H', 2, 60001),
 'medalErohin': ('p', 'H', 2, 60001),
 'medalHoroshilov': ('p', 'H', 2, 60001),
 'medalLister': ('p', 'H', 2, 60001),
 'beasthunter': ('p', 'H', 2, 60001),
 'mousebane': ('p', 'H', 2, 60001),
 'tankExpert': ('p', 'B', 1, 1),
 'titleSniper': ('p', 'B', 1, 1),
 'invincible': ('p', 'B', 1, 1),
 'diehard': ('p', 'B', 1, 1),
 'raider': ('p', 'H', 2, 60001),
 'handOfDeath': ('p', 'B', 1, 1),
 'armorPiercer': ('p', 'B', 1, 1),
 'kamikaze': ('p', 'H', 2, 60001),
 'lumberjack': ('p', 'B', 1, 1),
 'markOfMastery': ('p', 'B', 1, 4),
 'vehTypeFrags': ('d', getVehTypeFragsFmtValues, unpackVehTypeFrags),
 'vehDossiersCut': ('d', getVehDossiersCutFmtValues, unpackVehDossiersCut)}
__ACCOUNT_LAYOUT_20 = (['_version',
  'creationTime',
  'maxXPVehicle',
  'maxFragsVehicle',
  'lastBattleTime',
  'battleLifeTime',
  'maxFrags',
  'xp',
  'maxXP',
  'battlesCount',
  'wins',
  'losses',
  'survivedBattles',
  'winAndSurvived',
  'frags',
  'frags8p',
  'fragsBeast',
  'shots',
  'hits',
  'spotted',
  'damageDealt',
  'damageReceived',
  'treesCut',
  'capturePoints',
  'droppedCapturePoints',
  'sniperSeries',
  'maxSniperSeries',
  'invincibleSeries',
  'maxInvincibleSeries',
  'diehardSeries',
  'maxDiehardSeries',
  'killingSeries',
  'maxKillingSeries',
  'piercingSeries',
  'maxPiercingSeries',
  'battleHeroes',
  'warrior',
  'invader',
  'sniper',
  'defender',
  'steelwall',
  'supporter',
  'scout',
  'evileye',
  'medalKay',
  'medalCarius',
  'medalKnispel',
  'medalPoppel',
  'medalAbrams',
  'medalLeClerc',
  'medalLavrinenko',
  'medalEkins',
  'medalWittmann',
  'medalOrlik',
  'medalOskin',
  'medalHalonen',
  'medalBurda',
  'medalBillotte',
  'medalKolobanov',
  'medalFadin',
  'medalHeroesOfRassenai',
  'medalDeLaglanda',
  'medalTamadaYoshio',
  'medalErohin',
  'medalHoroshilov',
  'medalLister',
  'beasthunter',
  'mousebane',
  'tankExpert',
  'titleSniper',
  'invincible',
  'diehard',
  'raider',
  'handOfDeath',
  'armorPiercer',
  'kamikaze',
  'lumberjack',
  '_dynRecPos_account'], ['vehTypeFrags', 'vehDossiersCut'])
extendRecordPacking(__ACCOUNT_LAYOUT_20, '_dynRecPos_account', __RECORD_PACKING_3)
__VEHICLE_LAYOUT_19 = (['_version',
  'lastBattleTime',
  'battleLifeTime',
  'maxFrags',
  'xp',
  'maxXP',
  'battlesCount',
  'wins',
  'losses',
  'survivedBattles',
  'winAndSurvived',
  'frags',
  'frags8p',
  'fragsBeast',
  'shots',
  'hits',
  'spotted',
  'damageDealt',
  'damageReceived',
  'treesCut',
  'capturePoints',
  'droppedCapturePoints',
  'sniperSeries',
  'maxSniperSeries',
  'invincibleSeries',
  'maxInvincibleSeries',
  'diehardSeries',
  'maxDiehardSeries',
  'killingSeries',
  'maxKillingSeries',
  'piercingSeries',
  'maxPiercingSeries',
  'battleHeroes',
  'warrior',
  'invader',
  'sniper',
  'defender',
  'steelwall',
  'supporter',
  'scout',
  'evileye',
  'medalKay',
  'medalCarius',
  'medalKnispel',
  'medalPoppel',
  'medalAbrams',
  'medalLeClerc',
  'medalLavrinenko',
  'medalEkins',
  'medalWittmann',
  'medalOrlik',
  'medalOskin',
  'medalHalonen',
  'medalBurda',
  'medalBillotte',
  'medalKolobanov',
  'medalFadin',
  'medalHeroesOfRassenai',
  'medalDeLaglanda',
  'medalTamadaYoshio',
  'medalErohin',
  'medalHoroshilov',
  'medalLister',
  'beasthunter',
  'mousebane',
  'tankExpert',
  'titleSniper',
  'invincible',
  'diehard',
  'raider',
  'handOfDeath',
  'armorPiercer',
  'kamikaze',
  'lumberjack',
  'markOfMastery',
  '_dynRecPos_vehicle'], ['vehTypeFrags'])
extendRecordPacking(__VEHICLE_LAYOUT_19, '_dynRecPos_vehicle', __RECORD_PACKING_3)
DOSSIER_FMTS = {'account': {19: {'record_packing': __RECORD_PACKING_1,
                  'layout': __ACCOUNT_LAYOUT_19},
             20: {'record_packing': __RECORD_PACKING_3,
                  'layout': __ACCOUNT_LAYOUT_20}},
 'vehicle': {17: {'record_packing': __RECORD_PACKING_1,
                  'layout': __VEHICLE_LAYOUT_17},
             18: {'record_packing': __RECORD_PACKING_2,
                  'layout': __VEHICLE_LAYOUT_18},
             19: {'record_packing': __RECORD_PACKING_3,
                  'layout': __VEHICLE_LAYOUT_19}},
 'tankman': {10: {'record_packing': __RECORD_PACKING_1,
                  'layout': __TANKMAN_LAYOUT_10}}}
