# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/client/gui/impl/lobby/common/main_menu_utils.py
from gui.Scaleform.daapi.settings.views import VIEW_ALIAS
from shared_utils import CONST_CONTAINER

class TABS(CONST_CONTAINER):
    HANGAR = VIEW_ALIAS.LOBBY_HANGAR
    STORE = VIEW_ALIAS.LOBBY_STORE
    STORAGE = VIEW_ALIAS.LOBBY_STORAGE
    PROFILE = VIEW_ALIAS.LOBBY_PROFILE
    TECHTREE = VIEW_ALIAS.LOBBY_TECHTREE
    BARRACKS = VIEW_ALIAS.LOBBY_BARRACKS
    BROWSER = VIEW_ALIAS.BROWSER
    RESEARCH = VIEW_ALIAS.LOBBY_RESEARCH
    PERSONAL_MISSIONS = VIEW_ALIAS.LOBBY_PERSONAL_MISSIONS
    MISSIONS = VIEW_ALIAS.LOBBY_MISSIONS
    STRONGHOLD = VIEW_ALIAS.LOBBY_STRONGHOLD
    PERSONAL_MISSIONS_PAGE = VIEW_ALIAS.PERSONAL_MISSIONS_PAGE
    TOURNAMENTS = VIEW_ALIAS.LOBBY_TOURNAMENTS
