# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/client/gui/Scaleform/daapi/view/battle/pve_base/secondary_objectives/state_machine/machine.py
from gui.Scaleform.daapi.view.battle.pve_base.base.state_machine.machine import BaseTimerStateMachine
from gui.Scaleform.daapi.view.battle.pve_base.base.state_machine.transitions import PostponedTransition, CountdownTimerCondition, RegularTimerCondition
from gui.Scaleform.daapi.view.battle.pve_base.secondary_objectives.state_machine import states
from gui.Scaleform.daapi.view.battle.pve_base.secondary_objectives.state_machine.transitions import ToAppearanceTransition, ToRegularTransition, ToCountdownTransition, ToHiddenTransition, ToSuccessTransition, ToFailureTransition, ToDisappearanceTransition, ToRestoredTransition

class SecondaryObjectiveStateMachine(BaseTimerStateMachine):

    def configure(self, view, widgetType, widgetId):
        initialState = states.InitialState()
        appearanceState = states.AppearanceState()
        regularState = states.RegularState()
        restoredState = states.RestoredState()
        countdownState = states.CountdownState()
        successState = states.SuccessState()
        failureState = states.FailureState()
        disappearingState = states.DisappearingState()
        hiddenState = states.HiddenState()
        initialState.configure(view, widgetType, widgetId)
        appearanceState.configure(view, widgetType, widgetId)
        regularState.configure(view, widgetType, widgetId)
        restoredState.configure(view, widgetType, widgetId)
        countdownState.configure(view, widgetType, widgetId)
        successState.configure(view, widgetType, widgetId)
        failureState.configure(view, widgetType, widgetId)
        disappearingState.configure(view, widgetType, widgetId)
        hiddenState.configure(view, widgetType, widgetId)
        initialState.addTransition(ToAppearanceTransition(), target=appearanceState)
        initialState.addTransition(ToRestoredTransition(), target=restoredState)
        initialState.addTransition(ToHiddenTransition(), target=hiddenState)
        appearanceState.addTransition(ToRegularTransition(), target=regularState)
        appearanceState.addTransition(ToCountdownTransition(), target=countdownState)
        appearanceState.addTransition(ToSuccessTransition(), target=successState)
        appearanceState.addTransition(ToFailureTransition(), target=failureState)
        appearanceState.addTransition(ToDisappearanceTransition(), target=disappearingState)
        appearanceState.addTransition(ToHiddenTransition(), target=hiddenState)
        appearanceState.addTransition(CountdownTimerCondition(), target=countdownState)
        restoredState.addTransition(ToRegularTransition(), target=regularState)
        restoredState.addTransition(ToCountdownTransition(), target=countdownState)
        restoredState.addTransition(ToSuccessTransition(), target=successState)
        restoredState.addTransition(ToFailureTransition(), target=failureState)
        restoredState.addTransition(ToDisappearanceTransition(), target=disappearingState)
        restoredState.addTransition(ToHiddenTransition(), target=hiddenState)
        restoredState.addTransition(CountdownTimerCondition(), target=countdownState)
        regularState.addTransition(ToCountdownTransition(), target=countdownState)
        regularState.addTransition(ToSuccessTransition(), target=successState)
        regularState.addTransition(ToFailureTransition(), target=failureState)
        regularState.addTransition(ToDisappearanceTransition(), target=disappearingState)
        regularState.addTransition(ToHiddenTransition(), target=hiddenState)
        regularState.addTransition(CountdownTimerCondition(), target=countdownState)
        countdownState.addTransition(ToRegularTransition(), target=regularState)
        countdownState.addTransition(ToSuccessTransition(), target=successState)
        countdownState.addTransition(ToFailureTransition(), target=failureState)
        countdownState.addTransition(ToDisappearanceTransition(), target=disappearingState)
        countdownState.addTransition(ToHiddenTransition(), target=hiddenState)
        countdownState.addTransition(RegularTimerCondition(), target=regularState)
        successState.addTransition(ToHiddenTransition(), target=hiddenState)
        successState.addTransition(PostponedTransition(), target=hiddenState)
        failureState.addTransition(ToHiddenTransition(), target=hiddenState)
        failureState.addTransition(PostponedTransition(), target=hiddenState)
        disappearingState.addTransition(ToHiddenTransition(), target=hiddenState)
        disappearingState.addTransition(PostponedTransition(), target=hiddenState)
        self.addState(initialState)
        self.addState(appearanceState)
        self.addState(restoredState)
        self.addState(regularState)
        self.addState(countdownState)
        self.addState(successState)
        self.addState(failureState)
        self.addState(disappearingState)
        self.addState(hiddenState)
