# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/client/gui/Scaleform/daapi/view/battle/pve_base/primary_objective/state_machine/machine.py
from gui.Scaleform.daapi.view.battle.pve_base.base.state_machine.machine import BaseTimerStateMachine
from gui.Scaleform.daapi.view.battle.pve_base.base.state_machine.transitions import PostponedTransition, CountdownTimerCondition, RegularTimerCondition
from gui.Scaleform.daapi.view.battle.pve_base.primary_objective.state_machine import states
from gui.Scaleform.daapi.view.battle.pve_base.primary_objective.state_machine.transitions import ToAppearanceTransition, ToRegularTransition, ToLargeTimerTransition, ToCountdownTransition, ToRemindTransition, ToLastRemindTransition, ToSuccessTransition, ToFailureTransition, ToHiddenTransition, RemindTimerCondition, LastRemindTimerCondition, ToNoTimerTransition

class PrimaryObjectiveStateMachine(BaseTimerStateMachine):

    def configure(self, view, widgetType, widgetId):
        initialState = states.InitialState()
        noTimerState = states.NoTimerState()
        appearanceState = states.AppearanceState()
        regularState = states.RegularState()
        remindState = states.RemindState()
        lastRemindState = states.LastRemindState()
        largeTimerState = states.LargeTimerState()
        countdownState = states.CountdownState()
        successState = states.SuccessState()
        failureState = states.FailureState()
        hiddenState = states.HiddenState()
        initialState.configure(view, widgetType, widgetId)
        noTimerState.configure(view, widgetType, widgetId)
        appearanceState.configure(view, widgetType, widgetId)
        regularState.configure(view, widgetType, widgetId)
        remindState.configure(view, widgetType, widgetId)
        lastRemindState.configure(view, widgetType, widgetId)
        largeTimerState.configure(view, widgetType, widgetId)
        countdownState.configure(view, widgetType, widgetId)
        successState.configure(view, widgetType, widgetId)
        failureState.configure(view, widgetType, widgetId)
        hiddenState.configure(view, widgetType, widgetId)
        initialState.addTransition(ToAppearanceTransition(), target=appearanceState)
        initialState.addTransition(ToNoTimerTransition(), target=noTimerState)
        initialState.addTransition(ToRegularTransition(), target=regularState)
        initialState.addTransition(ToLargeTimerTransition(), target=largeTimerState)
        initialState.addTransition(ToCountdownTransition(), target=countdownState)
        initialState.addTransition(ToHiddenTransition(), target=hiddenState)
        noTimerState.addTransition(ToSuccessTransition(), target=successState)
        noTimerState.addTransition(ToFailureTransition(), target=failureState)
        noTimerState.addTransition(ToHiddenTransition(), target=hiddenState)
        appearanceState.addTransition(PostponedTransition(), target=regularState)
        appearanceState.addTransition(ToRegularTransition(), target=regularState)
        appearanceState.addTransition(ToLargeTimerTransition(), target=largeTimerState)
        appearanceState.addTransition(ToSuccessTransition(), target=successState)
        appearanceState.addTransition(ToFailureTransition(), target=failureState)
        appearanceState.addTransition(ToHiddenTransition(), target=hiddenState)
        regularState.addTransition(ToRemindTransition(), target=remindState)
        regularState.addTransition(ToLastRemindTransition(), target=lastRemindState)
        regularState.addTransition(ToLargeTimerTransition(), target=largeTimerState)
        regularState.addTransition(ToCountdownTransition(), target=countdownState)
        regularState.addTransition(ToSuccessTransition(), target=successState)
        regularState.addTransition(ToFailureTransition(), target=failureState)
        regularState.addTransition(ToHiddenTransition(), target=hiddenState)
        regularState.addTransition(RemindTimerCondition(), target=remindState)
        regularState.addTransition(LastRemindTimerCondition(), target=lastRemindState)
        regularState.addTransition(CountdownTimerCondition(), target=countdownState)
        largeTimerState.addTransition(ToRegularTransition(), target=regularState)
        largeTimerState.addTransition(ToRemindTransition(), target=remindState)
        largeTimerState.addTransition(ToLastRemindTransition(), target=lastRemindState)
        largeTimerState.addTransition(ToCountdownTransition(), target=countdownState)
        largeTimerState.addTransition(ToSuccessTransition(), target=successState)
        largeTimerState.addTransition(ToFailureTransition(), target=failureState)
        largeTimerState.addTransition(ToHiddenTransition(), target=hiddenState)
        largeTimerState.addTransition(RemindTimerCondition(), target=remindState)
        largeTimerState.addTransition(LastRemindTimerCondition(), target=lastRemindState)
        largeTimerState.addTransition(CountdownTimerCondition(), target=countdownState)
        remindState.addTransition(PostponedTransition(), target=regularState)
        remindState.addTransition(ToRegularTransition(), target=regularState)
        remindState.addTransition(ToLargeTimerTransition(), target=largeTimerState)
        remindState.addTransition(ToSuccessTransition(), target=successState)
        remindState.addTransition(ToFailureTransition(), target=failureState)
        remindState.addTransition(ToHiddenTransition(), target=hiddenState)
        remindState.addTransition(CountdownTimerCondition(), target=countdownState)
        lastRemindState.addTransition(PostponedTransition(), target=largeTimerState)
        lastRemindState.addTransition(ToRegularTransition(), target=regularState)
        lastRemindState.addTransition(ToLargeTimerTransition(), target=largeTimerState)
        lastRemindState.addTransition(ToSuccessTransition(), target=successState)
        lastRemindState.addTransition(ToFailureTransition(), target=failureState)
        lastRemindState.addTransition(ToHiddenTransition(), target=hiddenState)
        lastRemindState.addTransition(CountdownTimerCondition(), target=countdownState)
        countdownState.addTransition(ToRegularTransition(), target=regularState)
        countdownState.addTransition(RegularTimerCondition(), target=regularState)
        countdownState.addTransition(ToLargeTimerTransition(), target=largeTimerState)
        countdownState.addTransition(ToSuccessTransition(), target=successState)
        countdownState.addTransition(ToFailureTransition(), target=failureState)
        countdownState.addTransition(ToHiddenTransition(), target=hiddenState)
        successState.addTransition(PostponedTransition(), target=hiddenState)
        successState.addTransition(ToHiddenTransition(), target=hiddenState)
        failureState.addTransition(PostponedTransition(), target=hiddenState)
        failureState.addTransition(ToHiddenTransition(), target=hiddenState)
        self.addState(initialState)
        self.addState(noTimerState)
        self.addState(appearanceState)
        self.addState(regularState)
        self.addState(remindState)
        self.addState(lastRemindState)
        self.addState(largeTimerState)
        self.addState(countdownState)
        self.addState(successState)
        self.addState(failureState)
        self.addState(hiddenState)
