# Embedded file name: scripts/client/gui/Scaleform/daapi/view/lobby/fortifications/__init__.py
from gui.shared.utils import CONST_CONTAINER
from gui.Scaleform.framework.ScopeTemplates import SimpleScope, VIEW_SCOPE, LOBBY_SUB_SCOPE, MultipleScope, WINDOW_SCOPE
from gui.Scaleform.genConsts.FORTIFICATION_ALIASES import FORTIFICATION_ALIASES
from gui.Scaleform.locale.FORTIFICATIONS import FORTIFICATIONS
from gui.Scaleform.genConsts.CONTEXT_MENU_HANDLER_TYPE import CONTEXT_MENU_HANDLER_TYPE
from gui.Scaleform.managers.context_menu import ContextMenuManager

class FORT_SCOPE_TYPE(CONST_CONTAINER):
    FORT_WINDOWED_MULTISCOPE = 'FortWindowed'


class FortifiedWindowScopes(object):
    ASSIGN_BUILD_DLG_SCOPE = SimpleScope(FORTIFICATION_ALIASES.FORT_FIXED_PLAYERS_WINDOW_ALIAS, VIEW_SCOPE)
    FORT_MAIN_SCOPE = SimpleScope(FORTIFICATION_ALIASES.MAIN_VIEW_ALIAS, LOBBY_SUB_SCOPE)
    FORT_WINDOWED_MULTISCOPE = MultipleScope(FORT_SCOPE_TYPE.FORT_WINDOWED_MULTISCOPE, (WINDOW_SCOPE, FORT_MAIN_SCOPE))


ContextMenuManager.registerHandler(CONTEXT_MENU_HANDLER_TYPE.FORT_BUILDING, 'gui.Scaleform.daapi.view.lobby.fortifications.FortContextMenuHandler', 'FortContextMenuHandler')

class FortificationEffects(object):
    NONE_STATE = 'none'
    FADE_IN = 0
    VISIBLE = 2
    FADE_OUT = 1
    INVISIBLE = 3
    DONT_MOVE = 0
    MOVE_UP = 1
    MOVE_DOWN = 2
    TEXTS = {FORTIFICATION_ALIASES.MODE_COMMON: {'headerTitle': FORTIFICATIONS.FORTMAINVIEW_COMMON_TITLE,
                                         'descrText': ''},
     FORTIFICATION_ALIASES.MODE_COMMON_TUTORIAL: {'headerTitle': FORTIFICATIONS.FORTMAINVIEW_COMMONTUTOR_TITLE,
                                                  'descrText': ''},
     FORTIFICATION_ALIASES.MODE_DIRECTIONS: {'headerTitle': FORTIFICATIONS.FORTMAINVIEW_DIRECTIONS_TITLE,
                                             'descrText': FORTIFICATIONS.FORTMAINVIEW_DIRECTIONS_SELECTINGSTATUS},
     FORTIFICATION_ALIASES.MODE_DIRECTIONS_TUTORIAL: {'headerTitle': FORTIFICATIONS.FORTMAINVIEW_DIRECTIONSTUTOR_TITLE,
                                                      'descrText': ''},
     FORTIFICATION_ALIASES.MODE_TRANSPORTING_FIRST_STEP: {'headerTitle': FORTIFICATIONS.FORTMAINVIEW_TRANSPORTING_TITLE,
                                                          'descrText': FORTIFICATIONS.FORTMAINVIEW_TRANSPORTING_EXPORTINGSTATUS},
     FORTIFICATION_ALIASES.MODE_TRANSPORTING_NEXT_STEP: {'headerTitle': FORTIFICATIONS.FORTMAINVIEW_TRANSPORTING_TITLE,
                                                         'descrText': FORTIFICATIONS.FORTMAINVIEW_TRANSPORTING_IMPORTINGSTATUS},
     FORTIFICATION_ALIASES.MODE_TRANSPORTING_NOT_AVAILABLE: {'headerTitle': FORTIFICATIONS.FORTMAINVIEW_TRANSPORTING_TITLE,
                                                             'descrText': FORTIFICATIONS.FORTMAINVIEW_TRANSPORTING_NOTAVAILABLESTATUS},
     FORTIFICATION_ALIASES.MODE_TRANSPORTING_TUTORIAL: {'headerTitle': FORTIFICATIONS.FORTMAINVIEW_TRANSPORTINGTUTOR_TITLE,
                                                        'descrText': FORTIFICATIONS.FORTMAINVIEW_TRANSPORTING_TUTORIALDESCR},
     FORTIFICATION_ALIASES.MODE_TRANSPORTING_TUTORIAL_FIRST_STEP: {'headerTitle': FORTIFICATIONS.FORTMAINVIEW_TRANSPORTING_TITLE,
                                                                   'descrText': FORTIFICATIONS.FORTMAINVIEW_TRANSPORTING_EXPORTINGSTATUS},
     FORTIFICATION_ALIASES.MODE_TRANSPORTING_TUTORIAL_NEXT_STEP: {'headerTitle': FORTIFICATIONS.FORTMAINVIEW_TRANSPORTING_TITLE,
                                                                  'descrText': FORTIFICATIONS.FORTMAINVIEW_TRANSPORTING_IMPORTINGSTATUS}}
    STATES = {NONE_STATE: {FORTIFICATION_ALIASES.MODE_COMMON: {'yellowVignette': INVISIBLE,
                                                      'descrTextMove': DONT_MOVE,
                                                      'statsBtn': VISIBLE,
                                                      'clanListBtn': VISIBLE,
                                                      'settingBtn': VISIBLE,
                                                      'calendarBtn': VISIBLE,
                                                      'transportToggle': VISIBLE,
                                                      'clanInfo': VISIBLE,
                                                      'totalDepotQuantity': VISIBLE,
                                                      'footerBitmapFill': VISIBLE,
                                                      'ordersPanel': VISIBLE,
                                                      'orderSelector': VISIBLE,
                                                      'sortieBtn': VISIBLE,
                                                      'intelligenceButton': VISIBLE,
                                                      'leaveModeBtn': INVISIBLE,
                                                      'tutorialArrow': INVISIBLE,
                                                      'infoTF': VISIBLE,
                                                      'timeAlert': VISIBLE},
                  FORTIFICATION_ALIASES.MODE_COMMON_TUTORIAL: {'yellowVignette': FADE_IN,
                                                               'descrTextMove': DONT_MOVE,
                                                               'statsBtn': INVISIBLE,
                                                               'clanListBtn': INVISIBLE,
                                                               'settingBtn': INVISIBLE,
                                                               'calendarBtn': INVISIBLE,
                                                               'transportToggle': INVISIBLE,
                                                               'clanInfo': INVISIBLE,
                                                               'totalDepotQuantity': INVISIBLE,
                                                               'footerBitmapFill': INVISIBLE,
                                                               'ordersPanel': INVISIBLE,
                                                               'orderSelector': INVISIBLE,
                                                               'sortieBtn': INVISIBLE,
                                                               'intelligenceButton': INVISIBLE,
                                                               'leaveModeBtn': INVISIBLE,
                                                               'tutorialArrow': INVISIBLE,
                                                               'infoTF': FADE_OUT,
                                                               'timeAlert': FADE_OUT},
                  FORTIFICATION_ALIASES.MODE_DIRECTIONS_TUTORIAL: {'yellowVignette': FADE_IN,
                                                                   'descrTextMove': DONT_MOVE,
                                                                   'statsBtn': INVISIBLE,
                                                                   'clanListBtn': INVISIBLE,
                                                                   'settingBtn': INVISIBLE,
                                                                   'calendarBtn': INVISIBLE,
                                                                   'transportToggle': INVISIBLE,
                                                                   'clanInfo': INVISIBLE,
                                                                   'totalDepotQuantity': INVISIBLE,
                                                                   'footerBitmapFill': INVISIBLE,
                                                                   'ordersPanel': INVISIBLE,
                                                                   'orderSelector': INVISIBLE,
                                                                   'sortieBtn': INVISIBLE,
                                                                   'intelligenceButton': INVISIBLE,
                                                                   'leaveModeBtn': INVISIBLE,
                                                                   'tutorialArrow': INVISIBLE,
                                                                   'infoTF': FADE_OUT,
                                                                   'timeAlert': FADE_OUT},
                  FORTIFICATION_ALIASES.MODE_TRANSPORTING_TUTORIAL: {'yellowVignette': FADE_IN,
                                                                     'descrTextMove': MOVE_DOWN,
                                                                     'statsBtn': INVISIBLE,
                                                                     'clanListBtn': INVISIBLE,
                                                                     'settingBtn': INVISIBLE,
                                                                     'calendarBtn': INVISIBLE,
                                                                     'transportToggle': VISIBLE,
                                                                     'clanInfo': INVISIBLE,
                                                                     'totalDepotQuantity': VISIBLE,
                                                                     'footerBitmapFill': INVISIBLE,
                                                                     'ordersPanel': INVISIBLE,
                                                                     'orderSelector': INVISIBLE,
                                                                     'sortieBtn': INVISIBLE,
                                                                     'intelligenceButton': INVISIBLE,
                                                                     'leaveModeBtn': INVISIBLE,
                                                                     'tutorialArrow': FADE_IN,
                                                                     'infoTF': FADE_OUT,
                                                                     'timeAlert': FADE_OUT}},
     FORTIFICATION_ALIASES.MODE_COMMON: {FORTIFICATION_ALIASES.MODE_DIRECTIONS: {'yellowVignette': FADE_IN,
                                                                                 'descrTextMove': MOVE_DOWN,
                                                                                 'statsBtn': VISIBLE,
                                                                                 'clanListBtn': VISIBLE,
                                                                                 'settingBtn': VISIBLE,
                                                                                 'calendarBtn': VISIBLE,
                                                                                 'transportToggle': INVISIBLE,
                                                                                 'clanInfo': FADE_OUT,
                                                                                 'totalDepotQuantity': INVISIBLE,
                                                                                 'footerBitmapFill': FADE_OUT,
                                                                                 'ordersPanel': FADE_OUT,
                                                                                 'orderSelector': FADE_OUT,
                                                                                 'sortieBtn': FADE_OUT,
                                                                                 'intelligenceButton': FADE_OUT,
                                                                                 'leaveModeBtn': FADE_IN,
                                                                                 'tutorialArrow': INVISIBLE,
                                                                                 'infoTF': FADE_OUT,
                                                                                 'timeAlert': FADE_OUT},
                                         FORTIFICATION_ALIASES.MODE_TRANSPORTING_FIRST_STEP: {'yellowVignette': FADE_IN,
                                                                                              'descrTextMove': MOVE_DOWN,
                                                                                              'statsBtn': FADE_OUT,
                                                                                              'clanListBtn': FADE_OUT,
                                                                                              'settingBtn': FADE_OUT,
                                                                                              'calendarBtn': FADE_OUT,
                                                                                              'transportToggle': VISIBLE,
                                                                                              'clanInfo': FADE_OUT,
                                                                                              'totalDepotQuantity': VISIBLE,
                                                                                              'footerBitmapFill': FADE_OUT,
                                                                                              'ordersPanel': FADE_OUT,
                                                                                              'orderSelector': FADE_OUT,
                                                                                              'sortieBtn': FADE_OUT,
                                                                                              'intelligenceButton': FADE_OUT,
                                                                                              'leaveModeBtn': FADE_IN,
                                                                                              'tutorialArrow': INVISIBLE,
                                                                                              'infoTF': FADE_OUT,
                                                                                              'timeAlert': FADE_OUT},
                                         FORTIFICATION_ALIASES.MODE_TRANSPORTING_NOT_AVAILABLE: {'yellowVignette': FADE_IN,
                                                                                                 'descrTextMove': MOVE_DOWN,
                                                                                                 'statsBtn': FADE_OUT,
                                                                                                 'clanListBtn': FADE_OUT,
                                                                                                 'settingBtn': FADE_OUT,
                                                                                                 'calendarBtn': FADE_OUT,
                                                                                                 'transportToggle': VISIBLE,
                                                                                                 'clanInfo': FADE_OUT,
                                                                                                 'totalDepotQuantity': VISIBLE,
                                                                                                 'footerBitmapFill': FADE_OUT,
                                                                                                 'ordersPanel': FADE_OUT,
                                                                                                 'orderSelector': FADE_OUT,
                                                                                                 'sortieBtn': FADE_OUT,
                                                                                                 'intelligenceButton': FADE_OUT,
                                                                                                 'leaveModeBtn': FADE_IN,
                                                                                                 'tutorialArrow': INVISIBLE,
                                                                                                 'infoTF': FADE_OUT,
                                                                                                 'timeAlert': FADE_OUT}},
     FORTIFICATION_ALIASES.MODE_TRANSPORTING_FIRST_STEP: {FORTIFICATION_ALIASES.MODE_COMMON: {'yellowVignette': FADE_OUT,
                                                                                              'descrTextMove': MOVE_UP,
                                                                                              'statsBtn': FADE_IN,
                                                                                              'clanListBtn': FADE_IN,
                                                                                              'settingBtn': FADE_IN,
                                                                                              'calendarBtn': FADE_IN,
                                                                                              'transportToggle': VISIBLE,
                                                                                              'clanInfo': FADE_IN,
                                                                                              'totalDepotQuantity': VISIBLE,
                                                                                              'footerBitmapFill': FADE_IN,
                                                                                              'ordersPanel': FADE_IN,
                                                                                              'orderSelector': FADE_IN,
                                                                                              'sortieBtn': FADE_IN,
                                                                                              'intelligenceButton': FADE_IN,
                                                                                              'leaveModeBtn': FADE_OUT,
                                                                                              'tutorialArrow': INVISIBLE,
                                                                                              'infoTF': FADE_IN,
                                                                                              'timeAlert': FADE_IN},
                                                          FORTIFICATION_ALIASES.MODE_TRANSPORTING_NEXT_STEP: {'yellowVignette': VISIBLE,
                                                                                                              'descrTextMove': DONT_MOVE,
                                                                                                              'statsBtn': INVISIBLE,
                                                                                                              'clanListBtn': INVISIBLE,
                                                                                                              'settingBtn': INVISIBLE,
                                                                                                              'calendarBtn': INVISIBLE,
                                                                                                              'transportToggle': VISIBLE,
                                                                                                              'clanInfo': INVISIBLE,
                                                                                                              'totalDepotQuantity': VISIBLE,
                                                                                                              'footerBitmapFill': INVISIBLE,
                                                                                                              'ordersPanel': INVISIBLE,
                                                                                                              'orderSelector': INVISIBLE,
                                                                                                              'sortieBtn': INVISIBLE,
                                                                                                              'intelligenceButton': INVISIBLE,
                                                                                                              'leaveModeBtn': VISIBLE,
                                                                                                              'tutorialArrow': INVISIBLE,
                                                                                                              'infoTF': FADE_OUT,
                                                                                                              'timeAlert': FADE_OUT}},
     FORTIFICATION_ALIASES.MODE_TRANSPORTING_NEXT_STEP: {FORTIFICATION_ALIASES.MODE_COMMON: {'yellowVignette': FADE_OUT,
                                                                                             'descrTextMove': MOVE_UP,
                                                                                             'statsBtn': FADE_IN,
                                                                                             'clanListBtn': FADE_IN,
                                                                                             'settingBtn': FADE_IN,
                                                                                             'calendarBtn': FADE_IN,
                                                                                             'transportToggle': VISIBLE,
                                                                                             'clanInfo': FADE_IN,
                                                                                             'totalDepotQuantity': VISIBLE,
                                                                                             'footerBitmapFill': FADE_IN,
                                                                                             'ordersPanel': FADE_IN,
                                                                                             'orderSelector': FADE_IN,
                                                                                             'sortieBtn': FADE_IN,
                                                                                             'intelligenceButton': FADE_IN,
                                                                                             'leaveModeBtn': FADE_OUT,
                                                                                             'tutorialArrow': INVISIBLE,
                                                                                             'infoTF': FADE_IN,
                                                                                             'timeAlert': FADE_IN},
                                                         FORTIFICATION_ALIASES.MODE_TRANSPORTING_FIRST_STEP: {'yellowVignette': VISIBLE,
                                                                                                              'descrTextMove': DONT_MOVE,
                                                                                                              'statsBtn': INVISIBLE,
                                                                                                              'clanListBtn': INVISIBLE,
                                                                                                              'settingBtn': INVISIBLE,
                                                                                                              'calendarBtn': INVISIBLE,
                                                                                                              'transportToggle': VISIBLE,
                                                                                                              'clanInfo': INVISIBLE,
                                                                                                              'totalDepotQuantity': VISIBLE,
                                                                                                              'footerBitmapFill': INVISIBLE,
                                                                                                              'ordersPanel': INVISIBLE,
                                                                                                              'orderSelector': INVISIBLE,
                                                                                                              'sortieBtn': INVISIBLE,
                                                                                                              'intelligenceButton': INVISIBLE,
                                                                                                              'leaveModeBtn': VISIBLE,
                                                                                                              'tutorialArrow': INVISIBLE,
                                                                                                              'infoTF': FADE_OUT,
                                                                                                              'timeAlert': FADE_OUT},
                                                         FORTIFICATION_ALIASES.MODE_TRANSPORTING_NOT_AVAILABLE: {'yellowVignette': VISIBLE,
                                                                                                                 'descrTextMove': DONT_MOVE,
                                                                                                                 'statsBtn': INVISIBLE,
                                                                                                                 'clanListBtn': INVISIBLE,
                                                                                                                 'settingBtn': INVISIBLE,
                                                                                                                 'calendarBtn': INVISIBLE,
                                                                                                                 'transportToggle': VISIBLE,
                                                                                                                 'clanInfo': INVISIBLE,
                                                                                                                 'totalDepotQuantity': VISIBLE,
                                                                                                                 'footerBitmapFill': INVISIBLE,
                                                                                                                 'ordersPanel': INVISIBLE,
                                                                                                                 'orderSelector': INVISIBLE,
                                                                                                                 'sortieBtn': INVISIBLE,
                                                                                                                 'intelligenceButton': INVISIBLE,
                                                                                                                 'leaveModeBtn': VISIBLE,
                                                                                                                 'tutorialArrow': INVISIBLE,
                                                                                                                 'infoTF': FADE_OUT,
                                                                                                                 'timeAlert': FADE_OUT}},
     FORTIFICATION_ALIASES.MODE_TRANSPORTING_NOT_AVAILABLE: {FORTIFICATION_ALIASES.MODE_COMMON: {'yellowVignette': FADE_OUT,
                                                                                                 'descrTextMove': MOVE_UP,
                                                                                                 'statsBtn': FADE_IN,
                                                                                                 'clanListBtn': FADE_IN,
                                                                                                 'settingBtn': FADE_IN,
                                                                                                 'calendarBtn': FADE_IN,
                                                                                                 'transportToggle': VISIBLE,
                                                                                                 'clanInfo': FADE_IN,
                                                                                                 'totalDepotQuantity': VISIBLE,
                                                                                                 'footerBitmapFill': FADE_IN,
                                                                                                 'ordersPanel': FADE_IN,
                                                                                                 'orderSelector': FADE_IN,
                                                                                                 'sortieBtn': FADE_IN,
                                                                                                 'intelligenceButton': FADE_IN,
                                                                                                 'leaveModeBtn': FADE_OUT,
                                                                                                 'tutorialArrow': INVISIBLE,
                                                                                                 'infoTF': FADE_IN,
                                                                                                 'timeAlert': FADE_IN},
                                                             FORTIFICATION_ALIASES.MODE_TRANSPORTING_FIRST_STEP: {'yellowVignette': VISIBLE,
                                                                                                                  'descrTextMove': DONT_MOVE,
                                                                                                                  'statsBtn': INVISIBLE,
                                                                                                                  'clanListBtn': INVISIBLE,
                                                                                                                  'settingBtn': INVISIBLE,
                                                                                                                  'calendarBtn': INVISIBLE,
                                                                                                                  'transportToggle': VISIBLE,
                                                                                                                  'clanInfo': INVISIBLE,
                                                                                                                  'totalDepotQuantity': VISIBLE,
                                                                                                                  'footerBitmapFill': INVISIBLE,
                                                                                                                  'ordersPanel': INVISIBLE,
                                                                                                                  'orderSelector': INVISIBLE,
                                                                                                                  'sortieBtn': INVISIBLE,
                                                                                                                  'intelligenceButton': INVISIBLE,
                                                                                                                  'leaveModeBtn': VISIBLE,
                                                                                                                  'tutorialArrow': INVISIBLE,
                                                                                                                  'infoTF': FADE_OUT,
                                                                                                                  'timeAlert': FADE_OUT}},
     FORTIFICATION_ALIASES.MODE_DIRECTIONS: {FORTIFICATION_ALIASES.MODE_COMMON: {'yellowVignette': FADE_OUT,
                                                                                 'descrTextMove': MOVE_UP,
                                                                                 'statsBtn': VISIBLE,
                                                                                 'clanListBtn': VISIBLE,
                                                                                 'settingBtn': VISIBLE,
                                                                                 'calendarBtn': VISIBLE,
                                                                                 'transportToggle': VISIBLE,
                                                                                 'clanInfo': FADE_IN,
                                                                                 'totalDepotQuantity': VISIBLE,
                                                                                 'footerBitmapFill': FADE_IN,
                                                                                 'ordersPanel': FADE_IN,
                                                                                 'orderSelector': FADE_IN,
                                                                                 'sortieBtn': FADE_IN,
                                                                                 'intelligenceButton': FADE_IN,
                                                                                 'leaveModeBtn': FADE_OUT,
                                                                                 'tutorialArrow': INVISIBLE,
                                                                                 'infoTF': FADE_IN,
                                                                                 'timeAlert': FADE_IN}},
     FORTIFICATION_ALIASES.MODE_DIRECTIONS_TUTORIAL: {FORTIFICATION_ALIASES.MODE_COMMON_TUTORIAL: {'yellowVignette': VISIBLE,
                                                                                                   'descrTextMove': DONT_MOVE,
                                                                                                   'statsBtn': INVISIBLE,
                                                                                                   'clanListBtn': INVISIBLE,
                                                                                                   'settingBtn': INVISIBLE,
                                                                                                   'calendarBtn': INVISIBLE,
                                                                                                   'transportToggle': INVISIBLE,
                                                                                                   'clanInfo': INVISIBLE,
                                                                                                   'totalDepotQuantity': INVISIBLE,
                                                                                                   'footerBitmapFill': INVISIBLE,
                                                                                                   'ordersPanel': INVISIBLE,
                                                                                                   'orderSelector': INVISIBLE,
                                                                                                   'sortieBtn': INVISIBLE,
                                                                                                   'intelligenceButton': INVISIBLE,
                                                                                                   'leaveModeBtn': INVISIBLE,
                                                                                                   'tutorialArrow': INVISIBLE,
                                                                                                   'infoTF': FADE_OUT,
                                                                                                   'timeAlert': FADE_OUT}},
     FORTIFICATION_ALIASES.MODE_COMMON_TUTORIAL: {FORTIFICATION_ALIASES.MODE_TRANSPORTING_TUTORIAL: {'yellowVignette': VISIBLE,
                                                                                                     'descrTextMove': MOVE_DOWN,
                                                                                                     'statsBtn': INVISIBLE,
                                                                                                     'clanListBtn': INVISIBLE,
                                                                                                     'settingBtn': INVISIBLE,
                                                                                                     'calendarBtn': INVISIBLE,
                                                                                                     'transportToggle': VISIBLE,
                                                                                                     'clanInfo': INVISIBLE,
                                                                                                     'totalDepotQuantity': FADE_IN,
                                                                                                     'footerBitmapFill': INVISIBLE,
                                                                                                     'ordersPanel': INVISIBLE,
                                                                                                     'orderSelector': INVISIBLE,
                                                                                                     'sortieBtn': INVISIBLE,
                                                                                                     'intelligenceButton': INVISIBLE,
                                                                                                     'leaveModeBtn': INVISIBLE,
                                                                                                     'tutorialArrow': FADE_IN,
                                                                                                     'infoTF': FADE_OUT,
                                                                                                     'timeAlert': FADE_OUT}},
     FORTIFICATION_ALIASES.MODE_TRANSPORTING_TUTORIAL_FIRST_STEP: {FORTIFICATION_ALIASES.MODE_TRANSPORTING_TUTORIAL_NEXT_STEP: {'yellowVignette': VISIBLE,
                                                                                                                                'descrTextMove': DONT_MOVE,
                                                                                                                                'statsBtn': INVISIBLE,
                                                                                                                                'clanListBtn': INVISIBLE,
                                                                                                                                'settingBtn': INVISIBLE,
                                                                                                                                'calendarBtn': INVISIBLE,
                                                                                                                                'transportToggle': INVISIBLE,
                                                                                                                                'clanInfo': INVISIBLE,
                                                                                                                                'totalDepotQuantity': VISIBLE,
                                                                                                                                'footerBitmapFill': INVISIBLE,
                                                                                                                                'ordersPanel': INVISIBLE,
                                                                                                                                'orderSelector': INVISIBLE,
                                                                                                                                'sortieBtn': INVISIBLE,
                                                                                                                                'intelligenceButton': INVISIBLE,
                                                                                                                                'leaveModeBtn': INVISIBLE,
                                                                                                                                'tutorialArrow': INVISIBLE,
                                                                                                                                'infoTF': FADE_OUT,
                                                                                                                                'timeAlert': FADE_OUT}},
     FORTIFICATION_ALIASES.MODE_TRANSPORTING_TUTORIAL_NEXT_STEP: {FORTIFICATION_ALIASES.MODE_TRANSPORTING_FIRST_STEP: {'yellowVignette': VISIBLE,
                                                                                                                       'descrTextMove': DONT_MOVE,
                                                                                                                       'statsBtn': INVISIBLE,
                                                                                                                       'clanListBtn': INVISIBLE,
                                                                                                                       'settingBtn': INVISIBLE,
                                                                                                                       'calendarBtn': INVISIBLE,
                                                                                                                       'transportToggle': FADE_IN,
                                                                                                                       'clanInfo': INVISIBLE,
                                                                                                                       'totalDepotQuantity': VISIBLE,
                                                                                                                       'footerBitmapFill': INVISIBLE,
                                                                                                                       'ordersPanel': INVISIBLE,
                                                                                                                       'orderSelector': INVISIBLE,
                                                                                                                       'sortieBtn': INVISIBLE,
                                                                                                                       'intelligenceButton': INVISIBLE,
                                                                                                                       'leaveModeBtn': FADE_IN,
                                                                                                                       'tutorialArrow': INVISIBLE,
                                                                                                                       'infoTF': FADE_OUT,
                                                                                                                       'timeAlert': FADE_OUT},
                                                                  FORTIFICATION_ALIASES.MODE_TRANSPORTING_TUTORIAL_FIRST_STEP: {'yellowVignette': VISIBLE,
                                                                                                                                'descrTextMove': DONT_MOVE,
                                                                                                                                'statsBtn': INVISIBLE,
                                                                                                                                'clanListBtn': INVISIBLE,
                                                                                                                                'settingBtn': INVISIBLE,
                                                                                                                                'calendarBtn': INVISIBLE,
                                                                                                                                'transportToggle': INVISIBLE,
                                                                                                                                'clanInfo': INVISIBLE,
                                                                                                                                'totalDepotQuantity': VISIBLE,
                                                                                                                                'footerBitmapFill': INVISIBLE,
                                                                                                                                'ordersPanel': INVISIBLE,
                                                                                                                                'orderSelector': INVISIBLE,
                                                                                                                                'sortieBtn': INVISIBLE,
                                                                                                                                'intelligenceButton': INVISIBLE,
                                                                                                                                'leaveModeBtn': INVISIBLE,
                                                                                                                                'tutorialArrow': INVISIBLE,
                                                                                                                                'infoTF': FADE_OUT,
                                                                                                                                'timeAlert': FADE_OUT},
                                                                  FORTIFICATION_ALIASES.MODE_TRANSPORTING_NOT_AVAILABLE: {'yellowVignette': VISIBLE,
                                                                                                                          'descrTextMove': DONT_MOVE,
                                                                                                                          'statsBtn': INVISIBLE,
                                                                                                                          'clanListBtn': INVISIBLE,
                                                                                                                          'settingBtn': INVISIBLE,
                                                                                                                          'calendarBtn': INVISIBLE,
                                                                                                                          'transportToggle': FADE_IN,
                                                                                                                          'clanInfo': INVISIBLE,
                                                                                                                          'totalDepotQuantity': VISIBLE,
                                                                                                                          'footerBitmapFill': INVISIBLE,
                                                                                                                          'ordersPanel': INVISIBLE,
                                                                                                                          'orderSelector': INVISIBLE,
                                                                                                                          'sortieBtn': INVISIBLE,
                                                                                                                          'intelligenceButton': INVISIBLE,
                                                                                                                          'leaveModeBtn': VISIBLE,
                                                                                                                          'tutorialArrow': INVISIBLE,
                                                                                                                          'infoTF': FADE_OUT,
                                                                                                                          'timeAlert': FADE_OUT}},
     FORTIFICATION_ALIASES.MODE_TRANSPORTING_TUTORIAL: {FORTIFICATION_ALIASES.MODE_TRANSPORTING_TUTORIAL_FIRST_STEP: {'yellowVignette': VISIBLE,
                                                                                                                      'descrTextMove': DONT_MOVE,
                                                                                                                      'statsBtn': INVISIBLE,
                                                                                                                      'clanListBtn': INVISIBLE,
                                                                                                                      'settingBtn': INVISIBLE,
                                                                                                                      'calendarBtn': INVISIBLE,
                                                                                                                      'transportToggle': FADE_OUT,
                                                                                                                      'clanInfo': INVISIBLE,
                                                                                                                      'totalDepotQuantity': VISIBLE,
                                                                                                                      'footerBitmapFill': INVISIBLE,
                                                                                                                      'ordersPanel': INVISIBLE,
                                                                                                                      'orderSelector': INVISIBLE,
                                                                                                                      'sortieBtn': INVISIBLE,
                                                                                                                      'intelligenceButton': INVISIBLE,
                                                                                                                      'leaveModeBtn': INVISIBLE,
                                                                                                                      'tutorialArrow': FADE_OUT,
                                                                                                                      'infoTF': FADE_OUT,
                                                                                                                      'timeAlert': FADE_OUT}}}
