# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/client/gui/Scaleform/genConsts/BARRACKS_CONSTANTS.py


class BARRACKS_CONSTANTS(object):
    LOCATION_FILTER_TANKS = 'tanks'
    LOCATION_FILTER_BARRACKS = 'barracks'
    LOCATION_FILTER_BARRACKS_AND_TANKS = 'barracksAndTanks'
    LOCATION_FILTER_DISMISSED = 'dismissed'
    LOCATION_FILTER_NOT_RECRUITED = 'notRecruited'
    LOCATION_FILTERS = [LOCATION_FILTER_TANKS,
     LOCATION_FILTER_BARRACKS,
     LOCATION_FILTER_BARRACKS_AND_TANKS,
     LOCATION_FILTER_DISMISSED,
     LOCATION_FILTER_NOT_RECRUITED]
