# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/client/gui/Scaleform/genConsts/BATTLE_EFFICIENCY_TYPES.py


class BATTLE_EFFICIENCY_TYPES(object):
    ARMOR = 'armor'
    DAMAGE = 'damage'
    RAM = 'ram'
    BURN = 'burn'
    DESTRUCTION = 'kill'
    TEAM_DESTRUCTION = 'teamKill'
    DETECTION = 'spotted'
    ASSIST_TRACK = 'assistTrack'
    ASSIST_SPOT = 'assistSpot'
    CRITS = 'crits'
    CAPTURE = 'capture'
    DEFENCE = 'defence'
    ASSIST = 'assist'
    WORLD_COLLISION = 'worldCollision'
    RECEIVED_CRITS = 'receivedCrits'
    RECEIVED_DAMAGE = 'receivedDamage'
    RECEIVED_BURN = 'receivedBurn'
    RECEIVED_RAM = 'receivedRam'
    RECEIVED_WORLD_COLLISION = 'receivedWorldCollision'
    ASSIST_STUN = 'assistStun'
    STUN = 'stun'
    PERK = 'perk'
    STATIC_DEATH_ZONE = 'staticDeathZone'
    VEHICLE_HEALTH_ADDED = 'healthAdded'
    VEHICLE_RECOVERY = 'vehicleRecovery'
    ENEMY_SECTOR_CAPTURED = 'enemySectorCaptured'
    DESTRUCTIBLE_DAMAGED = 'destructibleDamaged'
    DESTRUCTIBLE_DESTROYED = 'destructibleDestroyed'
    DESTRUCTIBLES_DEFENDED = 'destructiblesDefended'
    DEFENDER_BONUS = 'defenderBonus'
    BASE_CAPTURE_BLOCKED = 'baseCaptureBlocked'
    ASSIST_BY_ABILITY = 'assistByAbility'
    DAMAGE_BY_AIRSTRIKE = 'damageByAirStrike'
    RECEIVED_BY_AIRSTRIKE = 'receivedByAirStrike'
    DAMAGE_BY_ARTILLERY = 'damageByArtillery'
    RECEIVED_BY_ARTILLERY = 'receivedByArtillery'
    RECEIVED_BY_DEATH_ZONE = 'receivedByDeathZone'
    DEATH_ZONE = 'deathZone'
    BERSERKER = 'berserker'
    SPAWNED_BOT_DMG = 'spawnedBotDmg'
    RECEIVED_DMG_BY_SPAWNED_BOT = 'receivedDmgBySpawnedBot'
    RECEIVED_BY_MINEFIELD = 'receivedByMinefield'
    DAMAGE_BY_MINEFIELD = 'damageByMinefield'
    RECEIVED_BY_SMOKE = 'receivedBySmoke'
    DEALT_DMG_BY_CORRODING_SHOT = 'dealtDamageByCorrodingShot'
    RECEIVED_BY_CORRODING_SHOT = 'receivedByCorrodingShot'
    DEALT_DMG_BY_FIRE_CIRCLE = 'dealtDamageByFireCircle'
    RECEIVED_BY_FIRE_CIRCLE = 'receivedByFireCircle'
    DEALT_DMG_BY_CLING_BRANDER = 'dealtDamageByClingBrander'
    RECEIVED_BY_CLING_BRANDER = 'receivedByClingBrander'
    DEALT_DMG_BY_THUNDER_STRIKE = 'dealtDamageByThunderStrike'
    RECEIVED_BY_THUNDER_STRIKE = 'receivedByThunderStrike'
    RECEIVED_BY_CIRCUIT_OVERLOAD = 'wtReceivedCircuitOverload'
