# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/client/gui/Scaleform/genConsts/BATTLE_MARKER_STATES.py


class BATTLE_MARKER_STATES(object):
    STUN_STATE = 0
    DEBUFF_STATE = 1
    INSPIRING_STATE = 2
    INSPIRED_STATE = 3
    ENGINEER_STATE = 4
    HEALING_STATE = 5
    BERSERKER_STATE = 6
    REPAIRING_STATE = 7
    STEALTH_STATE = 8
    FL_REGENERATION_KIT_STATE = 9
    FIRE_CIRCLE_STATE = 10
    THUNDER_STRIKE_STATE = 11
    SHOT_PASSION_STATE = 12
    ADAPTATION_HEALTH_RESTORE_STATE = 13
    WT_BOMB_CAPTURING_STATE = 14
    WT_BOMB_INSTALLING_STATE = 15
