# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/client/gui/Scaleform/genConsts/BATTLE_ROYAL_CONSTS.py


class BATTLE_ROYAL_CONSTS(object):
    DEATH_ZONE_STATE_NONE = 0
    DEATH_ZONE_STATE_WARNING = 1
    DEATH_ZONE_STATE_CLOSED = 2
    COUNTER_STATE_INITIAL = 0
    COUNTER_STATE_EXTRA = 1
    COUNTER_STATE_MAX = 2
    MESSAGE_TIMER_LINKAGE = 'RespawnMessageTimerUI'
    MESSAGE_RESPAWN_AVAILABLE_LINKAGE = 'RespawnMessageAvailableUI'
    MESSAGE_RESPAWN_NOT_AVAILABLE_LINKAGE = 'RespawnMessageNotAvailableUI'
    MESSAGE_RESPAWN_NO_ICON_LINKAGE = 'RespawnMessageNoIconUI'
    VOICE_DEFAULT = 'default'
    VOICE_ACTIVE = 'active'
    VOICE_MUTED = 'mute'
    VOICE_BLOCKED = 'block'
    VOICE_CHAT_DISABLED = 'chat_disabled'
    RESPAWN_MESSAGE_LINKAGES = [MESSAGE_TIMER_LINKAGE,
     MESSAGE_RESPAWN_AVAILABLE_LINKAGE,
     MESSAGE_RESPAWN_NOT_AVAILABLE_LINKAGE,
     MESSAGE_RESPAWN_NO_ICON_LINKAGE]
