# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/client/gui/Scaleform/genConsts/BATTLE_NOTIFICATIONS_TIMER_TYPES.py


class BATTLE_NOTIFICATIONS_TIMER_TYPES(object):
    DROWN = 'drown'
    DEATH_ZONE = 'deathZone'
    OVERTURNED = 'overturned'
    FIRE = 'fire'
    GAS_ATTACK = 'gasAtack'
    UNDER_FIRE = 'underFire'
    SECTOR_AIRSTRIKE = 'sectorAirstrike'
    RECOVERY = 'recovery'
    HALF_OVERTURNED = 'halfOverturned'
    EVENT_WARNING = 'eventWarning'
    STUN = 'stun'
    CAPTURE_BLOCK = 'captureLock'
    SMOKE = 'smoke'
    DAMAGING_SMOKE = 'damagingSmoke'
    INSPIRE = 'inspire'
    INSPIRE_CD = 'inspireCoolDown'
    INSPIRE_SOURCE = 'inspireSource'
    INSPIRE_INACTIVATION_SOURCE = 'inspireInactivationSource'
    HEALING = 'healing'
    HEALING_CD = 'healingCoolDown'
    ORANGE_ZONE = 'orangeZone'
    DAMAGING_ZONE = 'damagingZone'
    BERSERKER = 'berserker'
    REPAIRING = 'repairing'
    REPAIRING_CD = 'repairingCoolDown'
    LOOT_PICKUP = 'lootPickUp'
    RESUPPLY = 'resupply'
    STEALTH_RADAR = 'stealthRadar'
    STEALTH_RADAR_INACTIVE = 'stealthRadarInactive'
    WARNING_VIEW = 'warningView'
    CRITICAL_VIEW = 'criticalView'
    WT_BOMB_CAPTURE = 'wtBombCapture'
    WT_BOMB_DEPLOY = 'wtBombDeploy'
    WT_BOMB_ABSORB = 'wtBombAbsorb'
    WT_BOMB_CARRY = 'wtBombCarry'
