# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/client/gui/Scaleform/genConsts/BATTLE_NOTIFICATIONS_TIMER_LINKAGES.py


class BATTLE_NOTIFICATIONS_TIMER_LINKAGES(object):
    DESTROY_TIMER_UI = 'destroyTimerUI'
    SECONDARY_TIMER_UI = 'secondaryTimerUI'
    BATTLE_ROYALE_DESTROY_TIMER_UI = 'BattleRoyaleDestroyTimerUI'
    BATTLE_ROYALE_TIMER_UI = 'BattleRoyaleTimerUI'
    WEEKEND_BRAWL_GREEN_TIMER_UI = 'WeekendBrawlGreenTimerUI'
    WEEKEND_BRAWL_ORANGE_TIMER_UI = 'WeekendBrawlOrangeTimerUI'
    WEEKEND_BRAWL_NOTIFICATION_UI = 'WeekendBrawlNotificationUI'
    WEEKEND_BRAWL_WARNING_UI = 'WeekendBrawlWarningUI'
    FIRE_ICON = 'destroyTimerFireUI'
    BERSERKER_ICON = 'destroyTimerBerserkerUI'
    RECOVERY_ZONE_ICON = 'secondaryRecoveryZoneIconUI'
    OVERTURNED_ICON = 'destroyTimerOverTurnedUI'
    HALF_OVERTURNED_ICON = 'HalfOverTurnedIconUI'
    DEATHZONE_ICON = 'destroyTimerDeathZoneUI'
    DEATHZONE_ICON_CN = 'destroyTimerDeathZoneCNUI'
    DAMAGING_DEATHZONE_ICON = 'DamageZoneIconContentUI'
    DAMAGING_DEATHZONE_ICON_CN = 'DamageZoneIconContentCNUI'
    AIRSTRIKE_ICON = 'destroyTimerAirStrikeUI'
    UNDER_FIRE_ICON = 'destroyTimerDeathLandingUI'
    RECOVERY_ICON = 'destroyTimerRecoveryUI'
    DROWN_ICON = 'destroyTimerDrownUI'
    GAS_DRAFT_ICON = 'destroyTimerGazDraftUI'
    STUN_ICON = 'secondaryStunIconUI'
    BLOCKED_ICON = 'secondaryBlockedIconUI'
    SMOKE_ICON = 'secondarySmokeIconUI'
    INSPIRE_ICON = 'secondaryInspireIconUI'
    HEAL_POINT_ICON = 'secondaryHealPointIconUI'
    RECOVERY_ICON_CONTENT = 'RecoverIconContentUI'
    ORANGE_ZONE_ICON_CONTENT = 'OrangeZoneIconContentUI'
    DAMAGING_SMOKE_ICON = 'DamagingSmokeIconUI'
    EVENTWARNING_ICON = 'destroyTimerEventWarningUI'
    INTEREST_POINT_CAPTURING_ICON = 'InterestPointCapturingIconUI'
    INTEREST_POINT_CAPTURED_ICON = 'InterestPointCapturedIconUI'
    INTEREST_POINT_BLOCKED_ICON = 'InterestPointBlockedIconUI'
    INTEREST_POINT_COOLDOWN_ICON = 'InterestPointCooldownIconUI'
