# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/client/gui/Scaleform/genConsts/BATTLE_VIEW_ALIASES.py


class BATTLE_VIEW_ALIASES(object):
    BATTLE_LOADING = 'battleLoading'
    TEAM_BASES_PANEL = 'teamBasesPanel'
    VEHICLE_MESSAGES = 'battleVehicleMessages'
    VEHICLE_ERROR_MESSAGES = 'battleVehicleErrorMessages'
    PLAYER_MESSAGES = 'battlePlayerMessages'
    DAMAGE_PANEL = 'damagePanel'
    BATTLE_STATISTIC_DATA_CONTROLLER = 'battleStatisticDataController'
    FRAG_CORRELATION_BAR = 'fragCorrelationBar'
    BATTLE_TIMER = 'battleTimer'
    PREBATTLE_TIMER = 'prebattleTimer'
    DEBUG_PANEL = 'debugPanel'
    SIXTH_SENSE = 'sixthSense'
    DAMAGE_INFO_PANEL = 'damageInfoPanel'
    BATTLE_MESSENGER = 'battleMessenger'
    BATTLE_TUTORIAL = 'battleTutorial'
    CONSUMABLES_PANEL = 'consumablesPanel'
    DAMAGE_INDICATOR = 'damageIndicator'
    DESTROY_TIMERS_PANEL = 'destroyTimersPanel'
    REPORT_BUG = 'reportBug'
    FULL_STATS = 'fullStats'
    RIBBONS_PANEL = 'ribbonsPanel'
    MINIMAP = 'minimap'
    RADIAL_MENU = 'radialMenu'
    PLAYERS_PANEL = 'playersPanel'
    TICKER = 'battleTicker'
    REPAIR_POINT_TIMER = 'repairPointTimer'
    FLAG_NOTIFICATION = 'flagNotification'
    BATTLE_END_WARNING_PANEL = 'battleEndWarningPanel'
    POSTMORTEM_PANEL = 'postmortemPanel'
    BATTLE_DAMAGE_LOG_PANEL = 'battleDamageLogPanel'
    CROSSHAIR_PANEL = 'crosshairPanel'
    MARKERS_2D = 'markers2D'
    HIT_DIRECTION = 'hitDirection'
    SIEGE_MODE_INDICATOR = 'siegeModeIndicator'
    BOOTCAMP_CONSUMABLES_PANEL = 'bootcampConsumablesPanel'
    BOOTCAMP_RIBBONS_PANEL = 'bootcampRibbonsPanel'
    BOOTCAMP_SECONDARY_HINT = 'bootcampSecondaryHint'
    BOOTCAMP_BATTLE_TOP_HINT = 'bootcampBattleTopHint'
    GAME_MESSAGES_PANEL = 'gameMessagesPanel'
    EPIC_RANDOM_SCORE_PANEL = 'epicRandomScorePanel'
    COLOR_SETTINGS_TIP_PANEL = 'colorSettingsTipPanel'
