# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/client/gui/Scaleform/genConsts/BATTLE_NOTIFICATIONS_TIMER_LINKAGES.py


class BATTLE_NOTIFICATIONS_TIMER_LINKAGES(object):
    DESTROY_TIMER_UI = 'destroyTimerUI'
    SECONDARY_TIMER_UI = 'secondaryTimerUI'
    BATTLE_ROYALE_DESTROY_TIMER_UI = 'BattleRoyaleDestroyTimerUI'
    BATTLE_ROYALE_COUNTER_TIMER_UI = 'BattleRoyaleCounterTimerUI'
    BATTLE_ROYALE_TIMER_UI = 'BattleRoyaleTimerUI'
    RESUPPLY_TIMER_UI = 'ResupplyTimerUI'
    RESUPPLY_TIMER_SMALL_UI = 'ResupplyTimerSmallUI'
    FIRE_ICON = 'destroyTimerFireUI'
    BERSERKER_ICON = 'destroyTimerBerserkerUI'
    RECOVERY_ZONE_ICON = 'secondaryRecoveryZoneIconUI'
    OVERTURNED_ICON = 'destroyTimerOverTurnedUI'
    HALF_OVERTURNED_ICON = 'HalfOverTurnedIconUI'
    DEATHZONE_ICON = 'destroyTimerDeathZoneUI'
    DEATHZONE_ICON_CN = 'destroyTimerDeathZoneCNUI'
    DAMAGING_DEATHZONE_ICON = 'DamageZoneIconContentUI'
    DAMAGING_DEATHZONE_ICON_CN = 'DamageZoneIconContentCNUI'
    AIRSTRIKE_ICON = 'destroyTimerAirStrikeUI'
    UNDER_FIRE_ICON = 'destroyTimerDeathLandingUI'
    RECOVERY_ICON = 'destroyTimerRecoveryUI'
    DROWN_ICON = 'destroyTimerDrownUI'
    GAS_DRAFT_ICON = 'destroyTimerGazDraftUI'
    STUN_ICON = 'secondaryStunIconUI'
    BLOCKED_ICON = 'secondaryBlockedIconUI'
    SMOKE_ICON = 'secondarySmokeIconUI'
    INSPIRE_ICON = 'secondaryInspireIconUI'
    HEAL_POINT_ICON = 'secondaryHealPointIconUI'
    RECOVERY_ICON_CONTENT = 'RecoverIconContentUI'
    ORANGE_ZONE_ICON_CONTENT = 'OrangeZoneIconContentUI'
    DAMAGING_SMOKE_ICON = 'DamagingSmokeIconUI'
    EVENTWARNING_ICON = 'destroyTimerEventWarningUI'
    HEAL_ICON_FRONTLINE = 'secondaryTimerHealIconUI'
    INSPIRE_SOURCE_ICON = 'secondaryTimerInspireSourceIconUI'
    STEALTH_ICON = 'secondaryTimerStealthIconUI'
    STEALTH_INACTIVE_ICON = 'secondaryTimerStealthInactiveIconUI'
    ENEMY_SMOKE_ICON = 'enemySmokeIconUI'
    CORRODING_SHOT_ICON = 'corrodingShotIconUI'
    FIRE_CIRCLE_ICON = 'fireCircleIconUI'
    THUNDER_STRIKE_ICON = 'thunderStrikeIconUI'
    SHOT_PASSION_ICON = 'shotPassionIconUI'
    HP_RESTORE_ON_DAMAGE_ICON = 'hpRestoreOnDamageIconUI'
