# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/client/gui/Scaleform/genConsts/BATTLE_MARKER_STATES.py


class BATTLE_MARKER_STATES(object):
    STUN_STATE = 0
    DEBUFF_STATE = 1
    INSPIRING_STATE = 2
    INSPIRED_STATE = 3
    ENGINEER_STATE = 4
    HEALING_STATE = 5
    BERSERKER_STATE = 6
    REPAIRING_STATE = 7
    STEALTH_STATE = 8
    FL_REGENERATION_KIT_STATE = 9
    FIRE_CIRCLE_STATE = 10
    THUNDER_STRIKE_STATE = 11
    SHOT_PASSION_STATE = 12
    ADAPTATION_HEALTH_RESTORE_STATE = 13
    COMP7_RISKY_ATTACK_STATE = 14
    COMP7_SNIPER_STATE = 15
    COMP7_ALLY_SUPPORT_STATE = 16
    COMP7_AOE_HEAL_STATE = 17
    COMP7_HUNTER_STATE = 18
    COMP7_CONCENTRATION_STATE = 19
    COMP7_JUGGERNAUT_STATE = 20
    COMP7_RISKY_ATTACK_HEAL_STATE = 21
    COMP7_BERSERK_STATE = 22
    COMP7_FAST_RECHARGE_STATE = 23
    COMP7_SURE_SHOT_STATE = 24
    COMP7_AOE_INSPIRE_STATE = 25
    COMP7_ARTYLLERY_SUPPORT_STATE = 26
    COMP7_MARCH_STATE = 27
    COMP7_AGGRESSIVE_DETECTION_STATE = 28
    COMP7_POINT_RECON_STATE = 29
    CONFIRMED_STATE = 30
    HW_DEBUFF_STATE = 31
