# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/client/gui/Scaleform/genConsts/COLOR_SETTINGS.py


class COLOR_SETTINGS(object):
    COLOR_SETTINGS_TYPE_NO_CHANGES = 0
    COLOR_SETTINGS_TYPE_FILTERS = 1
    COLOR_SETTINGS_TYPE_MANUAL = 2
    COLOR_SETTINGS_TYPES = [COLOR_SETTINGS_TYPE_NO_CHANGES, COLOR_SETTINGS_TYPE_FILTERS, COLOR_SETTINGS_TYPE_MANUAL]
    COLOR_FILTER_INTENSITY = 'colorFilterIntensity'
    BRIGHTNESS_CORRECTION = 'brightnessCorrection'
    SATURATION_CORRECTON = 'saturationCorrection'
    CONTRAST_CORRECTION = 'contrastCorrection'
    COLOR_GRADING_TECHNIQUE = 'COLOR_GRADING_TECHNIQUE'
    FIELDS = [COLOR_FILTER_INTENSITY,
     BRIGHTNESS_CORRECTION,
     SATURATION_CORRECTON,
     CONTRAST_CORRECTION,
     COLOR_GRADING_TECHNIQUE]
