# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/client/gui/Scaleform/genConsts/COMPONENTS.py


class COMPONENTS(object):
    ACTION_BG_TOTAL = 'action_bg_total'
    ACTION_PRICE_BG_SIMPLE = 'action_price_bg_simple'
    ALERT_ICON = 'alertIcon'
    AT_SPG = 'AT_SPG'
    AT_SPG_ELITE = 'AT_SPG_elite'
    CHECKBOX_DISABLE = 'checkbox_disable'
    CHECKBOX_HOVER = 'checkbox_hover'
    CHECKBOX_SELECTION = 'checkbox_selection'
    CHECKBOX_UP = 'checkbox_up'
    CM_ACCEPT_INVITATION = 'cm_acceptInvitation'
    CM_ADD_TO_BLACKLIST = 'cm_addToBlacklist'
    CM_ADD_TO_FRIENDS = 'cm_addToFriends'
    CM_ADD_TO_SQUAD = 'cm_addToSquad'
    CM_ARROW_DD = 'cm_arrowDD'
    CM_DISABLE_COMMUNICATIONS = 'cm_disableCommunications'
    CM_DISABLE_VOICE = 'cm_disableVoice'
    CM_ENABLE_COMMUNICATIONS = 'cm_enableCommunications'
    CM_ENABLE_VOICE = 'cm_enableVoice'
    CM_IN_SQUAD = 'cm_inSquad'
    CM_OK_ICON = 'cm_okIcon'
    CM_REJECT_INVITATION = 'cm_rejectInvitation'
    CM_REMOVE_FROM_BLACKLIST = 'cm_removeFromBlacklist'
    CM_REMOVE_FROM_FRIENDS = 'cm_removeFromFriends'
    CM_SEPARATE_BG = 'cm_separate_bg'
    CM_SUB_CIRCLE = 'cm_sub_circle'
    CREDITS_ICON_1 = 'CreditsIcon_1'
    CREDITS_ICON_2 = 'CreditsIcon_2'
    CRYSTAL_16X16 = 'crystal_16x16'
    FREE_XP_ICON_1 = 'FreeXpIcon_1'
    FREE_XP_ICON_2 = 'FreeXpIcon_2'
    GOLD_ICON_1 = 'GoldIcon_1'
    GOLD_ICON_2 = 'GoldIcon_2'
    HEAVY_TANK = 'heavyTank'
    HEAVY_TANK_ELITE = 'heavyTank_elite'
    ITEM_ACTIVE_ARROW = 'item_active_arrow'
    ITEM_ACTIVE_ARROW_DOWN = 'item_active_arrow_down'
    ITEM_ACTIVE_BACKGROUND = 'item_active_background'
    ITEM_ACTIVE_HIGHLIGHT = 'item_active_highlight'
    ITEM_ACTIVE_SHINE = 'item_active_shine'
    LIGHT_TANK = 'lightTank'
    LIGHT_TANK_ELITE = 'lightTank_elite'
    MEDIUM_TANK = 'mediumTank'
    MEDIUM_TANK_ELITE = 'mediumTank_elite'
    ORANGE_BIG_NORMAL = 'orange_big_normal'
    SPG = 'SPG'
    SPG_ELITE = 'SPG_elite'
    XP_ICON_1 = 'XpIcon_1'
