# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/client/gui/Scaleform/genConsts/CONSUMABLES_PANEL_SETTINGS.py


class CONSUMABLES_PANEL_SETTINGS(object):
    DEFAULT_SETTINGS_ID = 0
    BIG_SETTINGS_ID = 1
    BATTLE_ROYALE_SETTINGS_ID = 2
    MAPS_TRAINING_SETTINGS_ID = 3
    EPIC_BATTLE_SETTINGS_ID = 4
    GLOW_ID_GREEN = 0
    GLOW_ID_ORANGE = 1
    GLOW_ID_GREEN_SPECIAL = 2
    GLOW_ID_GREEN_UNLOCK = 3
    GLOW_ID_GREEN_UPGRADE = 4
    GLOW_ID_ORANGE_SPECIAL = 5
    GLOW_ID_ORANGE_UPGRADE = 6
