# Embedded file name: scripts/client/gui/Scaleform/genConsts/CONTACTS_ALIASES.py


class CONTACTS_ALIASES(object):
    FIND_CONTACT_VIEW_ALIAS = 'SearchContactView'
    FIND_CONTACT_VIEW_LINKAGE = 'SearchContactViewUI'
    GROUP_RENAME_VIEW_ALIAS = 'GroupRenameView'
    GROUP_CREATE_VIEW_ALIAS = 'GroupCreateView'
    GROUP_MANAGE_VIEW_LINKAGE = 'GroupManageViewUI'
    CONTACT_EDIT_NOTE_VIEW_ALIAS = 'ContactEditNoteView'
    CONTACT_CREATE_NOTE_VIEW_ALIAS = 'ContactCreateNoteView'
    CONTACT_NOTE_MANAGE_LINKAGE = 'ContactNoteManageViewUI'
    GROUP_DELETE_VIEW_ALIAS = 'GroupDeleteView'
    GROUP_DELETE_VIEW_LINKAGE = 'GroupDeleteViewUI'
    CONTACTS_SETTINGS_VIEW_ALIAS = 'ContactsSettingsView'
    CONTACTS_SETTINGS_VIEW_LINKAGE = 'ContactsSettingsViewUI'
    CONTACTS_LIST_MAIN_CATEGORY_LINKAGE = 'ContactsListMainCategoryUI'
    CONTACTS_LIST_GROUP_CATEGORY_LINKAGE = 'ContactsListGroupCategoryUI'
    CONTACTS_LIST_USER_ROSTER_ITEM_RENDERER_LINKAGE = 'ContactsListItemRendererUI'
    CONTACTS_TREE = 'contactsTree'
    CONTACTS_MENAGE_MESSAGES_NORMALLY = 0
    CONTACTS_MENAGE_MESSAGES_GROUP = 1
    CONTACTS_POPOVER = 'ContactsPopover'
    GROUP_FRIENDS_CATEGORY_ID = 0
    GROUP_FORMATIONS_CATEGORY_ID = 1
    GROUP_OTHER_CATEGORY_ID = 2
    IGNORED_GROUP_RESERVED_ID = 101
    PENDING_FRIENDS_GROUP_RESERVED_ID = 102
    CLAN_GROUP_RESERVED_ID = 103
    REFERRALS_GROUP_RESERVED_ID = 104
    REFERRERS_GROUP_RESERVED_ID = 105
    CLUB_GROUP_RESERVED_ID = 106
    CAN_MOVE_TO_FRIENDS_GROUPS_IDS = [101,
     102,
     103,
     104,
     105,
     106]
    GROUP_IS_RESIZABLE = 1
    GROUP_IS_DROP_ALLOWED = 2
    GROUP_CAN_BE_MANAGED = 4
