# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/client/gui/Scaleform/genConsts/CONTEXT_MENU_HANDLER_TYPE.py


class CONTEXT_MENU_HANDLER_TYPE(object):
    CREW = 'crew'
    CHANNEL_LIST = 'channelList'
    VEHICLE = 'vehicle'
    RESEARCH_ITEM = 'researchItem'
    RESEARCH_VEHICLE = 'researchVehicle'
    BLUEPRINT_VEHICLE = 'blueprintVehicle'
    BASE_USER = 'baseUser'
    BASE_CLAN = 'baseClan'
    BATTLE_RESULTS_USER = 'battleResultsUser'
    PREBATTLE_USER = 'prebattleUser'
    UNIT_USER = 'unitUser'
    FORT_BUILDING = 'fortBuilding'
    TECHNICAL_MAINTENANCE = 'technicalMaintenance'
    CONTACTS_GROUP = 'contactsGroup'
    PLAYER_CONTACTS = 'playerContacts'
    STORE_VEHICLE = 'storeVehicle'
    PROFILE_VEHICLE = 'profileVehicle'
    VEH_COMPARE = 'vehCompare'
    CUSTOM_USER = 'customUser'
    CUSTOMIZATION_ITEM = 'customizationItem'
    STRONGHOLD_USER = 'strongholdUser'
    SHOP = 'shop'
    STORAGE_FOR_SELL_ITEM = 'storageForSellItem'
    STORAGE_MODULES_SHELLS_ITEM = 'storageModulesShellsItem'
    STORAGE_EQUIPMENT_ITEM = 'storageEquipmentItem'
    STORAGE_BONS_ITEM = 'storageBonsItem'
    STORAGE_VEHICLES_REGULAR_ITEM = 'storageVehiclesRegularItem'
    STORAGE_VEHICLES_RESTORE_ITEM = 'storageVehiclesRestoreItem'
    STORAGE_VEHICLES_RENTED_ITEM = 'storageVehiclesRentedItem'
    STORAGE_PERSONAL_RESERVE_ITEM = 'storagePersonalReserveItem'
    STORAGE_CUSTOMZIZATION_ITEM = 'storageCustomizationItem'
    STORAGE_BLUEPRINTS_ITEM = 'storageBlueprintsItem'
    STORAGE_CREW_BOOKS_ITEM = 'storageCrewBooksItem'
    STORAGE_CREW_BOOKS_NO_SALE_ITEM = 'storageCrewBooksNoSaleItem'
    STORAGE_DEMOUNT_KIT_ITEM = 'storageDemountKitItem'
    STORAGE_OPTIONAL_DEVICE_ITEM = 'storageOptionalDeviceItem'
