# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/client/gui/Scaleform/genConsts/CUSTOMIZATION_ALIASES.py


class CUSTOMIZATION_ALIASES(object):
    CONFIRM_CUSTOMIZATION_ITEM_DIALOG = 'ConfirmCustomizationItemDialog_UI'
    CUSTOMIZATION_SHEET_BTN_RENDERER_UI = 'CustomizationSheetBtnRendererUI'
    CUSTOMIZATION_SHEET_SCALE_COLOR_RENDERER_UI = 'CustomizationSheetScaleColorsRendererUI'
    CUSTOMIZATION_SHEET_STYLE_RENDERER_UI = 'CustomizationSheetStyleRendererUI'
    CUSTOMIZATION_SHEET_STYLE_ITEM_RENDERER_UI = 'CustomizationSheetStyleItemRendererUI'
    CUSTOMIZATION_SHEET_CHECKBOX_RENDERER_UI = 'CustomizationSheetCheckboxRendererUI'
    CUSTOMIZATION_SHEET_ACTION_APPLY_TO_ALL_PARTS = 0
    CUSTOMIZATION_SHEET_ACTION_APPLY_TO_ALL_SEASONS = 1
    CUSTOMIZATION_SHEET_ACTION_REMOVE_ONE = 2
    CUSTOMIZATION_SHEET_ACTION_COLOR_CHANGE = 3
    CUSTOMIZATION_SHEET_ACTION_SCALE_CHANGE = 4
    CUSTOMIZATION_SHEET_RENT_CHECKBOX_CHANGE = 5
    COLOR_BTNS_GROUP = 'colorsGroup'
    SCALE_BTNS_GROUP = 'scaleGroup'
