# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/client/gui/Scaleform/genConsts/CUSTOMIZATION_ALIASES.py


class CUSTOMIZATION_ALIASES(object):
    CONFIRM_CUSTOMIZATION_ITEM_DIALOG = 'ConfirmCustomizationItemDialog_UI'
    CUSTOMIZATION_SHEET_BTN_RENDERER_UI = 'CustomizationSheetBtnRendererUI'
    CUSTOMIZATION_SHEET_SCALE_COLOR_RENDERER_UI = 'CustomizationSheetScaleColorsRendererUI'
    CUSTOMIZATION_SHEET_SWITCH_RENDERER_UI = 'CustomizationSheetSwitchRendererUI'
    CUSTOMIZATION_SHEET_ACTION_APPLY_TO_ALL_PARTS = 0
    CUSTOMIZATION_SHEET_ACTION_APPLY_TO_ALL_SEASONS = 1
    CUSTOMIZATION_SHEET_ACTION_REMOVE_ONE = 2
    CUSTOMIZATION_SHEET_ACTION_COLOR_CHANGE = 3
    CUSTOMIZATION_SHEET_ACTION_SCALE_CHANGE = 4
    CUSTOMIZATION_SHEET_RENT_CHECKBOX_CHANGE = 5
    CUSTOMIZATION_SHEET_ACTION_REMOVE_FROM_ALL_PARTS = 6
    CUSTOMIZATION_SHEET_ACTION_CLOSE = 7
    CUSTOMIZATION_SHEET_ACTION_MIRROR = 8
    CUSTOMIZATION_SHEET_ACTION_MOVE = 9
    CUSTOMIZATION_SHEET_ACTION_EDIT = 10
    CUSTOMIZATION_SHEET_ACTION_INFO = 11
    CUSTOMIZATION_POJECTION_INTERACTION_DEFAULT = -1
    CUSTOMIZATION_POJECTION_INTERACTION_MOVE = 0
    CUSTOMIZATION_POJECTION_INTERACTION_SCALE = 1
    CUSTOMIZATION_POJECTION_INTERACTION_ROTATION = 2
    CUSTOMIZATION_SEASON_SUMMER = 0
    CUSTOMIZATION_SEASON_ = 1
    CUSTOMIZATION_SEASON = 2
    COLOR_BTNS_GROUP = 'colorsGroup'
    SCALE_BTNS_GROUP = 'scaleGroup'
    ANCHOR_TYPE_REGION = 0
    ANCHOR_TYPE_DECAL = 1
    ANCHOR_TYPE_PROJECTION_DECAL = 2
    SOUND_CUST_NEGATIVE = 'cust_negative'
    SOUND_RADIAL_BIG = 'radial_big'
    SOUND_RADIAL_SMALL = 'radial_small'
    SOUND_CUST_LOCK = 'cust_lock'
    SOUND_RADIAL_UNLOCK = 'cust_unlock'
    SOUND_CUST_CHOICE_NUMBER_DENIED = 'cust_choice_number_denied'
    PROJECTION_DECAL_TAB_SHOWN_FIELD = 'isProjectionDecalTabShown'
    USER_NUMBER_TAB_SHOWN_FIELD = 'isUserNumberTabShown'
    PROJECTION_DECAL_FORMFACTOR_ANY = 'formfactor_any'
    PROJECTION_DECAL_FORMFACTOR_SQUARE = 'formfactor_square'
    PROJECTION_DECAL_FORMFACTOR_RECT1X2 = 'formfactor_rect1x2'
    PROJECTION_DECAL_FORMFACTOR_RECT1X3 = 'formfactor_rect1x3'
    PROJECTION_DECAL_FORMFACTOR_RECT1X4 = 'formfactor_rect1x4'
    PROJECTION_DECAL_FORMFACTOR_RECT1X6 = 'formfactor_rect1x6'
