# Embedded file name: scripts/client/gui/Scaleform/genConsts/CYBER_SPORT_HELP_IDS.py


class CYBER_SPORT_HELP_IDS(object):
    CYBERSPORT_INTRO_HELP = 'CYBERSPORT_INTRO_HELP'
    CYBERSPORT_STATIC_TEAM_ROOM_HELP = 'CYBERSPORT_STATIC_TEAM_ROOM_HELP'
    CYBERSPORT_TEAM_LIST_HELP = 'CYBERSPORT_TEAM_LIST_HELP'
