# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/client/gui/Scaleform/genConsts/DAMAGEINDICATOR.py


class DAMAGEINDICATOR(object):
    ALLY_AT_SPG = 'ally_AT-SPG'
    ALLY_HEAVY_TANK = 'ally_heavyTank'
    ALLY_LIGHT_TANK = 'ally_lightTank'
    ALLY_MEDIUM_TANK = 'ally_mediumTank'
    ALLY_SPG = 'ally_SPG'
    AMMO_CIRCLE = 'ammoCircle'
    ARTILLERY = 'artillery'
    AT_SPG = 'AT-SPG'
    BLOCK_CIRCLE = 'blockCircle'
    BLOCKED_BIG = 'blockedBig'
    BLOCKED_MEDIUM = 'blockedMedium'
    BLOCKED_SMALL = 'blockedSmall'
    BLOCKED_STANDARD = 'blockedStandard'
    BOMBER = 'bomber'
    COMMANDER_CIRCLE = 'commanderCircle'
    CRIT = 'crit'
    CRIT_BLIND = 'critBlind'
    CRIT_CIRCLE = 'critCircle'
    CRIT_CIRCLE_BLIND = 'critCircleBlind'
    DAMAGE_BIG = 'damageBig'
    DAMAGE_BIG_BLIND = 'damageBigBlind'
    DAMAGE_CIRCLE = 'damageCircle'
    DAMAGE_CIRCLE_BLIND = 'damageCircleBlind'
    DAMAGE_MEDIUM = 'damageMedium'
    DAMAGE_MEDIUM_BLIND = 'damageMediumBlind'
    DAMAGE_SMALL = 'damageSmall'
    DAMAGE_SMALL_BLIND = 'damageSmallBlind'
    DAMAGE_STANDARD = 'damageStandard'
    DAMAGE_STANDARD_BLIND = 'damageStandardBlind'
    DRIVER_CIRCLE = 'driverCircle'
    ENGINE_CIRCLE = 'engineCircle'
    EVENT_BIG_BOSS_BOT = 'eventBigBossBot'
    EVENT_BOMBER_BOT = 'eventBomberBot'
    EVENT_HUNTER_BOT = 'eventHunterBot'
    EVENT_RUNNER_BOT = 'eventRunnerBot'
    EVENT_RUNNER_SHOOTER_BOT = 'eventRunnerShooterBot'
    EVENT_SENTRY_BOT = 'eventSentryBot'
    EVENT_TURRET_BOT = 'eventTurretBot'
    GUN_CIRCLE = 'gunCircle'
    GUNNER_CIRCLE = 'gunnerCircle'
    HEAVY_TANK = 'heavyTank'
    LIGHT_TANK = 'lightTank'
    MEDIUM_TANK = 'mediumTank'
    RADIO_CIRCLE = 'radioCircle'
    RADIOMAN_CIRCLE = 'radiomanCircle'
    RELOADER_CIRCLE = 'reloaderCircle'
    SPG = 'SPG'
    TANKS_CIRCLE = 'tanksCircle'
    TRACKS_CIRCLE = 'tracksCircle'
    TRIPLEX_CIRCLE = 'triplexCircle'
    TURRET_CIRCLE = 'turretCircle'
    WHEEL_CIRCLE = 'wheelCircle'
