# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/client/gui/Scaleform/genConsts/EVENT_LOG_CONSTANTS.py


class EVENT_LOG_CONSTANTS(object):
    """
    DO NOT MODIFY!
    Generated with yaml.
    __author__ = 'yaml_processor'
    null
    """
    SST_EVENT_LOG = 0
    SST_TOOLTIP = 2
    SST_VIEWSTACK = 4
    SST_CONTEXT_MENU = 8
    SST_LOADER = 16
    SST_HANDLE_INPUT = 32
    SST_UI_COMMON = 128
    SUB_SYSTEMS = [SST_EVENT_LOG,
     SST_TOOLTIP,
     SST_VIEWSTACK,
     SST_CONTEXT_MENU,
     SST_LOADER,
     SST_HANDLE_INPUT,
     SST_UI_COMMON]
    EVENT_TYPE_CLICK = 'click'
    EVENT_TYPE_ROLL_OVER = 'rollOver'
    EVENT_TYPE_ROLL_OUT = 'rollOut'
    EVENT_TYPE_MOUSE_DOWN = 'mouseDown'
    EVENT_TYPE_MOUSE_UP = 'mouseUp'
    EVENT_TYPE_DOUBLE_CLICK = 'doubleClick'
    EVENT_TYPE_ITEM_BUTTON_CLICK = 'buttonClick'
    EVENT_TYPE_ITEM_CLICK = 'itemClick'
    EVENT_TYPE_ITEM_PRESS = 'itemPress'
    EVENT_TYPE_ITEM_ROLL_OVER = 'itemRollOver'
    EVENT_TYPE_ITEM_ROLL_OUT = 'itemRollOut'
    EVENT_TYPE_ITEM_DOUBLE_CLICK = 'itemDoubleClick'
    EVENT_TYPE_ITEM_INDEX_CHANGE = 'listIndexChange'
    EVENT_TYPE_ITEM_DRAG_OVER = 'itemDragOver'
    EVENT_TYPE_ITEM_DRAG_OUT = 'itemDragOut'
    EVENT_TYPE_ITEM_RELEASE_OUTSIDE = 'itemReleaseOutside'
    EVENT_TYPE_ON_WINDOW_OPEN = 'onWindowOpen'
    EVENT_TYPE_ON_WINDOW_CLOSE = 'onWindowClose'
    EVENT_TYPE_ON_WINDOW_MINIMIZE = 'onWindowMinimize'
    EVENT_TYPE_ON_WINDOW_RESIZE = 'onWindowResize'
    EVENT_TYPE_ON_DROPDOWN_OPEN = 'onDropDownOpen'
    EVENT_TYPE_ON_DROPDOWN_CLOSE = 'onDropDownClose'
    EVENT_TYPE_ON_TOOLTIP_SHOW = 'onToolTipShow'
    EVENT_TYPE_ON_TOOLTIP_HIDE = 'onToolTipHide'
    EVENT_TYPE_VIEWSTAK_ITEM_SHOW = 'onViewStackItemShow'
    EVENT_TYPE_VIEWSTAK_ITEM_HIDE = 'onViewStackItemHide'
    EVENT_TYPE_CONTEXT_MENU_SHOW = 'onContextMenuShow'
    EVENT_TYPE_CONTEXT_MENU_HIDE = 'onContextMenuHide'
    EVENT_TYPE_SYSTEM_MESSAGE_SHOW = 'onSystemMessgeShow'
    EVENT_TYPE_SYSTEM_MESSAGE_HIDE = 'onSystemMessgeHide'
    EVENT_TYPE_VIEW_LOADED = 'viewLoaded'
    EVENT_TYPE_VIEW_UNLOADED = 'viewUnloaded'
    EVENT_TYPE_HANDLER_INPUT_KEY_DOWN = 'keyDown'
    EVENT_TYPE_HANDLER_INPUT_KEY_UP = 'keyUp'
    EVENT_TYPE_DATA = 'data'
    EVENT_TYPES = [EVENT_TYPE_CLICK,
     EVENT_TYPE_ROLL_OVER,
     EVENT_TYPE_ROLL_OUT,
     EVENT_TYPE_MOUSE_DOWN,
     EVENT_TYPE_MOUSE_UP,
     EVENT_TYPE_DOUBLE_CLICK,
     EVENT_TYPE_ITEM_BUTTON_CLICK,
     EVENT_TYPE_ITEM_CLICK,
     EVENT_TYPE_ITEM_PRESS,
     EVENT_TYPE_ITEM_ROLL_OVER,
     EVENT_TYPE_ITEM_ROLL_OUT,
     EVENT_TYPE_ITEM_DOUBLE_CLICK,
     EVENT_TYPE_ITEM_INDEX_CHANGE,
     EVENT_TYPE_ITEM_DRAG_OVER,
     EVENT_TYPE_ITEM_DRAG_OUT,
     EVENT_TYPE_ITEM_RELEASE_OUTSIDE,
     EVENT_TYPE_ON_WINDOW_OPEN,
     EVENT_TYPE_ON_WINDOW_CLOSE,
     EVENT_TYPE_ON_WINDOW_MINIMIZE,
     EVENT_TYPE_ON_WINDOW_RESIZE,
     EVENT_TYPE_ON_DROPDOWN_OPEN,
     EVENT_TYPE_ON_DROPDOWN_CLOSE,
     EVENT_TYPE_ON_TOOLTIP_SHOW,
     EVENT_TYPE_ON_TOOLTIP_HIDE,
     EVENT_TYPE_VIEWSTAK_ITEM_SHOW,
     EVENT_TYPE_VIEWSTAK_ITEM_HIDE,
     EVENT_TYPE_CONTEXT_MENU_SHOW,
     EVENT_TYPE_CONTEXT_MENU_HIDE,
     EVENT_TYPE_VIEW_LOADED,
     EVENT_TYPE_VIEW_UNLOADED,
     EVENT_TYPE_HANDLER_INPUT_KEY_DOWN,
     EVENT_TYPE_HANDLER_INPUT_KEY_UP,
     EVENT_TYPE_DATA]
    EVENT_CODE_CLICK = 0
    EVENT_CODE_ROLL_OVER = 1
    EVENT_CODE_ROLL_OUT = 2
    EVENT_CODE_MOUSE_DOWN = 3
    EVENT_CODE_MOUSE_UP = 4
    EVENT_CODE_DOUBLE_CLICK = 5
    EVENT_CODE_ITEM_BUTTON_CLICK = 6
    EVENT_CODE_ITEM_CLICK = 7
    EVENT_CODE_ITEM_PRESS = 8
    EVENT_CODE_ITEM_ROLL_OVER = 9
    EVENT_CODE_ITEM_ROLL_OUT = 10
    EVENT_CODE_ITEM_DOUBLE_CLICK = 11
    EVENT_CODE_ITEM_INDEX_CHANGE = 12
    EVENT_CODE_ITEM_DRAG_OVER = 13
    EVENT_CODE_ITEM_DRAG_OUT = 14
    EVENT_CODE_ITEM_RELEASE_OUTSIDE = 15
    EVENT_CODE_ON_WINDOW_OPEN = 32
    EVENT_CODE_ON_WINDOW_CLOSE = 33
    EVENT_CODE_ON_WINDOW_MINIMIZE = 34
    EVENT_CODE_ON_WINDOW_RESIZE = 35
    EVENT_CODE_ON_DROPDOWN_OPEN = 36
    EVENT_CODE_ON_DROPDOWN_CLOSE = 37
    EVENT_CODE_ON_TOOLTIP_SHOW = 128
    EVENT_CODE_ON_TOOLTIP_HIDE = 129
    EVENT_CODE_VIEWSTAK_ITEM_SHOW = 130
    EVENT_CODE_VIEWSTAK_ITEM_HIDE = 131
    EVENT_CODE_CONTEXT_MENU_SHOW = 132
    EVENT_CODE_CONTEXT_MENU_HIDE = 133
    EVENT_CODE_VIEW_LOADED = 134
    EVENT_CODE_VIEW_UNLOADED = 135
    EVENT_CODE_HANDLER_INPUT_KEY_DOWN = 256
    EVENT_CODE_HANDLER_INPUT_KEY_UP = 257
    EVENT_CODE_DATA = 4096
    EVENT_CODES = [EVENT_CODE_CLICK,
     EVENT_CODE_ROLL_OVER,
     EVENT_CODE_ROLL_OUT,
     EVENT_CODE_MOUSE_DOWN,
     EVENT_CODE_MOUSE_UP,
     EVENT_CODE_DOUBLE_CLICK,
     EVENT_CODE_ITEM_BUTTON_CLICK,
     EVENT_CODE_ITEM_CLICK,
     EVENT_CODE_ITEM_PRESS,
     EVENT_CODE_ITEM_ROLL_OVER,
     EVENT_CODE_ITEM_ROLL_OUT,
     EVENT_CODE_ITEM_DOUBLE_CLICK,
     EVENT_CODE_ITEM_INDEX_CHANGE,
     EVENT_CODE_ITEM_DRAG_OVER,
     EVENT_CODE_ITEM_DRAG_OUT,
     EVENT_CODE_ITEM_RELEASE_OUTSIDE,
     EVENT_CODE_ON_WINDOW_OPEN,
     EVENT_CODE_ON_WINDOW_CLOSE,
     EVENT_CODE_ON_WINDOW_MINIMIZE,
     EVENT_CODE_ON_WINDOW_RESIZE,
     EVENT_CODE_ON_DROPDOWN_OPEN,
     EVENT_CODE_ON_DROPDOWN_CLOSE,
     EVENT_CODE_ON_TOOLTIP_SHOW,
     EVENT_CODE_ON_TOOLTIP_HIDE,
     EVENT_CODE_VIEWSTAK_ITEM_SHOW,
     EVENT_CODE_VIEWSTAK_ITEM_HIDE,
     EVENT_CODE_CONTEXT_MENU_SHOW,
     EVENT_CODE_CONTEXT_MENU_HIDE,
     EVENT_CODE_VIEW_LOADED,
     EVENT_CODE_VIEW_UNLOADED,
     EVENT_CODE_HANDLER_INPUT_KEY_DOWN,
     EVENT_CODE_HANDLER_INPUT_KEY_UP,
     EVENT_CODE_DATA]
    IMAGINARY_UIID = 0
