# Embedded file name: scripts/client/gui/Scaleform/genConsts/EVENT_LOG_CONSTANTS.py


class EVENT_LOG_CONSTANTS(object):
    SST_EVENT_LOG = 0
    SST_TOOLTIP = 2
    SST_CONTEXT_MENU = 4
    SST_UI_COMMON = 128
    SST_UI_FORT = 129
    SUB_SYSTEMS = [SST_EVENT_LOG,
     SST_TOOLTIP,
     SST_CONTEXT_MENU,
     SST_UI_COMMON,
     SST_UI_FORT]
    EVENT_TYPE_CLICK = 'click'
    EVENT_TYPE_BUTTON_CLICK = 'buttonClick'
    EVENT_TYPE_ON_WINDOW_OPEN = 'onWindowOpen'
    EVENT_TYPE_ON_WINDOW_CLOSE = 'onWindowClose'
    EVENT_TYPE_ON_WINDOW_MINIMIZE = 'onWindowMinimize'
    EVENT_TYPE_STEP_1 = 'step1'
    EVENT_TYPE_STEP_2 = 'step2'
    EVENT_TYPE_STEP_3 = 'step3'
    EVENT_TYPE_DATA = 'data'
    EVENT_TYPE_INDEX_CHANGE = 'listIndexChange'
    EVENT_TYPES = [EVENT_TYPE_CLICK,
     EVENT_TYPE_BUTTON_CLICK,
     EVENT_TYPE_ON_WINDOW_OPEN,
     EVENT_TYPE_ON_WINDOW_CLOSE,
     EVENT_TYPE_ON_WINDOW_MINIMIZE,
     EVENT_TYPE_STEP_1,
     EVENT_TYPE_STEP_2,
     EVENT_TYPE_STEP_3,
     EVENT_TYPE_DATA,
     EVENT_TYPE_INDEX_CHANGE]
    CLICK = 0
    BUTTON_CLICK = 1
    ON_WINDOW_OPEN = 16
    ON_WINDOW_CLOSE = 17
    ON_WINDOW_MINIMIZE = 18
    STEP_1 = 256
    STEP_2 = 257
    STEP_3 = 258
    DATA = 4096
    INDEX_CHANGE = 4097
    EVENT_CODES = [CLICK,
     BUTTON_CLICK,
     ON_WINDOW_OPEN,
     ON_WINDOW_CLOSE,
     ON_WINDOW_MINIMIZE,
     STEP_1,
     STEP_2,
     STEP_3,
     DATA,
     INDEX_CHANGE]
