# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/client/gui/Scaleform/genConsts/HANGAR_ALIASES.py


class HANGAR_ALIASES(object):
    TANK_CAROUSEL = 'tankCarousel'
    RANKED_TANK_CAROUSEL = 'rankedTankCarousel'
    ENTRIES_CONTAINER = 'entriesContainer'
    EPICBATTLE_TANK_CAROUSEL = 'epicBattleTankCarousel'
    BATTLEPASS_TANK_CAROUSEL = 'battlePassTankCarousel'
    ROYALE_TANK_CAROUSEL = 'royaleTankCarousel'
    MAPBOX_TANK_CAROUSEL = 'mapboxTankCarousel'
    CREW = 'crew'
    AMMUNITION_PANEL = 'ammunitionPanel'
    RESEARCH_PANEL = 'researchPanel'
    TMEN_XP_PANEL = 'tmenXpPanel'
    VEHICLE_PARAMETERS = 'params'
    HEADER = 'header'
    RANKED_WIDGET = 'rankedWdgt'
    ALERT_MESSAGE_BLOCK = 'alertMessageBlock'
    EPIC_WIDGET = 'epicWdgt'
    SENIORITY_AWARDS_ENTRY_POINT_2020 = 'SeniorityAwardsEntryPoint2020'
    RANKED_PRIME_TIME = 'rankedPrimeTime.swf'
    EPIC_PRIME_TIME = 'epicPrimeTime.swf'
    TANK_CAROUSEL_UI = 'TankCarouselUI'
    VEH_PARAM_RENDERER_STATE_SIMPLE_TOP = 'simpleTop'
    VEH_PARAM_RENDERER_STATE_SIMPLE_BOTTOM = 'simpleBottom'
    VEH_PARAM_RENDERER_STATE_ADVANCED = 'advanced'
    VEH_PARAM_RENDERER_STATE_SEPARATOR = 'separator'
    VEH_PARAM_RENDERER_STATE_LINE_SEPARATOR = 'lineSeparator'
    VEH_PARAM_RENDERER_STATE_EXTRA = 'extra'
    VEH_PARAM_RENDERER_HIGHLIGHT_NONE = 'none'
    VEH_PARAM_RENDERER_HIGHLIGHT_POSITIVE = 'positive'
    VEH_PARAM_RENDERER_HIGHLIGHT_NEGATIVE = 'negative'
    VEH_PARAM_RENDERER_HIGHLIGHT_MIXED = 'mixed'
    PROGRESSIVE_REWARD_WIDGET = 'progressiveRewardWdgt'
    DAILY_QUEST_WIDGET = 'dqWidget'
    YHA_ENTRANCE_POINT = 'yhaEntrancePoint'
    BATTLE_PASSS_ENTRY_POINT = 'battlePassEntryPoint'
    BATTLE_ROYALE_ENTRY_POINT = 'battleRoyaleEntryPoint'
    BATTLE_ROYALE_TOURNAMENT = 'battleRoyaleTournament'
    SECONDARY_ENTRY_POINT = 'secondaryEntryPoint'
    AMMUNITION_SETUP_VIEW_VEHICLE_PARAMS = 'ammunitionSetupViewVehicleParams'
    AMMUNITION_PANEL_INJECT = 'ammunitionPanelInject'
    AMMUNITION_SETUP_VIEW_INJECT = 'ammunitionSetupViewInject'
    CREW_XP_PANEL_INJECT = 'crewXPPanelInject'
    CRAFT_MACHINE_ENTRY_POINT = 'CraftMachineEntryPoint'
    MAPBOX_ENTRY_POINT = 'MapBoxEntryPoint'
    MARATHON_ENTRY_POINT = 'MarathonEntryPoint'
    POST_PROGRESSION_INJECT = 'PostProgressionInject'
    POST_PROGRESSION_CMP_INJECT = 'PostProgressionCmpInject'
    POST_PROGRESSION_VIEW = 'VehPostProgressionView'
    POST_PROGRESSION_VEHICLE_PARAMS = 'PostProgressionVehicleParams'
