# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/client/gui/Scaleform/genConsts/HANGAR_ALIASES.py


class HANGAR_ALIASES(object):
    TANK_CAROUSEL = 'tankCarousel'
    RANKED_TANK_CAROUSEL = 'rankedTankCarousel'
    EPICBATTLE_TANK_CAROUSEL = 'epicBattleTankCarousel'
    BATTLEPASS_TANK_CAROUSEL = 'battlePassTankCarousel'
    ROYALE_TANK_CAROUSEL = 'royaleTankCarousel'
    BOB_TANK_CAROUSEL = 'bobTankCarousel'
    CREW = 'crew'
    AMMUNITION_PANEL = 'ammunitionPanel'
    RESEARCH_PANEL = 'researchPanel'
    TMEN_XP_PANEL = 'tmenXpPanel'
    VEHICLE_PARAMETERS = 'params'
    HEADER = 'header'
    RANKED_WIDGET = 'rankedWdgt'
    ALERT_MESSAGE_BLOCK = 'alertMessageBlock'
    EPIC_WIDGET = 'epicWdgt'
    SENIORITY_AWARDS_ENTRY_POINT = 'SENIORITY_AWARDS_ENTRY_POINT'
    RANKED_PRIME_TIME = 'rankedPrimeTime.swf'
    EPIC_PRIME_TIME = 'epicPrimeTime.swf'
    BOB_PRIME_TIME = 'rankedPrimeTime.swf'
    TANK_CAROUSEL_UI = 'TankCarouselUI'
    VEH_PARAM_RENDERER_STATE_SIMPLE_TOP = 'simpleTop'
    VEH_PARAM_RENDERER_STATE_SIMPLE_BOTTOM = 'simpleBottom'
    VEH_PARAM_RENDERER_STATE_ADVANCED = 'advanced'
    VEH_PARAM_RENDERER_STATE_SEPARATOR = 'separator'
    VEH_PARAM_RENDERER_STATE_LINE_SEPARATOR = 'lineSeparator'
    VEH_PARAM_RENDERER_STATE_EXTRA = 'extra'
    PROGRESSIVE_REWARD_WIDGET = 'progressiveRewardWdgt'
    DAILY_QUEST_WIDGET = 'dqWidget'
    BATTLE_PASSS_ENTRY_POINT = 'battlePassEntryPoint'
    TEN_YEARS_COUNTDOWN_ENTRY_POINT_INJECT = 'tenYearsCountdownEntryPointInject'
    AMMUNITION_SETUP_VIEW_VEHICLE_PARAMS = 'ammunitionSetupViewVehicleParams'
    AMMUNITION_PANEL_INJECT = 'ammunitionPanelInject'
    AMMUNITION_SETUP_VIEW_INJECT = 'ammunitionSetupViewInject'
    WHITE_TIGER_WIDGET = 'whiteTigerWidget'
    LOOTBOXES_WIDGET = 'lootboxesWidget'
    WT_EVENT_ENTRY_POINT = 'wtEventEntryPoint'
    WT_EVENT_PRIME_TIME_VIEW = 'wtEventPrimeTimeView'
    WT_EVENT_PRIME_TIME = 'wtEventPrimeTime.swf'
    WT_EVENT_CAROUSEL_WIDGET = 'wtEventCarouselWidget'
    WT_EVENT_CREW_WIDGET = 'wtEventCrewWidget'
    WT_EVENT_PARAMS_WIDGET = 'wtEventParamsWidget'
    HANGAR_COMMON = 'hangarCommon'
    HANGAR_EVENT = 'hangarEvent'
    HANGAR_BATTLE_ROYALE = 'hangarBattleRoyale'
    HANGAR_MODES = [HANGAR_COMMON, HANGAR_EVENT, HANGAR_BATTLE_ROYALE]
