# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/client/gui/Scaleform/genConsts/HANGAR_ALIASES.py


class HANGAR_ALIASES(object):
    TANK_CAROUSEL = 'tankCarousel'
    RANKED_TANK_CAROUSEL = 'rankedTankCarousel'
    EPICBATTLE_TANK_CAROUSEL = 'epicBattleTankCarousel'
    BATTLEPASS_TANK_CAROUSEL = 'battlePassTankCarousel'
    BOB_TANK_CAROUSEL = 'bobTankCarousel'
    EVENT_TANK_CAROUSEL = 'eventTankCarousel'
    CREW = 'crew'
    AMMUNITION_PANEL = 'ammunitionPanel'
    RESEARCH_PANEL = 'researchPanel'
    TMEN_XP_PANEL = 'tmenXpPanel'
    VEHICLE_PARAMETERS = 'params'
    HEADER = 'header'
    RANKED_WIDGET = 'rankedWdgt'
    ALERT_MESSAGE_BLOCK = 'alertMessageBlock'
    EPIC_WIDGET = 'epicWdgt'
    SENIORITY_AWARDS_ENTRY_POINT = 'SENIORITY_AWARDS_ENTRY_POINT'
    RANKED_PRIME_TIME = 'rankedPrimeTime.swf'
    EPIC_PRIME_TIME = 'epicPrimeTime.swf'
    BOB_PRIME_TIME = 'rankedPrimeTime.swf'
    TANK_CAROUSEL_UI = 'TankCarouselUI'
    VEH_PARAM_RENDERER_STATE_SIMPLE_TOP = 'simpleTop'
    VEH_PARAM_RENDERER_STATE_SIMPLE_BOTTOM = 'simpleBottom'
    VEH_PARAM_RENDERER_STATE_ADVANCED = 'advanced'
    VEH_PARAM_RENDERER_STATE_SEPARATOR = 'separator'
    PROGRESSIVE_REWARD_WIDGET = 'progressiveRewardWdgt'
    DAILY_QUEST_WIDGET = 'dqWidget'
    BATTLE_PASSS_ENTRY_POINT = 'battlePassEntryPoint'
    TEN_YEARS_COUNTDOWN_ENTRY_POINT_INJECT = 'tenYearsCountdownEntryPointInject'
    EVENT_REPAIR_COMPONENT = 'eventRepairComponent'
    EVENT_TANK_RENT_COMPONENT = 'eventTankRentComponent'
    EVENT_QUESTS_COMPONENT = 'eventQuestsComponent'
    SE20_BANNER = 'se20Banner'
