# Embedded file name: scripts/client/gui/Scaleform/genConsts/ICON_TEXT_FRAMES.py


class ICON_TEXT_FRAMES(object):
    EMPTY = 'empty'
    CREDITS = 'credits'
    GOLD = 'gold'
    GOLD_DISCOUNT = 'goldDiscount'
    XP = 'xp'
    ELITE_XP = 'eliteXp'
    ELITE = 'elite'
    ARROW_DOWN = 'arrowDown'
    ARROW_UP = 'arrowUp'
    ARROW_DOWN_DISABLED = 'arrowDownDisabled'
    ELITE_TANK_XP = 'elite_tank_xp'
    FREE_XP = 'freeXp'
    TANK_DAILYXPFACTOR = 'tank_dailyXPFactor'
    TANK_UNLOCK_PRICE = 'tank_unlock_price'
    DOUBLE_XP_FACTOR = 'doubleXPFactor'
    ACTION_XP_FACTOR = 'actionXPFactor'
    VCOIN = 'vcoin'
    CLASS1 = 'class1'
    CLASS2 = 'class2'
    CLASS3 = 'class3'
    CLASS4 = 'class4'
    XP_PRICE = 'xp_price'
    DEFRES = 'defRes'
    RENTALS = 'rentals'
    REWARD_SHEET = 'sheets'
