# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/client/gui/Scaleform/genConsts/PERSONAL_MISSIONS_ALIASES.py


class PERSONAL_MISSIONS_ALIASES(object):
    PERSONAL_MISSIONS_PAGE_ALIAS = 'PersonalMissionsPage'
    PERSONAL_MISSIONS_MAP_VIEW_ALIAS = 'PersonalMissionsMapView'
    PERSONAL_MISSIONS_MAP_VIEW_LINKAGE = 'PersonalMissionsMapViewUI'
    PERSONAL_MISSIONS_OPERATIONS_PAGE_ALIAS = 'PersonalMissionOperationsPage'
    PERSONAL_MISSIONS_OPERATIONS_PAGE_LINKAGE = 'personalMissionOperationsPage_UI'
    PERSONAL_MISSION_FIRST_ENTRY_VIEW_ALIAS = 'PersonalMissionFirstEntryView'
    PERSONAL_MISSION_FIRST_ENTRY_AWARD_VIEW_ALIAS = 'PersonalMissionFirstEntryAwardView'
    PERSONAL_MISSION_AWARD_CONGRATULATION_VIEW_ALIAS = 'PersonalMissionAwardCongratulationView'
    PERSONAL_MISSIONS_AWARDS_VIEW_ALIAS = 'PersonalMissionsAwardsView'
    PERSONAL_MISSIONS_AWARDS_VIEW_LINKAGE = 'PersonalMissionsAwardsViewUI'
    PERSONAL_MISSIONS_PLAN_OPER_1_LINKAGE = 'PersonalMissionsPlanOper1UI'
    PERSONAL_MISSIONS_PLAN_OPER_2_LINKAGE = 'PersonalMissionsPlanOper2UI'
    PERSONAL_MISSIONS_PLAN_LT_LINKAGE = 'PersonalMissionsPlanLTUI'
    PERSONAL_MISSIONS_PLAN_MT_LINKAGE = 'PersonalMissionsPlanMTUI'
    PERSONAL_MISSIONS_PLAN_HT_LINKAGE = 'PersonalMissionsPlanHTUI'
    PERSONAL_MISSIONS_PLAN_AT_SPG_LINKAGE = 'PersonalMissionsPlanAT_SPGUI'
    PERSONAL_MISSIONS_PLAN_SPG_LINKAGE = 'PersonalMissionsPlanSPGUI'
    FREE_SHEET_POPOVER = 'FreeSheetPopover'
    TANK_GIRLS_POPOVER = 'TankgirlsPopover'
    OPERATION_MAIN_AWARD_LINKAGE = 'MainAwardsUI'
    REGION_NOT_COMPLETED = 0
    REGION_COMPLETED = 1
    REGION_FULLY_COMPLETED = 2
    REGION_NOT_AVAILABLE = 3
    REGION_IN_PROGRESS = 4
    REGION_STATES = [REGION_NOT_COMPLETED,
     REGION_COMPLETED,
     REGION_FULLY_COMPLETED,
     REGION_NOT_AVAILABLE,
     REGION_IN_PROGRESS]
    OPERATION_UNLOCKED_STATE = 'unlocked'
    OPERATION_CURRENT_STATE = 'current'
    OPERATION_LOCKED_STATE = 'locked'
    OPERATION_COMPLETE_STATE = 'completed'
    OPERATION_COMPLETE_FULL_STATE = 'fullyCompleted'
    OPERATION_NO_VEHICLE_STATE = 'noVehicle'
    OPERATION_STATES = [OPERATION_UNLOCKED_STATE,
     OPERATION_CURRENT_STATE,
     OPERATION_LOCKED_STATE,
     OPERATION_COMPLETE_STATE,
     OPERATION_COMPLETE_FULL_STATE]
    BADGES_1_LINKAGE = 'Badges1UI'
    BADGES_2_LINKAGE = 'Badges2UI'
    BADGES_3_LINKAGE = 'Badges3UI'
    BADGES_4_LINKAGE = 'Badges4UI'
    BADGES_5_LINKAGE = 'Badges5UI'
    BADGES_CMP_LINKAGES = [BADGES_1_LINKAGE,
     BADGES_2_LINKAGE,
     BADGES_3_LINKAGE,
     BADGES_4_LINKAGE,
     BADGES_5_LINKAGE]
    AWARDS_1_LINKAGE = 'Awards1UI'
    AWARDS_2_LINKAGE = 'Awards2UI'
    AWARDS_3_LINKAGE = 'Awards3UI'
    AWARDS_4_LINKAGE = 'Awards4UI'
    AWARDS_CMP_LINKAGES = [AWARDS_1_LINKAGE,
     AWARDS_2_LINKAGE,
     AWARDS_3_LINKAGE,
     AWARDS_4_LINKAGE]
