# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/client/gui/Scaleform/genConsts/PERSONAL_MISSIONS_BUTTONS.py


class PERSONAL_MISSIONS_BUTTONS(object):
    NO_BUTTONS = 0
    START_BTN_VISIBLE = 1
    START_BTN_ENABLED = 2
    RETRY_BTN_VISIBLE = 4
    DISCARD_BTN_VISIBLE = 8
    DISCARD_BTN_ENABLED = 16
    HOLD_AWARD_SHEET_BTN_VISIBLE = 32
    HOLD_AWARD_SHEET_BTN_ENABLED = 64
    OBTAIN_AWARD_BTN_VISIBLE = 128
    RETRY_BTN_ENABLED = 256
    PAUSE_BTN_VISIBLE = 512
    DETAILED_VIEW_BTN_STATES = [NO_BUTTONS,
     START_BTN_VISIBLE,
     START_BTN_ENABLED,
     RETRY_BTN_VISIBLE,
     DISCARD_BTN_VISIBLE,
     DISCARD_BTN_ENABLED,
     HOLD_AWARD_SHEET_BTN_VISIBLE,
     HOLD_AWARD_SHEET_BTN_ENABLED,
     OBTAIN_AWARD_BTN_VISIBLE,
     RETRY_BTN_ENABLED,
     PAUSE_BTN_VISIBLE]
    OPERATION_FOOTER_BTN_NONE = 0
    OPERATION_FOOTER_BTN_COMPLETE_USING_SHEETS = 1
    OPERATION_FOOTER_BTN_RESUME_TO_CAMPAIGN = 2
    OPERATION_FOOTER_BTN_PROCEED_EXECUTION = 3
    OPERATION_FOOTER_BTN_STATES = [OPERATION_FOOTER_BTN_NONE, OPERATION_FOOTER_BTN_COMPLETE_USING_SHEETS, OPERATION_FOOTER_BTN_RESUME_TO_CAMPAIGN]
