# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/client/gui/Scaleform/genConsts/PERSONAL_MISSIONS_ALIASES.py


class PERSONAL_MISSIONS_ALIASES(object):
    PERSONAL_MISSIONS_PAGE_ALIAS = 'PersonalMissionsPage'
    PERSONAL_MISSIONS_MAP_VIEW_ALIAS = 'PersonalMissionsMapView'
    PERSONAL_MISSIONS_OPERATIONS = 'PersonalMissionOperations'
    PERSONAL_MISSIONS_OPERATIONS_PAGE_ALIAS = 'PersonalMissionOperationsPage'
    PERSONAL_MISSIONS2_OPERATIONS_PAGE_ALIAS = 'PersonalMissionSeason2OperationsPage'
    PERSONAL_MISSION_FIRST_ENTRY_VIEW_ALIAS = 'PersonalMissionFirstEntryView'
    PERSONAL_MISSION_BROWSER_VIEW_ALIAS = 'PersonalMissionsBrowserView'
    PERSONAL_MISSION_FIRST_ENTRY_AWARD_VIEW_ALIAS = 'PersonalMissionFirstEntryAwardView'
    PERSONAL_MISSIONS_AWARDS_VIEW_ALIAS = 'PersonalMissionsAwardsView'
    PERSONAL_MISSIONS_AWARDS_VIEW_LINKAGE = 'PersonalMissionsAwardsViewUI'
    PERSONAL_MISSIONS_PLAN_OPER_1_LINKAGE = 'PersonalMissionsPlanOper1UI'
    PERSONAL_MISSIONS_PLAN_OPER_2_LINKAGE = 'PersonalMissionsPlanOper2UI'
    PERSONAL_MISSIONS_PLAN_LT_LINKAGE = 'PersonalMissionsPlanLTUI'
    PERSONAL_MISSIONS_PLAN_MT_LINKAGE = 'PersonalMissionsPlanMTUI'
    PERSONAL_MISSIONS_PLAN_HT_LINKAGE = 'PersonalMissionsPlanHTUI'
    PERSONAL_MISSIONS_PLAN_AT_SPG_LINKAGE = 'PersonalMissionsPlanAT_SPGUI'
    PERSONAL_MISSIONS_PLAN_SPG_LINKAGE = 'PersonalMissionsPlanSPGUI'
    PERSONAL_MISSIONS_OPERATION_AWARDS_SCREEN_ALIAS = 'PersonalMissionsOperationAwardsScreen'
    PM_S2_PLAN_1_LINKAGE = 'PersonalMissionsS2Plan1UI'
    PM_S2_PLAN_2_LINKAGE = 'PersonalMissionsS2Plan2UI'
    PM_S2_PLAN_3_LINKAGE = 'PersonalMissionsS2Plan3UI'
    PM_S2_PLAN_4_LINKAGE = 'PersonalMissionsS2Plan4UI'
    PM_S1_PLAN_1_URL = 'personalMissionsPlanLT.swf'
    PM_S1_PLAN_2_URL = 'personalMissionsPlanMT.swf'
    PM_S1_PLAN_3_URL = 'personalMissionsPlanHT.swf'
    PM_S1_PLAN_4_URL = 'personalMissionsPlanAT_SPG.swf'
    PM_S1_PLAN_5_URL = 'personalMissionsPlanSPG.swf'
    PM_S2_PLAN_1_URL = 'PersonalMissionsS2Plan1.swf'
    PM_S2_PLAN_2_URL = 'PersonalMissionsS2Plan2.swf'
    PM_S2_PLAN_3_URL = 'PersonalMissionsS2Plan3.swf'
    PM_S2_PLAN_4_URL = 'PersonalMissionsS2Plan4.swf'
    FREE_SHEET_POPOVER = 'FreeSheetPopover'
    FREE_SHEET_PM2_POPOVER = 'FreeSheetMP2Popover'
    TANK_GIRLS_POPOVER = 'TankgirlsPopover'
    OPERATION_MAIN_AWARD_LINKAGE = 'MainAwardsUI'
    PERSONAL_MISSIONS_QUEST_AWARD_SCREEN_ALIAS = 'PersonalMissionsQuestAwardScreen'
    CHAIN_BTN_LINKACGE = 'ChainButtonUI'
    PERONAL_MISSIONS_OPERATIONS_SEASON_1_ID = 1
    PERONAL_MISSIONS_OPERATIONS_SEASON_2_ID = 2
    PERONAL_MISSIONS_PM_TYPE_REGULAR = 0
    PERONAL_MISSIONS_PM_TYPE_PERSONAL_MISSION_2 = 2
    REGION_NOT_COMPLETED = 0
    REGION_COMPLETED = 1
    REGION_FULLY_COMPLETED = 2
    REGION_NOT_AVAILABLE = 3
    REGION_IN_PROGRESS = 4
    REGION_DISABLED = 5
    REGION_ON_PAUSE = 6
    REGION_STATES = [REGION_NOT_COMPLETED,
     REGION_COMPLETED,
     REGION_FULLY_COMPLETED,
     REGION_NOT_AVAILABLE,
     REGION_IN_PROGRESS,
     REGION_DISABLED]
    OPERATION_UNLOCKED_STATE = 'unlocked'
    OPERATION_CURRENT_STATE = 'current'
    OPERATION_LOCKED_STATE = 'locked'
    OPERATION_COMPLETE_STATE = 'completed'
    OPERATION_COMPLETE_FULL_STATE = 'fullyCompleted'
    OPERATION_NO_VEHICLE_STATE = 'noVehicle'
    OPERATION_DISABLED_STATE = 'disabled'
    OPERATION_POSTPONED_STATE = 'postponed'
    OPERATION_STATES = [OPERATION_UNLOCKED_STATE,
     OPERATION_CURRENT_STATE,
     OPERATION_LOCKED_STATE,
     OPERATION_COMPLETE_STATE,
     OPERATION_COMPLETE_FULL_STATE,
     OPERATION_DISABLED_STATE,
     OPERATION_POSTPONED_STATE]
    BADGES_1_LINKAGE = 'Badges1UI'
    BADGES_2_LINKAGE = 'Badges2UI'
    BADGES_3_LINKAGE = 'Badges3UI'
    BADGES_4_LINKAGE = 'Badges4UI'
    BADGES_5_LINKAGE = 'Badges5UI'
    BADGES_CMP_LINKAGES = [BADGES_1_LINKAGE,
     BADGES_2_LINKAGE,
     BADGES_3_LINKAGE,
     BADGES_4_LINKAGE,
     BADGES_5_LINKAGE]
    AWARDS_1_LINKAGE = 'Awards1UI'
    AWARDS_2_LINKAGE = 'Awards2UI'
    AWARDS_3_LINKAGE = 'Awards3UI'
    AWARDS_4_LINKAGE = 'Awards4UI'
    AWARDS_CMP_LINKAGES = [AWARDS_1_LINKAGE,
     AWARDS_2_LINKAGE,
     AWARDS_3_LINKAGE,
     AWARDS_4_LINKAGE]
    POST_BATTLE_STATE_NONE = 'none'
    POST_BATTLE_STATE_DONE = 'done'
    POST_BATTLE_STATE_FULL_DONE = 'fullDone'
    POST_BATTLE_STATE_FAILED = 'failed'
    POST_BATTLE_STATE_IN_PROGRESS = 'inProgress'
