# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/client/gui/Scaleform/genConsts/PLAYERS_PANEL_STATE.py
"""
This file was generated using the wgpygen.
Please, don't edit this file manually.
"""

class PLAYERS_PANEL_STATE(object):
    NONE = -1
    HIDDEN = 0
    SHORT = 1
    MEDIUM = 2
    LONG = 3
    FULL = 4
    MEDIUM_NO_BADGES = 5
    FULL_NO_BADGES = 6
    EPIC_RANDOM_MEDIUM_PLAYER = 7
    EPIC_RANDOM_MEDIUM_TANK = 8
    EPIC_RANDOM_TOGGLED_HIDDEN = 9
    EPIC_RANDOM_TOGGLED_SHORT = 10
    EPIC_RANDOM_TOGGLED_MEDIUM_PLAYER = 11
    EPIC_RANDOM_TOGGLED_MEDIUM_TANK = 12
    EPIC_RANDOM_TOGGLED_FOCUS_SECOND = 13
    EPIC_RANDOM_TOGGLED_FOCUS_THIRD = 14
    EPIC_RANDOM_TOGGLED_BUTTON = 15
    EXTENDED_STATES = [EPIC_RANDOM_TOGGLED_HIDDEN,
     EPIC_RANDOM_TOGGLED_SHORT,
     EPIC_RANDOM_TOGGLED_MEDIUM_PLAYER,
     EPIC_RANDOM_TOGGLED_MEDIUM_TANK,
     EPIC_RANDOM_TOGGLED_FOCUS_SECOND,
     EPIC_RANDOM_TOGGLED_FOCUS_THIRD,
     EPIC_RANDOM_TOGGLED_BUTTON]
