# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/client/gui/Scaleform/genConsts/PLAYERS_PANEL_STATE.py
"""
This file was generated using the wgpygen.
Please, don't edit this file manually.
"""

class PLAYERS_PANEL_STATE(object):
    NONE = -1
    HIDDEN = 0
    SHORT = 1
    MEDIUM = 2
    LONG = 3
    FULL = 4
    MEDIUM_NO_BADGES = 5
    FULL_NO_BADGES = 6
    SHORT_NO_BADGES = 20
    LONG_NO_BADGES = 21
    EPIC_RANDOM_SINGLE_COLUMN_MEDIUM_PLAYER = 7
    EPIC_RANDOM_SINGLE_COLUMN_MEDIUM_TANK = 8
    EPIC_RANDOM_THREE_COLUMN_HIDDEN = 9
    EPIC_RANDOM_THREE_COLUMN_SHORT = 10
    EPIC_RANDOM_THREE_COLUMN_MEDIUM_PLAYER = 11
    EPIC_RANDOM_THREE_COLUMN_MEDIUM_TANK = 12
    EPIC_RANDOM_THREE_COLUMN_SHORT_SECOND_FOCUS = 13
    EPIC_RANDOM_THREE_COLUMN_MEDIUM_PLAYER_SECOND_FOCUS = 14
    EPIC_RANDOM_THREE_COLUMN_MEDIUM_TANK_SECOND_FOCUS = 15
    EPIC_RANDOM_THREE_COLUMN_SHORT_THIRD_FOCUS = 16
    EPIC_RANDOM_THREE_COLUMN_MEDIUM_PLAYER_THIRD_FOCUS = 17
    EPIC_RANDOM_THREE_COLUMN_MEDIUM_TANK_THIRD_FOCUS = 18
    EPIC_RANDOM_THREE_COLUMN_BUTTON = 19
    EXTENDED_STATES = [EPIC_RANDOM_THREE_COLUMN_HIDDEN,
     EPIC_RANDOM_THREE_COLUMN_SHORT,
     EPIC_RANDOM_THREE_COLUMN_MEDIUM_PLAYER,
     EPIC_RANDOM_THREE_COLUMN_MEDIUM_TANK,
     EPIC_RANDOM_THREE_COLUMN_SHORT_SECOND_FOCUS,
     EPIC_RANDOM_THREE_COLUMN_MEDIUM_PLAYER_SECOND_FOCUS,
     EPIC_RANDOM_THREE_COLUMN_MEDIUM_TANK_SECOND_FOCUS,
     EPIC_RANDOM_THREE_COLUMN_SHORT_THIRD_FOCUS,
     EPIC_RANDOM_THREE_COLUMN_MEDIUM_PLAYER_THIRD_FOCUS,
     EPIC_RANDOM_THREE_COLUMN_MEDIUM_TANK_THIRD_FOCUS,
     EPIC_RANDOM_THREE_COLUMN_BUTTON]
    BASE_STATES = [SHORT,
     MEDIUM,
     LONG,
     FULL]
    BASE_STATES_NO_BADGES = [SHORT_NO_BADGES,
     MEDIUM_NO_BADGES,
     LONG_NO_BADGES,
     FULL_NO_BADGES]
