# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/client/gui/Scaleform/genConsts/QUESTS_ALIASES.py


class QUESTS_ALIASES(object):
    FALLOUT_TILE_CHAINS_VIEW_ALIAS = 'FalloutQuestsTileChainsView'
    SLOTS_COUNT = 5
    NEED_RECEIVED_AWARD = 'needReceivedAward'
    FREE_SLOTS_AND_FREE_QUESTS = 'freeSlotsAndFreeQuests'
    FIRST_RUN = 'firstRun'
    EMPTY = 'empty'
    SEASON_VIEW_TAB_RANDOM = 'seasonViewTabRandom'
    SEASON_VIEW_TAB_FALLOUT = 'seasonViewTabFallout'
    RENDERER_TYPE_BLOCK_TITLE = 1
    RENDERER_TYPE_QUEST = 2
    MISSIONS_MARATHON_VIEW_PY_ALIAS = 'MissionsMarathonView'
    MISSIONS_MARATHON_VIEW_LINKAGE = 'MissionsMarathonViewUI'
    MISSIONS_GROUPED_VIEW_PY_ALIAS = 'MissionsGroupedView'
    MISSIONS_GROUPED_VIEW_LINKAGE = 'MissionsGroupedViewUI'
    MISSIONS_EVENT_BOARDS_VIEW_PY_ALIAS = 'MissionsEventBoardsView'
    MISSIONS_EVENT_BOARDS_VIEW_LINKAGE = 'MissionsEventBoardsViewUI'
    MISSIONS_CATEGORIES_VIEW_PY_ALIAS = 'MissionsCategoriesView'
    MISSIONS_CATEGORIES_VIEW_LINKAGE = 'MissionsCategoriesViewUI'
    CURRENT_VEHICLE_MISSIONS_VIEW_PY_ALIAS = 'CurrentVehicleMissionsView'
    CURRENT_VEHICLE_MISSIONS_VIEW_LINKAGE = 'CurrentVehicleMissionsViewUI'
    MISSIONS_FILTER_POPOVER_ALIAS = 'MissionsFilterPopover'
    MISSIONS_TOKEN_POPOVER_ALIAS = 'MissionsTokenPopover'
    MISSIONS_VEHICLE_SELECTOR_ALIAS = 'MissionsVehicleSelector'
    MISSIONS_VEHICLE_SELECTOR_LINKAGE = 'MissionsVehicleSelectorUI'
    VEHICLE_SELECTOR_CAROUSEL_ALIAS = 'VehicleSelectorCarousel'
    VEHICLE_SELECTOR_CAROUSEL_LINKAGE = 'VehicleSelectorCarouselUI'
    MISSION_CARD_RENDERER_LINKAGE = 'MissionCardRendererUI'
    MISSION_PACK_MARATHON_HEADER_LINKAGE = 'MissionPackMarathonHeaderUI'
    MISSION_PACK_MARATHON_BODY_LINKAGE = 'MissionPackMarathonBodyUI'
    MISSION_PACK_CATEGORY_HEADER_LINKAGE = 'MissionPackCategoryHeaderUI'
    MISSION_PACK_CURRENT_VEHICLE_HEADER_LINKAGE = 'MissionPackCurrentVehicleHeaderUI'
    MISSIONS_EVENT_BOARDS_CARD_RENDERER_LINKAGE = 'MissionsEventBoardsCardRendererUI'
    MISSIONS_LINKED_SET_CARD_RENDERER_LINKAGE = 'MissionsLinkedSetCardRendererUI'
    MISSIONS_EVENT_BOARDS_HEADER_LINKAGE = 'MissionsEventBoardsHeaderUI'
    MISSIONS_EVENT_BOARDS_BODY_LINKAGE = 'MissionsEventBoardsBodyUI'
    MISSIONS_LINKED_SET_HEADER_LINKAGE = 'MissionsLinkedSetHeaderUI'
    MISSIONS_LINKED_SET_BODY_LINKAGE = 'MissionsLinkedSetBodyUI'
    MISSIONS_PREMIUM_HEADER_LINKAGE = 'MissionsPremiumHeaderUI'
    MISSIONS_PREMIUM_BODY_LINKAGE = 'MissionsPremiumBodyUI'
    MISSIONS_VIEW_PY_ALIASES = [MISSIONS_MARATHON_VIEW_PY_ALIAS,
     MISSIONS_GROUPED_VIEW_PY_ALIAS,
     MISSIONS_EVENT_BOARDS_VIEW_PY_ALIAS,
     MISSIONS_CATEGORIES_VIEW_PY_ALIAS,
     CURRENT_VEHICLE_MISSIONS_VIEW_PY_ALIAS]
