# Embedded file name: scripts/client/gui/Scaleform/genConsts/QUEST_TASKS_STATES.py


class QUEST_TASKS_STATES(object):
    UNAVAILABLE = 1
    AVAILABLE = 2
    IN_PROGRESS = 3
    COMPLETED_BASIC = 4
    COMPLETED_BASIC_AWARD_RECEIVED = 5
    IN_PROGRESS_REPEATED = 6
    COMPLETED_FULL_BASIC_AWARD_RECEIVED = 7
    COMPLETED_FULL = 8
    COMPLETED_FULL_ALL_AWARDS_RECEIVED = 9
