# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/client/gui/Scaleform/genConsts/RANKEDBATTLES_ALIASES.py
"""
This file was generated using the wgpygen.
Please, don't edit this file manually.
"""

class RANKEDBATTLES_ALIASES(object):
    RANKED_BATTLES_VIEW_ALIAS = 'rankedBattlesViewAlias'
    RANKED_BATTLES_WELCOME_VIEW_ALIAS = 'rankedBattlesWelcomeView'
    RANKED_BATTLES_UNREACHABLE_VIEW_ALIAS = 'rankedBattlesUnreachableView'
    RANKED_BATTLES_CYCLES_VIEW_ALIAS = 'rankedBattlesCyclesView'
    RANKED_BATTLES_CALENDAR_POPOVER = 'rankedBattlesCalendarPopoverAlias'
    RANKED_BATTLES_BATTLE_RESULTS = 'rankedBattlesBattleResults'
    RANKED_BATTLES_AWARD = 'rankedBattlesAwardView'
    RANKED_BATTLES_SEASON_COMPLETE = 'rankedBattlesSeasonCompleteView'
    RANKED_BATTLES_STAGE_COMPLETE = 'rankedBattlesStageCompleteView'
    RANKED_BATTLES_BROWSER_VIEW = 'rankedBattlesBrowserView'
    RANKED_BATTLE_RESULTS_WIDGET = 'battleResWidget'
    RANKED_BATTLE_RESULTS_FINAL_WIDGET = 'battleResFinalWidget'
    RANKED_BATTLE_PRIME_TIME = 'rankedBattlesPrimeTime'
    RANKED_AWARD_RENDERER_ALIAS = 'AwardItemRendererExUI'
    SOUND_WIDGET_FLICKER = 'gui_rb_rank_flicker'
    SOUND_WIDGET_CENTER_LEFT_RECEIVE = 'gui_rb_rank_back'
    SOUND_WIDGET_CENTER_LEFT_LOST = 'gui_rb_rank_back2'
    RANKED_BATTLES_VIEW_UI = 'rankedBattlesView.swf'
    RANKED_BATTLES_WELCOME_VIEW_UI = 'rankedBattlesWelcomeView.swf'
    RANKED_BATTLES_UNREACHABLE_VIEW_UI = 'rankedBattlesUnreachableView.swf'
    RANKED_BATTLES_CYCLES_VIEW_UI = 'rankedBattlesCyclesView.swf'
    RANKED_BATTLES_CALENDAR_POPOVER_UI = 'rankedBattlesCalendarPopover.swf'
    RANKED_BATTLES_BATTLE_RESULTS_UI = 'rankedBattlesBattleResults.swf'
    RANKED_BATTLES_AWARD_UI = 'rankedBattlesAwardView.swf'
    RANKED_BATTLES_SEASON_COMPLETE_UI = 'rankedBattlesSeasonCompleteView.swf'
    RANKED_BATTLES_STAGE_COMPLETE_UI = 'rankedBattlesStageCompleteView.swf'
    RANKED_BATTLES_BROWSER_VIEW_UI = 'rankedBattlesBrowserView.swf'
    RANKED_BATTLE_PRIME_TIME_UI = 'rankedBattlesPrimeTime.swf'
    STEP_RECEIVED_STATE = 'received'
    STEP_NOT_RECEIVED_STATE = 'not_received'
    STEP_JUST_RECEIVED_STATE = 'just_received'
    STEP_JUST_RECEIVED_SHORT_STATE = 'just_received_short'
    STEP_JUST_LOST_STATE = 'just_lost'
    RANK_IDLE_STATE = 'rank_idle'
    RANK_INIT_STATE = 'rank_init'
    FIRST_RANK_RECEIVE_STATE = 'first_rank_receive'
    NEW_RANK_CONGRAT_STATE = 'new_rank_congrat'
    RANK_RECEIVE_FOR_FIRST_TIME_STATE = 'rank_receive_for_first_time'
    RANK_RECEIVE_STATE = 'rank_receive'
    RANK_LOST_STATE = 'rank_lost'
    RANK_RECEIVE_HUGE_STATE = 'rank_receive_huge'
    RANK_LOST_HUGE_STATE = 'rank_lost_huge'
    BLINK_BACKGROUND_SHOW = 'show'
    WIDGET_SMALL = 'small'
    WIDGET_MEDIUM = 'medium'
    WIDGET_BIG = 'big'
    WIDGET_HUGE = 'huge'
    PAST_MISSED = 'past_missed'
    PAST_COMPLETED = 'past_completed'
    CURRENT = 'current'
    FUTURE = 'future'
    FINAL = 'final'
    BATTLE_RESULTS_SUB_TASK_UI = 'RankedBattleSubTaskUI'
    BACKGROUND_STATE_TOP = 'top'
    BACKGROUND_STATE_LOSE = 'lose'
    BACKGROUND_STATE_NOTEFFECTIVE = 'notEffective'
    BACKGROUNDS = [BACKGROUND_STATE_TOP, BACKGROUND_STATE_LOSE, BACKGROUND_STATE_NOTEFFECTIVE]
    GUI_RB_INPUT_ANIMATION_01 = 'gui_rb_input_animation_01'
    GUI_RB_INPUT_ANIMATION_02 = 'gui_rb_input_animation_02'
    GUI_RB_INPUT_ANIMATION_03 = 'gui_rb_input_animation_03'
    GUI_RB_INPUT_RANK = 'gui_rb_input_rank'
    GUI_RB_INPUT_RANK_MAX = 'gui_rb_input_rank_max'
    GUI_RB_INPUT_RANK_BACK = 'gui_rb_input_rank_back'
    GUI_RB_INPUT_RANK_UNITY = 'gui_rb_input_rank_unity'
    GUI_RB_INPUT_RULE = 'gui_rb_input_rule'
    SOUND_INFO_ANIMATION_START = 'sound_info_animation_start'
    SOUND_BOX_ANIMATION_START = 'sound_box_animation_start'
    SOUND_AWARD_ANIMATION_START = 'sound_award_animation_start'
    SOUND_BTN_ANIMATION_START = 'sound_btn_animation_start'
    SUBTASK_STATE_STAGE = 'stage'
    SUBTASK_STATE_RANK = 'rank'
    SUBTASK_STATE_MASTER = 'master'
