# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/client/gui/Scaleform/genConsts/RANKEDBATTLES_CONSTS.py


class RANKEDBATTLES_CONSTS(object):
    RANKED_BATTLES_RANKS_ID = 'rankedBattlesRanks'
    RANKED_BATTLES_REWARDS_ID = 'rankedBattlesRewards'
    RANKED_BATTLES_RATING_ID = 'rankedBattlesRating'
    RANKED_BATTLES_INFO_ID = 'rankedBattlesInfo'
    RANKED_BATTLES_REWARDS_RANKEDS_ID = 'rankedBattlesRewardsRankeds'
    RANKED_BATTLES_REWARDS_LEAGUES_ID = 'rankedBattlesRewardsLeagues'
    RANKED_BATTLES_REWARDS_YEAR_ID = 'rankedBattlesRewardsYear'
    RANKED_REWARDS_RANK_RECEIVED = 'received'
    RANKED_REWARDS_RANK_CURRENT = 'current'
    RANKED_REWARDS_RANK_NEXT = 'next'
    RANKED_REWARDS_RANK_LOCKED = 'locked'
    RANKED_REWARDS_REWARD_SIZE_SMALL = 'small'
    RANKED_REWARDS_REWARD_SIZE_BIG = 'big'
    RANKED_REWARDS_REWARDS_COUNT_4 = 4
    RANKED_REWARDS_REWARDS_COUNT_5 = 5
    RANKED_REWARDS_REWARDS_COUNT_7 = 7
    STATUS_ID_DONE = 'done'
    STATUS_ID_LOCK = 'lock'
    STATUS_ID_CURRENT = 'current'
    RANKED_REWARDS_YEAR_SMALL = 'small'
    RANKED_REWARDS_YEAR_MEDIUM = 'medium'
    RANKED_REWARDS_YEAR_BIG = 'big'
    RANKED_REWARDS_YEAR_LARGE = 'large'
    RANKED_REWARDS_YEAR_MAIN_AVAILABLE_FOR = [RANKED_REWARDS_YEAR_BIG, RANKED_REWARDS_YEAR_LARGE]
    YEAR_REWARD_STATUS_PASSED = 'passed'
    YEAR_REWARD_STATUS_LOCKED = 'locked'
    YEAR_REWARD_STATUS_CURRENT = 'current'
    YEAR_REWARD_STATUS_PASSED_FINAL = 'passedFinal'
    YEAR_REWARD_STATUS_LOCKED_FINAL = 'lockedFinal'
    YEAR_REWARD_STATUS_CURRENT_FINAL = 'currentFinal'
    WIDGET_MEDIUM_WIDTH = 340
    WIDGET_SMALL_WIDTH = 290
