# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/client/gui/Scaleform/genConsts/STORE_CONSTANTS.py


class STORE_CONSTANTS(object):
    """
    DO NOT MODIFY!
    Generated with yaml.
    __author__ = 'yaml_processor'
    """
    SHOP = 'shop'
    INVENTORY = 'inventory'
    SHOP_LINKAGE = 'ShopUI'
    INVENTORY_LINKAGE = 'InventoryUI'
    STORE = 'store'
    SHELL = 'shell'
    MODULE = 'module'
    VEHICLE = 'vehicle'
    OPTIONAL_DEVICE = 'optionalDevice'
    EQUIPMENT = 'equipment'
    RESTORE_VEHICLE = 'restoreVehicle'
    VEHICLES_FILTERS_VO_CLASS = 'net.wg.gui.lobby.store.views.data.VehiclesFiltersVO'
    SHOP_VEHICLES_FILTERS_VO_CLASS = 'net.wg.gui.lobby.store.views.data.ShopVehiclesFiltersVO'
    FIT_ITEMS_FILTERS_VO_CLASS = 'net.wg.gui.lobby.store.views.data.FitItemsFiltersVO'
    EXT_FIT_ITEMS_FILTERS_VO_CLASS = 'net.wg.gui.lobby.store.views.data.ExtFitItemsFiltersVO'
    BUY_VEHICLE_OBTAINING_TYPE = 'buyingVehicle'
    RESTORE_VEHICLE_OBTAINING_TYPE = 'restoreVehicle'
    VEHICLE_OBTAINING_TYPES = [BUY_VEHICLE_OBTAINING_TYPE, RESTORE_VEHICLE_OBTAINING_TYPE]
    LOCKED_EXTRA_NAME = 'locked'
    IN_HANGAR_EXTRA_NAME = 'inHangar'
    RENTALS_EXTRA_NAME = 'rentals'
    BROCKEN_EXTRA_NAME = 'brocken'
    PREMIUM_IGR_EXTRA_NAME = 'premiumIGR'
    ON_VEHICLE_EXTRA_NAME = 'onVehicle'
    GUN_MODULE_NAME = 'vehicleGun'
    TURRET_MODULE_NAME = 'vehicleTurret'
    ENGINE_MODULE_NAME = 'vehicleEngine'
    CHASSIS_MODULE_NAME = 'vehicleChassis'
    RADIO_MODULE_NAME = 'vehicleRadio'
    ARMOR_PIERCING_SHELL = 'ARMOR_PIERCING'
    ARMOR_PIERCING_CR_SHELL = 'ARMOR_PIERCING_CR'
    HOLLOW_CHARGE_SHELL = 'HOLLOW_CHARGE'
    HIGH_EXPLOSIVE_SHELL = 'HIGH_EXPLOSIVE'
    CURRENT_VEHICLE_ARTEFACT_FIT = 'myVehicle'
    MY_VEHICLES_ARTEFACT_FIT = 'myVehicles'
    OTHER_VEHICLES_ARTEFACT_FIT = 'otherVehicles'
    CURRENT_VEHICLE_SHELL_FIT = 'myVehicleGun'
    INVENTORY_VEHICLE_SHELL_FIT = 'myInventoryGuns'
    MY_VEHICLES_SHELL_FIT = 'myVehiclesInventoryGuns'
    OTHER_VEHICLES_SHELL_FIT = 'otherGuns'
    LIGHT_TANK_FILTER_NAME = 'lightTank'
    MEDIUM_TANK_FILTER_NAME = 'mediumTank'
    HEAVY_TANK_FILTER_NAME = 'heavyTank'
    AT_SPG_FILTER_NAME = 'at-spg'
    SPG_FILTER_NAME = 'spg'
    ALL_FILTER_NAME = 'all'
