# Embedded file name: scripts/client/gui/Scaleform/genConsts/TEXT_MANAGER_STYLES.py


class TEXT_MANAGER_STYLES(object):
    PROMO_TITLE = 'promoTitle'
    PROMO_SUB_TITLE = 'promoSubTitle'
    HIGH_TITLE = 'highTitle'
    MIDDLE_TITLE = 'middleTitle'
    STATUS_CRITICAL_TEXT = 'statusCriticalText'
    STATUS_WARNING_TEXT = 'statusWarningText'
    STATUS_INFO_TEXT = 'statusInfoText'
    MAIN_TEXT = 'mainText'
    STANDARD_TEXT = 'standardText'
    DISABLED_TEXT = 'disabledText'
    SUCCESS_TEXT = 'successText'
    ALERT_TEXT = 'alertText'
    ERROR_TEXT = 'errorText'
    NEUTRAL_TEXT = 'neutralText'
    DEFRES_TEXT = 'defresText'
    GOLD_TEXT = 'goldText'
    GOLD_TEXT_BIG = 'goldTextBig'
    CREDITS_TEXT = 'creditsText'
    CREDITS_TEXT_BIG = 'creditsTextBig'
    EXP_TEXT = 'expText'
    ERR_CURRENCY_TEXT_BIG = 'errCurrencyTextBig'
    STATS_TEXT = 'statsText'
    PLAYER_ONLINE = 'playerOnline'
    PLAYER_OFFLINE = 'playerOffline'
    COUNTER_TEXT = 'counterText'
    TUTORIAL_TEXT = 'tutorialText'
