# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/client/gui/Scaleform/genConsts/TOOLTIPS_CONSTANTS.py


class TOOLTIPS_CONSTANTS(object):
    DEFAULT = 'default'
    TANKMAN = 'tankman'
    TANKMAN_NOT_RECRUITED = 'tankmanNotRecruited'
    BATTLE_ROYALE_TANKMAN = 'battleRoyaleTankman'
    CONTACT = 'contact'
    BATTLE_STATS_ACHIEVS = 'battleStatsAchievementData'
    ACHIEVEMENT = 'achievement'
    ACHIEVEMENT_ATTR = 'achievementAttr'
    GLOBAL_RATING = 'globalRating'
    MARK_OF_MASTERY = 'markOfMastery'
    MARKS_ON_GUN_ACHIEVEMENT = 'marksOnGun'
    BATTLE_STATS_MARKS_ON_GUN_ACHIEVEMENT = 'battleStatsMarksOnGun'
    CAROUSEL_VEHICLE = 'carouselVehicle'
    INVENTORY_VEHICLE = 'inventoryVehicle'
    TECHTREE_VEHICLE = 'techtreeVehicle'
    TECHTREE_VEHICLE_ANNOUNCEMENT = 'techtreeVehicleAnnouncement'
    TECHTREE_VEHICLE_STATUS = 'techtreeVehicleStatus'
    HISTORICAL_VEHICLE = 'historicalVehicle'
    INVENTORY_SHELL = 'inventoryShell'
    INVENTORY_MODULE = 'inventoryModule'
    INVENTORY_BATTLE_BOOSTER = 'inventoryBattleBooster'
    TECH_MAIN_MODULE = 'techMainModule'
    TECHTREE_MODULE = 'techtreeModule'
    TECHTREE_DISCOUNT_INFO = 'techtreeDiscount'
    TECHTREE_NATION_DISCOUNT = 'techtreeNationDiscount'
    VEH_COMPARE_TECHTREE_MODULE = 'vehCompareTechtreeModule'
    TECH_MAIN_SHELL = 'techMainShell'
    HANGAR_MODULE = 'hangarModule'
    HANGAR_CARD_MODULE = 'hangarCardModule'
    HANGAR_SLOT_MODULE = 'hangarSlotModule'
    OPT_DEVICE_EMPTY_SLOT = 'optDeviceEmptySlot'
    AMMUNITION_EMPTY_SLOT = 'ammunitionEmptySlot'
    CREW_SKIN = 'crewSkin'
    CREW_SKIN_NO_AVAILABLE_SKINS = 'crewSkinNoAvailableSkins'
    CREW_SKIN_RESTRICTED = 'crewSkinRestricted'
    CREW_SKIN_SOUND = 'crewSkinSound'
    CREW_BOOK = 'crewBook'
    CREW_BOOK_RESTRICTED = 'crewBookRestricted'
    VEHICLE_COLLECTOR_INFO = 'vehicleCollectorInfo'
    VEHICLE_COLLECTOR_DISABLED = 'vehicleCollectorDisabled'
    NATION_CHANGE_HANGAR_MODULE = 'nationChangeHangarModule'
    COMPARE_MODULE = 'compareModule'
    COMPARE_SLOT_MODULE = 'compareSlotModule'
    DIRECT_MODULE = 'directModule'
    RESERVE_MODULE = 'reserveModule'
    PREVIEW_MODULE = 'previewModule'
    PERSONAL_MISSION_INFO = 'personalMissionInfo'
    BATTLE_BOOSTER_BLOCK = 'battleBoosterBlock'
    NATION_CHANGE_BATTLE_BOOSTER = 'nationChangeBattleBooster'
    BATTLE_BOOSTER_COMPARE = 'battleBoosterCompare'
    SHOP_VEHICLE = 'shopVehicle'
    AWARD_VEHICLE = 'awardVehicle'
    DEFAULT_SHELL = 'defaultShell'
    HANGAR_SHELL = 'hangarShell'
    NATION_CHANGE_HANGAR_SHELL = 'nationChangeHangarShell'
    COMPARE_SHELL = 'compareShell'
    AWARD_SHELL = 'awardShell'
    DEFAULT_MODULE = 'defaultModule'
    DEFAULT_BATTLE_BOOSTER = 'defaultBattleBooster'
    AWARD_MODULE = 'awardModule'
    AWARD_BATTLE_BOOSTER = 'awardBattleBooster'
    EPIC_AWARD_BATTLE_BOOSTER = 'epicAwardBattleBooster'
    SHOP_MODULE = 'shopModule'
    SHOP_SHELL = 'shopShell'
    SHOP_BOOSTER = 'shopBooster'
    SHOP_BATTLE_BOOSTER = 'shopBattleBooster'
    SHOP_CUSTOMIZATION_ITEM = 'shopCustomizationItem'
    SHOP_ACHIEVEMENT = 'shopAchievement'
    SHOP_BADGE = 'shopBadge'
    SHOP_CREW_BUNDLE = 'shopCrewBundle'
    AWARD_DEMOUNT_KIT = 'awardDemountKit'
    NOT_ENOUGH_MONEY = 'notEnoughMoney'
    TANKMAN_SKILL = 'tankmanSkill'
    TANKMAN_NEW_SKILL = 'tankmanNewSkill'
    PREVIEW_CREW_SKILL = 'previewCrewSkill'
    EFFICIENCY_PARAM = 'efficiencyParam'
    MAP = 'map'
    SETTINGS_CONTROL = 'control'
    SETTINGS_BUTTON = 'settingsButton'
    TECH_CUSTOMIZATION_ITEM = 'techCustomizationItem'
    TECH_CUSTOMIZATION_ITEM_ICON = 'techCustomizationItemIcon'
    TECH_CUSTOMIZATION_ITEM_AWARD = 'techCustomizationItemAward'
    TECH_CUSTOMIZATION_ITEM_PURCHASE = 'techCustomizationItemPurchase'
    TECH_CUSTOMIZATION_NONHISTORIC_ITEM = 'techCustomizationNonhistoricItem'
    TECH_CUSTOMIZATION_POPOVER_ITEM = 'techCustomizationPopoverItem'
    VEHICLE_FILTER = 'vehicleFilter'
    LADDER = 'ladder'
    CLAN_INFO = 'clanInfo'
    CLAN_COMMON_INFO = 'clanCommonInfo'
    FORT_WRONG_TIME = 'fortWrongTime'
    FORT_DIVISION = 'fortDivision'
    FORT_CONSUMABLE_ORDER = 'fortConsumableOrder'
    BATTLE_CONSUMABLE = 'battleConsumable'
    BATTLE_OPT_DEVICE = 'battleOptDevice'
    IGR_INFO = 'igrInfo'
    CYBER_SPORT_SLOT = 'cyberSportSlot'
    CYBER_SPORT_SELECTED_VEHICLE = 'cyberSportSelectedVehicle'
    CYBER_SPORT_SLOT_SELECTED = 'cyberSportSlotSelected'
    CYBER_SPORT_TEAM = 'cyberSportTeam'
    CYBER_SPORT_UNIT_LEVEL = 'cyberSportUnitLevel'
    CYBER_SPORT_VEHICLE_NOT_READY = 'cyberSportVehicleNotReady'
    SQUAD_SLOT_VEHICLE_SELECTED = 'squadSlotVehicleSelected'
    SORTIE_DIVISION = 'sortieDivision'
    MARATHON_QUESTS_PREVIEW = 'marathonQuestsPreview'
    QUESTS_PREVIEW = 'questsPreview'
    EPIC_QUESTS_PREVIEW = 'epicQuestsPreview'
    EVENT_QUESTS_PREVIEW = 'EventQuestsPreview'
    PERSONAL_QUESTS_PREVIEW = 'presonalQuestsPreview'
    SHEDULE_QUEST = 'scheduleQuest'
    MISSION_VEHICLE = 'missionVehicle'
    MISSION_VEHICLE_TYPE = 'missionVehicleType'
    ADDITIONAL_AWARDS = 'additionalAwards'
    PACK_RENT_VEHICLES = 'packRentVehicles'
    UNAVAILABLE_QUEST = 'unavailibleQuest'
    ACTION_PRICE = 'actionPrice'
    ACTION_SLOT_PRICE = 'actionSlotPrice'
    PRICE_DISCOUNT = 'priceDiscount'
    FRONTLINE_PRICE_DISCOUNT = 'frontlinePriceDiscount'
    FRONTLINE_COUPON = 'frontlineCoupon'
    FRONTLINE_RANK = 'frontlineRank'
    ACTION_XP = 'actionXP'
    SPECIAL = 'special'
    SIMPLE = 'simple'
    COMPLEX = 'complex'
    PRIVATE_QUESTS_TILE = 'privateQuestsTile'
    PRIVATE_QUESTS_FALLOUT_TILE = 'privateQuestsFalloutTile'
    PRIVATE_QUESTS_CHAIN = 'privateQuestsChain'
    QUESTS_VEHICLE_BONUSES = 'questVehiclesBonus'
    MAP_SMALL = 'mapSmall'
    FORT_SORTIE_SLOT = 'fortSortieSlot'
    FORT_SORTIE = 'fortSortie'
    FORT_SORTIE_TIME_LIMIT = 'fortSortieTimeLimit'
    FORT_POPOVER_DEFRESPROGRESS = 'fortPopoverDefResProgress'
    FORT_SORTIE_SERVER_LIMIT = 'fortSortieServerLimit'
    CLAN_PROFILE_FORT_BUILDING = 'clanProfileFortBuilding'
    HANGAR_TUTORIAL_CUSTOMIZATION_TYPES = 'hangarTutorialCustomizationTypes'
    HANGAR_TUTORIAL_PERSONAL_CASE_SKILLS = 'hangarTutorialPersonalCaseSkills'
    HANGAR_TUTORIAL_PERSONAL_CASE_PERKS = 'hangarTutorialPersonalCasePerks'
    HANGAR_TUTORIAL_PERSONAL_CASE_ADDITIONAL = 'hangarTutorialPersonalCaseAdditional'
    HANGAR_TUTORIAL_AMMUNITION = 'hangarTutorialAmmunition'
    HANGAR_TUTORIAL_EQUPMENT = 'hangarTutorialEquipment'
    ENVIRONMENT = 'environment'
    CLAN_PROFILE_REQUEST_ACCPETED = 'clanProfileRequestAccepted'
    CLAN_PROFILE_REQUEST_DECLINED = 'clanProfileRequestDeclined'
    CLAN_PROFILE_REQUEST_EXPIRED = 'clanProfileRequestExpired'
    LADDER_REGULATIONS = 'ladderRegulations'
    PRIVATE_QUESTS_FEMALE_TANKMAN_AWARD = 'femaleTankmanPersonalQuestAward'
    PRIVATE_QUESTS_TOKENS_AWARD = 'tokensPersonalQuestAward'
    BOOSTERS_BOOSTER_INFO = 'boostersBoosterInfo'
    CLAN_RESERVE_INFO = 'clanReserveInfo'
    BOOSTERS_QUESTS = 'boostersQuests'
    BOOSTER = 'booster'
    VEHICLE_SIMPLE_PARAMETERS = 'vehicleSimpleParameters'
    VEHICLE_ADVANCED_PARAMETERS = 'vehicleAdvancedParameters'
    VEHICLE_AVG_PARAMETERS = 'vehicleAvgParameters'
    VEHICLE_PREVIEW_SIMPLE_PARAMETERS = 'vehiclePreviewSimpleParameters'
    VEHICLE_PREVIEW_ADVANCED_PARAMETERS = 'vehiclePreviewAdvancedParameters'
    VEHICLE_PREVIEW_AVG_PARAMETERS = 'vehiclePreviewAvgParameters'
    VEHICLE_CMP_PARAMETERS = 'vehicleCmpParameters'
    VEHICLE_TANK_SETUP_PARAMETERS = 'vehicleTankSetupParameters'
    BASE_VEHICLE_PARAMETERS = 'baseVehicleParameters'
    DEFAULT_CREW_MEMBER = 'defaultCrewMember'
    VEHICLE_PREVIEW_CREW_MEMBER = 'vehiclePreviewCrewMember'
    TRADE_IN = 'tradeIn'
    TRADE_IN_INFO = 'tradeInInfo'
    TRADE_IN_INFO_NOT_AVAILABLE = 'tradeInInfoNotAvailable'
    TRADE_IN_STATE_NOT_AVAILABLE = 'tradeInStateNotAvailable'
    TRADE_IN_PRICE = 'ToolTipTradeInPriceUI'
    SELECTED_VEHICLE_TRADEOFF = 'selectedVehicleTradeOff'
    FREE_SHEET = 'freeSheet'
    FREE_SHEET_RETURN = 'freeSheetReturn'
    FREE_SHEET_NOT_ENOUGH = 'freeSheetNotEnough'
    FREE_SHEET_USED = 'freeSheetUsed'
    BADGE = 'badge'
    REFERRAL_BADGE = 'referralBadge'
    BADGE_LOYAL_SERVICE = 'badgeLoyalService'
    EVENT_BOARDS_BADGE = 'eventBoardsBadge'
    EVENT_BOARDS_BADGES_GROUP = 'eventBoardsBadgesGroup'
    OPERATION = 'operation'
    OPERATIONS_CHAIN_DETAILS = 'operationsChainDetails'
    PERSONAL_MISSIONS_MAP_REGION = 'personalMissionsMapRegion'
    BATTLE_TRAINING = 'battleTraining'
    OPERATION_POSTPONED = 'operationPostponed'
    SQUAD_BONUS = 'squadBonus'
    GF_TEST_TOOLTIP = 'gfTestTooltip'
    BATTLE_PASS_VEHICLE_POINTS = 'battlePassVehiclePoints'
    BATTLE_PASS_POINTS = 'battlePassPoints'
    BATTLE_PASS_NOT_STARTED = 'battlePassNotStarted'
    BATTLE_PASS_IN_PROGRESS = 'battlePassInProgress'
    BATTLE_PASS_COMPLETED = 'battlePassCompleted'
    BATTLE_PASS_CHOSE_WINNER = 'battlePassChoseWinner'
    SINGAPORE_WALLET_STATS = 'Stats'
    GOLD_STATS = 'goldStats'
    CREDITS_STATS = 'creditsStats'
    CRYSTAL_INFO = 'crystalInfo'
    CREDITS_INFO = 'creditsInfo'
    GOLD_INFO = 'goldInfo'
    GOLD_ALTERNATIVE_INFO = 'goldAlternativeInfo'
    GOLD_ALTERNATIVE_STATS = 'goldAlternativeStats'
    EVENT_COIN_INFO = 'eventCoinInfo'
    FREEXP_INFO = 'freeXPInfo'
    HEADER_BUTTON_INFO = 'Info'
    RANKED_BATTLES_RANK = 'rankedBattlesRank'
    RANKED_BATTLES_BONUS = 'rankedBattlesBonus'
    RANKED_BATTLES_LEAGUE = 'rankedBattlesLeague'
    RANKED_BATTLES_EFFICIENCY = 'rankedBattlesEfficiency'
    RANKED_BATTLES_POSITION = 'rankedBattlesPosition'
    RANKED_STEP = 'rankedStep'
    RANKED_CALENDAR_DAY_INFO = 'rankedCalendarDayInfo'
    RANKED_SELECTOR_INFO = 'rankedSelectorInfo'
    RANKED_UNAVAILABLE_INFO = 'rankedUnavailableInfo'
    RANKED_CALENDAR_STEPS_INFO = 'rankedCalendarStepsInfo'
    RANKED_DIVISION_INFO = 'rankedDivisionInfo'
    RANKED_BATTLES_YEAR_REWARD = 'rankedBattlesYearReward'
    RANKED_SERVER_PRIMETIME = 'rankedServerPrimeTime'
    RANKED_BATTLES_ROLES = 'rankedBattlesRoles'
    RANKED_QUESTS_PREVIEW = 'rankedQuestsPreview'
    EPIC_SKILL_INFO = 'epicSkillInfo'
    EPIC_SKILL_SLOT_INFO = 'epicSkillSlotInfo'
    EVENT_PROGRESSION_PROGRESS_INFO = 'eventProgressionProgressInfo'
    EVENT_PROGRESSION_SELECTOR_INFO = 'eventProgressionSelectorInfo'
    EPIC_PRESTIGE_PROGRESS_BLOCK_INFO = 'epicPrestigeProgressBlockInfo'
    BATTLE_ROYALE_WEAK_ZONES = 'BattleRoyaleWeakZonesBlockUI'
    BATTLE_ROYALE_MODULES = 'battleRoyaleModules'
    BATTLE_ROYALE_MODULES_HANGAR = 'battleRoyaleModulesHangar'
    BATTLE_ROYALE_BATTLE_PROGRESSION = 'battleRoyaleBattleProgression'
    BATTLE_ROYALE_EQUIPMENT = 'battleRoyaleEquipment'
    BATTLE_ROYALE_VEHICLE = 'battleRoyaleVehicle'
    BATTLE_ROYALE_PERF_SIMPLE = 'battleRoyalePerfSimple'
    BATTLE_ROYALE_PERF_ADVANCED = 'battleRoyalePerfAdvanced'
    BATTLE_ROYALE_SELECTOR_INFO = 'battleRoyaleSelectorInfo'
    BLUEPRINT_INFO = 'blueprintInfo'
    BLUEPRINT_CONVERT_INFO = 'blueprintConvertInfo'
    BLUEPRINT_FRAGMENT_INFO = 'blueprintFragmentInfo'
    BLUEPRINT_EMPTY_SLOT_INFO = 'blueprintEmptySlotInfo'
    BLUEPRINT_RANDOM_INFO = 'blueprintRandomInfo'
    BLOCKS_DEFAULT_UI = 'ToolTipInblocksDefaultUI'
    TANKMEN_UI = 'ToolTipTankmenUI'
    TANKMEN_SKILL_UI = 'ToolTipSkillUI'
    TANKMEN_BUY_SKILL_UI = 'ToolTipBuySkillUI'
    ACHIEVEMENT_UI = 'ToolTipAchievementUI'
    MARKS_ON_GUN_UI = 'ToolTipMarksOnGunUI'
    MARK_OF_MASTERY_UI = 'ToolTipMarkOfMasteryUI'
    VEHICLE_INFO_UI = 'ToolTipInblocksDefaultUI'
    EQUIPMENT_UI = 'ToolTipEquipmentUI'
    INBLOCKS_DEFAULT_UI = 'ToolTipInblocksDefaultUI'
    FINAL_STSTS_UI = 'ToolTipInblocksDefaultUI'
    IGR_INFO_UI = 'ToolTipIGRUI'
    SUITABLE_VEHICLE_UI = 'ToolTipSuitableVehicleUI'
    SELECTED_VEHICLE_UI = 'ToolTipSelectedVehicleUI'
    UNIT_COMMAND = 'ToolTipUnitCommandUI'
    CONTACT_UI = 'TooltipContactUI'
    UNIT_LEVEL_UI = 'ToolTipUnitLevelUI'
    SORTIE_DIVISION_UI = 'ToolTipSortieDivisionUI'
    MAP_UI = 'ToolTipMapUI'
    COMPLEX_UI = 'ToolTipComplexUI'
    REF_SYS_DIRECTS_UI = 'ToolTipRefSysDirectsUI'
    REF_SYS_RESERVES_UI = 'ToolTipRefSysReservesUI'
    CLAN_INFO_UI = 'ToolTipClanInfoUI'
    SETTINGS_BUTTON_UI = 'ToolTipInblocksDefaultUI'
    CUSTOMIZATION_ITEM_UI = 'ToolTipCustomizationItemUI'
    TECH_CUSTOMIZATION_ITEM_UI = 'ToolTipInblocksDefaultUI'
    PRIVATE_QUESTS_UI = 'ToolTipPrivateQuestsUI'
    COLUMN_FIELDS_UI = 'ToolTipColumnFieldsUI'
    MAP_SMALL_UI = 'ToolTipMapSmallUI'
    LADDER_UI = 'ToolTipLadderUI'
    FORT_DIVISION_UI = 'ToolTipFortDivisionUI'
    FORT_SORTIE_UI = 'ToolTipFortSortieUI'
    FORT_SORTIE_TIME_LIMIT_UI = 'ToolTipInblocksDefaultUI'
    FORT_SORTIE_SERVER_LIMIT_UI = 'ToolTipInblocksDefaultUI'
    FORT_POPOVER_DEFRESPROGRESS_UI = 'ToolTipInblocksDefaultUI'
    CLAN_PROFILE_FORT_BUILDING_UI = 'ToolTipInblocksDefaultUI'
    HANGAR_TUTORIAL_CUSTOMIZATION_TYPES_UI = 'ToolTipInblocksDefaultUI'
    HANGAR_TUTORIAL_PERSONAL_CASE_SKILLS_UI = 'ToolTipInblocksDefaultUI'
    HANGAR_TUTORIAL_PERSONAL_CASE_PERKS_UI = 'ToolTipInblocksDefaultUI'
    HANGAR_TUTORIAL_PERSONAL_CASE_ADDITIONAL_UI = 'ToolTipInblocksDefaultUI'
    HANGAR_TUTORIAL_AMMUNITION_UI = 'ToolTipInblocksDefaultUI'
    HANGAR_TUTORIAL_EQUPMENT_UI = 'ToolTipInblocksDefaultUI'
    ENVIRONMENT_UI = 'TooltipEnvironmentUI'
    LADDER_REGULATIONS_UI = 'ToolTipLadderRegulationsUI'
    CLAN_COMMON_INFO_UI = 'ToolTipClanCommonInfoUI'
    SETTINGS_MINIMAP_CIRCLES = 'SettingsMinimapCircles'
    SETTINGS_MINIMAP_CIRCLES_UI = 'ToolTipInblocksDefaultUI'
    SQUAD_RESTRICTIONS_INFO = 'SquadRestrictionsInfo'
    SQUAD_RESTRICTIONS_INFO_UI = 'ToolTipInblocksDefaultUI'
    BOOSTERS_BOOSTER_INFO_UI = 'ToolTipInblocksDefaultUI'
    VEHICLE_PARAMETERS_UI = 'ToolTipInblocksDefaultUI'
    VEHICLE_PREVIEW_CREW_MEMBER_UI = 'ToolTipInblocksDefaultUI'
    VEH_CMP_CUSTOMIZATION = 'vehCmpCustomiztion'
    VEH_CMP_CUSTOMIZATION_UI = 'ToolTipInblocksDefaultUI'
    SETTINGS_KEY_SWITCH_MODE = 'SettingKeySwitchMode'
    SETTINGS_KEY_SWITCH_MODE_UI = 'ToolTipInblocksDefaultUI'
    SETTINGS_KEY_HIGHLIGHTLOCATION = 'SettingsKeyHighlightLocation'
    SETTINGS_KEY_HIGHLIGHTLOCATION_UI = 'ToolTipInblocksDefaultUI'
    SETTINGS_KEY_HIGHLIGHTTARGET = 'SettingsKeyHighlightTarget'
    SETTINGS_KEY_HIGHLIGHTTARGET_UI = 'ToolTipInblocksDefaultUI'
    SETTINGS_KEY_SHOWRADIALMENU = 'SettingsKeyShowRadialMenu'
    SETTINGS_KEY_SHOWRADIALMENU_UI = 'ToolTipInblocksDefaultUI'
    SETTINGS_KEY_CHARGE_FIRE = 'SettingsKeyChargeFire'
    SETTINGS_KEY_CHARGE_FIRE_UI = 'ToolTipInblocksDefaultUI'
    VEH_CMP_SKILLS = 'vehCmpSkills'
    VEH_CMP_SKILLS_UI = 'ToolTipInblocksDefaultUI'
    TANKMAN_SKILL_EXTENDED = 'tankmanSkillExtended'
    TANKMAN_SKILL_EXTENDED_UI = 'ToolTipInblocksDefaultUI'
    MISSIONS_TOKEN = 'missionsToken'
    MISSIONS_TOKEN_UI = 'ToolTipInblocksDefaultUI'
    BOOTCAMP_AWARD_MEDAL = 'BSTooltipMedalContainer'
    PERSONAL_MISSIONS_TANKWOMAN = 'personalMissionsTankwoman'
    PERSONAL_MISSIONS_TANKMODULE = 'personalMissionsTankmodule'
    VEHICLE_ELITE_BONUS = 'vehicleEliteBonus'
    VEHICLE_HISTORICAL_REFERENCE = 'vehicleHistoricalReference'
    BLUEPRINT_UI = 'ToolTipInblocksDefaultUI'
    BLUEPRINT_FRAGMENT_UI = 'ToolTipInblocksDefaultUI'
    BLUEPRINT_EMPTY_SLOT_UI = 'ToolTipInblocksDefaultUI'
    SESSION_STATS_TANK_INFO = 'sessionStatsTankInfo'
    SESSION_STATS_TANK_INFO_UI = 'ToolTipInblocksDefaultUI'
    SESSION_STATS_EFFICIENCY_PARAM = 'sessionStatsEfficientParam'
    SESSION_STATS_EFFICIENCY_PARAM_UI = 'ToolTipInblocksDefaultUI'
    BADGES_SUFFIX_ITEM = 'badgesSuffixItem'
    BADGES_SUFFIX_RANKED_ITEM = 'badgesSuffixRankedItem'
    BADGES_SUFFIX_ITEM_UI = 'ToolTipInblocksDefaultUI'
    BADGES_SUFFIX_RANKED_ITEM_UI = 'ToolTipInblocksDefaultUI'
    EVENT_PROGRESSION_COMPLETED_QUESTS_INFO = 'EventProgressionQuestsTooltipData'
    BATTLE_OPT_DEVICE_UI = 'ToolTipInblocksDefaultUI'
    ACHIEVEMENTS_SET = [BATTLE_STATS_ACHIEVS,
     BATTLE_STATS_MARKS_ON_GUN_ACHIEVEMENT,
     ACHIEVEMENT,
     MARKS_ON_GUN_ACHIEVEMENT,
     GLOBAL_RATING,
     MARK_OF_MASTERY,
     ACHIEVEMENT_ATTR,
     SHOP_ACHIEVEMENT,
     SHOP_BADGE,
     REFERRAL_BADGE]
    BOOSTERS_SET = [INVENTORY_BATTLE_BOOSTER,
     AWARD_BATTLE_BOOSTER,
     EPIC_AWARD_BATTLE_BOOSTER,
     BATTLE_BOOSTER_BLOCK,
     DEFAULT_BATTLE_BOOSTER,
     SHOP_BATTLE_BOOSTER,
     BATTLE_BOOSTER_COMPARE,
     BOOSTERS_BOOSTER_INFO,
     CLAN_RESERVE_INFO,
     BOOSTER,
     SHOP_BOOSTER,
     BOOSTERS_QUESTS,
     NATION_CHANGE_BATTLE_BOOSTER]
    COMMON_SET = [EFFICIENCY_PARAM,
     IGR_INFO,
     CONTACT,
     SORTIE_DIVISION,
     MAP,
     MAP_SMALL,
     CLAN_COMMON_INFO,
     ACTION_PRICE,
     ACTION_SLOT_PRICE,
     PRICE_DISCOUNT,
     FRONTLINE_PRICE_DISCOUNT,
     ACTION_XP,
     QUESTS_VEHICLE_BONUSES,
     ENVIRONMENT,
     SQUAD_RESTRICTIONS_INFO,
     MISSIONS_TOKEN,
     RESERVE_MODULE,
     CRYSTAL_INFO,
     EVENT_COIN_INFO,
     CREDITS_INFO,
     GOLD_INFO,
     FREEXP_INFO,
     VEHICLE_FILTER,
     VEHICLE_ELITE_BONUS,
     VEHICLE_HISTORICAL_REFERENCE,
     BATTLE_TRAINING,
     SQUAD_BONUS,
     BATTLE_PASS_VEHICLE_POINTS,
     BATTLE_PASS_IN_PROGRESS,
     BATTLE_PASS_COMPLETED,
     BATTLE_PASS_CHOSE_WINNER,
     TECHTREE_DISCOUNT_INFO,
     TECHTREE_NATION_DISCOUNT]
    CUSTOMIZATION_SET = [TECH_CUSTOMIZATION_ITEM,
     TECH_CUSTOMIZATION_NONHISTORIC_ITEM,
     TECH_CUSTOMIZATION_POPOVER_ITEM,
     TECH_CUSTOMIZATION_ITEM_ICON,
     TECH_CUSTOMIZATION_ITEM_AWARD,
     TECH_CUSTOMIZATION_ITEM_PURCHASE,
     SHOP_CUSTOMIZATION_ITEM]
    CYBER_SPORT_SET = [CYBER_SPORT_SLOT,
     CYBER_SPORT_SLOT_SELECTED,
     CYBER_SPORT_SELECTED_VEHICLE,
     SELECTED_VEHICLE_TRADEOFF,
     CYBER_SPORT_TEAM,
     CYBER_SPORT_UNIT_LEVEL,
     CYBER_SPORT_VEHICLE_NOT_READY,
     SQUAD_SLOT_VEHICLE_SELECTED]
    FORT_SORTIE_SET = [DIRECT_MODULE, FORT_SORTIE_SLOT]
    ELEN_SET = [EVENT_QUESTS_PREVIEW, EVENT_BOARDS_BADGE, EVENT_BOARDS_BADGES_GROUP]
    EVENT_PROGRESSION_SET = [EVENT_PROGRESSION_SELECTOR_INFO, EVENT_PROGRESSION_PROGRESS_INFO]
    EPIC_BATTLE_SET = [EPIC_SKILL_INFO,
     EPIC_SKILL_SLOT_INFO,
     EPIC_PRESTIGE_PROGRESS_BLOCK_INFO,
     EPIC_QUESTS_PREVIEW,
     EVENT_PROGRESSION_COMPLETED_QUESTS_INFO]
    PERSONAL_MISSION_SET = [PERSONAL_QUESTS_PREVIEW,
     PERSONAL_MISSIONS_TANKWOMAN,
     PERSONAL_MISSIONS_TANKMODULE,
     FREE_SHEET,
     FREE_SHEET_RETURN,
     FREE_SHEET_NOT_ENOUGH,
     FREE_SHEET_USED,
     BADGE,
     BADGE_LOYAL_SERVICE,
     OPERATION,
     PERSONAL_MISSION_INFO,
     PERSONAL_MISSIONS_MAP_REGION,
     OPERATIONS_CHAIN_DETAILS,
     OPERATION_POSTPONED]
    QUESTS_SET = [QUESTS_PREVIEW,
     SHEDULE_QUEST,
     MISSION_VEHICLE,
     MISSION_VEHICLE_TYPE,
     ADDITIONAL_AWARDS,
     PACK_RENT_VEHICLES,
     UNAVAILABLE_QUEST]
    MARATHON_SET = [MARATHON_QUESTS_PREVIEW]
    TANKMAN_SET = [TANKMAN,
     TANKMAN_SKILL,
     TANKMAN_NEW_SKILL,
     TANKMAN_SKILL_EXTENDED,
     TANKMAN_NOT_RECRUITED,
     PREVIEW_CREW_SKILL,
     BATTLE_ROYALE_TANKMAN]
    RANKED_SET = [RANKED_BATTLES_POSITION,
     RANKED_BATTLES_EFFICIENCY,
     RANKED_BATTLES_LEAGUE,
     RANKED_BATTLES_BONUS,
     RANKED_BATTLES_RANK,
     RANKED_STEP,
     RANKED_CALENDAR_DAY_INFO,
     RANKED_CALENDAR_STEPS_INFO,
     RANKED_SELECTOR_INFO,
     RANKED_UNAVAILABLE_INFO,
     RANKED_DIVISION_INFO,
     RANKED_BATTLES_YEAR_REWARD,
     RANKED_SERVER_PRIMETIME,
     RANKED_BATTLES_ROLES,
     RANKED_QUESTS_PREVIEW]
    SETTINGS_SET = [SETTINGS_CONTROL,
     SETTINGS_BUTTON,
     SETTINGS_MINIMAP_CIRCLES,
     SETTINGS_KEY_SWITCH_MODE,
     SETTINGS_KEY_HIGHLIGHTLOCATION,
     SETTINGS_KEY_HIGHLIGHTTARGET,
     SETTINGS_KEY_SHOWRADIALMENU,
     SETTINGS_KEY_CHARGE_FIRE]
    TUTORIAL_SET = [HANGAR_TUTORIAL_CUSTOMIZATION_TYPES,
     HANGAR_TUTORIAL_PERSONAL_CASE_SKILLS,
     HANGAR_TUTORIAL_PERSONAL_CASE_PERKS,
     HANGAR_TUTORIAL_PERSONAL_CASE_ADDITIONAL,
     HANGAR_TUTORIAL_AMMUNITION,
     HANGAR_TUTORIAL_EQUPMENT]
    VEH_CMP_SET = [VEH_CMP_CUSTOMIZATION, VEH_CMP_SKILLS]
    VEHICLES_SET = [CAROUSEL_VEHICLE,
     INVENTORY_VEHICLE,
     TECHTREE_VEHICLE,
     SHOP_VEHICLE,
     AWARD_VEHICLE,
     TRADE_IN,
     TRADE_IN_PRICE,
     HISTORICAL_VEHICLE,
     VEHICLE_SIMPLE_PARAMETERS,
     BASE_VEHICLE_PARAMETERS,
     VEHICLE_CMP_PARAMETERS,
     VEHICLE_AVG_PARAMETERS,
     VEHICLE_ADVANCED_PARAMETERS,
     VEHICLE_PREVIEW_SIMPLE_PARAMETERS,
     VEHICLE_PREVIEW_AVG_PARAMETERS,
     VEHICLE_PREVIEW_ADVANCED_PARAMETERS,
     DEFAULT_CREW_MEMBER,
     VEHICLE_PREVIEW_CREW_MEMBER,
     TECHTREE_VEHICLE_ANNOUNCEMENT,
     TECHTREE_VEHICLE_STATUS,
     VEHICLE_TANK_SETUP_PARAMETERS]
    BLUEPRINTS_SET = [BLUEPRINT_INFO,
     BLUEPRINT_FRAGMENT_INFO,
     BLUEPRINT_EMPTY_SLOT_INFO,
     BLUEPRINT_CONVERT_INFO,
     BLUEPRINT_RANDOM_INFO]
    VEHICLES_ITEMS_SET = [INVENTORY_MODULE,
     DEFAULT_MODULE,
     SHOP_MODULE,
     TECHTREE_MODULE,
     TECH_MAIN_MODULE,
     HANGAR_MODULE,
     HANGAR_SLOT_MODULE,
     COMPARE_MODULE,
     COMPARE_SLOT_MODULE,
     VEH_COMPARE_TECHTREE_MODULE,
     PREVIEW_MODULE,
     AWARD_MODULE,
     DEFAULT_SHELL,
     SHOP_SHELL,
     AWARD_SHELL,
     HANGAR_SHELL,
     COMPARE_SHELL,
     INVENTORY_SHELL,
     TECH_MAIN_SHELL,
     NATION_CHANGE_HANGAR_SHELL,
     NATION_CHANGE_HANGAR_MODULE,
     OPT_DEVICE_EMPTY_SLOT,
     AMMUNITION_EMPTY_SLOT,
     HANGAR_CARD_MODULE]
    WGM_CURRENCY_SET = [GOLD_STATS, CREDITS_STATS]
    CREW_SKIN_SET = [CREW_SKIN,
     CREW_SKIN_RESTRICTED,
     CREW_SKIN_NO_AVAILABLE_SKINS,
     CREW_SKIN_SOUND]
    CREW_BOOK_SET = [CREW_BOOK, CREW_BOOK_RESTRICTED]
    CREW_BUNDLE_SET = [SHOP_CREW_BUNDLE]
    FRONTLINE_SET = [FRONTLINE_COUPON, FRONTLINE_RANK]
    SESSION_STATS_SET = [SESSION_STATS_TANK_INFO, SESSION_STATS_EFFICIENCY_PARAM]
    TRADE_IN_SET = [TRADE_IN_INFO, TRADE_IN_INFO_NOT_AVAILABLE, TRADE_IN_STATE_NOT_AVAILABLE]
    DEMOUNT_KIT_SET = [AWARD_DEMOUNT_KIT,
     GOLD_ALTERNATIVE_INFO,
     GOLD_ALTERNATIVE_STATS,
     NOT_ENOUGH_MONEY]
    DEVELOPMENT_SET = [GF_TEST_TOOLTIP]
    VEHICLE_COLLECTOR_SET = [VEHICLE_COLLECTOR_INFO, VEHICLE_COLLECTOR_DISABLED]
    BADGES_SET = [BADGES_SUFFIX_ITEM, BADGES_SUFFIX_RANKED_ITEM]
    ROYALE_BATTLE_SET = [BATTLE_ROYALE_WEAK_ZONES, BATTLE_ROYALE_MODULES]
    ROYALE_LOBBY_SET = [BATTLE_ROYALE_VEHICLE,
     BATTLE_ROYALE_MODULES_HANGAR,
     BATTLE_ROYALE_BATTLE_PROGRESSION,
     BATTLE_ROYALE_EQUIPMENT,
     BATTLE_ROYALE_PERF_SIMPLE,
     BATTLE_ROYALE_PERF_ADVANCED,
     BATTLE_ROYALE_SELECTOR_INFO]
    BATTLE_BLOCK_TOOLTIPS = [BATTLE_OPT_DEVICE]
    OPTDEV_SLOT_STATE_EMPTY = 'empty'
    OPTDEV_SLOT_STATE_EMPTY_SELECTED = 'emptySelected'
    OPTDEV_SLOT_STATE_ACTIVE_SELECTED = 'activeSelected'
