# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/client/gui/Scaleform/genConsts/WEEKEND_BRAWL_CONSTS.py


class WEEKEND_BRAWL_CONSTS(object):
    INTEREST_POINT_STATE_NONE = 0
    INTEREST_POINT_STATE_IS_CAPTURING = 1
    INTEREST_POINT_STATE_CAPTURED = 2
    ABILITY_STATE_NONE = 'none'
    ABILITY_STATE_EXTENDED = 'extended'
    ABILITY_STATE_EXTENDED_TIGHT = 'extendedTight'
    ABILITY_STATE_NORMAL = 'normal'
    ABILITY_STATE_COMPACT = 'compact'
    ABILITY_STATE_AVAILABLE = 'available'
    ABILITY_STATE_NOT_AVAILABLE = 'notAvailable'
    ABILITY_CHOICE_PANEL_ALL_STATES = [ABILITY_STATE_NONE,
     ABILITY_STATE_EXTENDED,
     ABILITY_STATE_NORMAL,
     ABILITY_STATE_COMPACT,
     ABILITY_STATE_AVAILABLE,
     ABILITY_STATE_NOT_AVAILABLE]
    ABILITY_CHOICE_PANEL_SIMPLE_STATES = [ABILITY_STATE_AVAILABLE, ABILITY_STATE_NOT_AVAILABLE]
    ABILITY_CARD_ALL_STATES = [ABILITY_STATE_EXTENDED,
     ABILITY_STATE_EXTENDED_TIGHT,
     ABILITY_STATE_NORMAL,
     ABILITY_STATE_COMPACT]
    ABILITY_CARD_TYPE_INSPIRE = 'inspire_weekend_brawl'
    ABILITY_CARD_TYPE_AIRSTRIKE = 'bomber_weekend_brawl'
    ABILITY_CARD_TYPE_RECON = 'recon_weekend_brawl'
    ABILITY_CARD_TYPE_SMOKE = 'smokes_weekend_brawl'
