# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/client/PlayerEvents.py
from __future__ import absolute_import
from events_containers.common.containers import ClientEventsContainer

class _PlayerEvents(ClientEventsContainer):

    def __init__(self):
        super(_PlayerEvents, self).__init__()
        self.onPlayerEntityChanging = self._createEvent()
        self.onPlayerEntityChangeCanceled = self._createEvent()
        self.isPlayerEntityChanging = True
        self.onAvatarObserverVehicleChanged = self._createEvent()
        self.onObservedByEnemy = self._createEvent()
        self.onSightPointerEnemySpotted = self._createEvent()
        self.onAccountBecomePlayer = self._createEvent()
        self.onAccountBecomeNonPlayer = self._createEvent()
        self.onAccountShowGUI = self._createEvent()
        self.onAccountComponentsSynced = self._createEvent()
        self.onClientSynchronize = self._createEvent()
        self.onClientUpdated = self._createEvent()
        self.onEnqueued = self._createEvent()
        self.onDequeued = self._createEvent()
        self.onEnqueueFailure = self._createEvent()
        self.onKickedFromQueue = self._createEvent()
        self.onPrbDispatcherCreated = self._createEvent()
        self.onPrebattleJoined = self._createEvent()
        self.onPrebattleLeft = self._createEvent()
        self.onPrebattleJoinFailure = self._createEvent()
        self.onArenaCreated = self._createEvent()
        self.onArenaJoinFailure = self._createEvent()
        self.onKickedFromUnitsQueue = self._createEvent()
        self.onKickedFromPrebattle = self._createEvent()
        self.onKickedFromArena = self._createEvent()
        self.onQueueInfoReceived = self._createEvent()
        self.onPrebattlesListReceived = self._createEvent()
        self.onPrebattleAutoInvitesChanged = self._createEvent()
        self.onAccountGlobalRatingChanged = self._createEvent()
        self.onPrebattleInvitesChanged = self._createEvent()
        self.onPrebattleInvitationsChanged = self._createEvent()
        self.onPrebattleInvitationAccepted = self._createEvent()
        self.onPrebattleInvitesStatus = self._createEvent()
        self.onPrebattleInvitationsError = self._createEvent()
        self.onClanMembersListChanged = self._createEvent()
        self.onEventsDataChanged = self._createEvent()
        self.onPrebattleRosterReceived = self._createEvent()
        self.onArenaListReceived = self._createEvent()
        self.onServerStatsReceived = self._createEvent()
        self.onInventoryResync = self._createEvent()
        self.onStatsResync = self._createEvent()
        self.onShopResyncStarted = self._createEvent()
        self.onShopResync = self._createEvent()
        self.onDossiersResync = self._createEvent()
        self.onOffersResync = self._createEvent()
        self.onEventNotificationsChanged = self._createEvent()
        self.onVehicleLockChanged = self._createEvent()
        self.onVehicleBecomeElite = self._createEvent()
        self.onCenterIsLongDisconnected = self._createEvent()
        self.onIGRTypeChanged = self._createEvent()
        self.onAvatarBecomePlayer = self._createEvent()
        self.onAvatarBecomeNonPlayer = self._createEvent()
        self.onArenaPeriodChange = self._createEvent()
        self.onAvatarReady = self._createEvent()
        self.onBattleResultsReceived = self._createEvent()
        self.onAvatarVehicleLeaveWorld = self._createEvent()
        self.onLoginQueueNumberReceived = self._createEvent()
        self.onKickWhileLoginReceived = self._createEvent()
        self.onPeripheryRoutingGroupReceived = self._createEvent()
        self.onGuiCacheSyncCompleted = self._createEvent()
        self.onPMLocksChanged = self._createEvent()
        self.onDailyQuestsInfoChange = self._createEvent()
        self.onWeeklyQuestsInfoChange = self._createEvent()
        self.onNotification = self._createEvent()
        self.onTeamChanged = self._createEvent()
        self.onDisconnected = self._createEvent()
        self.onShowDevelopmentInfo = self._createEvent()
        self.onRoundFinished = self._createEvent()
        self.crosshairPanelInitialized = self._createEvent()
        self.onServerReplayEntering = self._createEvent()
        self.onServerReplayExiting = self._createEvent()
        self.onPlatformBlueprintsConvertSaleLimits = self._createEvent()
        self.onCollectPrebattleInvites = self._createEvent()
        self.onUpdateSpecBattlesWindow = self._createEvent()
        self.onLoadingMilestoneReached = self._createEvent()
        self.onConfigModelUpdated = self._createEvent()
        self.onShowBattleHint = self._createEvent()
        self.onHideBattleHint = self._createEvent()
        self.onEmptyBattleHintsQueue = self._createEvent()
        self.onTracerReceived = self._createEvent()
        self.onVehicleEntityCreated = self._createEvent()
        self.onUILoggingStarted = self._createEvent()
        self.onRenewableSubscriptionStatusChanged = self._createEvent()


g_playerEvents = _PlayerEvents()
