# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: mt_birthday/scripts/common/mt_birthday_common/constants.py
MT_BIRTHDAY_PROGRESSION_TOKEN_PREFIX = 'mtBirthday2025'
MT_BIRTHDAY_PROGRESSION_TOKEN = MT_BIRTHDAY_PROGRESSION_TOKEN_PREFIX + ':progression'
MT_BIRTHDAY_INFINITY_PROGRESSION_TOKEN = MT_BIRTHDAY_PROGRESSION_TOKEN_PREFIX + ':progression_infinity'
MT_BIRTHDAY_INFINITY_COMPLETE_TOKEN = MT_BIRTHDAY_PROGRESSION_TOKEN_PREFIX + ':infinity_complete'
MT_BIRTHDAY_QUEST_PROGRESSION_PREFIX = 'mtBirthday2025Progression'
MT_BIRTHDAY_QUEST_PROGRESSION_ID = MT_BIRTHDAY_QUEST_PROGRESSION_PREFIX + ':level'
MT_BIRTHDAY_BADGE_QUEST_PROGRESSION_ID = MT_BIRTHDAY_QUEST_PROGRESSION_PREFIX + ':badge_level'
MT_BIRTHDAY_QUEST_PROGRESSION_ID_FORMAT = MT_BIRTHDAY_QUEST_PROGRESSION_PREFIX + ':level_{}'
MT_BIRTHDAY_WELCOME_QUEST_ID = 'mtBirthday2025WelcomeAward'
CMD_GET_PLAYERS_FROM_BATTLES = 31027
