# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: mt_birthday/scripts/common/mt_birthday_common/constants.py
MT_BIRTHDAY_PROGRESSION_TOKEN_PREFIX = 'mtBirthday2026'
MT_BIRTHDAY_PROGRESSION_TOKEN = MT_BIRTHDAY_PROGRESSION_TOKEN_PREFIX + ':progression'
MT_BIRTHDAY_INFINITY_PROGRESSION_TOKEN = MT_BIRTHDAY_PROGRESSION_TOKEN_PREFIX + ':progression_infinity'
MT_BIRTHDAY_INFINITY_COMPLETE_TOKEN = MT_BIRTHDAY_PROGRESSION_TOKEN_PREFIX + ':infinity_complete'
MT_BIRTHDAY_QUEST_PROGRESSION_PREFIX = 'mtBirthday2026Progression'
MT_BIRTHDAY_QUEST_PROGRESSION_ID = MT_BIRTHDAY_QUEST_PROGRESSION_PREFIX + ':level'
MT_BIRTHDAY_QUEST_PROGRESSION_ID_FORMAT = MT_BIRTHDAY_QUEST_PROGRESSION_PREFIX + ':level_{}'
MT_BIRTHDAY_WELCOME_QUEST_ID = 'mtBirthday2026WelcomeAward'
BIRTHDAY_BADGE_QUEST = 'mt_birthday_badge_quest'
BIRTHDAY_CHALLENGE_COMPLETE_QUEST = 'mt_birthday_challenges_complete_quest'
CMD_GET_PLAYERS_FROM_BATTLES = 31027
