# Python 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/client/bwobsolete_helpers/PyGUI/LLMozlibKeys.py
LL_DOM_VK_CANCEL = 3
LL_DOM_VK_HELP = 6
LL_DOM_VK_BACK_SPACE = 8
LL_DOM_VK_TAB = 9
LL_DOM_VK_CLEAR = 12
LL_DOM_VK_RETURN = 13
LL_DOM_VK_ENTER = 14
LL_DOM_VK_SHIFT = 16
LL_DOM_VK_CONTROL = 17
LL_DOM_VK_ALT = 18
LL_DOM_VK_PAUSE = 19
LL_DOM_VK_CAPS_LOCK = 20
LL_DOM_VK_ESCAPE = 27
LL_DOM_VK_SPACE = 32
LL_DOM_VK_PAGE_UP = 33
LL_DOM_VK_PAGE_DOWN = 34
LL_DOM_VK_END = 35
LL_DOM_VK_HOME = 36
LL_DOM_VK_LEFT = 37
LL_DOM_VK_UP = 38
LL_DOM_VK_RIGHT = 39
LL_DOM_VK_DOWN = 40
LL_DOM_VK_PRINTSCREEN = 44
LL_DOM_VK_INSERT = 45
LL_DOM_VK_DELETE = 46
