# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: portal/scripts/common/portal_common/account_commands_extension.py
CMD_PURCHASE_TOKEN = 15001
CMD_PORTAL_INSTALL_UPGRADE = 15002
CMD_PORTAL_ADD_VEHICLE_EXP_DEV = 15003
CMD_PORTAL_SET_COMPLEXITY_LEVEL_DEV = 15004
CMD_PORTAL_RESET_UPGRADE = 15005
CMD_PORTAL_ADD_PORTAL_PROGRESSION_TOKEN = 15006
CMD_PORTAL_SUBTRACT_PORTAL_PROGRESSION_TOKEN = 15007
CMD_PORTAL_GET_LAST_LEVEL_VICTORY_ACHIEVEMENT = 15008
CMD_PORTAL_GET_ALL_VEHICLES_UPGRADED_ACHIEVEMENT = 15009
