# Embedded file name: scripts/common/dossiers2/custom/layouts.py
VERSION_RECORD_FORMAT = 'H'
BLOCK_SIZE_RECORD_FORMAT = 'H'
from dossiers2.common.DossierBlockBuilders import *
from dossiers2.custom.dependencies import A15X15_STATS_DEPENDENCIES, A7X7_STATS_DEPENDENCIES
from dossiers2.custom.dependencies import ACHIEVEMENT_DEPENDENCIES, VEH_TYPE_FRAGS_DEPENDENCIES
from dossiers2.custom.dependencies import ACHIEVEMENT7X7_DEPENDENCIES
from dossiers2.custom.dependencies import HISTORICAL_STATS_DEPENDENCIES
from dossiers2.custom.dependencies import HISTORICAL_ACHIEVEMENTS_DEPENDENCIES
from dossiers2.custom.dependencies import FORT_BATTLES_STATS_DEPENDENCIES
from dossiers2.custom.dependencies import FORT_SORTIES_STATS_DEPENDENCIES
from dossiers2.custom.dependencies import FORT_MISC_DEPENDENCIES
from dossiers2.custom.dependencies import CLAN_STATS_DEPENDENCIES
from dossiers2.custom.dependencies import FORT_ACHIEVEMENTS_DEPENDENCIES
TOTAL_BLOCK_LAYOUT = ['creationTime',
 'lastBattleTime',
 'battleLifeTime',
 'treesCut',
 'mileage']
_totalBlockBuilder = StaticSizeBlockBuilder('total', TOTAL_BLOCK_LAYOUT, {}, [])
A15X15_BLOCK_LAYOUT = ['xp',
 'battlesCount',
 'wins',
 'losses',
 'survivedBattles',
 'frags',
 'shots',
 'directHits',
 'spotted',
 'damageDealt',
 'damageReceived',
 'capturePoints',
 'droppedCapturePoints',
 'xpBefore8_8',
 'battlesCountBefore8_8',
 'winAndSurvived',
 'frags8p',
 'battlesCountBefore9_0']
_a15x15BlockBuilder = StaticSizeBlockBuilder('a15x15', A15X15_BLOCK_LAYOUT, A15X15_STATS_DEPENDENCIES, [])
A15X15_2_BLOCK_LAYOUT = ['originalXP',
 'damageAssistedTrack',
 'damageAssistedRadio',
 'directHitsReceived',
 'noDamageDirectHitsReceived',
 'piercingsReceived',
 'explosionHitsReceived',
 'explosionHits',
 'piercings',
 'potentialDamageReceived',
 'damageBlockedByArmor']
_a15x15_2BlockBuilder = StaticSizeBlockBuilder('a15x15_2', A15X15_2_BLOCK_LAYOUT, {}, [])
CLAN_BLOCK_LAYOUT = ['xp',
 'battlesCount',
 'wins',
 'losses',
 'survivedBattles',
 'frags',
 'shots',
 'directHits',
 'spotted',
 'damageDealt',
 'damageReceived',
 'capturePoints',
 'droppedCapturePoints',
 'xpBefore8_9',
 'battlesCountBefore8_9',
 'battlesCountBefore9_0']
_clanBlockBuilder = StaticSizeBlockBuilder('clan', CLAN_BLOCK_LAYOUT, CLAN_STATS_DEPENDENCIES, [])
CLAN2_BLOCK_LAYOUT = ['originalXP',
 'damageAssistedTrack',
 'damageAssistedRadio',
 'directHitsReceived',
 'noDamageDirectHitsReceived',
 'piercingsReceived',
 'explosionHitsReceived',
 'explosionHits',
 'piercings',
 'potentialDamageReceived',
 'damageBlockedByArmor']
_clan2BlockBuilder = StaticSizeBlockBuilder('clan2', CLAN2_BLOCK_LAYOUT, {}, [])
COMPANY_BLOCK_LAYOUT = ['xp',
 'battlesCount',
 'wins',
 'losses',
 'survivedBattles',
 'frags',
 'shots',
 'directHits',
 'spotted',
 'damageDealt',
 'damageReceived',
 'capturePoints',
 'droppedCapturePoints',
 'xpBefore8_9',
 'battlesCountBefore8_9',
 'battlesCountBefore9_0']
_companyBlockBuilder = StaticSizeBlockBuilder('company', COMPANY_BLOCK_LAYOUT, {}, [])
COMPANY2_BLOCK_LAYOUT = ['originalXP',
 'damageAssistedTrack',
 'damageAssistedRadio',
 'directHitsReceived',
 'noDamageDirectHitsReceived',
 'piercingsReceived',
 'explosionHitsReceived',
 'explosionHits',
 'piercings',
 'potentialDamageReceived',
 'damageBlockedByArmor']
_company2BlockBuilder = StaticSizeBlockBuilder('company2', COMPANY2_BLOCK_LAYOUT, {}, [])
A7X7_BLOCK_LAYOUT = ['xp',
 'battlesCount',
 'wins',
 'losses',
 'survivedBattles',
 'frags',
 'shots',
 'directHits',
 'spotted',
 'damageDealt',
 'damageReceived',
 'capturePoints',
 'droppedCapturePoints',
 'originalXP',
 'damageAssistedTrack',
 'damageAssistedRadio',
 'directHitsReceived',
 'noDamageDirectHitsReceived',
 'piercingsReceived',
 'explosionHitsReceived',
 'explosionHits',
 'piercings',
 'winAndSurvived',
 'frags8p',
 'potentialDamageReceived',
 'damageBlockedByArmor',
 'battlesCountBefore9_0']
_a7x7BlockBuilder = StaticSizeBlockBuilder('a7x7', A7X7_BLOCK_LAYOUT, A7X7_STATS_DEPENDENCIES, [])
MAX_BLOCK_LAYOUT = ['maxXP', 'maxFrags', 'maxDamage']
ACCOUNT_MAX_BLOCK_LAYOUT = MAX_BLOCK_LAYOUT + ['maxXPVehicle', 'maxFragsVehicle', 'maxDamageVehicle']
_accountMax15x15BlockBuilder = StaticSizeBlockBuilder('max15x15', ACCOUNT_MAX_BLOCK_LAYOUT, {}, [])
_accountMax7x7BlockBuilder = StaticSizeBlockBuilder('max7x7', ACCOUNT_MAX_BLOCK_LAYOUT, {}, [])
_accountMaxHistoricalBlockBuilder = StaticSizeBlockBuilder('maxHistorical', ACCOUNT_MAX_BLOCK_LAYOUT, {}, [])
_accountMaxFortBattlesBlockBuilder = StaticSizeBlockBuilder('maxFortBattles', ACCOUNT_MAX_BLOCK_LAYOUT, {}, [])
_accountMaxFortSortiesBlockBuilder = StaticSizeBlockBuilder('maxFortSorties', ACCOUNT_MAX_BLOCK_LAYOUT, {}, [])
_accountMaxFortBattlesInClanBlockBuilder = StaticSizeBlockBuilder('maxFortBattlesInClan', ACCOUNT_MAX_BLOCK_LAYOUT, {}, [])
_accountMaxFortSortiesInClanBlockBuilder = StaticSizeBlockBuilder('maxFortSortiesInClan', ACCOUNT_MAX_BLOCK_LAYOUT, {}, [])
ACCOUNT_ACHIEVEMENTS_BLOCK_LAYOUT = ['fragsBeast',
 'sniperSeries',
 'maxSniperSeries',
 'invincibleSeries',
 'maxInvincibleSeries',
 'diehardSeries',
 'maxDiehardSeries',
 'killingSeries',
 'fragsSinai',
 'maxKillingSeries',
 'piercingSeries',
 'maxPiercingSeries',
 'battleHeroes',
 'warrior',
 'invader',
 'sniper',
 'defender',
 'steelwall',
 'supporter',
 'scout',
 'evileye',
 'medalKay',
 'medalCarius',
 'medalKnispel',
 'medalPoppel',
 'medalAbrams',
 'medalLeClerc',
 'medalLavrinenko',
 'medalEkins',
 'medalWittmann',
 'medalOrlik',
 'medalOskin',
 'medalHalonen',
 'medalBurda',
 'medalBillotte',
 'medalKolobanov',
 'medalFadin',
 'medalRadleyWalters',
 'medalBrunoPietro',
 'medalTarczay',
 'medalPascucci',
 'medalDumitru',
 'medalLehvaslaiho',
 'medalNikolas',
 'medalLafayettePool',
 'sinai',
 'heroesOfRassenay',
 'beasthunter',
 'mousebane',
 'tankExpertStrg',
 'raider',
 'kamikaze',
 'lumberjack',
 'medalBrothersInArms',
 'medalCrucialContribution',
 'medalDeLanglade',
 'medalTamadaYoshio',
 'bombardier',
 'huntsman',
 'alaric',
 'sturdy',
 'ironMan',
 'luckyDevil',
 'pattonValley',
 'fragsPatton',
 'mechanicEngineerStrg',
 'sniper2',
 'mainGun',
 'medalMonolith',
 'medalAntiSpgFire',
 'medalGore',
 'medalCoolBlood',
 'medalStark',
 'maxWFC2014WinSeries',
 'WFC2014WinSeries',
 'impenetrable',
 'reliableComradeSeries',
 'reliableComrade',
 'maxAimerSeries',
 'shootToKill',
 'fighter',
 'duelist',
 'demolition',
 'arsonist',
 'bonecrusher',
 'charmed',
 'even',
 'maxDeathTrackWinSeries',
 'deathTrackWinSeries',
 'readyForBattleLT',
 'readyForBattleMT',
 'readyForBattleHT',
 'readyForBattleSPG',
 'readyForBattleATSPG',
 'readyForBattleALL',
 'tankwomenProgress']
_accountAchievementsPopUps = ['warrior',
 'invader',
 'sniper',
 'defender',
 'steelwall',
 'supporter',
 'scout',
 'medalKay',
 'medalCarius',
 'medalKnispel',
 'medalPoppel',
 'medalAbrams',
 'medalLeClerc',
 'medalLavrinenko',
 'medalEkins',
 'medalWittmann',
 'medalOrlik',
 'medalOskin',
 'medalHalonen',
 'medalBurda',
 'medalBillotte',
 'medalKolobanov',
 'medalFadin',
 'beasthunter',
 'mousebane',
 'tankExpert',
 'raider',
 'kamikaze',
 'lumberjack',
 'evileye',
 'medalRadleyWalters',
 'medalLafayettePool',
 'medalBrunoPietro',
 'medalTarczay',
 'medalPascucci',
 'medalDumitru',
 'medalLehvaslaiho',
 'medalNikolas',
 'sinai',
 'pattonValley',
 'heroesOfRassenay',
 'mechanicEngineer',
 'tankExpert0',
 'tankExpert1',
 'tankExpert2',
 'tankExpert3',
 'tankExpert4',
 'tankExpert5',
 'tankExpert6',
 'tankExpert7',
 'tankExpert8',
 'tankExpert9',
 'tankExpert10',
 'tankExpert11',
 'tankExpert12',
 'tankExpert13',
 'tankExpert14',
 'mechanicEngineer0',
 'mechanicEngineer1',
 'mechanicEngineer2',
 'mechanicEngineer3',
 'mechanicEngineer4',
 'mechanicEngineer5',
 'mechanicEngineer6',
 'mechanicEngineer7',
 'mechanicEngineer8',
 'mechanicEngineer9',
 'mechanicEngineer10',
 'mechanicEngineer11',
 'mechanicEngineer12',
 'mechanicEngineer13',
 'mechanicEngineer14',
 'medalBrothersInArms',
 'medalCrucialContribution',
 'medalDeLanglade',
 'medalTamadaYoshio',
 'bombardier',
 'huntsman',
 'alaric',
 'sturdy',
 'ironMan',
 'luckyDevil',
 'sniper2',
 'mainGun',
 'medalMonolith',
 'medalAntiSpgFire',
 'medalGore',
 'medalCoolBlood',
 'medalStark',
 'impenetrable',
 'reliableComrade',
 'shootToKill',
 'fighter',
 'duelist',
 'demolition',
 'arsonist',
 'bonecrusher',
 'charmed',
 'even',
 'readyForBattleLT',
 'readyForBattleMT',
 'readyForBattleHT',
 'readyForBattleSPG',
 'readyForBattleATSPG',
 'readyForBattleALL']
_accountAchievementsBlockBuilder = StaticSizeBlockBuilder('achievements', ACCOUNT_ACHIEVEMENTS_BLOCK_LAYOUT, ACHIEVEMENT_DEPENDENCIES, _accountAchievementsPopUps)
_vehTypeFragsBlockBuilder = DictBlockBuilder('vehTypeFrags', 'I', 'H', VEH_TYPE_FRAGS_DEPENDENCIES)
_a15x15CutBlockBuilder = DictBlockBuilder('a15x15Cut', 'I', 'IIII', {})
_a7x7CutBlockBuilder = DictBlockBuilder('a7x7Cut', 'I', 'IIIIIII', {})
_rareAchievementsBlockBuilder = ListBlockBuilder('rareAchievements', 'I', {})
ACHIEVEMENTS7X7_BLOCK_LAYOUT = ['wolfAmongSheep',
 'wolfAmongSheepMedal',
 'geniusForWar',
 'geniusForWarMedal',
 'kingOfTheHill',
 'tacticalBreakthroughSeries',
 'maxTacticalBreakthroughSeries',
 'armoredFist',
 'godOfWar',
 'fightingReconnaissance',
 'fightingReconnaissanceMedal',
 'willToWinSpirit',
 'crucialShot',
 'crucialShotMedal',
 'forTacticalOperations',
 'promisingFighter',
 'promisingFighterMedal',
 'heavyFire',
 'heavyFireMedal',
 'ranger',
 'rangerMedal',
 'fireAndSteel',
 'fireAndSteelMedal',
 'pyromaniac',
 'pyromaniacMedal',
 'noMansLand',
 'guerrilla',
 'guerrillaMedal',
 'infiltrator',
 'infiltratorMedal',
 'sentinel',
 'sentinelMedal',
 'prematureDetonation',
 'prematureDetonationMedal',
 'bruteForce',
 'bruteForceMedal',
 'awardCount',
 'battleTested']
_achievement7x7PopUps = ['wolfAmongSheepMedal',
 'geniusForWarMedal',
 'kingOfTheHill',
 'armoredFist',
 'godOfWar',
 'forTacticalOperations',
 'crucialShotMedal',
 'willToWinSpirit',
 'fightingReconnaissanceMedal',
 'promisingFighterMedal',
 'heavyFireMedal',
 'rangerMedal',
 'fireAndSteelMedal',
 'pyromaniacMedal',
 'noMansLand',
 'guerrillaMedal',
 'infiltratorMedal',
 'sentinelMedal',
 'prematureDetonationMedal',
 'bruteForceMedal',
 'battleTested']
_accountAchievements7x7BlockBuilder = StaticSizeBlockBuilder('achievements7x7', ACHIEVEMENTS7X7_BLOCK_LAYOUT, ACHIEVEMENT7X7_DEPENDENCIES, _achievement7x7PopUps)
HISTORICAL_BLOCK_LAYOUT = ['xp',
 'battlesCount',
 'wins',
 'losses',
 'survivedBattles',
 'frags',
 'shots',
 'directHits',
 'spotted',
 'damageDealt',
 'damageReceived',
 'capturePoints',
 'droppedCapturePoints',
 'originalXP',
 'damageAssistedTrack',
 'damageAssistedRadio',
 'directHitsReceived',
 'noDamageDirectHitsReceived',
 'piercingsReceived',
 'explosionHitsReceived',
 'explosionHits',
 'piercings',
 'winAndSurvived',
 'frags8p',
 'potentialDamageReceived',
 'damageBlockedByArmor']
_historicalBlockBuilder = StaticSizeBlockBuilder('historical', HISTORICAL_BLOCK_LAYOUT, HISTORICAL_STATS_DEPENDENCIES, [])
HISTORICAL_ACHIEVEMENTS_BLOCK_LAYOUT = ['guardsman',
 'makerOfHistory',
 'bothSidesWins',
 'weakVehiclesWins']
_historicalAchievementsPopUps = ['guardsman', 'makerOfHistory']
_historicalAchievementsBlockBuilder = StaticSizeBlockBuilder('historicalAchievements', HISTORICAL_ACHIEVEMENTS_BLOCK_LAYOUT, HISTORICAL_ACHIEVEMENTS_DEPENDENCIES, _historicalAchievementsPopUps)
_historicalCutBlockBuilder = DictBlockBuilder('historicalCut', 'I', 'III', {})
UNIQUE_ACHIEVEMENT_VALUES = ['histBattle1_battlefield',
 'histBattle1_historyLessons',
 'histBattle2_battlefield',
 'histBattle2_historyLessons',
 'histBattle3_battlefield',
 'histBattle3_historyLessons',
 'histBattle4_battlefield',
 'histBattle4_historyLessons',
 'histBattle5_battlefield',
 'histBattle5_historyLessons',
 'histBattle6_battlefield',
 'histBattle6_historyLessons']
_uniqueAchievementPopUps = ['histBattle1_battlefield',
 'histBattle1_historyLessons',
 'histBattle2_battlefield',
 'histBattle2_historyLessons',
 'histBattle3_battlefield',
 'histBattle3_historyLessons',
 'histBattle4_battlefield',
 'histBattle4_historyLessons',
 'histBattle5_battlefield',
 'histBattle5_historyLessons',
 'histBattle6_battlefield',
 'histBattle6_historyLessons']
_uniqueAchievementBlockBuilder = BinarySetDossierBlockBuilder('uniqueAchievements', UNIQUE_ACHIEVEMENT_VALUES, {}, _uniqueAchievementPopUps)
ACCOUNT_SINGLE_ACHIEVEMENTS_VALUES = ['titleSniper',
 'invincible',
 'diehard',
 'handOfDeath',
 'armorPiercer',
 'battleCitizen',
 'WFC2014',
 'tacticalBreakthrough',
 'aimer',
 'deathTrack',
 'firstMerit',
 'tankwomen']
_accountSingleAchievementsPopUps = ['titleSniper',
 'invincible',
 'diehard',
 'handOfDeath',
 'armorPiercer',
 'battleCitizen',
 'WFC2014',
 'tacticalBreakthrough',
 'aimer',
 'deathTrack',
 'firstMerit',
 'tankwomen']
_accountSingleAchievementsBlockBuilder = BinarySetDossierBlockBuilder('singleAchievements', ACCOUNT_SINGLE_ACHIEVEMENTS_VALUES, {}, _accountSingleAchievementsPopUps)
FORT_BLOCK_LAYOUT = ['xp',
 'battlesCount',
 'wins',
 'losses',
 'survivedBattles',
 'frags',
 'shots',
 'directHits',
 'spotted',
 'damageDealt',
 'damageReceived',
 'capturePoints',
 'droppedCapturePoints',
 'originalXP',
 'damageAssistedTrack',
 'damageAssistedRadio',
 'directHitsReceived',
 'noDamageDirectHitsReceived',
 'piercingsReceived',
 'explosionHitsReceived',
 'explosionHits',
 'piercings',
 'winAndSurvived',
 'frags8p',
 'potentialDamageReceived',
 'damageBlockedByArmor']
_fortBattlesInClanBlockBuilder = StaticSizeBlockBuilder('fortBattlesInClan', FORT_BLOCK_LAYOUT, {}, [])
_fortSortiesInClanBlockBuilder = StaticSizeBlockBuilder('fortSortiesInClan', FORT_BLOCK_LAYOUT, {}, [])
_fortBattlesBlockBuilder = StaticSizeBlockBuilder('fortBattles', FORT_BLOCK_LAYOUT, FORT_BATTLES_STATS_DEPENDENCIES, [])
_fortSortiesBlockBuilder = StaticSizeBlockBuilder('fortSorties', FORT_BLOCK_LAYOUT, FORT_SORTIES_STATS_DEPENDENCIES, [])
_fortBattlesCutBlockBuilder = DictBlockBuilder('fortBattlesCut', 'I', 'III', {})
_fortSortiesCutBlockBuilder = DictBlockBuilder('fortSortiesCut', 'I', 'III', {})
FORT_MISC_LAYOUT = ['fortResourceInBattles',
 'maxFortResourceInBattles',
 'fortResourceInSorties',
 'maxFortResourceInSorties',
 'defenceHours',
 'successfulDefenceHours',
 'attackNumber',
 'enemyBasePlunderNumber',
 'enemyBasePlunderNumberInAttack']
_fortMiscBlockBuilder = StaticSizeBlockBuilder('fortMisc', FORT_MISC_LAYOUT, FORT_MISC_DEPENDENCIES, [])
_fortMiscInClanBlockBuilder = StaticSizeBlockBuilder('fortMiscInClan', FORT_MISC_LAYOUT, {}, [])
FORT_ACHIEVEMENTS_BLOCK_LAYOUT = ['conqueror',
 'fireAndSword',
 'crusher',
 'counterblow',
 'kampfer',
 'soldierOfFortune',
 'wins',
 'capturedBasesInAttack',
 'capturedBasesInDefence']
_fortPersonalAchievementsPopUps = ['conqueror',
 'fireAndSword',
 'crusher',
 'counterblow',
 'kampfer',
 'soldierOfFortune']
_fortPersonalAchievementsBlockBuilder = StaticSizeBlockBuilder('fortAchievements', FORT_ACHIEVEMENTS_BLOCK_LAYOUT, FORT_ACHIEVEMENTS_DEPENDENCIES, _fortPersonalAchievementsPopUps)
CLAN_ACHIEVEMENTS_BLOCK_LAYOUT = ['medalRotmistrov']
_clanAchievementsPopUps = ['medalRotmistrov']
_accountClanAchievementsBlockBuilder = StaticSizeBlockBuilder('clanAchievements', CLAN_ACHIEVEMENTS_BLOCK_LAYOUT, {}, _clanAchievementsPopUps)
accountDossierLayout = (_a15x15BlockBuilder,
 _a15x15_2BlockBuilder,
 _clanBlockBuilder,
 _clan2BlockBuilder,
 _companyBlockBuilder,
 _company2BlockBuilder,
 _a7x7BlockBuilder,
 _accountAchievementsBlockBuilder,
 _vehTypeFragsBlockBuilder,
 _a15x15CutBlockBuilder,
 _rareAchievementsBlockBuilder,
 _totalBlockBuilder,
 _a7x7CutBlockBuilder,
 _accountMax15x15BlockBuilder,
 _accountMax7x7BlockBuilder,
 _accountAchievements7x7BlockBuilder,
 _historicalBlockBuilder,
 _accountMaxHistoricalBlockBuilder,
 _historicalAchievementsBlockBuilder,
 _historicalCutBlockBuilder,
 _uniqueAchievementBlockBuilder,
 _fortBattlesBlockBuilder,
 _accountMaxFortBattlesBlockBuilder,
 _fortBattlesCutBlockBuilder,
 _fortSortiesBlockBuilder,
 _accountMaxFortSortiesBlockBuilder,
 _fortSortiesCutBlockBuilder,
 _fortBattlesInClanBlockBuilder,
 _accountMaxFortBattlesInClanBlockBuilder,
 _fortSortiesInClanBlockBuilder,
 _accountMaxFortSortiesInClanBlockBuilder,
 _fortMiscBlockBuilder,
 _fortMiscInClanBlockBuilder,
 _fortPersonalAchievementsBlockBuilder,
 _accountSingleAchievementsBlockBuilder,
 _accountClanAchievementsBlockBuilder)
_vehicleMaxPopUps = ['maxXP', 'maxFrags', 'maxDamage']
_vehicleMax15x15BlockBuilder = StaticSizeBlockBuilder('max15x15', MAX_BLOCK_LAYOUT, {}, _vehicleMaxPopUps)
_vehicleMax7x7BlockBuilder = StaticSizeBlockBuilder('max7x7', MAX_BLOCK_LAYOUT, {}, _vehicleMaxPopUps)
_vehicleMaxHistoricalBlockBuilder = StaticSizeBlockBuilder('maxHistorical', MAX_BLOCK_LAYOUT, {}, _vehicleMaxPopUps)
_vehicleMaxFortBattlesBlockBuilder = StaticSizeBlockBuilder('maxFortBattles', MAX_BLOCK_LAYOUT, {}, _vehicleMaxPopUps)
_vehicleMaxFortSortiesBlockBuilder = StaticSizeBlockBuilder('maxFortSorties', MAX_BLOCK_LAYOUT, {}, _vehicleMaxPopUps)
VEHICLE_ACHIEVEMENTS_BLOCK_LAYOUT = ['fragsBeast',
 'sniperSeries',
 'maxSniperSeries',
 'invincibleSeries',
 'maxInvincibleSeries',
 'diehardSeries',
 'maxDiehardSeries',
 'killingSeries',
 'fragsSinai',
 'maxKillingSeries',
 'piercingSeries',
 'maxPiercingSeries',
 'battleHeroes',
 'warrior',
 'invader',
 'sniper',
 'defender',
 'steelwall',
 'supporter',
 'scout',
 'evileye',
 'medalKay',
 'medalCarius',
 'medalKnispel',
 'medalPoppel',
 'medalAbrams',
 'medalLeClerc',
 'medalLavrinenko',
 'medalEkins',
 'medalWittmann',
 'medalOrlik',
 'medalOskin',
 'medalHalonen',
 'medalBurda',
 'medalBillotte',
 'medalKolobanov',
 'medalFadin',
 'medalRadleyWalters',
 'medalBrunoPietro',
 'medalTarczay',
 'medalPascucci',
 'medalDumitru',
 'medalLehvaslaiho',
 'medalNikolas',
 'medalLafayettePool',
 'sinai',
 'heroesOfRassenay',
 'beasthunter',
 'mousebane',
 'tankExpertStrg',
 'raider',
 'kamikaze',
 'lumberjack',
 'medalBrothersInArms',
 'medalCrucialContribution',
 'medalDeLanglade',
 'medalTamadaYoshio',
 'bombardier',
 'huntsman',
 'alaric',
 'sturdy',
 'ironMan',
 'luckyDevil',
 'pattonValley',
 'fragsPatton',
 'markOfMastery',
 'sniper2',
 'mainGun',
 'marksOnGun',
 'movingAvgDamage',
 'medalMonolith',
 'medalAntiSpgFire',
 'medalGore',
 'medalCoolBlood',
 'medalStark',
 'damageRating',
 'impenetrable',
 'maxAimerSeries',
 'shootToKill',
 'fighter',
 'duelist',
 'demolition',
 'arsonist',
 'bonecrusher',
 'charmed',
 'even']
_vehicleAchievementsPopUps = ['tankExpert',
 'tankExpert0',
 'tankExpert1',
 'tankExpert2',
 'tankExpert3',
 'tankExpert4',
 'tankExpert5',
 'tankExpert6',
 'tankExpert7',
 'tankExpert8',
 'tankExpert9',
 'tankExpert10',
 'tankExpert11',
 'tankExpert12',
 'tankExpert13',
 'tankExpert14',
 'markOfMastery',
 'marksOnGun',
 'impenetrableshootToKill',
 'fighter',
 'duelist',
 'demolition',
 'arsonist',
 'bonecrusher',
 'charmed',
 'even']
_vehicleAchievementsBlockBuilder = StaticSizeBlockBuilder('achievements', VEHICLE_ACHIEVEMENTS_BLOCK_LAYOUT, ACHIEVEMENT_DEPENDENCIES, _vehicleAchievementsPopUps)
_playerInscriptionsBlockBuilder = ListBlockBuilder('inscriptions', 'H', {})
_playerEmblemsBlockBuilder = ListBlockBuilder('emblems', 'H', {})
_camouflagesBlockBuilder = ListBlockBuilder('camouflages', 'H', {})
COMPENSATION_BLOCK_LAYOUT = ['gold']
_compensationBlockBuilder = StaticSizeBlockBuilder('compensation', COMPENSATION_BLOCK_LAYOUT, {}, [])
_vehicleAchievements7x7BlockBuilder = StaticSizeBlockBuilder('achievements7x7', ACHIEVEMENTS7X7_BLOCK_LAYOUT, ACHIEVEMENT7X7_DEPENDENCIES, [])
UNIQUE_VEH_ACHIEVEMENT_VALUES = []
_uniqueVehAchievementPopUps = []
_uniqueVehAchievementBlockBuilder = BinarySetDossierBlockBuilder('uniqueAchievements', UNIQUE_VEH_ACHIEVEMENT_VALUES, {}, _uniqueVehAchievementPopUps)
VEHICLE_SINGLE_ACHIEVEMENTS_VALUES = ['titleSniper',
 'invincible',
 'diehard',
 'handOfDeath',
 'armorPiercer',
 'tacticalBreakthrough',
 'aimer']
_vehicleSingleAchievementsPopUps = ['titleSniper',
 'invincible',
 'diehard',
 'handOfDeath',
 'armorPiercer',
 'tacticalBreakthrough',
 'aimer']
_vehicleSingleAchievementsBlockBuilder = BinarySetDossierBlockBuilder('singleAchievements', VEHICLE_SINGLE_ACHIEVEMENTS_VALUES, {}, _vehicleSingleAchievementsPopUps)
_vehicleClanAchievementsBlockBuilder = StaticSizeBlockBuilder('clanAchievements', CLAN_ACHIEVEMENTS_BLOCK_LAYOUT, {}, [])
vehicleDossierLayout = (_a15x15BlockBuilder,
 _a15x15_2BlockBuilder,
 _clanBlockBuilder,
 _clan2BlockBuilder,
 _companyBlockBuilder,
 _company2BlockBuilder,
 _a7x7BlockBuilder,
 _vehicleAchievementsBlockBuilder,
 _vehTypeFragsBlockBuilder,
 _totalBlockBuilder,
 _vehicleMax15x15BlockBuilder,
 _vehicleMax7x7BlockBuilder,
 _playerInscriptionsBlockBuilder,
 _playerEmblemsBlockBuilder,
 _camouflagesBlockBuilder,
 _compensationBlockBuilder,
 _vehicleAchievements7x7BlockBuilder,
 _historicalBlockBuilder,
 _vehicleMaxHistoricalBlockBuilder,
 _uniqueVehAchievementBlockBuilder,
 _fortBattlesBlockBuilder,
 _vehicleMaxFortBattlesBlockBuilder,
 _fortSortiesBlockBuilder,
 _vehicleMaxFortSortiesBlockBuilder,
 _fortPersonalAchievementsBlockBuilder,
 _vehicleSingleAchievementsBlockBuilder,
 _vehicleClanAchievementsBlockBuilder)
_tmanTotalBlockLayout = ['battlesCount']
_tmanTotalBlockBuilder = StaticSizeBlockBuilder('total', _tmanTotalBlockLayout, {}, [])
TMAN_ACHIEVEMENTS_BLOCK_LAYOUT = ['warrior',
 'invader',
 'sniper',
 'defender',
 'steelwall',
 'supporter',
 'scout',
 'evileye',
 'medalWittmann',
 'medalOrlik',
 'medalOskin',
 'medalHalonen',
 'medalBurda',
 'medalBillotte',
 'medalKolobanov',
 'medalFadin',
 'medalRadleyWalters',
 'medalBrunoPietro',
 'medalTarczay',
 'medalPascucci',
 'medalDumitru',
 'medalLehvaslaiho',
 'medalNikolas',
 'medalLafayettePool',
 'heroesOfRassenay',
 'medalDeLanglade',
 'medalTamadaYoshio',
 'huntsman',
 'sniper2',
 'mainGun']
_tankmanAchievementsBlockBuilder = StaticSizeBlockBuilder('achievements', TMAN_ACHIEVEMENTS_BLOCK_LAYOUT, {}, [])
tmanDossierLayout = (_tmanTotalBlockBuilder, _tankmanAchievementsBlockBuilder)
_fortTotalBlockLayout = ['creationTime', 'production', 'reservedInt32']
_fortTotalBlockBuilder = StaticSizeBlockBuilder('total', _fortTotalBlockLayout, {}, [])
_fortBattlesBlockLayout = ['battlesCount',
 'battlesHours',
 'attackCount',
 'defenceCount',
 'enemyBaseCaptureCount',
 'ownBaseLossCount',
 'combatCount',
 'combatWins',
 'successDefenceCount',
 'successAttackCount',
 'captureEnemyBuildingTotalCount',
 'lossOwnBuildingTotalCount',
 'resourceCaptureCount',
 'resourceLossCount']
_fortBattlesBlockBuilder = StaticSizeBlockBuilder('fortBattles', _fortBattlesBlockLayout, {}, [])
_fortSortiesBlockLayout = ['battlesCount',
 'wins',
 'losses',
 'middleBattlesCount',
 'championBattlesCount',
 'absoluteBattlesCount',
 'fortResourceInMiddle',
 'fortResourceInChampion',
 'fortResourceInAbsolute']
_fortSortiesBlockBuilder = StaticSizeBlockBuilder('fortSorties', _fortSortiesBlockLayout, {}, [])
_fortAchievementsBlockLayout = ['citadel']
_fortAchievementsPopUps = ['citadel']
_fortAchievementsBlockBuilder = StaticSizeBlockBuilder('achievements', _fortAchievementsBlockLayout, {}, _fortAchievementsPopUps)
fortDossierLayout = (_fortTotalBlockBuilder,
 _fortBattlesBlockBuilder,
 _fortSortiesBlockBuilder,
 _fortAchievementsBlockBuilder)
