# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/client/bootcamp/BootcampConstants.py
from gui.Scaleform.genConsts.BOOTCAMP_MESSAGE_ALIASES import BOOTCAMP_MESSAGE_ALIASES

class UI_STATE(object):
    INIT = 1
    START = 2
    UPDATE = 3
    STOP = 4


BOOTCAMP_MESSAGE_WINDOW = {'FINISH': BOOTCAMP_MESSAGE_ALIASES.RENDERER_FIN_UI,
 'ORANGE': BOOTCAMP_MESSAGE_ALIASES.RENDERER_ORANGE_UI,
 'BLUE': BOOTCAMP_MESSAGE_ALIASES.RENDERER_BLUE,
 'GOLD': BOOTCAMP_MESSAGE_ALIASES.RENDERER_GOLD,
 'INTRO': BOOTCAMP_MESSAGE_ALIASES.RENDERER_INTRO}
MESSAGE_BOTTOM_RENDERER = {0: BOOTCAMP_MESSAGE_ALIASES.BOTTOM_REWARDS_VIEW_UI,
 1: BOOTCAMP_MESSAGE_ALIASES.BOTTOM_NODES_VIEW_UI,
 2: BOOTCAMP_MESSAGE_ALIASES.BOTTOM_BUTTONS_TANK_VIEW_UI,
 3: BOOTCAMP_MESSAGE_ALIASES.BOTTOM_BUTTONS_VIEW_UI,
 4: BOOTCAMP_MESSAGE_ALIASES.BOTTOM_NODE_LINE_VIEW_UI}

class BATTLE_STATS_TOOLTIPS:
    DESTROYED = 'destroyed'
    DAMAGE = 'damage'
    BLOCKED = 'blocked'
    DETECTED = 'detected'
    ASSISTED = 'assisted'


class BATTLE_STATS_INDEXES:
    DESTROYED = 12
    DAMAGE = 3
    BLOCKED = 9
    DETECTED = 11
    ASSISTED = 13


BATTLE_STATS_ICONS = {BATTLE_STATS_TOOLTIPS.DESTROYED: 'statIconDestroyed',
 BATTLE_STATS_TOOLTIPS.DAMAGE: 'statIconDamage',
 BATTLE_STATS_TOOLTIPS.BLOCKED: 'statIconBlocked',
 BATTLE_STATS_TOOLTIPS.DETECTED: 'statIconDetected',
 BATTLE_STATS_TOOLTIPS.ASSISTED: 'statIconAssisted'}
BATTLE_STATS_TOOLTIPS_INDEXES = {BATTLE_STATS_TOOLTIPS.DESTROYED: BATTLE_STATS_INDEXES.DESTROYED,
 BATTLE_STATS_TOOLTIPS.DAMAGE: BATTLE_STATS_INDEXES.DAMAGE,
 BATTLE_STATS_TOOLTIPS.BLOCKED: BATTLE_STATS_INDEXES.BLOCKED,
 BATTLE_STATS_TOOLTIPS.DETECTED: BATTLE_STATS_INDEXES.DETECTED,
 BATTLE_STATS_TOOLTIPS.ASSISTED: BATTLE_STATS_INDEXES.ASSISTED}
CONSUMABLE_ERROR_MESSAGES = ('repairkitAllDevicesAreNotDamaged', 'repairkitDeviceIsNotDamaged', 'medkitAllTankmenAreSafe', 'medkitTankmanIsSafe', 'extinguisherDoesNotActivated')
