# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: story_mode/scripts/client/story_mode/gui/sound_constants.py
from sound_gui_manager import CommonSoundSpaceSettings
GAMEMODE_GROUP = 'STATE_gamemode'
GAMEMODE_STATE = 'STATE_gamemode_story_mode'
GAMEMODE_DEFAULT = 'STATE_gamemode_default'
SOUND_REMAPPING = 'story_mode'
COMMON_SOUND_SPACE = 'Lobby_music_garage_story_mode'
HANGAR_GROUP = 'STATE_hangar_place'
HANGAR_STATE = 'STATE_hangar_place_garage'
STORY_MODE_SOUND_SPACE = CommonSoundSpaceSettings(name=COMMON_SOUND_SPACE, entranceStates={HANGAR_GROUP: HANGAR_STATE}, exitStates={}, persistentSounds=(), stoppableSounds=(), priorities=(), autoStart=True, enterEvent='', exitEvent='')
POST_BATTLE_MUSIC_WIN = 'gui_reward_v1_special'
POST_BATTLE_MUSIC_LOSE = 'reward_tank_marathon_A122_TS_5'
CONGRATULATION_MUSIC = 'gui_reward_v1_special'
SMN_ARCADE_ARTILLERY_ACTIVATE_SOUND = 'sm_gp_dday_ability_active'
SMN_ARCADE_ARTILLERY_DEACTIVATE_SOUND = 'sm_gp_dday_ability_deactive'
SMN_ARCADE_ARTILLERY_SET_SOUND = 'sm_gp_dday_ability_set'
SMN_ARCADE_ARTILLERY_STATE_GROUP = 'STATE_BR_death_zone_red'
SMN_ARCADE_ARTILLERY_STATE_IN = 'STATE_BR_death_zone_red_in'
SMN_ARCADE_ARTILLERY_STATE_OUT = 'STATE_BR_death_zone_red_out'
SMN_ARCADE_ARTILLERY_DESTROYER_SOUND = 'eb_ability_inspiration_apply'
ABILITY_ON_COOLDOWN_SOUND = 'sm_gp_vday_ability_cooldown'
ABILITY_CANT_ACTIVATE_SOUND = 'sm_gp_vday_ability_cant_activate'
RECON_ABILITY_ACTIVATE_SOUND = 'sm_gp_vday_ability_recon_activate'
RECON_ABILITY_DEACTIVATE_SOUND = 'sm_gp_vday_ability_recon_reset'
RECON_ABILITY_CANCEL_SOUND = 'sm_gp_vday_ability_recon_cancel'
RECON_ABILITY_SET_SOUND = 'sm_gp_vday_ability_recon_set'
RECON_ABILITY_ENGINE_STOP_SOUND = 'sm_gp_vday_ability_recon_engine_stop'
RECON_ABILITY_ENGINE_START_SOUND = 'sm_gp_vday_ability_recon_engine_start'
DISTRACTION_ABILITY_ACTIVATE_SOUND = 'sm_gp_vday_ability_distraction_activate'
DISTRACTION_ABILITY_CANCEL_SOUND = 'sm_gp_vday_ability_distraction_cancel'
DISTRACTION_ABILITY_SET_SOUND = 'sm_gp_vday_ability_distraction_set'
VDAY_SIXTH_SENSE_SOUND_START = 'sm_gp_vday_lightbulb_start'
VDAY_SIXTH_SENSE_SOUND_STOP = 'sm_gp_vday_lightbulb_stop'
VDAY_SIXTH_SENSE_RTPC_VALUE = 'RTPC_ext_vday_lightbulb_progress'
VDAY_LOOT_CAPTURE_START_SOUND = 'sm_gp_vday_zone_interest_capture_start'
VDAY_LOOT_CAPTURE_STOP_SOUND = 'sm_gp_vday_zone_interest_capture_stop'
VDAY_LOOT_CAPTURE_COMPLETE_SOUND = 'sm_gp_vday_zone_interest_capture_complete'
VDAY_LOOT_CAPTURE_PROGRESS_SOUND = 'sm_gp_vday_zone_interest_capture_progress'
VDAY_LOOT_CAPTURE_RTPC = 'RTPC_ext_vday_capture_progress'
RESPAWN_TIMER_SOUND_EVENT = 'sm_gp_vday_respawn_start'
RESPAWN_TIMER_STATE_GROUP = 'STATE_sm_gameplay_waiting'
RESPAWN_TIMER_STATE_ON = 'STATE_sm_gameplay_waiting_on'
RESPAWN_TIMER_STATE_OFF = 'STATE_sm_gameplay_waiting_off'
