# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: cosmic_event/scripts/client/cosmic_event/gui/gui_constants.py
from constants_utils import ConstInjector
from gui.battle_control import battle_constants
from gui.battle_control.controllers import feedback_events
from personal_missions_constants import CONDITION_ICON
from gui.server_events import cond_formatters
from messenger import m_constants
from cosmic_event.gui.impl.gen.view_models.views.battle.cosmic_hud.ability_model import Ability
from cosmic_event_common.cosmic_constants import BATTLE_EVENT_TYPE, COSMIC_EVENT_ROCKET_BOOSTER, COSMIC_EVENT_RAPIDSHELLING, COSMIC_EVENT_POWER_SHOT, COSMIC_EVENT_BLACKHOLE, COSMIC_EVENT_OVERCHARGE, COSMIC_EVENT_SHIELD, COSMIC_EVENT_WAVE, COSMIC_EVENT_STUN_SHOT, COSMIC_EVENT_MINE, COSMIC_EVENT_TELEPORT

class FEEDBACK_EVENT_ID(battle_constants.FEEDBACK_EVENT_ID, ConstInjector):
    COSMIC_KILL = 81
    COSMIC_ARTIFACT_SCAN = 82
    COSMIC_RAMMING = 83
    COSMIC_PICKUP_ABILITY = 84
    COSMIC_ABILITY_HIT = 85
    COSMIC_SHOT = 86
    COSMIC_ASSIST = 87
    COSMIC_FIRST_BLOOD = 88
    COSMIC_KILL_STREAK = 89
    MAX_KILL_SERIES = 90
    LOOT_RESEARCHING = 91
    LOOT_RESEARCHING_DONE = 92
    LOOT_RESEARCHABLE_PICK_UP = 93


class SCH_CLIENT_MSG_TYPE(m_constants.SCH_CLIENT_MSG_TYPE, ConstInjector):
    COSMIC_DAILY = 400
    COSMIC_EVENT_STATE = 401


BATTLE_RESULTS_KEYS = {'cosmicTotalScore': CONDITION_ICON.EXPERIENCE,
 'cosmicScore/SHOT': CONDITION_ICON.EXPERIENCE,
 'cosmicScore/RAMMING': CONDITION_ICON.EXPERIENCE,
 'cosmicScore/KILL': CONDITION_ICON.EXPERIENCE,
 'cosmicScore/PICKUP': CONDITION_ICON.EXPERIENCE,
 'cosmicScore/ABILITY_HIT': CONDITION_ICON.EXPERIENCE,
 'cosmicScore/ARTIFACT_SCAN': CONDITION_ICON.EXPERIENCE,
 'cosmicScore/ASSIST': CONDITION_ICON.EXPERIENCE,
 'cosmicScore/FIRST_BLOOD': CONDITION_ICON.EXPERIENCE,
 'cosmicScore/KILL_STREAK': CONDITION_ICON.EXPERIENCE,
 'cosmicScore/MAX_KILL_SERIES': CONDITION_ICON.EXPERIENCE,
 'cosmicScore/LOOT_RESEARCHING': CONDITION_ICON.EXPERIENCE,
 'cosmicScore/LOOT_RESEARCHING_DONE': CONDITION_ICON.EXPERIENCE,
 'cosmicScore/LOOT_RESEARCHABLE_PICK_UP': CONDITION_ICON.EXPERIENCE,
 'cosmicBattleEvent/SHOT': CONDITION_ICON.EXPERIENCE,
 'cosmicBattleEvent/RAMMING': CONDITION_ICON.EXPERIENCE,
 'cosmicBattleEvent/KILL': CONDITION_ICON.EXPERIENCE,
 'cosmicBattleEvent/PICKUP': CONDITION_ICON.EXPERIENCE,
 'cosmicBattleEvent/ABILITY_HIT': CONDITION_ICON.EXPERIENCE,
 'cosmicBattleEvent/ARTIFACT_SCAN': CONDITION_ICON.EXPERIENCE,
 'cosmicBattleEvent/ASSIST': CONDITION_ICON.EXPERIENCE,
 'cosmicBattleEvent/FIRST_BLOOD': CONDITION_ICON.EXPERIENCE,
 'cosmicBattleEvent/KILL_STREAK': CONDITION_ICON.EXPERIENCE,
 'cosmicBattleEvent/MAX_KILL_SERIES': CONDITION_ICON.EXPERIENCE,
 'cosmicBattleEvent/LOOT_RESEARCHING_DONE': CONDITION_ICON.EXPERIENCE,
 'cosmicBattleEvent/LOOT_RESEARCHABLE_PICK_UP': CONDITION_ICON.EXPERIENCE,
 'cosmicEquipment/2458107': CONDITION_ICON.EXPERIENCE,
 'cosmicEquipment/2458619': CONDITION_ICON.EXPERIENCE,
 'cosmicEquipment/2459899': CONDITION_ICON.EXPERIENCE,
 'cosmicAbilitiesImpacts/BLACK_HOLE': CONDITION_ICON.EXPERIENCE,
 'cosmicAbilitiesImpacts/GRAVITY_FIELD': CONDITION_ICON.EXPERIENCE,
 'cosmicAbilitiesImpacts/SNIPER_SHOT': CONDITION_ICON.EXPERIENCE,
 'cosmicAbilitiesImpacts/POWER_SHOT': CONDITION_ICON.EXPERIENCE,
 'cosmicAbilitiesImpacts/TELEPORT': CONDITION_ICON.EXPERIENCE}
_BATTLE_EVENT_TO_PLAYER_FEEDBACK_EVENT = {BATTLE_EVENT_TYPE.COSMIC_KILL: FEEDBACK_EVENT_ID.COSMIC_KILL,
 BATTLE_EVENT_TYPE.COSMIC_ARTIFACT_SCAN: FEEDBACK_EVENT_ID.COSMIC_ARTIFACT_SCAN,
 BATTLE_EVENT_TYPE.COSMIC_RAMMING: FEEDBACK_EVENT_ID.COSMIC_RAMMING,
 BATTLE_EVENT_TYPE.COSMIC_PICKUP_ABILITY: FEEDBACK_EVENT_ID.COSMIC_PICKUP_ABILITY,
 BATTLE_EVENT_TYPE.COSMIC_ABILITY_HIT: FEEDBACK_EVENT_ID.COSMIC_ABILITY_HIT,
 BATTLE_EVENT_TYPE.COSMIC_SHOT: FEEDBACK_EVENT_ID.COSMIC_SHOT,
 BATTLE_EVENT_TYPE.COSMIC_ASSIST: FEEDBACK_EVENT_ID.COSMIC_ASSIST,
 BATTLE_EVENT_TYPE.COSMIC_FIRST_BLOOD: FEEDBACK_EVENT_ID.COSMIC_FIRST_BLOOD,
 BATTLE_EVENT_TYPE.COSMIC_KILL_STREAK: FEEDBACK_EVENT_ID.COSMIC_KILL_STREAK,
 BATTLE_EVENT_TYPE.MAX_KILL_SERIES: FEEDBACK_EVENT_ID.MAX_KILL_SERIES,
 BATTLE_EVENT_TYPE.LOOT_RESEARCHING: FEEDBACK_EVENT_ID.LOOT_RESEARCHING,
 BATTLE_EVENT_TYPE.LOOT_RESEARCHING_DONE: FEEDBACK_EVENT_ID.LOOT_RESEARCHING_DONE,
 BATTLE_EVENT_TYPE.LOOT_RESEARCHABLE_PICK_UP: FEEDBACK_EVENT_ID.LOOT_RESEARCHABLE_PICK_UP}
_PLAYER_FEEDBACK_EXTRA_DATA_CONVERTERS = {FEEDBACK_EVENT_ID.COSMIC_KILL: feedback_events._unpackInteger,
 FEEDBACK_EVENT_ID.COSMIC_ARTIFACT_SCAN: feedback_events._unpackInteger,
 FEEDBACK_EVENT_ID.COSMIC_RAMMING: feedback_events._unpackInteger,
 FEEDBACK_EVENT_ID.COSMIC_PICKUP_ABILITY: feedback_events._unpackInteger,
 FEEDBACK_EVENT_ID.COSMIC_ABILITY_HIT: feedback_events._unpackInteger,
 FEEDBACK_EVENT_ID.COSMIC_SHOT: feedback_events._unpackInteger,
 FEEDBACK_EVENT_ID.COSMIC_ASSIST: feedback_events._unpackInteger,
 FEEDBACK_EVENT_ID.COSMIC_FIRST_BLOOD: feedback_events._unpackInteger,
 FEEDBACK_EVENT_ID.COSMIC_KILL_STREAK: feedback_events._unpackInteger,
 FEEDBACK_EVENT_ID.MAX_KILL_SERIES: feedback_events._unpackInteger,
 FEEDBACK_EVENT_ID.LOOT_RESEARCHING: feedback_events._unpackInteger,
 FEEDBACK_EVENT_ID.LOOT_RESEARCHING_DONE: feedback_events._unpackInteger,
 FEEDBACK_EVENT_ID.LOOT_RESEARCHABLE_PICK_UP: feedback_events._unpackInteger}
ABILITY_TYPE_BY_EQUIP_NAME = {COSMIC_EVENT_ROCKET_BOOSTER: Ability.ACCELERATION,
 COSMIC_EVENT_SHIELD: Ability.SHIELD,
 COSMIC_EVENT_RAPIDSHELLING: Ability.RAPID_SHELLING,
 COSMIC_EVENT_POWER_SHOT: Ability.POWER_SHOT,
 COSMIC_EVENT_BLACKHOLE: Ability.BLACK_HOLE,
 COSMIC_EVENT_OVERCHARGE: Ability.OVERCHARGE,
 COSMIC_EVENT_WAVE: Ability.WAVE,
 COSMIC_EVENT_STUN_SHOT: Ability.STUN_SHOT,
 COSMIC_EVENT_MINE: Ability.REPULSION_MINE,
 COSMIC_EVENT_TELEPORT: Ability.TELEPORT}
ACHIEVEMENTS_IDS = {'cosmic_event:achievements_1', 'cosmic_event:achievements_2'}

def injectClientConstants():
    feedback_events._BATTLE_EVENT_TO_PLAYER_FEEDBACK_EVENT.update(_BATTLE_EVENT_TO_PLAYER_FEEDBACK_EVENT)
    feedback_events._PLAYER_FEEDBACK_EXTRA_DATA_CONVERTERS.update(_PLAYER_FEEDBACK_EXTRA_DATA_CONVERTERS)
    cond_formatters.BATTLE_RESULTS_KEYS.update(BATTLE_RESULTS_KEYS)
