# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/client/uilogging/detachment/constants.py


class ACTION(object):
    OPEN = 'open'
    DIALOG_CONFIRM = 'dialog_confirm'
    DIALOG_EXIT = 'dialog_exit'
    DIALOG_CANCEL = 'dialog_cancel'
    TOOLTIP_WATCHED = 'tooltip_watched'
    DETACHMENT_MOVE_TO_BARRACKS = 'detachment_move_to_barracks'
    SHOW_VIDEO_INTRO = 'show_video_intro'
    BUY_GOLD = 'buy_gold'
    CONVERT_GOLD_TO_CREDITS = 'convert_gold_to_credits'
    DROP_SKILL_CHECKBOX = 'drop_skill_checkbox'
    SPEED_UP_LEARNING_CHECKBOX_CHANGED = 'speed_up_learning_checkbox_changed'
    ASSIGN_TO_VEHICLE_NO_TRAINING = 'assign_to_vehicle_no_training'
    USE_TTC_SECTION = 'use_ttc_section'
    TOGGLE_FILTER_CHANGED = 'toggle_filter_changed'
    POPOVER_FILTER_CHANGED = 'popover_filter_changed'
    POPOVER_FILTERS_RESET = 'popover_filters_reset'
    ALL_FILTERS_RESET = 'all_filters_reset'
    UNLOAD_ALL_RECRUITS = 'unload_all_recruits'
    UNLOAD_RECRUIT = 'unload_recruit'
    RETURN_PREVIOUS_RECRUIT_CONFIGURATION = 'return_previous_recruit_configuration'
    SELECT_BEST_RECRUITS = 'select_best_recruits'
    SET_NATIVE_CREW = 'set_native_crew'
    SET_BEST_DETACHMENT = 'set_best_detachment'
    SET_PREVIOUS_DETACHMENT = 'set_previous_detachment'
    COMMANDER_FIRST_NAME_CHANGED = 'commander_first_name_changed'
    COMMANDER_LAST_NAME_CHANGED = 'commander_last_name_changed'


class GROUP(object):
    HANGAR = 'hangar'
    PRESENTATION = 'presentation'
    MOBILIZE_CREW_INFO = 'mobilize_crew_info'
    MOBILIZE_CREW_CONFIRMATION = 'mobilize_crew_confirmation'
    MOBILIZE_CREW = 'mobilize_crew'
    RECRUIT_MOBILIZATION_CONTEXT_MENU = 'recruit_mobilization_context_menu'
    RECRUIT_ACTIONS_CONTEXT_MENU = 'recruit_actions_context_menu'
    RECRUIT_PANEL_CONTEXT_MENU = 'recruit_panel_context_menu'
    RETRAIN_CREW_DIALOG = 'retrain_crew_dialog'
    RETRAIN_TANKMAN_DIALOG = 'retrain_tankman_dialog'
    RECRUIT_ROLE_CHANGE_DIALOG = 'recruit_role_change_dialog'
    HANGAR_DETACHMENT_WIDGET = 'hangar_detachment_widget'
    HANGAR_DETACHMENT_WIDGET_CONTEXT_MENU = 'hangar_detachment_widget_context_menu'
    HANGAR_DETACHMENT_WIDGET_BUTTONS = 'hangar_detachment_widget_buttons'
    HANGAR_RECRUIT_PANEL = 'hangar_recruit_panel'
    SPEED_UP_LEARNING = 'speed_up_learning'
    LEARNED_SKILLS_LIST = 'learned_skills_list'
    ASSIGN_DETACHMENT = 'assign_detachment'
    SELECT_ASSIGN_METHOD_DIALOG = 'select_assign_method_dialog'
    TRAIN_VEHICLE_CONFIRM_DIALOG = 'train_vehicle_confirm_dialog'
    PERK_MATRIX = 'perk_matrix'
    PERK_MATRIX_DIALOGS_CLEAR_ALL = 'perk_matrix_dialogs_clear_all'
    VEHICLE_SELECTOR_GF_POPOVER = 'vehicle_selector_gf_popover'
    NEW_DETACHMENT_LEVEL = 'new_detachment_level'
    DETACHMENT_PERSONAL_CASE = 'detachment_personal_case'
    DEMOBILIZE_DETACHMENT_DIALOG = 'demobilize_detachment_dialog'
    DELETE_DETACHMENT_DIALOG = 'delete_detachment_dialog'
    RESTORE_DETACHMENT_DIALOG = 'restore_detachment_dialog'
    SPECIALIZATION_VEHICLE_LIST_CHOICE = 'specialization_vehicle_list_choice'
    BUY_VEHICLE_SLOT_DIALOG = 'buy_vehicle_slot_dialog'
    BUY_DORMITORY_DIALOG = 'buy_dormitory_dialog'
    INSTRUCTOR_CHOICE_LIST = 'instructor_choice_list'
    INSTRUCTOR_TOKEN_LIST = 'instructor_token_list'
    INSTRUCTOR_UNPACKING = 'instructor_unpacking'
    INSTRUCTOR_PAGE = 'instructor_page'
    DEMOUNT_INSTRUCTOR_DIALOG = 'demount_instructor_dialog'
    INSTRUCTOR_BARRACKS = 'instructor_barracks'
    DETACHMENT_BARRACKS = 'detachment_barracks'
    RECRUIT_BARRACKS = 'recruit_barracks'
    NEW_COMMANDER_LIST = 'new_commander_list'
    NEW_COMMANDER_DIALOG = 'new_commander_dialog'
    RAISE_EFFICIENCY = 'raise_efficiency'
    XP_EXCHANGE_CONFIRM_DIALOG = 'xp_exchange_confirm_dialog'
    COMMANDER_PROFILE = 'commander_profile'
    CHANGE_COMMANDER_LOOK_DIALOG = 'change_commander_look_dialog'
