# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/client/gui/shared/gui_items/vehicle_mechanics/constants.py
from __future__ import absolute_import
from gui.impl.gen.view_models.common.vehicle_mechanic_model import MechanicsEnum
from gui.shared.gui_items import GUI_ITEM_TYPE
from vehicles.mechanics.mechanic_constants import VehicleMechanic
VEHICLE_MECHANICS_GUI_MAP = {VehicleMechanic.ACCURACY_STACKS: MechanicsEnum.ACCURACY_STACKS,
 VehicleMechanic.AUTO_LOADER_GUN: MechanicsEnum.AUTO_LOADER_GUN,
 VehicleMechanic.AUTO_LOADER_GUN_BOOST: MechanicsEnum.AUTO_LOADER_GUN_BOOST,
 VehicleMechanic.AUTO_SHOOT_GUN: MechanicsEnum.AUTO_SHOOT_GUN,
 VehicleMechanic.BATTLE_FURY: MechanicsEnum.BATTLE_FURY,
 VehicleMechanic.CHARGEABLE_BURST: MechanicsEnum.CHARGEABLE_BURST,
 VehicleMechanic.CHARGE_SHOT: MechanicsEnum.CHARGE_SHOT,
 VehicleMechanic.CONCENTRATION_MODE: MechanicsEnum.CONCENTRATION_MODE,
 VehicleMechanic.DAMAGE_MUTABLE: MechanicsEnum.DAMAGE_MUTABLE,
 VehicleMechanic.DUAL_ACCURACY: MechanicsEnum.DUAL_ACCURACY,
 VehicleMechanic.DUAL_GUN: MechanicsEnum.DUAL_GUN,
 VehicleMechanic.EXTRA_SHOT_CLIP: MechanicsEnum.EXTRA_SHOT_CLIP,
 VehicleMechanic.HEATING_ZONES_GUN: MechanicsEnum.HEATING_ZONES_GUN,
 VehicleMechanic.HYDRAULIC_CHASSIS: MechanicsEnum.HYDRAULIC_CHASSIS,
 VehicleMechanic.HYDRAULIC_WHEELED_CHASSIS: MechanicsEnum.HYDRAULIC_WHEELED_CHASSIS,
 VehicleMechanic.IMPROVED_RAMMING: MechanicsEnum.IMPROVED_RAMMING,
 VehicleMechanic.MAGAZINE_GUN: MechanicsEnum.MAGAZINE_GUN,
 VehicleMechanic.OVERHEAT_GUN: MechanicsEnum.OVERHEAT_GUN,
 VehicleMechanic.OVERHEAT_STACKS: MechanicsEnum.OVERHEAT_STACKS,
 VehicleMechanic.PILLBOX_SIEGE_MODE: MechanicsEnum.PILLBOX_SIEGE_MODE,
 VehicleMechanic.POWER_MODE: MechanicsEnum.POWER_MODE,
 VehicleMechanic.RECHARGEABLE_NITRO: MechanicsEnum.RECHARGEABLE_NITRO,
 VehicleMechanic.ROCKET_ACCELERATION: MechanicsEnum.ROCKET_ACCELERATION,
 VehicleMechanic.STANCE_DANCE: MechanicsEnum.STANCE_DANCE,
 VehicleMechanic.STATIONARY_RELOAD: MechanicsEnum.STATIONARY_RELOAD,
 VehicleMechanic.SIEGE_MODE: MechanicsEnum.SIEGE_MODE,
 VehicleMechanic.STUN: MechanicsEnum.STUN,
 VehicleMechanic.SUPPORT_WEAPON: MechanicsEnum.SUPPORT_WEAPON,
 VehicleMechanic.TARGET_DESIGNATOR: MechanicsEnum.TARGET_DESIGNATOR,
 VehicleMechanic.TRACK_WITHIN_TRACK: MechanicsEnum.TRACK_WITHIN_TRACK,
 VehicleMechanic.TURBOSHAFT_ENGINE: MechanicsEnum.TURBOSHAFT_ENGINE,
 VehicleMechanic.TWIN_GUN: MechanicsEnum.TWIN_GUN,
 VehicleMechanic.STAGED_JET_BOOSTERS: MechanicsEnum.STAGED_JET_BOOSTERS}
MECHANIC_OVERRIDES = {GUI_ITEM_TYPE.GUN: {VehicleMechanic.AUTO_LOADER_GUN_BOOST: {VehicleMechanic.AUTO_LOADER_GUN, VehicleMechanic.MAGAZINE_GUN},
                     VehicleMechanic.AUTO_LOADER_GUN: {VehicleMechanic.MAGAZINE_GUN},
                     VehicleMechanic.AUTO_SHOOT_GUN: {VehicleMechanic.MAGAZINE_GUN},
                     VehicleMechanic.OVERHEAT_GUN: {VehicleMechanic.AUTO_SHOOT_GUN, VehicleMechanic.TEMPERATURE_GUN},
                     VehicleMechanic.HEATING_ZONES_GUN: {VehicleMechanic.TEMPERATURE_GUN}},
 GUI_ITEM_TYPE.CHASSIS: {VehicleMechanic.HYDRAULIC_WHEELED_CHASSIS: {VehicleMechanic.HYDRAULIC_CHASSIS}},
 GUI_ITEM_TYPE.VEHICLE: {VehicleMechanic.TURBOSHAFT_ENGINE: {VehicleMechanic.SIEGE_MODE},
                         VehicleMechanic.DUAL_GUN: {VehicleMechanic.SIEGE_MODE},
                         VehicleMechanic.DUAL_ACCURACY: {VehicleMechanic.SIEGE_MODE},
                         VehicleMechanic.TWIN_GUN: {VehicleMechanic.SIEGE_MODE},
                         VehicleMechanic.HYDRAULIC_WHEELED_CHASSIS: {VehicleMechanic.SIEGE_MODE}}}
