# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: gui_lootboxes/scripts/client/gui_lootboxes/gui/impl/lobby/gui_lootboxes/lootbox_video_reward_config.py
REWARD_VIDEO_CONFIG = {'tanks_birthday_2025': {'vehicles': {'hasFooter': True,
                                      'videos': [{'videoResName': 'intro',
                                                  'duration': 16}, {'videoResName': None,
                                                  'duration': 9,
                                                  'showFooterTiming': 3}]}},
 'cosmic_2025': {'vehicles': {'hasFooter': True,
                              'videos': [{'videoResName': 'intro',
                                          'duration': 11}, {'videoResName': None,
                                          'duration': 3,
                                          'showFooterTiming': 2}]}},
 'mtl_universal': {'vehicles': {'hasFooter': True,
                                'videos': [{'videoResName': None,
                                            'duration': 13,
                                            'showFooterTiming': 1}]}},
 'ny_2026_big': {'vehicles': {'hasFooter': True,
                              'videos': [{'videoResName': 'intro',
                                          'duration': 21}, {'videoResName': None,
                                          'duration': 18,
                                          'showFooterTiming': 2}]},
                 'lootBoxToken': {'hasFooter': True,
                                  'videos': [{'videoResName': 'intro',
                                              'duration': 21}, {'videoResName': 'ny_2026_tanks',
                                              'duration': 10,
                                              'showFooterTiming': 2}]},
                 'customizations': {'hasFooter': True,
                                    'videos': [{'videoResName': None,
                                                'duration': 23,
                                                'showFooterTiming': 2}]}},
 'ny_2026_tanks': {'vehicles': {'hasFooter': True,
                                'videos': [{'videoResName': None,
                                            'duration': 12,
                                            'showFooterTiming': 2}]}}}
