# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: gui_lootboxes/scripts/client/gui_lootboxes/gui/impl/lobby/gui_lootboxes/lootbox_video_reward_config.py
REWARD_VIDEO_CONFIG = {'common': {'vehicles': {'hasFooter': True,
                         'videos': [{'videoResName': None,
                                     'duration': 20}]}},
 'tanks_birthday_2025': {'vehicles': {'hasFooter': True,
                                      'videos': [{'videoResName': 'intro',
                                                  'duration': 16}, {'videoResName': None,
                                                  'duration': 9,
                                                  'showFooterTiming': 3}]}},
 'tanks_birthday_2026': {'vehicles': {'hasFooter': True,
                                      'videos': [{'videoResName': 'intro',
                                                  'duration': 12}, {'videoResName': None,
                                                  'duration': 12,
                                                  'showFooterTiming': 3}]}},
 'cosmic_2026': {'vehicles': {'hasFooter': True,
                              'videos': [{'videoResName': 'intro',
                                          'duration': 17}, {'videoResName': None,
                                          'duration': 17,
                                          'showFooterTiming': 2}]}},
 'cosmic_2026_2': {'vehicles': {'hasFooter': True,
                                'videos': [{'videoResName': 'intro',
                                            'duration': 17}, {'videoResName': None,
                                            'duration': 17,
                                            'showFooterTiming': 2}]}},
 'mtl_universal': {'vehicles': {'hasFooter': True,
                                'videos': [{'videoResName': None,
                                            'duration': 13,
                                            'showFooterTiming': 1}]}}}
